/**
 * Bihar Official State Ingestion Importer
 * Authoritative Sources:
 * - Bihar State Board of Religious Trusts (BSBRT) (https://bsbrt.bihar.gov.in)
 * - Bodh Gaya Temple Management Committee (BTMC) (https://bodhgayatemple.com)
 * - Bihar State Tourism Development Corporation (https://tourism.bihar.gov.in)
 * - Archaeological Survey of India (Patna Circle) (https://asipatnacircle.bihar.gov.in)
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const BIHAR_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Badi Patan Devi Temple Patna",
    nameLocal: "बड़ी पटन देवी मंदिर पटना",
    stateCode: "BR",
    districtName: "Patna",
    localityName: "Sadikpur, Patna",
    latitude: 25.5992,
    longitude: 85.1950,
    mainDeity: "Maa Patan Devi (Sarvanandakari)",
    deities: ["Maa Mahakali", "Maa Mahalakshmi", "Maa Mahasaraswati", "Bhairava"],
    templeType: "Supreme 51 Maha Shakti Peethas (Right Thigh / Nitambha Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Historic North Indian Nagar Style Shikhara on Ganga Basin",
    historicalPeriod: "Ancient Pataliputra Era / Vedic Antiquity",
    description: "Revered as the ancient guardian goddess of historical Pataliputra (Patna), where Sati's right thigh is believed to have fallen. The city of Patna derives its name from Maa Patan Devi.",
    officialWebsite: "https://patna.nic.in/tourist-place/patan-devi/",
    sourceRecordId: "BR-BSBRT-PAT-001",
    sourceName: "Bihar State Board of Religious Trusts & Patna Administration",
    sourceUrl: "https://patna.nic.in/tourist-place/patan-devi/",
    sourceType: "government",
  },
  {
    name: "Mahavir Mandir Patna Junction",
    nameLocal: "महावीर मंदिर पटना",
    stateCode: "BR",
    districtName: "Patna",
    localityName: "Station Road, Patna Junction",
    latitude: 25.6025,
    longitude: 85.1378,
    mainDeity: "Sankat Mochan Hanuman (Twin Deities)",
    deities: ["Hanuman (Mano-kamna Puran & Dukkha-harana)", "Rama", "Shiva"],
    templeType: "Supreme North Indian Hanuman Pilgrimage Shrine",
    tradition: ["Vaishnavism", "Ramanandi Sampradaya"],
    architecture: "Three-Storeyed Marble Temple with Magnificent Kalash Spire",
    historicalPeriod: "Swami Balanand (1730 CE) / Rebuilt by Acharya Kishore Kunal (1985 CE)",
    description: "One of the most visited religious shrines in North India, unique for housing twin idols of Lord Hanuman (one to grant wishes, the other to remove sorrows). Renowned for its Naivedyam prasad.",
    officialWebsite: "https://mahavirmandirpatna.org",
    sourceRecordId: "BR-MAHA-PAT-002",
    sourceName: "Shri Mahavir Mandir Trusts & BSBRT",
    sourceUrl: "https://mahavirmandirpatna.org",
    sourceType: "official",
  },
  {
    name: "Mundeshwari Devi Temple Kaimur",
    nameLocal: "माँ मुंडेश्वरी मंदिर कैमूर",
    stateCode: "BR",
    districtName: "Kaimur",
    localityName: "Ramgarh Village, Kaimur Hills, Bhabua",
    latitude: 25.0203,
    longitude: 83.5878,
    mainDeity: "Maa Mundeshwari (Goddess Varahi)",
    deities: ["Maa Mundeshwari", "Four-Faced Chaturmukha Shivalinga"],
    templeType: "Oldest Documented Operational Hindu Temple in India (625 CE)",
    tradition: ["Shaktism", "Shaivism"],
    architecture: "Rare Octagonal Stone Nagara Temple with Intricate Gupta Carvings",
    historicalPeriod: "Inscribed Seal Dated to 625 CE (Gupta / Post-Gupta Era)",
    description: "Protected as a national monument by the ASI, Mundeshwari is recognized as India's oldest continuously functional stone temple. Famous for its non-violent ritual where animals are sanctified without harm.",
    officialWebsite: "https://kaimur.nic.in/tourist-place/maa-mundeshwari-temple/",
    sourceRecordId: "BR-ASI-KAI-003",
    sourceName: "Archaeological Survey of India (Patna Circle) & Kaimur Admin",
    sourceUrl: "https://kaimur.nic.in/tourist-place/maa-mundeshwari-temple/",
    sourceType: "asi",
  },
  {
    name: "Deo Sun Temple Aurangabad",
    nameLocal: "देव सूर्य मंदिर औरंगाबाद",
    stateCode: "BR",
    districtName: "Aurangabad",
    localityName: "Deo, Aurangabad",
    latitude: 24.6548,
    longitude: 84.4372,
    mainDeity: "Lord Surya (Sun God)",
    deities: ["Surya Narayana", "Usha", "Pratyusha"],
    templeType: "Unique West-Facing Ancient Stone Sun Temple",
    tradition: ["Saura Tradition", "Vedic Sun Worship"],
    architecture: "Nagara Style 100-Foot Stone Shikhara with Golden Umbrella Dome",
    historicalPeriod: "King Aila / Ancient Magadha Era",
    description: "Unlike most east-facing Sun temples in India, Deo Sun Temple is unique in having its sanctum entrance facing west towards the setting sun. Epicenter of the celebrated Chhath Mahaparva in Bihar.",
    officialWebsite: "https://aurangabad.bihar.gov.in/tourist-place/deo-temple/",
    sourceRecordId: "BR-TOUR-AUR-004",
    sourceName: "Aurangabad District Administration & Bihar Tourism",
    sourceUrl: "https://aurangabad.bihar.gov.in/tourist-place/deo-temple/",
    sourceType: "government",
  },
  {
    name: "Ashokdham Temple Lakhisarai",
    nameLocal: "अशोकधाम मंदिर लखीसराय",
    stateCode: "BR",
    districtName: "Lakhisarai",
    localityName: "Chowki Village, Lakhisarai",
    latitude: 25.1783,
    longitude: 86.0889,
    mainDeity: "Indradyumneshwar Mahadev (Lord Shiva)",
    deities: ["Lord Shiva", "Maa Parvati"],
    templeType: "Monumental Black Granite Shivalinga Pilgrimage Complex",
    tradition: ["Shaivism"],
    architecture: "Grand Modern Nagara Complex Housing Ancient Monolithic Shivalinga",
    historicalPeriod: "Discovered April 7, 1977 CE / Ancient Pala Era Monolith",
    description: "Houses an enormous black stone monolithic Shivalinga unearthed by local youths in 1977. Expanded into a grand pilgrimage center consecrated by Jagadguru Shankaracharya.",
    officialWebsite: "https://lakhisarai.nic.in/tourist-place/ashokdham-temple/",
    sourceRecordId: "BR-TOUR-LAK-005",
    sourceName: "Lakhisarai District Administration & Ashokdham Trust",
    sourceUrl: "https://lakhisarai.nic.in/tourist-place/ashokdham-temple/",
    sourceType: "government",
  },
  {
    name: "Mandar Hill Madhusudan Temple Banka",
    nameLocal: "मन्दार पर्वत मधुसूदन मंदिर बांका",
    stateCode: "BR",
    districtName: "Banka",
    localityName: "Bousi, Banka",
    latitude: 24.8383,
    longitude: 87.0267,
    mainDeity: "Bhagwan Madhusudan (Lord Vishnu)",
    deities: ["Lord Vishnu", "Vamana", "Narasimha"],
    templeType: "Puranic Samudra Manthan Churning Mount Pilgrimage",
    tradition: ["Vaishnavism"],
    architecture: "Granite Hilltop and Foothill Shrines with Papaharini Sacred Tank",
    historicalPeriod: "Puranic Antiquity / Chola and Pala Inscriptions",
    description: "Revered in Hindu epics as the churning rod (Manthana Parvata) used by devas and asuras during the churning of the cosmic ocean (Samudra Manthan). Footprints of Lord Vishnu and the sacred Papaharini tank grace the hill.",
    officialWebsite: "https://banka.nic.in/tourist-place/mandar-hill/",
    sourceRecordId: "BR-TOUR-BNK-006",
    sourceName: "Banka District Administration & Bihar Tourism",
    sourceUrl: "https://banka.nic.in/tourist-place/mandar-hill/",
    sourceType: "government",
  },
  {
    name: "Brahmeshwar Nath Mandir Brahmpur",
    nameLocal: "ब्रह्मेश्वर नाथ मंदिर ब्रह्मपुर बक्सर",
    stateCode: "BR",
    districtName: "Buxar",
    localityName: "Brahmpur, Buxar",
    latitude: 25.5783,
    longitude: 83.9806,
    mainDeity: "Baba Brahmeshwar Nath (Lord Shiva)",
    deities: ["Lord Shiva", "Nandi"],
    templeType: "Ancient Swayambhu Shiva Shrine of Buxar",
    tradition: ["Shaivism"],
    architecture: "Historic West-Facing Nagara Temple with Sacred Shiva Pushkarini",
    historicalPeriod: "Treta Yuga Puranic Tradition / Medieval Reconstruction",
    description: "Known as the Baba Dham of Buxar, said to have been consecrated by Lord Brahma Himself. Celebrated for its legendary Shravani Mela and annual livestock trade festival dating back centuries.",
    officialWebsite: "https://buxar.nic.in/tourist-place/baba-brahmeshwar-nath-temple/",
    sourceRecordId: "BR-TOUR-BUX-007",
    sourceName: "Buxar District Administration & BSBRT",
    sourceUrl: "https://buxar.nic.in/tourist-place/baba-brahmeshwar-nath-temple/",
    sourceType: "government",
  },
  {
    name: "Shyama Mai Mandir Darbhanga",
    nameLocal: "श्यामा माई मंदिर दरभंगा",
    stateCode: "BR",
    districtName: "Darbhanga",
    localityName: "Lalbagh, Darbhanga Raj Complex",
    latitude: 26.1517,
    longitude: 85.8986,
    mainDeity: "Maa Shyama (Goddess Kali)",
    deities: ["Maa Kali", "Lord Shiva"],
    templeType: "Historic Mithila Cremation Ground Tantric Temple",
    tradition: ["Shaktism", "Tantra", "Mithila Tradition"],
    architecture: "Majestic Red Brick Temple Built on Royal Cremation Pyre",
    historicalPeriod: "Maharaja Kameshwar Singh of Darbhanga Raj (1933 CE)",
    description: "Built directly upon the funeral pyre of Maharaja Rameshwar Singh within the sprawling Darbhanga Raj complex. One of the most venerated Shakta pilgrimage centers in Mithilanchal.",
    officialWebsite: "https://darbhanga.nic.in/tourist-place/shyama-mai-temple/",
    sourceRecordId: "BR-TOUR-DAR-008",
    sourceName: "Darbhanga Raj Religious Trust & Darbhanga Administration",
    sourceUrl: "https://darbhanga.nic.in/tourist-place/shyama-mai-temple/",
    sourceType: "government",
  },
  {
    name: "Uchaitha Bhagwati Mandir Madhubani",
    nameLocal: "उच्चैठ भगवती मंदिर मधुबनी",
    stateCode: "BR",
    districtName: "Madhubani",
    localityName: "Uchaitha, Benipatti, Madhubani",
    latitude: 26.4717,
    longitude: 85.9083,
    mainDeity: "Chhinnamastika Bhagwati (Goddess Durga)",
    deities: ["Maa Durga / Kali"],
    templeType: "Mahakavi Kalidas Siddha Peetha of Mithila",
    tradition: ["Shaktism"],
    architecture: "Historic Mithila Temple on the Bank of Thumne River",
    historicalPeriod: "Ancient Antiquity / Kalidas Era",
    description: "The hallowed site where the great Sanskrit poet Kalidas is said to have been blessed with supreme wisdom and poetic genius by Goddess Bhagwati after cutting off his tongue as an offering.",
    officialWebsite: "https://madhubani.nic.in/tourist-place/uchaitha-bhagwati-temple/",
    sourceRecordId: "BR-TOUR-MDB-009",
    sourceName: "Madhubani District Administration & Bihar Tourism",
    sourceUrl: "https://madhubani.nic.in/tourist-place/uchaitha-bhagwati-temple/",
    sourceType: "government",
  },
  {
    name: "Punaura Dham Sita Janmasthali",
    nameLocal: "पुनौरा धाम सीता जन्मस्थली सीतामढ़ी",
    stateCode: "BR",
    districtName: "Sitamarhi",
    localityName: "Punaura, Sitamarhi",
    latitude: 26.6028,
    longitude: 85.4678,
    mainDeity: "Maa Janaki (Goddess Sita)",
    deities: ["Sita Devi", "Raja Janaka", "Lord Rama"],
    templeType: "Supreme Holy Birthplace of Mother Sita",
    tradition: ["Vaishnavism", "Ramayana Circuit"],
    architecture: "Vast Sacred Temple Complex with Janaki Kund Sarovar",
    historicalPeriod: "Treta Yuga Ramayana Era / Puranic Sanctuary",
    description: "The sacred agrarian site where King Janaka ploughed the field during a drought and discovered infant Sita in a golden casket. Anchors the national Ramayana pilgrimage circuit in Bihar.",
    officialWebsite: "https://sitamarhi.nic.in/tourist-place/punaura-dham/",
    sourceRecordId: "BR-TOUR-SIT-010",
    sourceName: "Sitamarhi District Administration & Ramayana Circuit Board",
    sourceUrl: "https://sitamarhi.nic.in/tourist-place/punaura-dham/",
    sourceType: "government",
  },
  {
    name: "Chandi Sthan Mandir Munger",
    nameLocal: "चंडी स्थान मंदिर मुंगेर",
    stateCode: "BR",
    districtName: "Munger",
    localityName: "Munger City, Near Ganga Bank",
    latitude: 25.3789,
    longitude: 86.4744,
    mainDeity: "Maa Chandi (Goddess Durga)",
    deities: ["Maa Chandi", "Bhairava"],
    templeType: "51 Maha Shakti Peethas (Left Eye / Netra Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Cave-like Underground Sanctum on Northern Spur of Kharagpur Hills",
    historicalPeriod: "Ancient Karna Kingdom of Anga / Puranic Era",
    description: "One of the 51 sacred Shakti Peethas where Goddess Sati's left eye is said to have fallen. Famous for miraculous eye cures and its subterranean rock-carved sanctum beside the Ganga.",
    officialWebsite: "https://munger.nic.in/tourist-place/chandi-sthan/",
    sourceRecordId: "BR-TOUR-MUN-011",
    sourceName: "Munger District Administration & Chandi Sthan Trust",
    sourceUrl: "https://munger.nic.in/tourist-place/chandi-sthan/",
    sourceType: "government",
  },
  {
    name: "Surya Mandir Baragaon Nalanda",
    nameLocal: "सूर्य मंदिर बड़गांव नालंदा",
    stateCode: "BR",
    districtName: "Nalanda",
    localityName: "Baragaon, Near Nalanda Ruins",
    latitude: 25.1375,
    longitude: 85.4489,
    mainDeity: "Lord Surya Narayana",
    deities: ["Surya", "Chhathi Maiya"],
    templeType: "Ancient Sun Worship & Chhath Mahaparva Kshetra",
    tradition: ["Saura Tradition", "Vedic Sun Worship"],
    architecture: "Historic Temple Enclosing Ancient Sun Carvings and Surya Kund",
    historicalPeriod: "Gupta and Pala Dynasties / Nalanda University Era",
    description: "Situated adjacent to the ancient ruins of Nalanda Mahavihara. The Sun idol was established during the Gupta period, and the temple's sacred Surya Kund attracts millions during Chhath festival.",
    officialWebsite: "https://nalanda.nic.in/tourist-place/surya-mandir-baragaon/",
    sourceRecordId: "BR-TOUR-NAL-012",
    sourceName: "Nalanda District Administration & Bihar Tourism",
    sourceUrl: "https://nalanda.nic.in/tourist-place/surya-mandir-baragaon/",
    sourceType: "government",
  },
  {
    name: "Baba Garibnath Temple Muzaffarpur",
    nameLocal: "बाबा गरीबनाथ मंदिर मुजफ्फरपुर",
    stateCode: "BR",
    districtName: "Muzaffarpur",
    localityName: "Purani Bazar, Muzaffarpur",
    latitude: 26.1219,
    longitude: 85.3908,
    mainDeity: "Baba Garibnath (Lord Shiva)",
    deities: ["Lord Shiva", "Gauri"],
    templeType: "Principal Shaivite Pilgrimage of North Bihar",
    tradition: ["Shaivism"],
    architecture: "Traditional Multi-Domed Nagara Structure in Central Muzaffarpur",
    historicalPeriod: "Ancient Peepal Tree Monolith (300+ Years Old)",
    description: "Revered as the Baba Dham of North Bihar. Devotees walk hundreds of kilometers as Kanwariyas carrying holy water from Pahleza Ghat to offer to Baba Garibnath during Shravan.",
    officialWebsite: "https://muzaffarpur.nic.in/tourist-place/baba-garibnath-temple/",
    sourceRecordId: "BR-BSBRT-MUZ-013",
    sourceName: "Bihar State Board of Religious Trusts & Muzaffarpur Admin",
    sourceUrl: "https://muzaffarpur.nic.in/tourist-place/baba-garibnath-temple/",
    sourceType: "government",
  },
  {
    name: "Thawe Mandir Gopalganj",
    nameLocal: "थावे मंदिर गोपालगंज",
    stateCode: "BR",
    districtName: "Gopalganj",
    localityName: "Thawe Forest, Gopalganj",
    latitude: 26.4028,
    longitude: 84.3878,
    mainDeity: "Maa Thawevali (Singhasini Bhavani)",
    deities: ["Maa Durga / Kamakhya"],
    templeType: "Celebrated Shakta Pilgrimage of Western Bihar",
    tradition: ["Shaktism"],
    architecture: "Nagara Temple in Sacred Thawe Jungle with Rahshu Bhagat Memorial",
    historicalPeriod: "14th Century CE (King Manbodh Sen of Hathwa)",
    description: "Located in the forest of Thawe, dedicated to Goddess Bhavani who manifested from Assam's Kamakhya to protect her staunch devotee Rahshu Bhagat. A vibrant center during Chaitra Navratri.",
    officialWebsite: "https://gopalganj.nic.in/tourist-place/thawe-temple/",
    sourceRecordId: "BR-TOUR-GOP-014",
    sourceName: "Gopalganj District Administration & Hathwa Raj Trust",
    sourceUrl: "https://gopalganj.nic.in/tourist-place/thawe-temple/",
    sourceType: "government",
  },
  {
    name: "Vishnupad Temple Gaya",
    nameLocal: "विष्णुपद मंदिर गया",
    stateCode: "BR",
    districtName: "Gaya",
    localityName: "Chandranath Hill, Falgu River Bank, Gaya",
    latitude: 24.7778,
    longitude: 85.0069,
    mainDeity: "Lord Vishnu (Dharmasila Footprint)",
    deities: ["Lord Vishnu", "Lord Shiva", "Goddess Lakshmi"],
    templeType: "Supreme Puranic Moksha & Pitru Paksha Pilgrimage",
    tradition: ["Vaishnavism"],
    architecture: "30-Meter Octagonal Basalt Shikhara with Solid Silver Gold-Plated Flag",
    historicalPeriod: "Ahilyabai Holkar of Indore (1787 CE) / Ancient Dharmasila",
    description: "The premier sacred shrine for performing Shraddha and Pinda Daan rituals for ancestors. Built in flawless black basalt by Queen Ahilyabai Holkar over Lord Vishnu's 40-centimeter footprint.",
    officialWebsite: "https://gaya.nic.in/tourist-place/vishnupad-temple/",
    sourceRecordId: "BR-BSBRT-GAY-015",
    sourceName: "Gaya District Administration & Gayawal Panda Samiti",
    sourceUrl: "https://gaya.nic.in/tourist-place/vishnupad-temple/",
    sourceType: "government",
  },
  {
    name: "Mangla Gauri Temple Gaya",
    nameLocal: "माँ मंगला गौरी मंदिर गया",
    stateCode: "BR",
    districtName: "Gaya",
    localityName: "Manglagauri Hill, Gaya",
    latitude: 24.7806,
    longitude: 84.9983,
    mainDeity: "Maa Mangla Gauri (Goddess Sati)",
    deities: ["Maa Mangla Gauri", "Bhairava"],
    templeType: "51 Maha Shakti Peethas (Breast / Stana Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Hilltop Temple with Flight of Stone Steps and Sacred Mandapa",
    historicalPeriod: "Padma Purana & Vayu Purana Antiquity (15th Century Reconstruction)",
    description: "Mentioned in the Padma Purana and Agni Purana as one of the 18 Maha Shakti Peethas where Goddess Sati's breasts fell. Devotees visit during Tuesday worships in the month of Shravan.",
    officialWebsite: "https://gaya.nic.in/tourist-place/maa-mangla-gauri-temple/",
    sourceRecordId: "BR-TOUR-GAY-016",
    sourceName: "Gaya District Administration & Mangla Gauri Temple Trust",
    sourceUrl: "https://gaya.nic.in/tourist-place/maa-mangla-gauri-temple/",
    sourceType: "government",
  },
  {
    name: "Baba Ajgaibinath Dham Sultanganj",
    nameLocal: "बाबा अजगैबीनाथ धाम सुल्तानगंज",
    stateCode: "BR",
    districtName: "Bhagalpur",
    localityName: "Jahangira Rock Island, Sultanganj, Bhagalpur",
    latitude: 25.2472,
    longitude: 86.7378,
    mainDeity: "Baba Ajgaibinath (Lord Shiva)",
    deities: ["Lord Shiva", "Ganga Devi"],
    templeType: "Maha Holy Kanwar Yatra Source on Uttarvahini Ganga",
    tradition: ["Shaivism"],
    architecture: "Granite Riverine Island Monolith Shrines Rising from the Ganga",
    historicalPeriod: "Ancient Sage Jahnu Hermitage / Medieval Stone Carvings",
    description: "Perched on a dramatic granite island in the middle of the sacred north-flowing (Uttarvahini) Ganga. Millions of Kanwariya pilgrims collect sacred water here to carry on foot to Baidyanath Jyotirlinga.",
    officialWebsite: "https://bhagalpur.nic.in/tourist-place/ajgaibinath-temple/",
    sourceRecordId: "BR-TOUR-BHA-017",
    sourceName: "Bhagalpur District Administration & Ajgaibinath Seva Samiti",
    sourceUrl: "https://bhagalpur.nic.in/tourist-place/ajgaibinath-temple/",
    sourceType: "government",
  },
];

export async function importBiharTemples(options = {}) {
  return processStateBatch(
    "Bihar State Board of Religious Trusts & Bihar Tourism",
    "https://bsbrt.bihar.gov.in",
    BIHAR_AUTHORITATIVE_TEMPLES,
    options
  );
}

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ BIHAR TEMPLE INGESTION ENGINE");
  console.log("Source: Bihar State Board of Religious Trusts & Bihar Tourism");
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await importBiharTemples({
    dryRun: isDryRun,
    parserVersion: "v1.0.0",
  });

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);

