/**
 * Chhattisgarh Official State Ingestion Importer
 * Authoritative Sources:
 * - Chhattisgarh Tourism Board (https://tourism.cg.gov.in)
 * - Archaeological Survey of India (Raipur Circle) (https://asiraipurcircle.in)
 * - Maa Danteshwari Temple Management Trust, Dantewada
 * - District Administrations of Chhattisgarh
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const CHHATTISGARH_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Maa Danteshwari Temple Dantewada",
    nameLocal: "माँ दंतेश्वरी मंदिर दंतेवाड़ा",
    stateCode: "CG",
    districtName: "Dantewada",
    localityName: "Dantewada Town",
    latitude: 18.8958,
    longitude: 81.3533,
    mainDeity: "Goddess Danteshwari (Kuldevi of Bastar)",
    deities: ["Maa Danteshwari", "Bhairava", "Lord Ganesha"],
    templeType: "51 Maha Shakti Peethas (Daant / Tooth Peetha)",
    tradition: ["Shaktism", "Tribal-Sanatana Confluence"],
    architecture: "Historic Bastar Wood and Stone Temple Complex",
    historicalPeriod: "Kakatiya Dynasty / 14th Century CE",
    description: "Revered as one of the 51 Shakti Peethas where Sati's tooth fell. Presiding deity of Bastar region, sacred site of historic Bastar Dussehra.",
    officialWebsite: "https://dantewada.nic.in/tourist-place/danteshwari-temple/",
    sourceRecordId: "CG-TOUR-DNT-001",
    sourceName: "Chhattisgarh Tourism & Danteshwari Temple Trust",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "official",
  },
  {
    name: "Bhoramdeo Temple Complex Kawardha",
    nameLocal: "भोरमदेव मंदिर कवर्धा",
    stateCode: "CG",
    districtName: "Kabirdham",
    localityName: "Chhapri, Kawardha",
    latitude: 22.1228,
    longitude: 81.1472,
    mainDeity: "Lord Shiva (Bhoramdeo)",
    deities: ["Lord Shiva", "Uma-Maheshwara", "Surya"],
    templeType: "Historic Nagara Stone Monument (Khajuraho of Chhattisgarh)",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Sandstone Architecture with Intricate Carvings",
    historicalPeriod: "Nagavanshi Dynasty / 11th Century CE",
    description: "A monument protected by the Archaeological Survey of India standing amidst the Maikal range. Renowned for its temple erotica and intricately sculpted shikhara.",
    officialWebsite: "https://kawardha.gov.in/tourist-place/bhoramdeo-temple/",
    sourceRecordId: "CG-ASI-KAB-002",
    sourceName: "Archaeological Survey of India Raipur Circle & CG Tourism",
    sourceUrl: "https://asiraipurcircle.in",
    sourceType: "asi",
  },
  {
    name: "Lakshmana Brick Temple Sirpur",
    nameLocal: "लक्ष्मण मंदिर सिरपुर",
    stateCode: "CG",
    districtName: "Mahasamund",
    localityName: "Sirpur Village, Mahanadi River",
    latitude: 21.3414,
    longitude: 82.1794,
    mainDeity: "Lord Vishnu",
    deities: ["Lord Vishnu", "Sheshashayi Vishnu", "Krishna Avatars"],
    templeType: "7th-Century Ancient Brick Temple Marvel",
    tradition: ["Vaishnavism"],
    architecture: "Ancient Red Brick Nagara Architecture on Stone Plinth",
    historicalPeriod: "Somavanshi Dynasty / 7th Century CE",
    description: "One of the finest and best-preserved red brick temples in India, built by Queen Vasata in memory of King Harshagupta. Maintained by ASI.",
    officialWebsite: "https://mahasamund.gov.in/tourist-place/sirpur/",
    sourceRecordId: "CG-ASI-MAH-003",
    sourceName: "Archaeological Survey of India & Chhattisgarh Tourism",
    sourceUrl: "https://asiraipurcircle.in",
    sourceType: "asi",
  },
  {
    name: "Maa Bambleshwari Temple Dongargarh",
    nameLocal: "माँ बम्लेश्वरी मंदिर डोंगरगढ़",
    stateCode: "CG",
    districtName: "Rajnandgaon",
    localityName: "Dongargarh Hill",
    latitude: 21.1897,
    longitude: 80.7583,
    mainDeity: "Maa Bambleshwari (Badi Bambleshwari)",
    deities: ["Maa Bambleshwari", "Chhoti Bambleshwari", "Lord Hanuman"],
    templeType: "Hilltop Shakti Kshetra",
    tradition: ["Shaktism"],
    architecture: "Hilltop Shikhar Temple with Ropeway & 1000 Steps",
    historicalPeriod: "King Vikramaditya Tradition / Modern Shrine Trust",
    description: "Prominent pilgrimage center situated atop a 1,600-foot hill in Dongargarh. Millions of devotees visit during Chaitra and Sharad Navratri.",
    officialWebsite: "https://rajnandgaon.nic.in/tourist-place/dongargarh/",
    sourceRecordId: "CG-TOUR-RAJ-004",
    sourceName: "Maa Bambleshwari Trust & Chhattisgarh Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "official",
  },
  {
    name: "Rajiv Lochan Temple Rajim",
    nameLocal: "राजीव लोचन मंदिर राजिम",
    stateCode: "CG",
    districtName: "Gariaband",
    localityName: "Rajim, Triveni Sangam",
    latitude: 20.9614,
    longitude: 81.8797,
    mainDeity: "Rajiv Lochan (Lord Vishnu)",
    deities: ["Lord Vishnu (Lotus-Eyed)", "Garuda", "Kuleshwar Mahadev"],
    templeType: "Holy Prayag of Chhattisgarh (Triveni Sangam)",
    tradition: ["Vaishnavism"],
    architecture: "Ancient Panchayatana Sandstone Architecture",
    historicalPeriod: "Nala & Somavanshi Dynasties / 8th Century CE",
    description: "Located at the holy Triveni Sangam confluence of Mahanadi, Pairi, and Sondhur rivers. Center of the famous annual Rajim Kumbh Mela.",
    officialWebsite: "https://gariaband.nic.in/tourist-place/rajim-kumbh-mela/",
    sourceRecordId: "CG-TOUR-GAR-005",
    sourceName: "Gariaband Administration & Chhattisgarh Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Maa Chandrahasini Devi Temple Chandrapur",
    nameLocal: "माँ चंद्रहासिनी देवी मंदिर चंद्रपुर",
    stateCode: "CG",
    districtName: "Janjgir Champa",
    localityName: "Chandrapur, Mahanadi-Mand Confluence",
    latitude: 21.7061,
    longitude: 83.2189,
    mainDeity: "Goddess Chandrahasini (Moon-Faced Devi)",
    deities: ["Chandrahasini Devi", "Nathaldai Devi"],
    templeType: "River Confluence Siddha Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Ornate Modern Shikhara Temple on Mahanadi Banks",
    historicalPeriod: "Ancient Shakti Sthal / Contemporary Trust Renovation",
    description: "Revered Shakti shrine on the banks of the sacred Mahanadi River, famous for its grand Navratri celebrations and mechanical mythological tableaus.",
    officialWebsite: "https://janjgir-champa.gov.in/tourist-place/chandrahasini-temple-chandrapur/",
    sourceRecordId: "CG-TOUR-JAN-006",
    sourceName: "Chandrahasini Trust & Janjgir Champa Administration",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "official",
  },
  {
    name: "Mahamaya Temple Ratanpur",
    nameLocal: "महामाया मंदिर रतनपुर",
    stateCode: "CG",
    districtName: "Bilaspur",
    localityName: "Ratanpur Historic Capital",
    latitude: 22.2961,
    longitude: 82.1333,
    mainDeity: "Maa Mahamaya (Dual Deity of Saraswati and Lakshmi)",
    deities: ["Maa Mahamaya", "Maa Mahakali", "Bhairava"],
    templeType: "51 Maha Shakti Peethas (Right Shoulder Peetha)",
    tradition: ["Shaktism", "Kalachuri Tradition"],
    architecture: "Kalachuri Nagara Stone Architecture with Sacred Kund",
    historicalPeriod: "Kalachuri King Ratnadeva I / 1050 CE",
    description: "The historical religious seat of the Kalachuri rulers of Ratanpur. Worshipped as a premier Shakti Peetha of Central India.",
    officialWebsite: "https://bilaspur.gov.in/tourist-place/ratanpur/",
    sourceRecordId: "CG-TOUR-BIL-007",
    sourceName: "Siddha Peeth Shri Mahamaya Mandir Trust & Bilaspur Admin",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "official",
  },
  {
    name: "Karneshwar Temple & Shringi Rishi Ashram Sihawa",
    nameLocal: "कर्णेश्वर मंदिर सिहावा",
    stateCode: "CG",
    districtName: "Dhamtari",
    localityName: "Sihawa Hills, Source of Mahanadi",
    latitude: 20.2861,
    longitude: 81.9333,
    mainDeity: "Lord Shiva (Karneshwar Mahadev)",
    deities: ["Lord Shiva", "Maharshi Shringi", "Goddess Shanta"],
    templeType: "River Origin Sacred Ashram & Shaiva Shrines",
    tradition: ["Shaivism", "Vedic Sage Tradition"],
    architecture: "Ancient Somavanshi Stone Temple Group",
    historicalPeriod: "Somavanshi King Karnaraj / 12th Century CE",
    description: "Located near the origin point of the sacred Mahanadi River in the Sihawa hills, where Sage Shringi Rishi performed the Putrakameshti Yajna for King Dasharatha.",
    officialWebsite: "https://dhamtari.gov.in/tourist-place/sihawa/",
    sourceRecordId: "CG-TOUR-DHA-008",
    sourceName: "Dhamtari District Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Chitrakote Shiva Temple & Danteshwari Jagdalpur",
    nameLocal: "चित्रकोट शिव मंदिर एवं दंतेश्वरी जगदलपुर",
    stateCode: "CG",
    districtName: "Bastar",
    localityName: "Jagdalpur & Chitrakote",
    latitude: 19.2081,
    longitude: 81.7011,
    mainDeity: "Lord Shiva & Maa Danteshwari",
    deities: ["Lord Shiva", "Maa Danteshwari", "Lord Bhairav"],
    templeType: "Indravati River Sacred Horseshoe Waterfall Shrines",
    tradition: ["Shaivism", "Bastar Tribal Heritage"],
    architecture: "Indigenous Stone and Timber Sanctum",
    historicalPeriod: "Kakatiya Era / 15th Century CE",
    description: "Historic sacred shrine complex located near the majestic Chitrakote Falls on the Indravati River, known as the Niagara of India.",
    officialWebsite: "https://bastar.gov.in/tourist-place/chitrakote-waterfall/",
    sourceRecordId: "CG-TOUR-BAS-009",
    sourceName: "Bastar District Administration & CG Tourism",
    sourceUrl: "https://bastar.gov.in",
    sourceType: "government",
  },
  {
    name: "Mahamaya Temple Ambikapur",
    nameLocal: "महामाया मंदिर अंबिकापुर",
    stateCode: "CG",
    districtName: "Surguja",
    localityName: "Ambikapur City",
    latitude: 23.1186,
    longitude: 83.1975,
    mainDeity: "Maa Mahamaya / Ambika Devi",
    deities: ["Ambika Devi", "Samaleswari", "Bhairava"],
    templeType: "Surguja Royal Kuldevi Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Traditional Central Indian Shikhara Architecture",
    historicalPeriod: "Surguja State Royal Dynasty / 16th Century CE",
    description: "The presiding goddess from whom Ambikapur derives its name. Highly revered across northern Chhattisgarh and adjacent Jharkhand regions.",
    officialWebsite: "https://surguja.gov.in/tourist-place/mahamaya-temple/",
    sourceRecordId: "CG-TOUR-SUR-010",
    sourceName: "Surguja District Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Maa Kankali Temple Kanker",
    nameLocal: "माँ कंकाली मंदिर कांकेर",
    stateCode: "CG",
    districtName: "Kanker",
    localityName: "Kanker Town",
    latitude: 20.2719,
    longitude: 81.4931,
    mainDeity: "Maa Kankali Devi",
    deities: ["Maa Kankali", "Lord Shiva", "Bhairava"],
    templeType: "Historic Kanker Royal Fortress Temple",
    tradition: ["Shaktism"],
    architecture: "Traditional Bastar Foothill Stone Architecture",
    historicalPeriod: "Kanker Royal Dynasty / 12th Century CE",
    description: "Historical temple dedicated to Goddess Kankali, situated at the base of the scenic Gadiya mountain fortress in North Bastar.",
    officialWebsite: "https://kanker.gov.in/tourist-place/kankali-temple/",
    sourceRecordId: "CG-TOUR-KAN-011",
    sourceName: "Kanker District Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Sarvamangala Temple Korba",
    nameLocal: "सर्वमंगला मंदिर कोरबा",
    stateCode: "CG",
    districtName: "Korba",
    localityName: "Hasdeo River Bank, Korba",
    latitude: 22.3619,
    longitude: 82.7233,
    mainDeity: "Maa Sarvamangala (Durga)",
    deities: ["Maa Durga", "Lord Shiva", "Trilokinath"],
    templeType: "Hasdeo River Sacred Shrine",
    tradition: ["Shaktism"],
    architecture: "Modern North Indian Nagara Style Temple",
    historicalPeriod: "Zamindari Era / 19th Century CE",
    description: "Most prominent religious center of the industrial hub Korba, situated on the banks of the sacred Hasdeo River, featuring subterranean caves.",
    officialWebsite: "https://korba.gov.in/tourist-place/sarvamangala-temple/",
    sourceRecordId: "CG-TOUR-KOR-012",
    sourceName: "Korba District Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Pahar Mandir Raigarh",
    nameLocal: "पहाड़ मंदिर रायगढ़",
    stateCode: "CG",
    districtName: "Raigarh",
    localityName: "Raigarh Hilltop",
    latitude: 21.8972,
    longitude: 83.3956,
    mainDeity: "Lord Shiva (Pahadi Mahadev)",
    deities: ["Lord Shiva", "Parvati", "Nandi"],
    templeType: "Hilltop Shaivite Pilgrimage",
    tradition: ["Shaivism"],
    architecture: "White Marble Shikhara Shrine atop Raigarh Hill",
    historicalPeriod: "19th Century CE / Community Trust",
    description: "Prominent hilltop temple in the cultural city of Raigarh, offering sweeping views of the Kelo river valley and hosting grand Maha Shivaratri fairs.",
    officialWebsite: "https://raigarh.gov.in/tourist-place/pahar-mandir/",
    sourceRecordId: "CG-TOUR-RAI-013",
    sourceName: "Raigarh District Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Giroudpuri Dham & Jaitkham",
    nameLocal: "गिरौदपुरी धाम एवं जैतखाम",
    stateCode: "CG",
    districtName: "Baloda Bazar",
    localityName: "Giroudpuri, Mahanadi Bank",
    latitude: 21.6586,
    longitude: 82.5761,
    mainDeity: "Satnam Guru Ghasidas Ji Sacred Memorial",
    deities: ["Satguru Ghasidas Ji Sthal", "Charnodak Kund"],
    templeType: "Supreme Sacred Satnampanth Pilgrimage Centre",
    tradition: ["Satnam Tradition", "Monotheistic Bhakti"],
    architecture: "World's Tallest Jaitkham Monument (77 meters) & Shrines",
    historicalPeriod: "18th Century CE Birthplace / Modern Pilgrimage Complex",
    description: "The holiest pilgrimage center for millions of Satnam devotees across India, birthplace of Guru Ghasidas who preached equality, truth, and non-violence.",
    officialWebsite: "https://balodabazar.gov.in/tourist-place/giroudpuri-dham/",
    sourceRecordId: "CG-TOUR-BLB-014",
    sourceName: "Baloda Bazar Administration & CG Tourism",
    sourceUrl: "https://balodabazar.gov.in",
    sourceType: "government",
  },
  {
    name: "Kotebira Mahadev Temple Pathalgaon",
    nameLocal: "कोटेबीरा महादेव मंदिर पत्थलगांव",
    stateCode: "CG",
    districtName: "Jashpur",
    localityName: "Kotebira, Eeb River Gorge",
    latitude: 22.5636,
    longitude: 83.8475,
    mainDeity: "Lord Shiva (Kotebira Mahadev)",
    deities: ["Lord Shiva", "Mata Parvati", "Ganga"],
    templeType: "Sacred River Gorge Rock-Cut Cavern Shrine",
    tradition: ["Shaivism"],
    architecture: "Natural Rock-Cut Cavern along Eeb River",
    historicalPeriod: "Ancient Tribal-Vedic Sacred Site",
    description: "Picturesque holy site where the Eeb River cuts a narrow canyon through ancient rock beds. Revered during Maha Shivaratri with deep tribal reverence.",
    officialWebsite: "https://jashpur.nic.in/tourist-place/kotebira-eb-river/",
    sourceRecordId: "CG-TOUR-JAS-015",
    sourceName: "Jashpur District Administration & CG Tourism",
    sourceUrl: "https://jashpur.nic.in",
    sourceType: "government",
  },
  {
    name: "Bhadrakali Temple Bemetara",
    nameLocal: "भद्रकाली मंदिर बेमेतरा",
    stateCode: "CG",
    districtName: "Bemetara",
    localityName: "Bemetara Town",
    latitude: 21.7022,
    longitude: 81.5475,
    mainDeity: "Goddess Bhadrakali",
    deities: ["Bhadrakali Devi", "Lord Shiva"],
    templeType: "Ancient Shakta Peetha",
    tradition: ["Shaktism"],
    architecture: "Traditional Chhattisgarh Shikhar Temple",
    historicalPeriod: "Kalachuri Dynasty Footprint / Renovated",
    description: "One of the most revered ancient temples in Bemetara district, drawing thousands of devotees during Chaitra and Sharadiya Navratri.",
    officialWebsite: "https://bemetara.gov.in/tourist-place/bhadrakali-mandir/",
    sourceRecordId: "CG-TOUR-BEM-016",
    sourceName: "Bemetara District Administration & CG Tourism",
    sourceUrl: "https://bemetara.gov.in",
    sourceType: "government",
  },
  {
    name: "Bhairamgarh Temple Complex",
    nameLocal: "भैरमगढ़ मंदिर संकुल",
    stateCode: "CG",
    districtName: "Bijapur",
    localityName: "Bhairamgarh",
    latitude: 18.8478,
    longitude: 80.8953,
    mainDeity: "Lord Bhairav & Shiva",
    deities: ["Bhairav", "Lord Shiva", "Goddess Durga"],
    templeType: "Historical Bastar Fort Shrine",
    tradition: ["Shaivism", "Tantra"],
    architecture: "Ancient Stone Carvings and Fort Complex",
    historicalPeriod: "Nagavanshi & Kakatiya Eras / 13th Century CE",
    description: "Historical sanctuary in southern Chhattisgarh with ancient stone images and fort ruins representing early medieval Bastar kingdom history.",
    officialWebsite: "https://bijapur.gov.in/tourist-place/bhairamgarh/",
    sourceRecordId: "CG-TOUR-BIJ-017",
    sourceName: "Bijapur District Administration & CG Tourism",
    sourceUrl: "https://bijapur.gov.in",
    sourceType: "government",
  },
  {
    name: "Jaleshwar Mahadev Temple Gaurella",
    nameLocal: "जलेश्वर महादेव मंदिर गौरेला",
    stateCode: "CG",
    districtName: "Gaurella Pendra Marwahi",
    localityName: "Jaleshwar, Amarkantak Border",
    latitude: 22.7667,
    longitude: 81.7500,
    mainDeity: "Lord Shiva (Jaleshwar Mahadev)",
    deities: ["Lord Shiva", "Nandi", "Narmada Devi"],
    templeType: "Source of Narmada-Son Sanctum",
    tradition: ["Shaivism"],
    architecture: "Ancient Stone Shikhara Temple",
    historicalPeriod: "Kalachuri Period / 11th Century CE",
    description: "Sacred Shiva shrine located in the holy Amarkantak plateau foothills, considered the source point of the sacred Jaleshwar stream.",
    officialWebsite: "https://gaurela-pendra-marwahi.cg.gov.in/tourist-place/jaleshwar-temple/",
    sourceRecordId: "CG-TOUR-GPM-018",
    sourceName: "Gaurella-Pendra-Marwahi Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Mandhata Shiva Temple Khairagarh",
    nameLocal: "मान्धाता शिव मंदिर खैरागढ़",
    stateCode: "CG",
    districtName: "Khairgarh Chhuikhadan",
    localityName: "Khairagarh, Amner-Pipariya Confluence",
    latitude: 21.4183,
    longitude: 80.9753,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Goddess Rukhad Devi"],
    templeType: "Royal Music City Confluence Temple",
    tradition: ["Shaivism"],
    architecture: "Historic Nagara Temple in Royal Estate",
    historicalPeriod: "Nagavanshi Era / Royal Khairagarh State",
    description: "Sacred confluence temple in India's premier university city of Indian classical music and fine arts, Khairagarh.",
    officialWebsite: "https://khairagarh-chhuikhadan-gandai.cg.gov.in/",
    sourceRecordId: "CG-TOUR-KHA-019",
    sourceName: "Khairagarh-Chhuikhadan Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Alor Lingeshwar Mahadev Cave Temple",
    nameLocal: "आलोर लिंगेश्वर महादेव मंदिर",
    stateCode: "CG",
    districtName: "Kondagaon",
    localityName: "Alor Village, Kondagaon",
    latitude: 19.6847,
    longitude: 81.6592,
    mainDeity: "Lord Shiva (Lingeshwar)",
    deities: ["Self-Manifested Swayambhu Shiva Lingam"],
    templeType: "Miraculous Annual Opening Cave Temple",
    tradition: ["Shaivism", "Tribal Faith"],
    architecture: "Natural Hilltop Cave Shrine",
    historicalPeriod: "Ancient Tribal Legend",
    description: "Famous cave temple that opens only once a year on the first Wednesday after Diwali. Thousands of childless couples visit to seek divine blessings.",
    officialWebsite: "https://kondagaon.gov.in/tourist-place/lingeshwar-temple-alor/",
    sourceRecordId: "CG-TOUR-KON-020",
    sourceName: "Kondagaon District Administration & CG Tourism",
    sourceUrl: "https://kondagaon.gov.in",
    sourceType: "government",
  },
  {
    name: "Chirmiri Jagannath Mandir",
    nameLocal: "चिरमिरी जगन्नाथ मंदिर",
    stateCode: "CG",
    districtName: "Koriya",
    localityName: "Chirmiri Hill City",
    latitude: 23.1814,
    longitude: 82.3511,
    mainDeity: "Lord Jagannath",
    deities: ["Lord Jagannath", "Balabhadra", "Subhadra"],
    templeType: "Puri Dham Replica Hilltop Shrine",
    tradition: ["Vaishnavism", "Jagannath Tradition"],
    architecture: "Kalinga Style Shikhara Architecture",
    historicalPeriod: "1960 CE by Odia Mining Community",
    description: "Magnificent replica of the sacred Shree Jagannath Temple of Puri, built atop a hill in the coal-mining green valleys of Chirmiri.",
    officialWebsite: "https://koriya.gov.in/tourist-place/jagannath-mandir-chirmiri/",
    sourceRecordId: "CG-TOUR-KOR-021",
    sourceName: "Koriya District Administration & CG Tourism",
    sourceUrl: "https://koriya.gov.in",
    sourceType: "government",
  },
  {
    name: "Amritdhara Shiva Temple Complex",
    nameLocal: "अमृतधारा शिव मंदिर",
    stateCode: "CG",
    districtName: "Manendragarh",
    localityName: "Amritdhara Waterfall, Hasdeo River",
    latitude: 23.3361,
    longitude: 82.3278,
    mainDeity: "Lord Shiva (Amriteshwar Mahadev)",
    deities: ["Lord Shiva", "Parvati"],
    templeType: "Water Cascade Sacred Fair Tirtha",
    tradition: ["Shaivism"],
    architecture: "Historic Shikhara Temple on Hasdeo Waterfall Ridge",
    historicalPeriod: "Koriya King Ramanuj Pratap Singh Deo Fair Tradition (1936)",
    description: "Famous waterfall tirtha on the Hasdeo River hosting the grand annual Maha Shivaratri Mela instituted by the royal house of Koriya.",
    officialWebsite: "https://mcbg.cg.gov.in/tourist-place/amritdhara-waterfall/",
    sourceRecordId: "CG-TOUR-MAN-022",
    sourceName: "Manendragarh-Chirmiri-Bharatpur Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Mohla Ancient Shiva Temple",
    nameLocal: "मोहला प्राचीन शिव मंदिर",
    stateCode: "CG",
    districtName: "Mohla Manpur",
    localityName: "Mohla, Kotri River Basin",
    latitude: 20.7333,
    longitude: 80.7333,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Nandi"],
    templeType: "Forest Heritage Shaivite Shrine",
    tradition: ["Shaivism"],
    architecture: "Ancient Central Indian Sandstone Mandapa",
    historicalPeriod: "Medieval Tribal Chieftain Period",
    description: "Venerated Shiva shrine located in the serene forest heartland of Mohla-Manpur-Ambagarh Chowki in southwest Chhattisgarh.",
    officialWebsite: "https://mmac.cg.gov.in/",
    sourceRecordId: "CG-TOUR-MOH-023",
    sourceName: "Mohla-Manpur District Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Setganga Shriram Janki Mandir",
    nameLocal: "श्वेतगंगा श्रीराम जानकी मंदिर",
    stateCode: "CG",
    districtName: "Mungeli",
    localityName: "Setganga Village, Mungeli",
    latitude: 22.0667,
    longitude: 81.6833,
    mainDeity: "Lord Rama & Mata Sita",
    deities: ["Lord Rama", "Mata Sita", "Lakshmana", "Shweta Ganga Kund"],
    templeType: "Sacred Natural Spring Temple (Shweta Ganga)",
    tradition: ["Vaishnavism"],
    architecture: "Nagara Style Temple with Underground Water Channel",
    historicalPeriod: "Kalachuri Dynasty / 10th-11th Century CE",
    description: "Famous for its natural holy spring (Shweta Ganga / Setganga) where water perpetually flows from an underground channel into the sacred kund.",
    officialWebsite: "https://mungeli.gov.in/tourist-place/setganga/",
    sourceRecordId: "CG-TOUR-MUN-024",
    sourceName: "Mungeli District Administration & CG Tourism",
    sourceUrl: "https://mungeli.gov.in",
    sourceType: "government",
  },
  {
    name: "Gadiya Mountain Cave Shrines Narayanpur",
    nameLocal: "गड़िया पहाड़ गुफा मंदिर नारायणपुर",
    stateCode: "CG",
    districtName: "Narayanpur",
    localityName: "Abujhmad Foothills, Narayanpur",
    latitude: 19.7167,
    longitude: 81.2500,
    mainDeity: "Lord Shiva & Tribal Deities",
    deities: ["Lord Shiva", "Bhairava", "Danteshwari Mata"],
    templeType: "Sacred Abujhmad Rock Shelter Shrines",
    tradition: ["Shaivism", "Abujhmad Indigenous Sacred Traditions"],
    architecture: "Natural Rock Shelters and Stone Shrines",
    historicalPeriod: "Ancient Indigenous Bastar Sanctuary",
    description: "Sacred rocky mountain sanctum guarding the threshold of the deep Abujhmad forests in Narayanpur, center of traditional tribal festivals.",
    officialWebsite: "https://narayanpur.gov.in/",
    sourceRecordId: "CG-TOUR-NAR-025",
    sourceName: "Narayanpur District Administration & CG Tourism",
    sourceUrl: "https://narayanpur.gov.in",
    sourceType: "government",
  },
  {
    name: "Adbhar Ashtabhuji Mandir",
    nameLocal: "अड़भार अष्टभुजी मंदिर",
    stateCode: "CG",
    districtName: "Sakti",
    localityName: "Adbhar Town, Sakti",
    latitude: 21.8547,
    longitude: 82.9739,
    mainDeity: "Goddess Ashtabhuji (Eight-Armed Durga)",
    deities: ["Ashtabhuji Devi", "Jyoti Kalash"],
    templeType: "Ancient Shakta Siddha Peetha",
    tradition: ["Shaktism"],
    architecture: "Ancient Stone Carvings & Contemporary Grand Shikhara",
    historicalPeriod: "Somavanshi Period / Renovated Temple Trust",
    description: "Famous for thousands of akhand jyotis lit by devotees during Navratri. Ancient stone remains date back to early medieval Somavanshi rule.",
    officialWebsite: "https://sakti.cg.gov.in/",
    sourceRecordId: "CG-TOUR-SAK-026",
    sourceName: "Sakti District Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Bilaigarh Jagannath Mandir",
    nameLocal: "बिलाईगढ़ जगन्नाथ मंदिर",
    stateCode: "CG",
    districtName: "Sarangarh Bilaigarh",
    localityName: "Bilaigarh Town",
    latitude: 21.6361,
    longitude: 82.9833,
    mainDeity: "Lord Jagannath",
    deities: ["Lord Jagannath", "Balabhadra", "Subhadra"],
    templeType: "Historical Zamindari Jagannath Temple",
    tradition: ["Vaishnavism", "Jagannath Cult"],
    architecture: "Kalinga Influenced Shikhara Architecture",
    historicalPeriod: "Bilaigarh Royal Zamindari / 18th Century CE",
    description: "Historic Jagannath temple celebrating the grand annual Ratha Yatra on the borders of Chhattisgarh and Western Odisha.",
    officialWebsite: "https://sarangarh-bilaigarh.cg.gov.in/",
    sourceRecordId: "CG-TOUR-SAR-027",
    sourceName: "Sarangarh-Bilaigarh District Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Dornapal Shiva Temple Sabari River",
    nameLocal: "दोर्नपाल शिव मंदिर शबरी नदी",
    stateCode: "CG",
    districtName: "Sukma",
    localityName: "Dornapal, Sabari River",
    latitude: 18.3639,
    longitude: 81.5694,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Mata Sabari Sthal"],
    templeType: "Sabari River Confluence Pilgrimage",
    tradition: ["Shaivism", "Ramayana Sthal Tradition"],
    architecture: "Coastal-Style Riverfront Stone Temple",
    historicalPeriod: "Puranic Sabari Tradition / Modern Shrine",
    description: "Located along the sacred Sabari River in southernmost Chhattisgarh, tied to the epic Ramayana traditions of the Dandakaranya forest.",
    officialWebsite: "https://sukma.gov.in/",
    sourceRecordId: "CG-TOUR-SUK-028",
    sourceName: "Sukma District Administration & CG Tourism",
    sourceUrl: "https://sukma.gov.in",
    sourceType: "government",
  },
  {
    name: "Kudargarh Maa Bagheshwari Devi",
    nameLocal: "कुदरगढ़ माँ बागेश्वरी देवी मंदिर",
    stateCode: "CG",
    districtName: "Surajpur",
    localityName: "Kudargarh Hilltop, Surajpur",
    latitude: 23.4547,
    longitude: 82.8833,
    mainDeity: "Maa Bagheshwari Devi",
    deities: ["Bagheshwari Devi", "Lord Bhairav"],
    templeType: "Hilltop Shakta Pilgrimage Center",
    tradition: ["Shaktism"],
    architecture: "High Ridge Hilltop Temple with Sacred Kund",
    historicalPeriod: "Balan Royal Chieftains / Ancient Sacred Hill",
    description: "Famous pilgrimage destination situated on a 1,500-foot hilltop in Surajpur district, drawing lakhs of devotees during Navratri.",
    officialWebsite: "https://surajpur.nic.in/tourist-place/kudargarh/",
    sourceRecordId: "CG-TOUR-SRP-029",
    sourceName: "Kudargarh Temple Trust & Surajpur Administration",
    sourceUrl: "https://surajpur.nic.in",
    sourceType: "official",
  },
  {
    name: "Vishrampur Shiv Mandir",
    nameLocal: "विश्रामपुर शिव मंदिर",
    stateCode: "CG",
    districtName: "Vishrampur",
    localityName: "Vishrampur Town, Surguja Coalfield",
    latitude: 23.2750,
    longitude: 82.9833,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Parvati"],
    templeType: "Mining Township Sacred Temple",
    tradition: ["Shaivism"],
    architecture: "Modern North Indian Temple",
    historicalPeriod: "Mid 20th Century CE",
    description: "Revered Shiva temple serving as the spiritual heart of the northern Chhattisgarh industrial-mining region in Vishrampur.",
    officialWebsite: "https://tourism.cg.gov.in",
    sourceRecordId: "CG-TOUR-VIS-030",
    sourceName: "Vishrampur Municipal Administration & CG Tourism",
    sourceUrl: "https://tourism.cg.gov.in",
    sourceType: "government",
  },
  {
    name: "Tatapani Hot Springs Shiva Temple",
    nameLocal: "तातापानी गर्म जल शिव मंदिर",
    stateCode: "CG",
    districtName: "Balrampur",
    localityName: "Tatapani, Balrampur-Ramanujganj",
    latitude: 23.6872,
    longitude: 83.6558,
    mainDeity: "Lord Shiva (Tateshwar Mahadev)",
    deities: ["Lord Shiva", "Giant Shiva Statue", "Hot Geothermal Springs"],
    templeType: "Geothermal Natural Hot Springs Teerth",
    tradition: ["Shaivism"],
    architecture: "Temple Complex with Natural Hot Sulphur Springs Kund",
    historicalPeriod: "Ancient Geothermal Pilgrimage / Renovated Complex",
    description: "Famous pilgrimage and geological wonder known for its perennial hot water springs and massive Shiva statue, hosting the major annual Tatapani Mahotsav on Makar Sankranti.",
    officialWebsite: "https://balrampur.gov.in/tourist-place/tatapani/",
    sourceRecordId: "CG-TOUR-BLP-031",
    sourceName: "Balrampur District Administration & CG Tourism",
    sourceUrl: "https://balrampur.gov.in",
    sourceType: "government",
  },
];

export async function importChhattisgarhTemples(options: { dryRun?: boolean; parserVersion?: string } = {}) {
  console.log("==================================================");
  console.log("🏛️ CHHATTISGARH TEMPLE INGESTION ENGINE");
  console.log("Source: Chhattisgarh Tourism, ASI Raipur & Temple Trusts");
  console.log(`Mode: ${options.dryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  return processStateBatch(
    "Chhattisgarh Tourism, ASI Raipur & Temple Trusts",
    "https://tourism.cg.gov.in",
    CHHATTISGARH_AUTHORITATIVE_TEMPLES,
    options
  );
}

// CLI runner
if (process.argv[1]?.endsWith("chhattisgarh.ts")) {
  const isDryRun = process.argv.includes("--dry-run");
  importChhattisgarhTemples({ dryRun: isDryRun })
    .then((report) => {
      console.log("\nTelemetry Report:");
      console.log(JSON.stringify(report, null, 2));
      process.exit(0);
    })
    .catch((err) => {
      console.error("\n❌ Importer crashed:", err);
      process.exit(1);
    });
}
