/**
 * Gujarat Official State Ingestion Importer
 * Authoritative Source: Shree Somnath Trust, Ambaji Devasthan, Dwarkadhish Devasthan Committee, Gujarat Pavitra Yatradham Vikas Board
 * Portal: https://somnath.org / https://ambajitemple.in / https://dwarkadhish.org / https://yatradham.gujarat.gov.in
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const GUJARAT_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Somnath Jyotirlinga Temple",
    nameLocal: "સોમનાથ જ્યોતિર્લિંગ મંદિર",
    stateCode: "GJ",
    districtName: "Gir Somnath",
    localityName: "Prabhas Patan, Veraval",
    latitude: 20.8880,
    longitude: 70.4012,
    mainDeity: "Somnath (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "First of the Twelve Holy Jyotirlingas",
    tradition: ["Shaivism"],
    architecture: "Maru-Gurjara (Chalukyan) Stone Architecture on Arabian Sea",
    historicalPeriod: "Rebuilt by Sardar Vallabhbhai Patel (Consecrated 1951 CE)",
    description: "Revered as the first among the twelve holy Jyotirlinga shrines of Lord Shiva, located on the shore of the Arabian Sea. Famed for the Baan Stambh (arrow pillar) pointing uninterruptedly to the South Pole.",
    officialWebsite: "https://somnath.org",
    sourceRecordId: "GJ-YATRA-SOM-001",
    sourceName: "Shree Somnath Trust & Gujarat Tourism",
    sourceUrl: "https://somnath.org",
    sourceType: "government",
  },
  {
    name: "Dwarkadhish Temple Dwarka",
    nameLocal: "દ્વારકાધીશ મંદિર જગતમંદિર",
    stateCode: "GJ",
    districtName: "Devbhoomi Dwarka",
    localityName: "Dwarka",
    latitude: 22.2376,
    longitude: 68.9678,
    mainDeity: "Dwarkadhish (Lord Krishna, King of Dwarka)",
    deities: ["Lord Krishna", "Balarama", "Subhadra", "Pradyumna"],
    templeType: "Maha Char Dham & Mokshapuri",
    tradition: ["Vaishnavism", "Pushtimarg"],
    architecture: "Chalukyan Five-Storeyed Sandstone Temple with 72 Pillars (Jagat Mandir)",
    historicalPeriod: "Vajranabha (Grandson of Krishna) / 16th Century Expansion",
    description: "One of the four cardinal Char Dham pilgrimage centers in India and one of seven holy Mokshapuris. Features the 52-yard sacred flag (Dhvaja) hoisted five times daily above its 78-meter pinnacle.",
    officialWebsite: "https://dwarkadhish.org",
    sourceRecordId: "GJ-YATRA-DWA-002",
    sourceName: "Dwarkadhish Devasthan Samiti & Devbhoomi Dwarka Administration",
    sourceUrl: "https://dwarkadhish.org",
    sourceType: "government",
  },
  {
    name: "Nageshwar Jyotirlinga Temple",
    nameLocal: "નાગેશ્વર જ્યોતિર્લિંગ મંદિર",
    stateCode: "GJ",
    districtName: "Devbhoomi Dwarka",
    localityName: "Daarukavanam, Dwarka",
    latitude: 22.3353,
    longitude: 69.0558,
    mainDeity: "Nageshwar (Lord Shiva)",
    deities: ["Lord Shiva", "Nageshwari Devi"],
    templeType: "Sacred Jyotirlinga Shrine",
    tradition: ["Shaivism"],
    architecture: "Modern Stone Complex with 80-Foot Towering Shiva Statue",
    historicalPeriod: "Ancient Puranic Darukavana Kshetra",
    description: "One of the 12 holy Jyotirlingas, situated between Dwarka and Bet Dwarka. Renowned for its southward-facing swayambhu lingam and colossal 80-foot statue of Lord Shiva in seated posture.",
    officialWebsite: "https://yatradham.gujarat.gov.in/Destinations/DevbhumiDwarka/Nageshwar.aspx",
    sourceRecordId: "GJ-YATRA-NAG-003",
    sourceName: "Gujarat Pavitra Yatradham Vikas Board",
    sourceUrl: "https://yatradham.gujarat.gov.in",
    sourceType: "government",
  },
  {
    name: "Shree Arasuri Ambaji Mata Temple",
    nameLocal: "શ્રી આરાસુરી અંબાજી માતા મંદિર",
    stateCode: "GJ",
    districtName: "Banaskantha",
    localityName: "Ambaji, Danta",
    latitude: 24.3314,
    longitude: 72.8539,
    mainDeity: "Amba Mata (Vishwakarma Viso Yantra worship)",
    deities: ["Goddess Amba"],
    templeType: "Maha Shakti Peetha (Hridaya Peetha)",
    tradition: ["Shaktism", "Sri Vidya"],
    architecture: "White Marble Architecture with Gold-Plated Kalash atop Arasur Hills",
    historicalPeriod: "Ancient Pre-Vedic Tradition / Solanki Era Sanctum",
    description: "One of the 51 holy Shakti Peethas where the heart of Goddess Sati fell. Uniquely worships no idol but a sacred, gold-plated Viso Yantra inscribed with Vedic mantras, visited by millions during Bhadarvi Poonam.",
    officialWebsite: "https://ambajitemple.in",
    sourceRecordId: "GJ-AMB-BAN-004",
    sourceName: "Shri Arasuri Ambaji Mata Devasthan Trust",
    sourceUrl: "https://ambajitemple.in",
    sourceType: "government",
  },
  {
    name: "Sun Temple Modhera",
    nameLocal: "મોઢેરા સૂર્ય મંદિર",
    stateCode: "GJ",
    districtName: "Mahesana",
    localityName: "Modhera",
    latitude: 23.5836,
    longitude: 72.1331,
    mainDeity: "Surya Deva (Sun God)",
    deities: ["Surya Deva"],
    templeType: "ASI Monument of National Importance",
    tradition: ["Saurism", "Smartha"],
    architecture: "Maru-Gurjara Solanki Stone Architecture with 108 Mini-Shrines around Surya Kund",
    historicalPeriod: "Solanki Dynasty / King Bhima I (1026 CE)",
    description: "An architectural marvel situated on the banks of River Pushpavati, designed so that the first rays of the equinox sun illuminate the inner sanctum. Features the grand stepped water reservoir (Surya Kund).",
    officialWebsite: "https://asi.nic.in/monuments-modhera/",
    sourceRecordId: "ASI-GJ-W-GJ-C1",
    sourceName: "Archaeological Survey of India & Gujarat Tourism",
    sourceUrl: "https://asi.nic.in/monuments-modhera/",
    sourceType: "government",
  },
  {
    name: "Shri Bahucharaji Mata Temple",
    nameLocal: "શ્રી બહુચરાજી માતા મંદિર",
    stateCode: "GJ",
    districtName: "Mahesana",
    localityName: "Becharaji",
    latitude: 23.4983,
    longitude: 72.0394,
    mainDeity: "Bala Tripura Sundari (Bahucharaji Mata)",
    deities: ["Bahucharaji"],
    templeType: "Prominent Shakta Pilgrimage Center",
    tradition: ["Shaktism"],
    architecture: "Nagara Style Stone Sanctum with Golden Shikhara",
    historicalPeriod: "Manaji Rao Gaekwad of Baroda (1783 CE)",
    description: "Revered as one of Gujarat's supreme mother goddess shrines, located in Mahesana district. Enshrines the goddess mounted on a rooster (Kukkuta) with ancient tantric Sri Chakra worship.",
    officialWebsite: "https://yatradham.gujarat.gov.in/Destinations/Mehsana/Bahucharaji.aspx",
    sourceRecordId: "GJ-YATRA-MAH-005",
    sourceName: "Shree Bahucharaji Mataji Temple Trust & Yatradham Board",
    sourceUrl: "https://yatradham.gujarat.gov.in",
    sourceType: "government",
  },
  {
    name: "Akshardham Mandir Gandhinagar",
    nameLocal: "અક્ષરધામ મંદિર ગાંધીનગર",
    stateCode: "GJ",
    districtName: "Gandhinagar",
    localityName: "Sector 20, Gandhinagar",
    latitude: 23.2325,
    longitude: 72.6739,
    mainDeity: "Bhagwan Swaminarayan",
    deities: ["Swaminarayan", "Gunatitanand Swami"],
    templeType: "Monumental Cultural & Spiritual Sansthan",
    tradition: ["Vaishnavism", "Swaminarayan"],
    architecture: "Intricately Sculpted Rajasthani Pink Sandstone Monolith (No Steel)",
    historicalPeriod: "Pramukh Swami Maharaj (Consecrated 1992 CE)",
    description: "A colossal spiritual complex carved from 6,000 tonnes of pink sandstone without the use of structural steel. Displays 97 sculpted pillars, 17 ornate domes, and extensive landscaped thematic gardens.",
    officialWebsite: "https://akshardham.com/gujarat/",
    sourceRecordId: "GJ-YATRA-GAN-006",
    sourceName: "BAPS Sansthan & Gujarat Tourism",
    sourceUrl: "https://akshardham.com/gujarat/",
    sourceType: "government",
  },
  {
    name: "Shamlaji Vishnu Temple",
    nameLocal: "શામળાજી મંદિર અરવલ્લી",
    stateCode: "GJ",
    districtName: "Aravalli",
    localityName: "Shamlaji",
    latitude: 23.6881,
    longitude: 73.3853,
    mainDeity: "Gadadhar Vishnu (Lord Shamlaji / Dark Krishna)",
    deities: ["Lord Vishnu", "Krishna"],
    templeType: "Ancient Vaishnavite Tirtha on River Meshwo",
    tradition: ["Vaishnavism"],
    architecture: "11th Century Maru-Gurjara White Sandstone with Elephant Friezes",
    historicalPeriod: "Chalukyan & Solanki Periods (11th Century CE)",
    description: "Enshrines a revered black stone idol of Lord Vishnu bearing mace, discus, conch, and lotus, situated on the banks of River Meshwo in Aravalli district. Famed for its massive tribal Kartik Purnima fair.",
    officialWebsite: "https://arvalli.nic.in/tourist-place/shamlaji-temple/",
    sourceRecordId: "GJ-YATRA-ARA-007",
    sourceName: "Shamlaji Temple Trust & Aravalli Administration",
    sourceUrl: "https://arvalli.nic.in/tourist-place/shamlaji-temple/",
    sourceType: "government",
  },
  {
    name: "Mahakali Temple Pavagadh",
    nameLocal: "મહાકાળી મંદિર પાવાગઢ",
    stateCode: "GJ",
    districtName: "Panch Mahals",
    localityName: "Pavagadh Hill, Halol",
    latitude: 22.4633,
    longitude: 73.5208,
    mainDeity: "Maa Mahakali",
    deities: ["Mahakali", "Bahuchara"],
    templeType: "UNESCO World Heritage Site (Champaner-Pavagadh) & Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Mountain-Peak Stone Sanctum with Golden Dhvaja Kalash",
    historicalPeriod: "Solanki Era & 11th Century CE Origin",
    description: "Perched 800 meters atop Pavagadh Hill overlooking the Champaner plains, venerated as the toe shrine of Sati. The newly restored shikhar with gold-plated flagstaff welcomes millions of pilgrims.",
    officialWebsite: "https://yatradham.gujarat.gov.in/Destinations/Panchmahal/Pavagadh.aspx",
    sourceRecordId: "GJ-YATRA-PAN-008",
    sourceName: "Shri Aradhana Trust Pavagadh & Gujarat Tourism",
    sourceUrl: "https://yatradham.gujarat.gov.in",
    sourceType: "government",
  },
  {
    name: "Shri Kashtbhanjan Dev Hanuman Mandir Salangpur",
    nameLocal: "શ્રી કષ્ટભંજન દેવ હનુમાન મંદિર સાળંગપુર",
    stateCode: "GJ",
    districtName: "Botad",
    localityName: "Salangpur, Barwala",
    latitude: 22.1469,
    longitude: 71.7619,
    mainDeity: "Kashtbhanjan Dev (Lord Hanuman Crushing Sorcery)",
    deities: ["Hanuman"],
    templeType: "World-Renowned Hanuman Kshetra",
    tradition: ["Vaishnavism", "Swaminarayan"],
    architecture: "Grand Golden Shikhara Shrine with 54-Foot Bronze Murti",
    historicalPeriod: "Gopalanand Swami (Consecrated 1848 CE)",
    description: "Dedicated to Lord Hanuman as Kashtbhanjan (remover of distress and evil spirits), where thousands gather on Saturdays and Tuesdays. Features the massive 54-foot King of Salangpur bronze sculpture.",
    officialWebsite: "https://salangpurhanumanji.org",
    sourceRecordId: "GJ-YATRA-BOT-009",
    sourceName: "Shree Kashtbhanjandev Hanumanji Mandir Trust",
    sourceUrl: "https://salangpurhanumanji.org",
    sourceType: "government",
  },
  {
    name: "Ranchhodraiji Mandir Dakor",
    nameLocal: "રણછોડરાયજી મંદિર ડાકોર",
    stateCode: "GJ",
    districtName: "Kheda",
    localityName: "Dakor, Thasra",
    latitude: 22.7533,
    longitude: 73.1497,
    mainDeity: "Ranchhodraiji (Lord Krishna)",
    deities: ["Ranchhodraiji"],
    templeType: "Supreme Pilgrimage Shrine of Central Gujarat",
    tradition: ["Vaishnavism", "Pushtimarg"],
    architecture: "Maharashtrian Peshwa & Maru-Gurjara Style with Gomti Lake Ghats",
    historicalPeriod: "Gopal Jagannath Tambvekar (1772 CE)",
    description: "Centuries-old pilgrimage center on the banks of holy Gomti Lake in Kheda district, enshrining the four-armed black granite deity brought from Dwarka by the devotee Bodana in the 12th century.",
    officialWebsite: "https://kheda.nic.in/tourist-place/dakor-temple/",
    sourceRecordId: "GJ-YATRA-KHE-010",
    sourceName: "Ranchhodraiji Temple Trust & Kheda Administration",
    sourceUrl: "https://kheda.nic.in/tourist-place/dakor-temple/",
    sourceType: "government",
  },
  {
    name: "Bhavnath Mahadev Temple Girnar",
    nameLocal: "ભવનાથ મહાદેવ મંદિર ગિરનાર",
    stateCode: "GJ",
    districtName: "Junagadh",
    localityName: "Girnar Taleti, Junagadh",
    latitude: 21.5283,
    longitude: 70.4994,
    mainDeity: "Bhavnath (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Historic Maha Shivaratri Gathering Shrine",
    tradition: ["Shaivism", "Nath Sampradaya"],
    architecture: "Ancient Stone Sanctum with Mrigi Kund Reservoir",
    historicalPeriod: "Ancient Girnar Pilgrimage Tradition",
    description: "Nestled at the base of sacred Mount Girnar surrounded by the Gir wilderness, world-famous for the midnight Maha Shivaratri procession when naked Naga sadhas take a sacred bath in Mrigi Kund.",
    officialWebsite: "https://junagadh.nic.in/tourist-place/bhavnath-temple/",
    sourceRecordId: "GJ-YATRA-JUN-011",
    sourceName: "Junagadh District Administration & Gujarat Tourism",
    sourceUrl: "https://junagadh.nic.in/tourist-place/bhavnath-temple/",
    sourceType: "government",
  },
  {
    name: "Shoolpaneshwar Shiva Temple",
    nameLocal: "શૂલપાણેશ્વર મહાદેવ મંદિર",
    stateCode: "GJ",
    districtName: "Narmada",
    localityName: "Rajpipla, Narmada",
    latitude: 21.7583,
    longitude: 73.6167,
    mainDeity: "Shoolpaneshwar (Trident-Bearing Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Narmada Parikrama Sacred Tirtha",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Temple Complex overlooking Narmada Gorges",
    historicalPeriod: "Ancient Narmada Puranic Pilgrimage",
    description: "Situated in the Satpura range within the Shoolpaneshwar Wildlife Sanctuary in Narmada district, an essential stopping point along the sacred 2,600-kilometer Narmada Parikrama pilgrimage trail.",
    officialWebsite: "https://narmada.nic.in/tourist-place/shoolpaneshwar-temple/",
    sourceRecordId: "GJ-YATRA-NAR-012",
    sourceName: "Narmada District Administration & Gujarat Tourism",
    sourceUrl: "https://narmada.nic.in/tourist-place/shoolpaneshwar-temple/",
    sourceType: "government",
  },
  {
    name: "Jadeshwar Mahadev Temple Wankaner",
    nameLocal: "જડેશ્વર મહાદેવ મંદિર વાંકાનેર",
    stateCode: "GJ",
    districtName: "Morbi",
    localityName: "Wankaner, Morbi",
    latitude: 22.6108,
    longitude: 70.9983,
    mainDeity: "Jadeshwar (Swayambhu Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Prominent Saurashtra Pilgrimage Shrine",
    tradition: ["Shaivism"],
    architecture: "Hillside Stone Complex with Perennial Water Springs",
    historicalPeriod: "Wankaner Royal Royalty Patronage",
    description: "Located on a scenic hillock near Wankaner in Morbi district, dedicated to a swayambhu lingam surrounded by natural gardens and natural freshwater springs, highly venerated during Shravan.",
    officialWebsite: "https://morbi.nic.in/tourist-place/jadeshwar-mahadev-temple/",
    sourceRecordId: "GJ-YATRA-MOR-013",
    sourceName: "Morbi District Administration & Devasthan Registry",
    sourceUrl: "https://morbi.nic.in/tourist-place/jadeshwar-mahadev-temple/",
    sourceType: "government",
  },
  {
    name: "Sahastralinga Talav & Shrines Patan",
    nameLocal: "સહસ્ત્રલિંગ તળાવ મંદિર સંકુલ પાટણ",
    stateCode: "GJ",
    districtName: "Patan",
    localityName: "Patan",
    latitude: 23.8569,
    longitude: 72.1158,
    mainDeity: "Sahasralinga (A Thousand Shiva Lingas)",
    deities: ["Lord Shiva"],
    templeType: "ASI Monument of National Importance",
    tradition: ["Shaivism"],
    architecture: "Colossal Medieval Hydraulic and Architectural Reservoir Complex",
    historicalPeriod: "Siddharaj Jaisinh / Solanki Dynasty (1084 CE)",
    description: "A monumental medieval lake and water architecture complex on River Saraswati, once lined with one thousand Shiva shrines and colonnaded pavilions, demonstrating ancient engineering excellence.",
    officialWebsite: "https://asi.nic.in/monuments-patan/",
    sourceRecordId: "ASI-GJ-W-GJ-C2",
    sourceName: "Archaeological Survey of India & Patan Administration",
    sourceUrl: "https://asi.nic.in/monuments-patan/",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ GUJARAT TEMPLE INGESTION ENGINE");
  console.log(`Source: Somnath Trust, Ambaji Devasthan, Dwarkadhish & Yatradham Board`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Shree Somnath Trust & Gujarat Yatradham Board",
    "https://yatradham.gujarat.gov.in",
    GUJARAT_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
