/**
 * Himachal Pradesh Official State Ingestion Importer
 * Authoritative Sources:
 * - Himachal Pradesh Language, Art & Culture Dept / Temple Trusts (https://himachalculture.nic.in)
 * - Himachal Pradesh Tourism Development Corporation (https://himachaltourism.gov.in)
 * - Kangra District Administration (https://hpkangra.nic.in)
 * - Archaeological Survey of India (Shimla Circle) (https://asishimla.nic.in)
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const HIMACHAL_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Maa Jwala Ji Temple Jawalamukhi",
    nameLocal: "माँ ज्वाला जी मंदिर ज्वालामुखी",
    stateCode: "HP",
    districtName: "Kangra",
    localityName: "Jawalamukhi, Kangra Valley",
    latitude: 31.8781,
    longitude: 76.3256,
    mainDeity: "Goddess Jwala Ji (Eternal Divine Flames)",
    deities: ["Nine Eternal Flames (Nava Durga)", "Lord Shiva (Unmatta Bhairava)"],
    templeType: "51 Maha Shakti Peethas (Tongue / Jihva Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Gilded Dome and Spire Gifted by Emperor Akbar and Maharaja Ranjit Singh",
    historicalPeriod: "Ancient Puranic Era / Inscribed Gold Canopy (1580 CE)",
    description: "One of the most sacred Shakti Peethas where Goddess Sati's tongue fell. Unique in having no idol; the divine presence is venerated as nine eternal blue natural gas flames burning perpetually through solid rock fissures.",
    officialWebsite: "https://hpkangra.nic.in/tourist-place/jawala-ji-temple/",
    sourceRecordId: "HP-JWALA-KAN-001",
    sourceName: "Shri Jwala Ji Temple Trust & Kangra Administration",
    sourceUrl: "https://hpkangra.nic.in/tourist-place/jawala-ji-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Chamunda Devi Temple Kangra",
    nameLocal: "माँ चामुंडा देवी मंदिर कांगड़ा",
    stateCode: "HP",
    districtName: "Kangra",
    localityName: "Padar, Dharamshala, Kangra",
    latitude: 32.1603,
    longitude: 76.4178,
    mainDeity: "Maa Chamunda (Slayer of Chanda and Munda)",
    deities: ["Maa Chamunda", "Lord Shiva (Nandikeshwar)"],
    templeType: "Sacred 16th-Century Hill River Shakti Shrine",
    tradition: ["Shaktism"],
    architecture: "Traditional Himachali Timber-Roof Structure on Baner River",
    historicalPeriod: "Raja of Alhilal / 16th Century CE",
    description: "Located picturesquely on the bank of the rushing Baner River facing the Dhauladhar range. Dedicated to Goddess Kali in her furious aspect slaying demons Chanda and Munda.",
    officialWebsite: "https://hpkangra.nic.in/tourist-place/chamunda-devi-temple/",
    sourceRecordId: "HP-TOUR-KAN-002",
    sourceName: "Chamunda Devi Temple Trust & HP Tourism",
    sourceUrl: "https://hpkangra.nic.in/tourist-place/chamunda-devi-temple/",
    sourceType: "government",
  },
  {
    name: "Baijnath Shiva Temple Kangra",
    nameLocal: "बैजनाथ शिव मंदिर कांगड़ा",
    stateCode: "HP",
    districtName: "Kangra",
    localityName: "Baijnath, Kangra Valley",
    latitude: 32.0522,
    longitude: 76.6478,
    mainDeity: "Vaidyanath (Lord Shiva as Supreme Healer)",
    deities: ["Lord Shiva", "Nandi", "Surya", "Ganesha"],
    templeType: "Historic 1204 CE Nagara Stone Shikhara (ASI National Monument)",
    tradition: ["Shaivism"],
    architecture: "Exquisite Early 13th-Century Nagara Style Monolithic Stone Temple",
    historicalPeriod: "Built in 1204 CE by Merchant Brothers Manyuka and Manyuka / ASI",
    description: "A monumental 13th-century stone temple dedicated to Lord Shiva as Vaidyanath (the divine physician). Houses an ancient Swayambhu Shivalinga associated with the legend of demon king Ravana.",
    officialWebsite: "https://asishimla.nic.in",
    sourceRecordId: "HP-ASI-KAN-003",
    sourceName: "Archaeological Survey of India (Shimla Circle)",
    sourceUrl: "https://asishimla.nic.in",
    sourceType: "asi",
  },
  {
    name: "Masrur Rock Cut Temples",
    nameLocal: "मसरूर शैल-उत्कीर्ण मंदिर",
    stateCode: "HP",
    districtName: "Kangra",
    localityName: "Masrur, Kangra",
    latitude: 32.0594,
    longitude: 76.1417,
    mainDeity: "Thakurdwara (Rama, Lakshmana, Sita)",
    deities: ["Rama", "Lakshmana", "Sita", "Shiva"],
    templeType: "Ellora of the North Monolithic Rock-Cut Monument",
    tradition: ["Shaivism", "Vaishnavism"],
    architecture: "8th-Century Monolithic Sandstone Shikhara Complex Hewn from Solid Rock",
    historicalPeriod: "8th Century CE (Yashovarman of Kanauj Era) / ASI Monument",
    description: "Known as the Ellora or Ajanta of the Himalayas, this stunning complex of 15 rock-cut monolithic sandstone shrines carved directly from a single sandstone ridge overlooks a sacred rock-cut pool.",
    officialWebsite: "https://asishimla.nic.in",
    sourceRecordId: "HP-ASI-KAN-004",
    sourceName: "Archaeological Survey of India (Shimla Circle)",
    sourceUrl: "https://asishimla.nic.in",
    sourceType: "asi",
  },
  {
    name: "Hidimba Devi Temple Manali",
    nameLocal: "हिडिम्बा देवी मंदिर मनाली",
    stateCode: "HP",
    districtName: "Kullu",
    localityName: "Dhungri Forest, Manali",
    latitude: 32.2483,
    longitude: 77.1814,
    mainDeity: "Goddess Hidimba (Wife of Bhima)",
    deities: ["Maa Hidimba", "Ghatotkacha"],
    templeType: "Historic 1553 CE Four-Tiered Pagoda Timber Architecture",
    tradition: ["Mahabharata Tradition", "Folk Deity of Kullu"],
    architecture: "Four-Tiered Wooden Pagoda with Intricately Carved Deodar Timber Base",
    historicalPeriod: "Raja Bahadur Singh of Kullu (1553 CE) / ASI National Monument",
    description: "Nestled within an ancient cedar (Deodar) forest at the foot of the Himalayas in Manali. Built around a natural cave where Hidimba meditated, featuring a 24-meter wooden pagoda tower.",
    officialWebsite: "https://hpkullu.nic.in/tourist-place/hadimba-temple/",
    sourceRecordId: "HP-ASI-KUL-005",
    sourceName: "Archaeological Survey of India (Shimla Circle) & Kullu Admin",
    sourceUrl: "https://hpkullu.nic.in/tourist-place/hadimba-temple/",
    sourceType: "asi",
  },
  {
    name: "Bijli Mahadev Temple Kullu",
    nameLocal: "बिजली महादेव मंदिर कुल्लू",
    stateCode: "HP",
    districtName: "Kullu",
    localityName: "Mathan Hill, Kullu Valley",
    latitude: 31.9567,
    longitude: 77.1892,
    mainDeity: "Bijli Mahadev (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Sacred Lightning Monolith Hilltop Sanctuary",
    tradition: ["Shaivism"],
    architecture: "Traditional Himachali Timber Kathkuni Temple with 60-Foot Pine Flagstaff",
    historicalPeriod: "Ancient Vedic Antiquity",
    description: "Perched at 2,460 meters overlooking the confluence of the Beas and Parbati rivers. Legend recounts that lightning strikes the tall staff and shatters the Shivalinga, which the priest restores with unsalted butter.",
    officialWebsite: "https://hpkullu.nic.in/tourist-place/bijli-mahadev/",
    sourceRecordId: "HP-TOUR-KUL-006",
    sourceName: "Kullu District Administration & Bijli Mahadev Trust",
    sourceUrl: "https://hpkullu.nic.in/tourist-place/bijli-mahadev/",
    sourceType: "government",
  },
  {
    name: "Bhimakali Temple Sarahan",
    nameLocal: "भीमाकाली मंदिर सराहन",
    stateCode: "HP",
    districtName: "Shimla",
    localityName: "Sarahan, Bushahr",
    latitude: 31.5133,
    longitude: 77.7944,
    mainDeity: "Maa Bhimakali (Goddess Durga)",
    deities: ["Maa Bhimakali", "Lord Shiva", "Raghunath"],
    templeType: "51 Maha Shakti Peethas (Ear / Karna Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Towering Timber and Stone Kathkuni Multi-Storeyed Royal Palace Architecture",
    historicalPeriod: "Bushahr Royal Dynasty (Ancient) / 12th-Century Foundations",
    description: "One of the 51 sacred Shakti Peethas and the ancient seat of the rulers of Bushahr. A magnificent specimen of timber-and-slate Himalayan architectural engineering looking towards Shrikhand Mahadev peak.",
    officialWebsite: "https://hpshimla.nic.in/tourist-place/bhimakali-temple/",
    sourceRecordId: "HP-TOUR-SHI-007",
    sourceName: "Shri Bhimakali Temple Trust & Shimla District Administration",
    sourceUrl: "https://hpshimla.nic.in/tourist-place/bhimakali-temple/",
    sourceType: "government",
  },
  {
    name: "Jakhoo Temple Shimla",
    nameLocal: "जाखू मंदिर शिमला",
    stateCode: "HP",
    districtName: "Shimla",
    localityName: "Jakhoo Hill, Shimla",
    latitude: 31.1011,
    longitude: 77.1844,
    mainDeity: "Lord Hanuman",
    deities: ["Lord Hanuman"],
    templeType: "Highest Himalayan Peak Hanuman Pilgrimage",
    tradition: ["Vaishnavism"],
    architecture: "Hilltop Sanctuary crowned by 108-Foot Colossal Hanuman Statue",
    historicalPeriod: "Treta Yuga Ramayana Era / Modern Colossus (2010 CE)",
    description: "Situated on the highest peak in Shimla at 2,455 meters. Legend relates that Lord Hanuman rested here on his flight to the Himalayas to procure the Sanjeevani herb during the Lanka war.",
    officialWebsite: "https://hpshimla.nic.in/tourist-place/jakhoo-temple/",
    sourceRecordId: "HP-TOUR-SHI-008",
    sourceName: "Shimla District Administration & Jakhoo Trust",
    sourceUrl: "https://hpshimla.nic.in/tourist-place/jakhoo-temple/",
    sourceType: "government",
  },
  {
    name: "Shri Naina Devi Ji Temple Bilaspur",
    nameLocal: "श्री नैना देवी जी मंदिर बिलासपुर",
    stateCode: "HP",
    districtName: "Bilaspur",
    localityName: "Naina Devi Hill, Bilaspur",
    latitude: 31.3061,
    longitude: 76.5369,
    mainDeity: "Maa Naina Devi (Eyes of Goddess Sati)",
    deities: ["Maa Naina Devi", "Lord Ganesha", "Hanuman"],
    templeType: "51 Maha Shakti Peethas (Eyes / Netra Peetha)",
    tradition: ["Shaktism"],
    architecture: "White Marble Shikhara Complex Overlooking Gobind Sagar Lake",
    historicalPeriod: "Raja Bir Chand of Bilaspur (8th Century CE)",
    description: "Perched high on a cliff-edge hill overlooking the vast Gobind Sagar reservoir. Venerated as the Shakti Peetha where Goddess Sati's divine eyes fell, visited by millions during Shravan Ashtami.",
    officialWebsite: "https://hpbilaspur.nic.in/tourist-place/shri-naina-devi-ji/",
    sourceRecordId: "HP-NAINA-BIL-009",
    sourceName: "Shri Naina Devi Ji Temple Trust & Bilaspur Administration",
    sourceUrl: "https://hpbilaspur.nic.in/tourist-place/shri-naina-devi-ji/",
    sourceType: "government",
  },
  {
    name: "Maa Chintpurni Temple Una",
    nameLocal: "माँ चिंतपूर्णी मंदिर ऊना",
    stateCode: "HP",
    districtName: "Una",
    localityName: "Chintpurni, Amb, Una",
    latitude: 31.8089,
    longitude: 76.1361,
    mainDeity: "Maa Chhinnamastika (Remover of Worries)",
    deities: ["Chhinnamastika Devi"],
    templeType: "51 Maha Shakti Peethas (Feet / Pada Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Sprawling Temple Complex Centered Around Sacred Banyan Tree",
    historicalPeriod: "Pandit Mai Das Tradition (16th Century CE)",
    description: "Dedicated to the headless aspect of Goddess Durga (Chhinnamasta), worshiped as Chintpurni—the remover of all worries and anxieties. An essential stop on the Navratra pilgrimage circuit.",
    officialWebsite: "https://chintpurni.hp.gov.in",
    sourceRecordId: "HP-CHINT-UNA-010",
    sourceName: "Shri Mata Chintpurni Temple Trust & Una Administration",
    sourceUrl: "https://chintpurni.hp.gov.in",
    sourceType: "government",
  },
  {
    name: "Maa Renuka Ji Temple Sirmaur",
    nameLocal: "माँ रेणुका जी मंदिर सिरमौर",
    stateCode: "HP",
    districtName: "Sirmaur",
    localityName: "Renuka Lake, Nahan, Sirmaur",
    latitude: 30.6083,
    longitude: 77.4589,
    mainDeity: "Maa Renuka (Mother of Lord Parshurama)",
    deities: ["Maa Renuka", "Bhagwan Parshurama", "Rishi Jamadagni"],
    templeType: "Sacred Lake Shrine of Maharshi Jamadagni & Parshurama",
    tradition: ["Vaishnavism", "Puranic Tradition"],
    architecture: "Pagoda Timber Shrines on the Shore of Woman-Shaped Sacred Lake",
    historicalPeriod: "Ancient Puranic Era / Celebrated Renuka Fair",
    description: "Situated on the bank of the largest natural lake in Himachal Pradesh, shaped naturally like a reclining woman. Epicenter of the centuries-old international Renuka Ji fair held ten days after Diwali.",
    officialWebsite: "https://hpsirmaur.nic.in/tourist-place/renukaji/",
    sourceRecordId: "HP-TOUR-SIR-011",
    sourceName: "Sirmaur District Administration & Renuka Trust",
    sourceUrl: "https://hpsirmaur.nic.in/tourist-place/renukaji/",
    sourceType: "government",
  },
  {
    name: "Bhootnath Temple Mandi",
    nameLocal: "भूतनाथ मंदिर मंडी",
    stateCode: "HP",
    districtName: "Mandi",
    localityName: "Main Market, Mandi City",
    latitude: 31.7083,
    longitude: 76.9322,
    mainDeity: "Bhootnath (Lord of Spirits, Shiva)",
    deities: ["Lord Shiva", "Nandi"],
    templeType: "Historic 1527 CE Chhatri Shikhara of Chhoti Kashi",
    tradition: ["Shaivism"],
    architecture: "Classic Shikhara Architecture in Indigenous Stone of Mandi",
    historicalPeriod: "Raja Ajbar Sen (1527 CE)",
    description: "The spiritual heart of Mandi (known as Chhoti Kashi for its 81 stone temples). Focus of the world-famous week-long international Mandi Shivaratri Fair.",
    officialWebsite: "https://hpmandi.nic.in/tourist-place/bhootnath-temple/",
    sourceRecordId: "HP-TOUR-MAN-012",
    sourceName: "Mandi District Administration & Mandi Temple Trust",
    sourceUrl: "https://hpmandi.nic.in/tourist-place/bhootnath-temple/",
    sourceType: "government",
  },
  {
    name: "Lakshmi Narayan Temple Complex Chamba",
    nameLocal: "लक्ष्मी नारायण मंदिर चंबा",
    stateCode: "HP",
    districtName: "Chamba",
    localityName: "Chamba Town",
    latitude: 32.5539,
    longitude: 76.1264,
    mainDeity: "Lord Lakshmi Narayan (Vishnu)",
    deities: ["Lakshmi Narayan", "Radha Krishna", "Gauri Shankar", "Chandragupta Shiva"],
    templeType: "10th-Century Royal Chamba Shikhara Complex (ASI Monument)",
    tradition: ["Vaishnavism", "Shaivism"],
    architecture: "Six Shikhara Temples with Wooden Canopied Roofs & Intricate Stone Reliefs",
    historicalPeriod: "Raja Sahil Varman (10th Century CE) / ASI National Monument",
    description: "The largest and most important temple complex in Chamba, containing six imposing stone Shikhara shrines with distinctive wooden overhanging canopies built to protect the stone from mountain snow.",
    officialWebsite: "https://asishimla.nic.in",
    sourceRecordId: "HP-ASI-CHM-013",
    sourceName: "Archaeological Survey of India (Shimla Circle) & Chamba Admin",
    sourceUrl: "https://asishimla.nic.in",
    sourceType: "asi",
  },
];

export async function importHimachalTemples(options = {}) {
  return processStateBatch(
    "Himachal Pradesh Tourism & Temple Trusts",
    "https://himachaltourism.gov.in",
    HIMACHAL_AUTHORITATIVE_TEMPLES,
    options
  );
}

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ HIMACHAL PRADESH TEMPLE INGESTION ENGINE");
  console.log("Source: Himachal Pradesh Tourism & Temple Trusts");
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await importHimachalTemples({
    dryRun: isDryRun,
    parserVersion: "v1.0.0",
  });

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);

