/**
 * Jammu & Kashmir Official State Ingestion Importer
 * Authoritative Sources:
 * - Shri Mata Vaishno Devi Shrine Board (https://maavaishnodevi.org)
 * - Shri Amarnathji Shrine Board (https://shriamarnathjishrine.com)
 * - Jammu & Kashmir Tourism Development Corporation (https://jktdc.co.in)
 * - Archaeological Survey of India (Srinagar Circle) (https://asisrinagar.in)
 * - District Administrations of Jammu & Kashmir
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const JAMMU_KASHMIR_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Shri Mata Vaishno Devi Shrine Katra",
    nameLocal: "श्री माता वैष्णो देवी श्राइन कटरा",
    stateCode: "JK",
    districtName: "Reasi",
    localityName: "Trikuta Hills, Katra",
    latitude: 33.0308,
    longitude: 74.9490,
    mainDeity: "Maa Vaishno Devi (Maha Kali, Maha Lakshmi, Maha Saraswati Pindis)",
    deities: ["Maha Kali", "Maha Lakshmi", "Maha Saraswati", "Bhairavnath"],
    templeType: "World-Renowned Holy Cave Pilgrimage (Trikuta Parvat)",
    tradition: ["Shaktism"],
    architecture: "Natural Holy Cave Sanctum at 5,200 ft with Modern Sacred Complex",
    historicalPeriod: "Ancient Puranic Treta Yuga Tradition / Board Constituted 1986",
    description: "One of the most visited pilgrimage destinations on Earth, situated inside a holy natural cave in the Trikuta Mountains at 5,200 feet above sea level.",
    officialWebsite: "https://maavaishnodevi.org",
    sourceRecordId: "JK-SMVD-REA-001",
    sourceName: "Shri Mata Vaishno Devi Shrine Board & J&K Tourism",
    sourceUrl: "https://maavaishnodevi.org",
    sourceType: "official",
  },
  {
    name: "Holy Cave Shrine of Shri Amarnathji",
    nameLocal: "श्री अमरनाथ जी पवित्र गुफा मंदिर",
    stateCode: "JK",
    districtName: "Anantnag",
    localityName: "Amarnath Holy Cave, Lidder Valley",
    latitude: 34.2153,
    longitude: 75.5039,
    mainDeity: "Lord Shiva (Ice Stalagmite Swayambhu Lingam)",
    deities: ["Baba Barfani (Ice Lingam)", "Goddess Parvati", "Lord Ganesha"],
    templeType: "51 Maha Shakti Peethas & Sacred Himalayan Cave Pilgrimage",
    tradition: ["Shaivism", "Shaktism"],
    architecture: "High Altitude Natural Glacial Cave at 12,756 ft Altitude",
    historicalPeriod: "Ancient Puranic Bhrigu Rishi Tradition / Board Constituted 2000",
    description: "The sacred Himalayan cave shrine situated at 12,756 feet where Lord Shiva revealed the Amar Katha (secret of immortality) to Goddess Parvati.",
    officialWebsite: "https://shriamarnathjishrine.com",
    sourceRecordId: "JK-SASB-ANA-002",
    sourceName: "Shri Amarnathji Shrine Board & J&K Tourism",
    sourceUrl: "https://shriamarnathjishrine.com",
    sourceType: "official",
  },
  {
    name: "Martand Sun Temple Complex",
    nameLocal: "मार्तंड सूर्य मंदिर",
    stateCode: "JK",
    districtName: "Anantnag",
    localityName: "Kehribal, Mattan, Anantnag",
    latitude: 33.7461,
    longitude: 75.2206,
    mainDeity: "Surya Bhagwan (Sun God)",
    deities: ["Lord Surya", "Vishnu", "Ganga-Yamuna"],
    templeType: "8th-Century Monumental Stone Temple Marvel (ASI Monument)",
    tradition: ["Solar Tradition", "Classical Kashmiri Architecture"],
    architecture: "Karkota Kashmiri Classical Architecture with Colonnaded Peristyle",
    historicalPeriod: "Emperor Lalitaditya Muktapida / 8th Century CE",
    description: "One of the greatest architectural achievements of ancient India, built by Emperor Lalitaditya atop a plateau overlooking the entire Kashmir Valley. Protected by ASI.",
    officialWebsite: "https://anantnag.nic.in/tourist-place/martand-sun-temple/",
    sourceRecordId: "JK-ASI-ANA-003",
    sourceName: "Archaeological Survey of India Srinagar Circle & J&K Tourism",
    sourceUrl: "https://asisrinagar.in",
    sourceType: "asi",
  },
  {
    name: "Shankaracharya Temple Jyeshtheshwara",
    nameLocal: "शंकराचार्य मंदिर ज्येष्ठेश्वर",
    stateCode: "JK",
    districtName: "Srinagar",
    localityName: "Gopadri Hill / Shankaracharya Hill, Srinagar",
    latitude: 34.0722,
    longitude: 74.8469,
    mainDeity: "Lord Shiva (Jyeshtheshwara)",
    deities: ["Lord Shiva Lingam", "Adi Shankaracharya Peetham"],
    templeType: "Historic Octagonal Hilltop Temple overlooking Dal Lake",
    tradition: ["Shaivism", "Advaita Vedanta", "Kashmir Shaivism"],
    architecture: "Ancient Octagonal Stone Platform with High Pyramidal Shikhara",
    historicalPeriod: "King Gopaditya (371 BCE tradition) / Adi Shankara visit (8th Cent CE)",
    description: "Situated atop Shankaracharya Hill at 1,000 feet above the valley floor overlooking Dal Lake and Srinagar city, where Adi Shankara attained spiritual realization.",
    officialWebsite: "https://srinagar.nic.in/tourist-place/shankaracharya-temple/",
    sourceRecordId: "JK-TOUR-SRI-004",
    sourceName: "Srinagar District Administration & J&K Tourism",
    sourceUrl: "https://jktdc.co.in",
    sourceType: "government",
  },
  {
    name: "Sharika Devi Temple Hari Parbat",
    nameLocal: "शारिका देवी मंदिर हरि पर्वत",
    stateCode: "JK",
    districtName: "Srinagar",
    localityName: "Hari Parbat (Koh-e-Maran), Srinagar",
    latitude: 34.0983,
    longitude: 74.8144,
    mainDeity: "Goddess Sharika (18-Armed Mahadurga / Sri Chakra)",
    deities: ["Goddess Sharika", "Sri Chakra Swaroopini"],
    templeType: "Presiding Kuldevi Shakti Peetha of Kashmir Valley",
    tradition: ["Shaktism", "Kashmir Shaivism"],
    architecture: "Historic Mountain Shikhara Shrine on Hari Parbat Hill",
    historicalPeriod: "Ancient Kashmiri Puranic Era",
    description: "The supreme presiding deity of the Kashmiri Pandit community, where Mother Goddess is worshipped as the sacred Swayambhu Shila embodying the Sri Chakra.",
    officialWebsite: "https://srinagar.nic.in/tourist-place/hari-parbat/",
    sourceRecordId: "JK-TOUR-SRI-005",
    sourceName: "Hari Parbat Coordination Committee & J&K Tourism",
    sourceUrl: "https://jktdc.co.in",
    sourceType: "government",
  },
  {
    name: "Mata Kheer Bhawani Temple Tulmulla",
    nameLocal: "माता क्षीर भवानी मंदिर तुलमुल",
    stateCode: "JK",
    districtName: "Ganderbal",
    localityName: "Tulmulla, Ganderbal",
    latitude: 34.2250,
    longitude: 74.7472,
    mainDeity: "Mata Ragnya Devi (Kheer Bhawani)",
    deities: ["Mata Ragnya Devi", "Sacred Color-Changing Spring Kund"],
    templeType: "Revered Natural Spring Shakti Shrine",
    tradition: ["Shaktism", "Kashmir Shaivism"],
    architecture: "Marble Sanctum situated in Hexagonal Holy Spring",
    historicalPeriod: "Ancient Kashmiri Tradition / Maharaja Pratap Singh (1912 CE)",
    description: "Famous holy spring shrine dedicated to Goddess Ragnya Devi, celebrated for its sacred natural spring waters that miraculously change color depending on cosmic conditions.",
    officialWebsite: "https://ganderbal.nic.in/tourist-place/kheer-bhawani-temple/",
    sourceRecordId: "JK-TOUR-GAN-006",
    sourceName: "Dharmath Trust & Ganderbal Administration",
    sourceUrl: "https://ganderbal.nic.in",
    sourceType: "official",
  },
  {
    name: "Ranbireshwar Shiva Temple Jammu",
    nameLocal: "रणवीरेश्वर शिव मंदिर जम्मू",
    stateCode: "JK",
    districtName: "Jammu",
    localityName: "Shalamar Road, Jammu City",
    latitude: 32.7317,
    longitude: 74.8622,
    mainDeity: "Lord Shiva (Giant 7.5-foot Black Stone Lingam)",
    deities: ["Lord Shiva", "12 Crystal Banalingas", "1.25 Lakh Narmadeshwar Lingams"],
    templeType: "Largest Shiva Temple in Northern India",
    tradition: ["Shaivism"],
    architecture: "Dogra Classical Nagara Temple Architecture",
    historicalPeriod: "Maharaja Ranbir Singh / 1883 CE",
    description: "Built by Maharaja Ranbir Singh in 1883 CE, housing a central 7.5-foot high black stone Shiva Lingam and twelve crystal banalingas brought from the Narmada River.",
    officialWebsite: "https://jammu.nic.in/tourist-place/ranbireshwar-temple/",
    sourceRecordId: "JK-TOUR-JAM-007",
    sourceName: "J&K Dharmarth Trust & Jammu District Administration",
    sourceUrl: "https://jammu.nic.in",
    sourceType: "official",
  },
  {
    name: "Bawe Wali Mata Temple Bahu Fort",
    nameLocal: "बावे वाली माता मंदिर बाहू किला",
    stateCode: "JK",
    districtName: "Jammu",
    localityName: "Bahu Fort, Tawi River Bank",
    latitude: 32.7297,
    longitude: 74.8833,
    mainDeity: "Maa Mahakali (Bawe Wali Mata)",
    deities: ["Maa Mahakali"],
    templeType: "Historic Dogra Fortress Shakti Shrine",
    tradition: ["Shaktism"],
    architecture: "Ancient Stone Fort Temple atop Tawi River Ridge",
    historicalPeriod: "Raja Bahu Lochan / 3,000 Year Legend / Rebuilt 1820 CE",
    description: "The presiding guardian deity of Jammu city, located within the historic 3,000-year-old Bahu Fort overlooking the serene Tawi River.",
    officialWebsite: "https://jammu.nic.in/tourist-place/bahu-fort/",
    sourceRecordId: "JK-TOUR-JAM-008",
    sourceName: "Jammu District Administration & J&K Tourism",
    sourceUrl: "https://jktdc.co.in",
    sourceType: "government",
  },
  {
    name: "Sudh Mahadev Temple Chenani",
    nameLocal: "सुध महादेव मंदिर चेनानी",
    stateCode: "JK",
    districtName: "Udhampur",
    localityName: "Chanhote, Chenani, Udhampur",
    latitude: 33.0236,
    longitude: 75.3611,
    mainDeity: "Lord Shiva (Sudh Mahadev)",
    deities: ["Lord Shiva", "Trishul of Shiva", "Goddess Parvati Sthal"],
    templeType: "Ancient Puranic Trishul Pilgrimage Center",
    tradition: ["Shaivism"],
    architecture: "Historic Himalayan Stone Temple & Sacred Papnashini Spring",
    historicalPeriod: "Ancient Puranic Era / Renovated by Raja Ram Chand",
    description: "Revered shrine housing pieces of Lord Shiva's divine iron trident (Trishul) and the sacred Papnashini spring where devotees wash away all sins.",
    officialWebsite: "https://udhampur.nic.in/tourist-place/sudh-mahadev-temple/",
    sourceRecordId: "JK-TOUR-UDH-009",
    sourceName: "Udhampur District Administration & J&K Tourism",
    sourceUrl: "https://udhampur.nic.in",
    sourceType: "government",
  },
  {
    name: "Krimchi Group of Temples Pandava Gufa",
    nameLocal: "क्रीमची मंदिर समूह (पांडव मंदिर)",
    stateCode: "JK",
    districtName: "Udhampur",
    localityName: "Krimchi Village, Udhampur",
    latitude: 32.9694,
    longitude: 75.1278,
    mainDeity: "Lord Shiva, Vishnu & Ganesha",
    deities: ["Lord Shiva", "Maha Vishnu", "Goddess Parvati"],
    templeType: "8th-9th Century Ancient Monument Complex (ASI Monument)",
    tradition: ["Shaivism", "Vaishnavism"],
    architecture: "Classical Kashmiri Nagara Stone Temple Architecture",
    historicalPeriod: "8th-9th Century CE / Pandava Tradition",
    description: "A complex of seven ancient stone temples protected by the Archaeological Survey of India, representing classical early medieval Kashmiri temple design.",
    officialWebsite: "https://udhampur.nic.in/tourist-place/krimchi-temple/",
    sourceRecordId: "JK-ASI-UDH-010",
    sourceName: "Archaeological Survey of India Srinagar Circle & CG Tourism",
    sourceUrl: "https://asisrinagar.in",
    sourceType: "asi",
  },
  {
    name: "Mata Sukrala Devi Temple Billawar",
    nameLocal: "माता सुकराला देवी मंदिर बिलावर",
    stateCode: "JK",
    districtName: "Kathua",
    localityName: "Sukrala Hills, Billawar",
    latitude: 32.6167,
    longitude: 75.6000,
    mainDeity: "Mata Sukrala Devi (Sharika Avatar)",
    deities: ["Sukrala Devi", "Lord Mahadev"],
    templeType: "Revered Hilltop Shakti Shrine of Dogra Region",
    tradition: ["Shaktism"],
    architecture: "Hillside White Shikhara Temple Complex",
    historicalPeriod: "18th Century CE by King Madho Singh of Billawar",
    description: "Famous shrine in Kathua district perched on a hillock, considered a manifestation of Goddess Sharika, drawing immense crowds during Navratri fairs.",
    officialWebsite: "https://kathua.nic.in/tourist-place/sukrala-mata-temple/",
    sourceRecordId: "JK-TOUR-KAT-011",
    sourceName: "Kathua District Administration & J&K Tourism",
    sourceUrl: "https://kathua.nic.in",
    sourceType: "government",
  },
  {
    name: "Purmandal & Utterbehni Temple Complex",
    nameLocal: "पुरमंडल एवं उत्तरवाहिनी मंदिर संकुल",
    stateCode: "JK",
    districtName: "Samba",
    localityName: "Devika River, Purmandal, Samba",
    latitude: 32.6958,
    longitude: 75.0569,
    mainDeity: "Lord Shiva (Umapati Mahadev)",
    deities: ["Lord Shiva", "Holy Devika River", "Gadadhar Temple"],
    templeType: "Chhota Kashi of Northern India (Underground Sacred Devika)",
    tradition: ["Shaivism", "Vedic Teertha Tradition"],
    architecture: "Medieval Dogra Shikhara Temples with Frescoes",
    historicalPeriod: "Guru Gobind Singh & Maharaja Ranjit Singh Endowments",
    description: "Known as 'Chhota Kashi', situated along the holy Devika River which flows underground and reappears at sacred bathing ghats.",
    officialWebsite: "https://samba.nic.in/tourist-place/purmandal-temple/",
    sourceRecordId: "JK-TOUR-SAM-012",
    sourceName: "Samba District Administration & J&K Tourism",
    sourceUrl: "https://samba.nic.in",
    sourceType: "government",
  },
  {
    name: "Maa Sarthal Devi Mandir Kishtwar",
    nameLocal: "माँ सरथल देवी मंदिर किश्तवाड़",
    stateCode: "JK",
    districtName: "Kishtwar",
    localityName: "Sarthal, Kishtwar",
    latitude: 33.3167,
    longitude: 75.7667,
    mainDeity: "Goddess Sarthal Devi (Ashtadashabhuja Durga)",
    deities: ["Maa Sarthal Devi (18-Armed Mother)"],
    templeType: "High Altitude Mountain Shakti Sanctuary",
    tradition: ["Shaktism"],
    architecture: "Traditional Himalayan Wood and Stone Architecture",
    historicalPeriod: "Kishtwar Royal Rajas Tradition / Ancient Idol",
    description: "Revered eighteen-armed Goddess Durga carved from single black stone brought from Kishkindha hills, situated amidst towering pine and deodar forests.",
    officialWebsite: "https://kishtwar.nic.in/tourist-place/sarthal-devi-ji-temple/",
    sourceRecordId: "JK-TOUR-KIS-013",
    sourceName: "Sarthal Devi Trust & Kishtwar Administration",
    sourceUrl: "https://kishtwar.nic.in",
    sourceType: "official",
  },
  {
    name: "Gupt Ganga Temple Bhaderwah",
    nameLocal: "गुप्त गंगा मंदिर भद्रवाह",
    stateCode: "JK",
    districtName: "Doda",
    localityName: "Neeru River Bank, Bhaderwah",
    latitude: 32.9806,
    longitude: 75.7139,
    mainDeity: "Lord Shiva (Gupt Ganga)",
    deities: ["Lord Shiva Lingam", "Bhimsen Footprint Shila"],
    templeType: "Pandava Exile Sacred River Sanctum",
    tradition: ["Shaivism"],
    architecture: "Ancient Monolithic Stone Slab Architecture",
    historicalPeriod: "Mahabharata Era Tradition / Ancient Mandir",
    description: "Ancient stone temple located on the banks of Neeru stream in scenic Bhaderwah valley, where a perennial underground stream flows directly over the Shiva Lingam.",
    officialWebsite: "https://doda.nic.in/tourist-place/gupt-ganga-temple/",
    sourceRecordId: "JK-TOUR-DOD-014",
    sourceName: "Doda District Administration & J&K Tourism",
    sourceUrl: "https://doda.nic.in",
    sourceType: "government",
  },
  {
    name: "Baba Budha Amarnath Temple Mandi",
    nameLocal: "बाबा बुड्ढा अमरनाथ मंदिर मंडी",
    stateCode: "JK",
    districtName: "Poonch",
    localityName: "Rajpura, Mandi, Poonch",
    latitude: 33.7833,
    longitude: 74.2500,
    mainDeity: "Lord Shiva (Chattani Natural Stone Lingam)",
    deities: ["Lord Shiva", "Pulastya River Sacred Bathing Ghats"],
    templeType: "Historic Frontier Shaivite Pilgrimage",
    tradition: ["Shaivism"],
    architecture: "White Stone Mountain Shikhara Temple",
    historicalPeriod: "Sage Pulatsya (Grandfather of Ravana) Ashram Legend",
    description: "One of the most sacred pilgrimage shrines of the Pir Panjal mountain range, standing on the banks of the sacred Pulastya stream in Poonch district.",
    officialWebsite: "https://poonch.nic.in/tourist-place/buddha-amarnath-temple/",
    sourceRecordId: "JK-TOUR-POO-015",
    sourceName: "Budha Amarnath Trust & Poonch Administration",
    sourceUrl: "https://poonch.nic.in",
    sourceType: "official",
  },
  {
    name: "Buniyar Shiva Temple Complex",
    nameLocal: "बुनियार शिव मंदिर",
    stateCode: "JK",
    districtName: "Baramulla",
    localityName: "Buniyar, Jhelum River Bank, Baramulla",
    latitude: 34.1333,
    longitude: 74.1833,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Granite Peristyle Shrines"],
    templeType: "Early Medieval Stone Temple (ASI Monument)",
    tradition: ["Shaivism", "Classical Kashmiri Architecture"],
    architecture: "Granite Stone Mandir with Complete Enclosing Peristyle Colonnade",
    historicalPeriod: "Karkota / Utpala Dynasties / 9th Century CE",
    description: "One of the best-preserved early medieval stone temples in Kashmir, standing with its entire peristyle arcade and central gateway along the historic Jhelum valley road.",
    officialWebsite: "https://baramulla.nic.in/tourist-place/buniyar-temple/",
    sourceRecordId: "JK-ASI-BAR-016",
    sourceName: "Archaeological Survey of India Srinagar Circle",
    sourceUrl: "https://asisrinagar.in",
    sourceType: "asi",
  },
  {
    name: "Avantiswami Temple Complex",
    nameLocal: "अवंतीस्वामी मंदिर अवंतीपोरा",
    stateCode: "JK",
    districtName: "Pulwama",
    localityName: "Awantipora, Jhelum River Bank",
    latitude: 33.9214,
    longitude: 75.0139,
    mainDeity: "Lord Vishnu (Avantiswami)",
    deities: ["Lord Vishnu", "Goddess Lakshmi", "Avantisvara Shiva"],
    templeType: "9th-Century Royal Monumental Capital Sanctuary (ASI Monument)",
    tradition: ["Vaishnavism", "Kashmiri Classical Architecture"],
    architecture: "Colonnaded Quadrangle with Finely Sculpted Relief Panels",
    historicalPeriod: "Emperor Avantivarman / 855-883 CE",
    description: "Majestic stone temple complex built by King Avantivarman on the banks of Jhelum River, renowned for its classical sculptures and Greek-influenced columns.",
    officialWebsite: "https://pulwama.nic.in/tourist-place/avantiswami-temple/",
    sourceRecordId: "JK-ASI-PUL-017",
    sourceName: "Archaeological Survey of India Srinagar Circle",
    sourceUrl: "https://asisrinagar.in",
    sourceType: "asi",
  },
  {
    name: "Mata Bhadrakali Temple Teetwal",
    nameLocal: "माता भद्रकाली मंदिर टीटवाल",
    stateCode: "JK",
    districtName: "Kupwara",
    localityName: "Kupwara-Handwara Forests",
    latitude: 34.4000,
    longitude: 74.2833,
    mainDeity: "Maa Bhadrakali",
    deities: ["Maa Bhadrakali"],
    templeType: "Ancient Forest Shakta Sanctuary",
    tradition: ["Shaktism"],
    architecture: "Himalayan Wood and Stone Devalaya",
    historicalPeriod: "Ancient Puranic Footprint / Consecrated 2023 CE",
    description: "Revered historical temple of Mother Goddess Bhadrakali located amidst the dense deodar hills of Kupwara in northwest Kashmir.",
    officialWebsite: "https://kupwara.nic.in/",
    sourceRecordId: "JK-TOUR-KUP-018",
    sourceName: "Kupwara District Administration & J&K Tourism",
    sourceUrl: "https://kupwara.nic.in",
    sourceType: "government",
  },
  {
    name: "Mangla Devi Mandir Sunderbani",
    nameLocal: "मंगला देवी मंदिर सुंदरबनी",
    stateCode: "JK",
    districtName: "Rajouri",
    localityName: "Nowshera-Sunderbani Hills, Rajouri",
    latitude: 33.1500,
    longitude: 74.2333,
    mainDeity: "Maa Mangla Devi",
    deities: ["Maa Mangla Devi", "Lord Shiva"],
    templeType: "Historical Hilltop Shakti Shrine",
    tradition: ["Shaktism"],
    architecture: "Hillside White Shikhara Temple",
    historicalPeriod: "Medieval Dogra Chieftain Period",
    description: "Sacred shrine overlooking the frontier mountain passes of Rajouri district, venerated by regional communities for centuries.",
    officialWebsite: "https://rajouri.nic.in/",
    sourceRecordId: "JK-TOUR-RAJ-019",
    sourceName: "Rajouri District Administration & J&K Tourism",
    sourceUrl: "https://rajouri.nic.in",
    sourceType: "government",
  },
  {
    name: "Neelkanth Mahadev Temple Ramban",
    nameLocal: "नीलकंठ महादेव मंदिर रामबन",
    stateCode: "JK",
    districtName: "Ramban",
    localityName: "Chanderkote, Chenab River Bank, Ramban",
    latitude: 33.2444,
    longitude: 75.2417,
    mainDeity: "Lord Shiva (Neelkanth)",
    deities: ["Lord Shiva", "Chenab River Sacred Bathing Ghats"],
    templeType: "Chenab River Canyon Shaivite Shrine",
    tradition: ["Shaivism"],
    architecture: "Traditional Himalayan Ridge Temple",
    historicalPeriod: "Ancient Chenab Valley Sacred Trail",
    description: "Revered Shiva temple situated along the deep, scenic gorges of the holy Chenab River (Asikni) in Ramban district.",
    officialWebsite: "https://ramban.gov.in/",
    sourceRecordId: "JK-TOUR-RAM-020",
    sourceName: "Ramban District Administration & J&K Tourism",
    sourceUrl: "https://ramban.gov.in",
    sourceType: "government",
  },
  {
    name: "Kaloosa Shiva Temple Bandipora",
    nameLocal: "कालूसा शिव मंदिर बांदीपोरा",
    stateCode: "JK",
    districtName: "Bandipora",
    localityName: "Kaloosa, Wular Lake Bank, Bandipora",
    latitude: 34.4167,
    longitude: 74.6500,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Wular Lake Sacred Tirthas"],
    templeType: "Wular Lake Shore Sacred Temple",
    tradition: ["Shaivism"],
    architecture: "Ancient Stone Temple Platform",
    historicalPeriod: "Medieval Kashmiri Era",
    description: "Historic temple situated near the shores of Asia's largest freshwater lake, Wular Lake, in northern Kashmir's Bandipora district.",
    officialWebsite: "https://bandipore.nic.in/",
    sourceRecordId: "JK-TOUR-BAN-021",
    sourceName: "Bandipora District Administration & J&K Tourism",
    sourceUrl: "https://bandipore.nic.in",
    sourceType: "government",
  },
  {
    name: "Budgam Ancient Mahadev Shrine",
    nameLocal: "बडगाम प्राचीन महादेव मंदिर",
    stateCode: "JK",
    districtName: "Budgam",
    localityName: "Beerwah Hills, Budgam",
    latitude: 34.0167,
    longitude: 74.7167,
    mainDeity: "Lord Shiva (Abhinavagupta Sthal)",
    deities: ["Lord Shiva", "Bhairava Cave"],
    templeType: "Kashmir Shaivism Philosophy Heritage Sthal",
    tradition: ["Kashmir Shaivism"],
    architecture: "Ancient Cave and Stone Sanctum",
    historicalPeriod: "Acharya Abhinavagupta Era / 10th-11th Century CE",
    description: "Historic sacred geography where great philosopher-saint Acharya Abhinavagupta composed monumental Kashmir Shaivism treatises.",
    officialWebsite: "https://budgam.nic.in/",
    sourceRecordId: "JK-TOUR-BUD-022",
    sourceName: "Budgam District Administration & J&K Tourism",
    sourceUrl: "https://budgam.nic.in",
    sourceType: "government",
  },
  {
    name: "Kulgam Ancient Mahadev Asthapan",
    nameLocal: "कुलगाम प्राचीन महादेव अस्थान",
    stateCode: "JK",
    districtName: "Kulgam",
    localityName: "Kulgam Town, Veshaw River",
    latitude: 33.6500,
    longitude: 75.0167,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Veshaw River Sthal"],
    templeType: "Southern Kashmir Sacred Asthapan",
    tradition: ["Shaivism"],
    architecture: "Traditional Kashmiri Mountain Temple",
    historicalPeriod: "Ancient Puranic Period",
    description: "Revered pilgrimage shrine situated in southern Kashmir along the fast-flowing Veshaw stream, renowned for its annual Shivaratri rituals.",
    officialWebsite: "https://kulgam.nic.in/",
    sourceRecordId: "JK-TOUR-KUL-023",
    sourceName: "Kulgam District Administration & J&K Tourism",
    sourceUrl: "https://kulgam.nic.in",
    sourceType: "government",
  },
  {
    name: "Kapal Mochan Sacred Tirtha Shopian",
    nameLocal: "कपाल मोचन तीर्थ शोपियां",
    stateCode: "JK",
    districtName: "Shopian",
    localityName: "Nagbal, Shopian",
    latitude: 33.7167,
    longitude: 74.8333,
    mainDeity: "Lord Shiva (Kapal Mochan)",
    deities: ["Lord Shiva", "Sacred Spring Ponds"],
    templeType: "Ancient Ancestral Pitru Tarpan Pilgrimage",
    tradition: ["Shaivism", "Vedic Shraddha Tradition"],
    architecture: "Sacred Natural Spring Kunds and Stone Temples",
    historicalPeriod: "Ancient Vedic Tradition / Puranic Teerth",
    description: "One of only three Kapal Mochan shrines in India, where sacred rituals for liberation of ancestors are performed in natural holy springs.",
    officialWebsite: "https://shopian.nic.in/tourist-place/kapal-mochan-temple/",
    sourceRecordId: "JK-TOUR-SHO-024",
    sourceName: "Kapal Mochan Trust & Shopian Administration",
    sourceUrl: "https://shopian.nic.in",
    sourceType: "official",
  },
];

export async function importJammuKashmirTemples(options: { dryRun?: boolean; parserVersion?: string } = {}) {
  console.log("==================================================");
  console.log("🏛️ JAMMU & KASHMIR TEMPLE INGESTION ENGINE");
  console.log("Source: SMVDSB, SASB, J&K Tourism & ASI Srinagar");
  console.log(`Mode: ${options.dryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  return processStateBatch(
    "SMVDSB, SASB, J&K Tourism & ASI Srinagar",
    "https://jktdc.co.in",
    JAMMU_KASHMIR_AUTHORITATIVE_TEMPLES,
    options
  );
}

// CLI runner
if (process.argv[1]?.endsWith("jammu-kashmir.ts")) {
  const isDryRun = process.argv.includes("--dry-run");
  importJammuKashmirTemples({ dryRun: isDryRun })
    .then((report) => {
      console.log("\nTelemetry Report:");
      console.log(JSON.stringify(report, null, 2));
      process.exit(0);
    })
    .catch((err) => {
      console.error("\n❌ Importer crashed:", err);
      process.exit(1);
    });
}
