/**
 * Jharkhand Official State Ingestion Importer
 * Authoritative Sources:
 * - Baba Baidyanath Temple Management Board (https://babadham.org)
 * - Jharkhand Tourism Development Corporation (https://tourism.jharkhand.gov.in)
 * - Archaeological Survey of India (Ranchi Circle) (https://asiranchicircle.in)
 * - District Administrations of Jharkhand
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const JHARKHAND_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Baba Baidyanath Jyotirlinga Temple Deoghar",
    nameLocal: "बाबा बैद्यनाथ ज्योतिर्लिंग मंदिर देवघर",
    stateCode: "JH",
    districtName: "Deoghar",
    localityName: "Deoghar City",
    latitude: 24.4925,
    longitude: 86.7003,
    mainDeity: "Lord Shiva (Baidyanath Jyotirlinga)",
    deities: ["Baidyanath Jyotirlinga", "Maa Parvati", "Ganesh", "Sandhya Devi"],
    templeType: "12 Holy Jyotirlingas & 51 Maha Shakti Peethas (Hardapeetha)",
    tradition: ["Shaivism", "Shaktism"],
    architecture: "Historic Nagara Stone Temple with Panchshool Spire",
    historicalPeriod: "Ancient Puranic / 1596 CE Stone Sanctum",
    description: "One of the twelve revered Jyotirlingas of Lord Shiva and site of the world-famous Shravani Mela Kanwar Yatra, where millions carry holy Ganga water from Sultanganj.",
    officialWebsite: "https://babadham.org",
    sourceRecordId: "JH-BABA-DEO-001",
    sourceName: "Baba Baidyanath Temple Management Board & Jharkhand Tourism",
    sourceUrl: "https://babadham.org",
    sourceType: "official",
  },
  {
    name: "Baba Basukinath Dham Temple",
    nameLocal: "बाबा बासुकीनाथ धाम मंदिर",
    stateCode: "JH",
    districtName: "Dumka",
    localityName: "Basukinath, Dumka",
    latitude: 24.3842,
    longitude: 86.8906,
    mainDeity: "Lord Shiva (Basukinath)",
    deities: ["Lord Shiva", "Mata Parvati"],
    templeType: "Sacred Kanwar Pilgrimage Completion Court",
    tradition: ["Shaivism"],
    architecture: "Traditional Nagara Shikhara Shrine Complex",
    historicalPeriod: "Ancient Pilgrimage / Modern Temple Trust",
    description: "Considered the spiritual court (Faujdari Darbar) of Lord Shiva where pilgrims must offer prayers to complete their Baidyanath Dham pilgrimage.",
    officialWebsite: "https://dumka.nic.in/tourist-place/basukinath-temple/",
    sourceRecordId: "JH-TOUR-DUM-002",
    sourceName: "Dumka District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Maa Chhinnamastika Temple Rajrappa",
    nameLocal: "माँ छिन्नमस्तिका मंदिर रजरप्पा",
    stateCode: "JH",
    districtName: "Ramgarh",
    localityName: "Rajrappa, Damodar-Bhairavi Confluence",
    latitude: 23.6319,
    longitude: 85.7144,
    mainDeity: "Maa Chhinnamasta (Tantric Mahavidya)",
    deities: ["Maa Chhinnamastika", "Dakini", "Varnini", "Lord Shiva"],
    templeType: "Das Mahavidya Tantra Pitha",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Historic Stone Temple at Sacred River Confluence",
    historicalPeriod: "Ancient Shakti Peetha / 17th Century CE Mandir",
    description: "One of the most famous Tantric Shakti shrines in India, dedicated to headless goddess Chhinnamasta at the rocky confluence of Damodar and Bhera (Bhairavi) rivers.",
    officialWebsite: "https://ramgarh.nic.in/tourist-place/rajrappa-temple/",
    sourceRecordId: "JH-TOUR-RAM-003",
    sourceName: "Ramgarh District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Jagannath Temple Ranchi",
    nameLocal: "जगन्नाथ मंदिर रांची",
    stateCode: "JH",
    districtName: "Ranchi",
    localityName: "Jagannathpur, Dhurwa, Ranchi",
    latitude: 23.3150,
    longitude: 85.2817,
    mainDeity: "Lord Jagannath",
    deities: ["Lord Jagannath", "Balabhadra", "Subhadra"],
    templeType: "Historic 17th-Century Hilltop Jagannath Sanctuary",
    tradition: ["Vaishnavism", "Jagannath Tradition"],
    architecture: "Kalinga-influenced Shikhara Architecture on Small Hillock",
    historicalPeriod: "King Ani Nath Shahdeo / 1691 CE",
    description: "Historical hilltop temple built on the model of the sacred Puri Jagannath Temple, celebrated for its massive annual Ratha Yatra fair.",
    officialWebsite: "https://ranchi.nic.in/tourist-place/jagannath-temple/",
    sourceRecordId: "JH-TOUR-RAN-004",
    sourceName: "Ranchi District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Luguburu Ghantabari Dharamgarh",
    nameLocal: "लुगुबुरू घांटाबाड़ी धरमगढ़",
    stateCode: "JH",
    districtName: "Bokaro",
    localityName: "Lugu Hills, Gomia, Bokaro",
    latitude: 23.7533,
    longitude: 85.8344,
    mainDeity: "Lugu Baba (Supreme Ancestral Spirit of Santhals)",
    deities: ["Lugu Baba", "Lugu Aayo", "Nature Spirits"],
    templeType: "Supreme Global Santhal Spiritual Heritage Sanctuary",
    tradition: ["Santhal Sarna Religion", "Indigenous Sacred Heritage"],
    architecture: "Natural Mountain Cave Sanctum in Lugu Hill Ranges",
    historicalPeriod: "Ancient Santhal Puranic Era",
    description: "The supreme global spiritual pilgrimage center for the Santhal community, drawing hundreds of thousands of tribal pilgrims on Kartik Purnima.",
    officialWebsite: "https://bokaro.nic.in/tourist-place/luguburu-ghantabari-dharamgarh/",
    sourceRecordId: "JH-TOUR-BOK-005",
    sourceName: "Bokaro District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Shakti Mandir Dhanbad",
    nameLocal: "शक्ति मंदिर धनबाद",
    stateCode: "JH",
    districtName: "Dhanbad",
    localityName: "Joraphatak Road, Dhanbad",
    latitude: 23.7958,
    longitude: 86.4294,
    mainDeity: "Maa Durga (Akhand Jyoti from Jwalamukhi)",
    deities: ["Maa Durga", "Radha-Krishna", "Hanuman"],
    templeType: "Revered City Shakti Shrine",
    tradition: ["Shaktism"],
    architecture: "Ornate Marble Nagara Style Temple",
    historicalPeriod: "Consecrated with Eternal Flame from Kangra Jwala Ji",
    description: "The primary devotional center of the coal capital Dhanbad, enshrining the eternal flame (Akhand Jyoti) brought from Maa Jwala Ji in Himachal Pradesh.",
    officialWebsite: "https://dhanbad.nic.in/tourist-place/shakti-mandir/",
    sourceRecordId: "JH-TOUR-DHA-006",
    sourceName: "Dhanbad District Administration & CG Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Shikharji Parasnath Sacred Tirth",
    nameLocal: "श्री सम्मेद शिखरजी पारसनाथ",
    stateCode: "JH",
    districtName: "Giridih",
    localityName: "Parasnath Hill, Madhuban",
    latitude: 23.9628,
    longitude: 86.1389,
    mainDeity: "Lord Parshvanatha & Tirthankaras",
    deities: ["20 Jain Tirthankaras Moksha Sthals", "Parshvanatha"],
    templeType: "Supreme Holy Jain Nirvana Tirth & Highest Peak of Jharkhand",
    tradition: ["Jainism (Digambara & Svetambara)"],
    architecture: "Sacred Mountain Tonks and Shikhara Temple Clusters",
    historicalPeriod: "Ancient Historical Era / 4,480 ft Highest Peak",
    description: "The holiest pilgrimage site in Jainism, where 20 of the 24 Tirthankaras attained Moksha. The summit rises to 4,480 feet amidst pristine sal forests.",
    officialWebsite: "https://giridih.nic.in/tourist-place/parasnath-temple/",
    sourceRecordId: "JH-TOUR-GIR-007",
    sourceName: "Giridih District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Jharkhandi Dham Shiva Temple",
    nameLocal: "झारखण्डी धाम शिव मंदिर",
    stateCode: "JH",
    districtName: "Giridih",
    localityName: "Dhanwar, Giridih",
    latitude: 24.2389,
    longitude: 85.9458,
    mainDeity: "Lord Shiva (Swayambhu Lingam)",
    deities: ["Lord Shiva"],
    templeType: "Open-Sky Sacred Shiva Shrine",
    tradition: ["Shaivism"],
    architecture: "Roofless Temple Tradition honoring Divine Immensity",
    historicalPeriod: "Ancient Swayambhu Pilgrimage Site",
    description: "Unique and revered open-roof Shiva shrine in Giridih district where the sanctum is intentionally open to the sky as per age-old local belief.",
    officialWebsite: "https://giridih.nic.in/tourist-place/jharkhandi-dham/",
    sourceRecordId: "JH-TOUR-GIR-008",
    sourceName: "Giridih District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Narsingh Sthan Mandir Hazaribagh",
    nameLocal: "नर्सिंग स्थान मंदिर हजारीबाग",
    stateCode: "JH",
    districtName: "Hazaribagh",
    localityName: "Khapriyaoon, Hazaribagh",
    latitude: 23.9717,
    longitude: 85.3956,
    mainDeity: "Lord Narasimha & Lord Shiva",
    deities: ["Lord Narasimha (Half-Man Half-Lion)", "Lord Shiva"],
    templeType: "Historic Harihara Confluence Shrine",
    tradition: ["Vaishnavism", "Shaivism"],
    architecture: "Ancient Stone and Lime Mortar Nagara Temple",
    historicalPeriod: "17th Century CE Temple Trust",
    description: "Famous pilgrimage site dedicated to Lord Narasimha, celebrated for its annual Kartik Purnima fair and continuous influx of devotees across Chota Nagpur.",
    officialWebsite: "https://hazaribag.nic.in/tourist-place/narsingh-sthan/",
    sourceRecordId: "JH-TOUR-HAZ-009",
    sourceName: "Hazaribagh District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Rankini Mandir Jadugoda",
    nameLocal: "रंकिणी मंदिर जादूगोड़ा",
    stateCode: "JH",
    districtName: "East Singhbhum",
    localityName: "Jadugoda Hills, Ghatshila",
    latitude: 22.6583,
    longitude: 86.3472,
    mainDeity: "Maa Rankini Devi",
    deities: ["Maa Rankini", "Lord Shiva"],
    templeType: "Historic Dhalbhum Royal Kuldevi Shrine",
    tradition: ["Shaktism", "Tribal-Sanatana Tradition"],
    architecture: "Hillside Stone Temple in Forest Foothills",
    historicalPeriod: "Dhalbhum Royal Dynasty / Ancient Rock-Cut Legend",
    description: "The presiding Kuldevi deity of the historic Dhalbhum kings, revered by all communities traveling through the mineral-rich hills of East Singhbhum.",
    officialWebsite: "https://jamshedpur.nic.in/tourist-place/rankini-temple/",
    sourceRecordId: "JH-TOUR-ESN-010",
    sourceName: "East Singhbhum District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Benisagar Archaeological Temple Complex",
    nameLocal: "बेनीसागर पुरातात्विक मंदिर समूह",
    stateCode: "JH",
    districtName: "West Singhbhum",
    localityName: "Benisagar, Majhgaon",
    latitude: 21.9889,
    longitude: 85.8750,
    mainDeity: "Lord Shiva & Agni",
    deities: ["Lord Shiva Lingams", "Goddess Durga", "Surya", "Ganesha"],
    templeType: "5th-9th Century Ancient ASI Monument Group",
    tradition: ["Shaivism", "Archaeological Heritage"],
    architecture: "Early Medieval Stone Temples around Historic Sagar Tank",
    historicalPeriod: "Post-Gupta to Somavanshi Era / 5th-9th Century CE",
    description: "An Archaeological Survey of India (ASI) protected heritage site with stone-sculpted temple remains and magnificent ancient water tank of King Beni.",
    officialWebsite: "https://chaibasa.nic.in/tourist-place/benisagar/",
    sourceRecordId: "JH-ASI-WSN-011",
    sourceName: "Archaeological Survey of India Ranchi Circle & CG Tourism",
    sourceUrl: "https://asiranchicircle.in",
    sourceType: "asi",
  },
  {
    name: "Bansidhar Temple Nagar Untari",
    nameLocal: "श्री बंशीधर मंदिर नगर उंटारी",
    stateCode: "JH",
    districtName: "Garhwa",
    localityName: "Nagar Untari / Shri Bansidhar Nagar",
    latitude: 24.2833,
    longitude: 83.5000,
    mainDeity: "Lord Krishna (Solid Gold Bansidhar)",
    deities: ["Bansidhar (Krishna Playing Flute)", "Radharani"],
    templeType: "Solid Gold Krishna Idol Heritage Shrine",
    tradition: ["Vaishnavism"],
    architecture: "Nagara Style Temple Complex",
    historicalPeriod: "Queen Shivmani Devi / 1885 CE",
    description: "Famed for its 4.5-foot, 1,280 kg solid gold idol of Lord Krishna playing the flute, discovered in the Shivpahari hills and enshrined by the Nagar Untari royal family.",
    officialWebsite: "https://garhwa.nic.in/tourist-place/banshidhar-temple/",
    sourceRecordId: "JH-TOUR-GAR-012",
    sourceName: "Shri Bansidhar Trust & Garhwa District Administration",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "official",
  },
  {
    name: "Maa Yogini Temple Pathergama",
    nameLocal: "माँ योगिनी मंदिर पथरगामा",
    stateCode: "JH",
    districtName: "Godda",
    localityName: "Lakhakiya Hills, Pathergama",
    latitude: 24.9667,
    longitude: 87.2833,
    mainDeity: "Maa Yogini (Goddess Sati's Thigh Peetha)",
    deities: ["Maa Yogini", "Bhairava"],
    templeType: "Secret Shakta Tantra Peetha (Gupt Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Hillside Rock-Cut Cave Temple",
    historicalPeriod: "Ancient Mahabharata Legend / Historic Shrine",
    description: "Revered as an esoteric Gupt Shakti Peetha where Goddess Sati's left thigh is believed to have fallen. Devotees climb 400 steps to reach the sacred cave shrine.",
    officialWebsite: "https://godda.nic.in/tourist-place/maa-yogini-temple/",
    sourceRecordId: "JH-TOUR-GOD-013",
    sourceName: "Godda District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Maa Chanchala Devi Temple Jamtara",
    nameLocal: "माँ चंचला देवी मंदिर जामताड़ा",
    stateCode: "JH",
    districtName: "Jamtara",
    localityName: "Chanchala Hill, Jamtara",
    latitude: 23.9583,
    longitude: 86.8000,
    mainDeity: "Maa Chanchala Devi",
    deities: ["Maa Chanchala Devi", "Lord Shiva"],
    templeType: "Historic District Kuldevi Shrine",
    tradition: ["Shaktism"],
    architecture: "Hilltop Shikhara Temple",
    historicalPeriod: "Historic Zamindari Period",
    description: "The guardian goddess of Jamtara district, situated atop a picturesque hillock, attracting thousands of pilgrims during annual Durga Puja and Navratri.",
    officialWebsite: "https://jamtara.nic.in/",
    sourceRecordId: "JH-TOUR-JAM-014",
    sourceName: "Jamtara District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Panchghagh Shiva Sthal Khunti",
    nameLocal: "पंचघाघ शिव स्थल खूंटी",
    stateCode: "JH",
    districtName: "Khunti",
    localityName: "Panchghagh Waterfalls, Khunti",
    latitude: 22.9833,
    longitude: 85.2667,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Mata Parvati"],
    templeType: "Five-Stream Waterfall Sacred Sthal",
    tradition: ["Shaivism"],
    architecture: "Natural River Rock Sanctum",
    historicalPeriod: "Ancient Indigenous Pilgrimage",
    description: "Sacred shrine nestled amidst the five cascading streams of Banai River in historic Khunti, the homeland of revolutionary tribal icon Bhagwan Birsa Munda.",
    officialWebsite: "https://khunti.nic.in/tourist-place/panch-ghagh-fall/",
    sourceRecordId: "JH-TOUR-KHU-015",
    sourceName: "Khunti District Administration & Jharkhand Tourism",
    sourceUrl: "https://khunti.nic.in",
    sourceType: "government",
  },
  {
    name: "Dhwajadhari Dham Koderma",
    nameLocal: "ध्वजाधारी धाम कोडरमा",
    stateCode: "JH",
    districtName: "Koderma",
    localityName: "Dhwajadhari Hill, Chandwara",
    latitude: 24.4667,
    longitude: 85.6000,
    mainDeity: "Lord Shiva (Dhwajadhari Mahadev)",
    deities: ["Lord Shiva", "Maharshi Kardam Rishi Ashram"],
    templeType: "Hilltop 777-Step Shaivite Pilgrimage",
    tradition: ["Shaivism", "Rishi Tradition"],
    architecture: "Hilltop Shikhara Shrine atop 777 Stone Steps",
    historicalPeriod: "Puranic Sage Kardam Ashram Legend",
    description: "Famous pilgrimage hill in the mica mining center Koderma, where pilgrims climb 777 steps to worship Lord Shiva on Maha Shivaratri.",
    officialWebsite: "https://koderma.nic.in/tourist-place/dhwajadhari-dham/",
    sourceRecordId: "JH-TOUR-KOD-016",
    sourceName: "Koderma District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Maa Ugra Tara Temple Chandwa",
    nameLocal: "माँ उग्रतारा मंदिर चंदवा",
    stateCode: "JH",
    districtName: "Latehar",
    localityName: "Nagar Village, Chandwa, Latehar",
    latitude: 23.6833,
    longitude: 84.7333,
    mainDeity: "Maa Ugra Tara",
    deities: ["Maa Ugra Tara", "Maa Manik Devi", "Lord Ganesha"],
    templeType: "Historic Tantric Siddha Peetha",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Ancient Stone Carvings and Mandapa",
    historicalPeriod: "Tori Royal Estate / Medieval Era",
    description: "Revered as one of the significant Tantric seats of Goddess Tara in Eastern India, situated in the scenic hills of Latehar district.",
    officialWebsite: "https://latehar.nic.in/tourist-place/ugra-tara-temple/",
    sourceRecordId: "JH-TOUR-LAT-017",
    sourceName: "Latehar District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Akhileshwar Dham Shiva Mandir Lohardaga",
    nameLocal: "अखिलेश्वर धाम शिव मंदिर लोहरदगा",
    stateCode: "JH",
    districtName: "Lohardaga",
    localityName: "Bhandra, Lohardaga",
    latitude: 23.4333,
    longitude: 84.6833,
    mainDeity: "Lord Shiva (Akhileshwar Mahadev)",
    deities: ["Lord Shiva", "Parvati", "Nandi"],
    templeType: "Historic District Shaiva Shrine",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Temple Complex",
    historicalPeriod: "Early 20th Century CE",
    description: "Prominent pilgrimage center of Lohardaga district hosting major annual Shravan and Maha Shivaratri religious gatherings.",
    officialWebsite: "https://lohardaga.nic.in/",
    sourceRecordId: "JH-TOUR-LOH-018",
    sourceName: "Lohardaga District Administration & Jharkhand Tourism",
    sourceUrl: "https://lohardaga.nic.in",
    sourceType: "government",
  },
  {
    name: "Nityakali Mandir Pakur",
    nameLocal: "नित्याकाली मंदिर पाकुड़",
    stateCode: "JH",
    districtName: "Pakur",
    localityName: "Pakur Town",
    latitude: 24.6333,
    longitude: 87.8500,
    mainDeity: "Maa Nityakali",
    deities: ["Maa Nityakali", "Lord Shiva"],
    templeType: "Historic Bengal-Jharkhand Border Kali Bari",
    tradition: ["Shaktism"],
    architecture: "Traditional Bengali Shikhara Kali Temple",
    historicalPeriod: "Pakur Royal Rajbari / 18th Century CE",
    description: "Centuries-old revered Kali shrine located near the Jharkhand-Bengal border in Pakur, established under royal patronages of local zamindars.",
    officialWebsite: "https://pakur.nic.in/",
    sourceRecordId: "JH-TOUR-PAK-019",
    sourceName: "Pakur District Administration & Jharkhand Tourism",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "government",
  },
  {
    name: "Palamu Fort Shiva Temple Medininagar",
    nameLocal: "पलामू किला शिव मंदिर मेदिनीनगर",
    stateCode: "JH",
    districtName: "Palamu",
    localityName: "Auranga River, Betla Reserve Border",
    latitude: 23.9000,
    longitude: 84.2333,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Chero Kings Ancestral Deities"],
    templeType: "Historical Chero Dynasty Fort Temple (ASI Monument)",
    tradition: ["Shaivism"],
    architecture: "Medieval Stone Fort Architecture with Intricate Carvings",
    historicalPeriod: "Chero King Medini Ray / 16th-17th Century CE",
    description: "Protected ASI heritage monument located within the historic Palamu fortresses on the banks of Auranga river, built by the celebrated Chero rulers.",
    officialWebsite: "https://palamu.nic.in/tourist-place/palamu-fort/",
    sourceRecordId: "JH-TOUR-PAL-020",
    sourceName: "Archaeological Survey of India & Palamu Administration",
    sourceUrl: "https://asiranchicircle.in",
    sourceType: "asi",
  },
  {
    name: "Bindudham Shakti Mandir Barharwa",
    nameLocal: "बिन्दुधाम शक्ति मंदिर बड़हरवा",
    stateCode: "JH",
    districtName: "Sahebganj",
    localityName: "Binduvasini Hill, Barharwa",
    latitude: 24.8583,
    longitude: 87.7750,
    mainDeity: "Maa Binduvasini (Durga)",
    deities: ["Maa Binduvasini", "Trishakti (Maha Lakshmi, Kali, Saraswati)"],
    templeType: "Ganga River Basin Hilltop Shakti Shrine",
    tradition: ["Shaktism"],
    architecture: "Hillside White Shikhara Temple Complex",
    historicalPeriod: "Ancient Folk Tradition / Modern Temple Trust",
    description: "Prominent hilltop pilgrimage shrine near the banks of River Ganga in Sahebganj, celebrated for its massive nine-day Chaitra Navratri Mela.",
    officialWebsite: "https://sahibganj.nic.in/tourist-place/bindudham/",
    sourceRecordId: "JH-TOUR-SAH-021",
    sourceName: "Sahebganj District Administration & Jharkhand Tourism",
    sourceUrl: "https://sahibganj.nic.in",
    sourceType: "government",
  },
  {
    name: "Maa Paudi Devi Mandir Seraikela",
    nameLocal: "माँ पौड़ी देवी मंदिर सरायकेला",
    stateCode: "JH",
    districtName: "Seraikela Kharsawan",
    localityName: "Seraikela Rajbari",
    latitude: 22.7000,
    longitude: 85.9333,
    mainDeity: "Maa Paudi Devi (Kuldevi of Chhau Artists)",
    deities: ["Maa Paudi Devi", "Lord Shiva"],
    templeType: "Seraikela Royal Palace & Chhau Dance Patron Shrine",
    tradition: ["Shaktism", "UNESCO Chhau Heritage"],
    architecture: "Traditional Royal Court Temple",
    historicalPeriod: "Seraikela Royal Singh Deo Dynasty / 16th Century CE",
    description: "Sacred patron goddess of the Seraikela royal family and world-famous UNESCO Intangible Cultural Heritage Seraikela Chhau dance tradition.",
    officialWebsite: "https://seraikela.nic.in/",
    sourceRecordId: "JH-TOUR-SER-022",
    sourceName: "Seraikela-Kharsawan Administration & Jharkhand Tourism",
    sourceUrl: "https://seraikela.nic.in",
    sourceType: "government",
  },
  {
    name: "Ramrekha Dham Simdega",
    nameLocal: "रामरेखा धाम सिमडेगा",
    stateCode: "JH",
    districtName: "Simdega",
    localityName: "Ramrekha Hills, Simdega",
    latitude: 22.4500,
    longitude: 84.3667,
    mainDeity: "Lord Rama, Sita & Lakshmana",
    deities: ["Lord Rama", "Mata Sita", "Lakshmana", "Gupt Ganga Kund"],
    templeType: "Ramayana Dandakaranya Exile Pilgrimage Cave",
    tradition: ["Vaishnavism"],
    architecture: "Natural Hilltop Cave Sanctuary & Holy Ponds",
    historicalPeriod: "Treta Yuga Legend / Sacred Tribal Pilgrimage",
    description: "Holy site where Lord Rama, Sita, and Lakshmana are believed to have stayed during their 14-year exile. Features Ramrekha line and Gupt Ganga spring.",
    officialWebsite: "https://simdega.nic.in/tourist-place/ramrekha-dham/",
    sourceRecordId: "JH-TOUR-SIM-023",
    sourceName: "Ramrekha Dham Development Committee & Simdega Admin",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "official",
  },
  {
    name: "Maa Bhadrakali Temple Itkhori",
    nameLocal: "माँ भद्रकाली मंदिर इटखोरी",
    stateCode: "JH",
    districtName: "Chatra",
    localityName: "Mohane River Bank, Itkhori",
    latitude: 24.2833,
    longitude: 85.1500,
    mainDeity: "Maa Bhadrakali",
    deities: ["Maa Bhadrakali", "Sahasralinga Mahadev", "Lord Buddha Stupa"],
    templeType: "Hindu, Buddhist and Jain Tri-Religious Sacred Heritage",
    tradition: ["Shaktism", "Buddhism", "Jainism"],
    architecture: "Ancient 9th-Century Pala Dynasty Black Stone Sculptures",
    historicalPeriod: "Pala Empire King Mahendrapala / 9th Century CE",
    description: "Unique spiritual site uniting Hinduism, Buddhism, and Jainism on the banks of Mohane River, featuring a monolithic Bhadrakali statue and Sahasralinga.",
    officialWebsite: "https://chatra.nic.in/tourist-place/bhadrakali-temple/",
    sourceRecordId: "JH-TOUR-CHA-024",
    sourceName: "Bhadrakali Temple Trust & Chatra District Administration",
    sourceUrl: "https://tourism.jharkhand.gov.in",
    sourceType: "official",
  },
];

export async function importJharkhandTemples(options: { dryRun?: boolean; parserVersion?: string } = {}) {
  console.log("==================================================");
  console.log("🏛️ JHARKHAND TEMPLE INGESTION ENGINE");
  console.log("Source: Baba Baidyanath Trust, Jharkhand Tourism & ASI");
  console.log(`Mode: ${options.dryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  return processStateBatch(
    "Baba Baidyanath Trust, Jharkhand Tourism & ASI",
    "https://tourism.jharkhand.gov.in",
    JHARKHAND_AUTHORITATIVE_TEMPLES,
    options
  );
}

// CLI runner
if (process.argv[1]?.endsWith("jharkhand.ts")) {
  const isDryRun = process.argv.includes("--dry-run");
  importJharkhandTemples({ dryRun: isDryRun })
    .then((report) => {
      console.log("\nTelemetry Report:");
      console.log(JSON.stringify(report, null, 2));
      process.exit(0);
    })
    .catch((err) => {
      console.error("\n❌ Importer crashed:", err);
      process.exit(1);
    });
}
