/**
 * Karnataka Official State Ingestion Importer
 * Authoritative Source: Karnataka Hindu Religious Institutions and Charitable Endowments (Muzrai) & KSTDC
 * Portal: https://kstdc.co / https://mysuru.nic.in
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const KARNATAKA_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Chamundeshwari Temple",
    nameLocal: "ಶ್ರೀ ಚಾಮುಂಡೇಶ್ವರಿ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Mysuru",
    localityName: "Chamundi Hill",
    latitude: 12.2727,
    longitude: 76.6711,
    mainDeity: "Goddess Chamundeshwari (Durga)",
    deities: ["Chamundeshwari", "Mahishasura Mardini"],
    templeType: "Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Dravidian Gopuram Architecture",
    historicalPeriod: "Hoysala & Wadiyar Dynasty",
    description: "Located atop the sacred Chamundi Hills overlooking Mysuru, dedicated to the tutelary deity of the Wadiyar royal family.",
    officialWebsite: "https://chamundeshwaritemple.karnataka.gov.in",
    sourceRecordId: "KA-MUZ-MYS-001",
    sourceName: "Karnataka Muzrai Department",
    sourceUrl: "https://chamundeshwaritemple.karnataka.gov.in",
    sourceType: "government",
  },
  {
    name: "Kollur Mookambika Temple",
    nameLocal: "ಕೊಲ್ಲೂರು ಮೂಕಾಂಬಿಕಾ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Udupi",
    localityName: "Kollur",
    latitude: 13.8653,
    longitude: 74.8142,
    mainDeity: "Goddess Mookambika",
    deities: ["Mookambika (Saraswati, Lakshmi, Parvati trinity)"],
    templeType: "Shakti Peetha",
    tradition: ["Shaktism", "Smartha"],
    architecture: "Malabar / Coastal Karnataka Timber and Stone",
    historicalPeriod: "Adi Shankara Consecration",
    description: "Nestled in the foothills of the Kodachadri mountain range, consecrated by Adi Shankara with a Jyotirlinga split into two halves representing Shiva and Shakti.",
    officialWebsite: "https://kollurmookambika.org",
    sourceRecordId: "KA-MUZ-UDU-002",
    sourceName: "Karnataka Muzrai Department",
    sourceUrl: "https://kollurmookambika.org",
    sourceType: "government",
  },
  {
    name: "Virupaksha Temple Hampi",
    nameLocal: "ವಿರೂಪಾಕ್ಷ ದೇವಾಲಯ ಹಂಪಿ",
    stateCode: "KA",
    districtName: "Vijayanagara",
    localityName: "Hampi",
    latitude: 15.3351,
    longitude: 76.4601,
    mainDeity: "Virupaksha (Lord Shiva)",
    deities: ["Virupaksha", "Pampa Devi"],
    templeType: "UNESCO World Heritage Site",
    tradition: ["Shaivism"],
    architecture: "Vijayanagara Architecture",
    historicalPeriod: "7th Century CE to Vijayanagara Golden Age",
    description: "The primary operational pilgrimage center in Hampi, intact through centuries and crowned by a towering 50-meter eastern gopuram on the banks of the Tungabhadra.",
    officialWebsite: "https://vijayanagara.nic.in/tourist-place/virupaksha-temple/",
    sourceRecordId: "ASI-KA-N-KA-C2",
    sourceName: "Archaeological Survey of India & Karnataka Tourism",
    sourceUrl: "https://asi.nic.in/monuments-hampi/",
    sourceType: "government",
  },
  {
    name: "Chennakeshava Temple Belur",
    nameLocal: "ಚೆನ್ನಕೇಶವ ದೇವಾಲಯ ಬೇಲೂರು",
    stateCode: "KA",
    districtName: "Hassan",
    localityName: "Belur",
    latitude: 13.1627,
    longitude: 75.8596,
    mainDeity: "Chennakeshava (Handsome Vishnu)",
    deities: ["Chennakeshava", "Soumyanayaki"],
    templeType: "UNESCO World Heritage Site (Sacred Ensembles of the Hoysalas)",
    tradition: ["Vaishnavism"],
    architecture: "Hoysala Stellate Architecture",
    historicalPeriod: "Hoysala Empire (1117 CE)",
    description: "Commissioned by King Vishnuvardhana in 1117 CE to commemorate his victory, renowned worldwide for intricate chloritic schist filigree carvings and Madanika dancers.",
    officialWebsite: "https://hassan.nic.in/tourist-place/chennakeshava-temple/",
    sourceRecordId: "ASI-KA-N-KA-B3",
    sourceName: "Archaeological Survey of India & KSTDC",
    sourceUrl: "https://asi.nic.in/world-heritage-sites-hoysala-temples/",
    sourceType: "government",
  },
  {
    name: "Mahabaleshwar Temple Gokarna",
    nameLocal: "ಗೋಕರ್ಣ ಮಹಾಬಲೇಶ್ವರ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Uttara Kannada",
    localityName: "Gokarna",
    latitude: 14.5429,
    longitude: 74.3184,
    mainDeity: "Mahabaleshwara (Atmalinga)",
    deities: ["Lord Shiva", "Bhadrakali"],
    templeType: "Dakshina Kashi",
    tradition: ["Shaivism"],
    architecture: "Dravidian Granite Architecture",
    historicalPeriod: "Kadamba Dynasty (4th Century CE)",
    description: "Revered as the Dakshina Kashi enshrining the legendary Atmalinga placed by Ravana on the western shore of Karnataka.",
    officialWebsite: "https://uttarakannada.nic.in/tourist-place/gokarna/",
    sourceRecordId: "KA-MUZ-UTT-004",
    sourceName: "Karnataka Tourism & District Administration",
    sourceUrl: "https://uttarakannada.nic.in/tourist-place/gokarna/",
    sourceType: "government",
  },
  {
    name: "Kukke Subramanya Temple",
    nameLocal: "ಕುಕ್ಕೆ ಸುಬ್ರಹ್ಮಣ್ಯ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Dakshina Kannada",
    localityName: "Subramanya",
    latitude: 12.6631,
    longitude: 75.3725,
    mainDeity: "Lord Subramanya (Kartikeya with Vasuki)",
    deities: ["Subramanya", "Vasuki", "Shesha"],
    templeType: "Principal Naga Kshetra of India",
    tradition: ["Kaumaram", "Smartha"],
    architecture: "Coastal Karnataka Wood & Granite Architecture",
    historicalPeriod: "Adi Shankara Consecration (Ancient)",
    description: "Situated in the Western Ghats surrounded by the Kumara Parvatha mountain. Pilgrims from all over India visit for Sarpa Samskara and Ashlesha Bali poojas.",
    officialWebsite: "https://kukke.org",
    sourceRecordId: "KA-MUZ-DAK-005",
    sourceName: "Karnataka Muzrai Department",
    sourceUrl: "https://kukke.org",
    sourceType: "government",
  },
  {
    name: "Sri Manjunatha Swamy Temple Dharmasthala",
    nameLocal: "ಧರ್ಮಸ್ಥಳ ಶ್ರೀ ಮಂಜುನಾಥ ಸ್ವಾಮಿ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Dakshina Kannada",
    localityName: "Dharmasthala",
    latitude: 12.9511,
    longitude: 75.3789,
    mainDeity: "Manjunatha Swamy (Lord Shiva)",
    deities: ["Lord Shiva", "Dharmadaivatagalu"],
    templeType: "Historic Pilgrimage & Anna Dana Shrine",
    tradition: ["Shaivism", "Jain Trusteeship"],
    architecture: "Coastal Karnataka Dravidian Style",
    historicalPeriod: "800-Year-Old Historic Tradition",
    description: "A remarkable sanctuary of communal harmony where a Shiva temple is administered by a Jain family (Heggade) and worship is conducted by Vaishnavite priests.",
    officialWebsite: "https://shridharmasthala.org",
    sourceRecordId: "KA-MUZ-DAK-006",
    sourceName: "Karnataka Muzrai Department",
    sourceUrl: "https://shridharmasthala.org",
    sourceType: "government",
  },
  {
    name: "Hoysaleswara Temple Halebidu",
    nameLocal: "ಹೊಯ್ಸಳೇಶ್ವರ ದೇವಾಲಯ ಹಳೇಬೀಡು",
    stateCode: "KA",
    districtName: "Hassan",
    localityName: "Halebidu",
    latitude: 13.2131,
    longitude: 75.9939,
    mainDeity: "Hoysaleswara & Shantaleswara (Dvimukha Shiva)",
    deities: ["Lord Shiva"],
    templeType: "UNESCO World Heritage Site",
    tradition: ["Shaivism"],
    architecture: "Twin Stellate Hoysala Architecture",
    historicalPeriod: "King Vishnuvardhana (1121 CE)",
    description: "Twin-shrine masterpiece of Hoysala architecture carved from soapstone, with exterior walls depicting thousands of detailed relief friezes of Indian epics.",
    officialWebsite: "https://hassan.nic.in/tourist-place/hoysaleswara-temple-halebidu/",
    sourceRecordId: "ASI-KA-N-KA-B4",
    sourceName: "Archaeological Survey of India & KSTDC",
    sourceUrl: "https://asi.nic.in/world-heritage-sites-hoysala-temples/",
    sourceType: "government",
  },
  {
    name: "Murudeshwara Shiva Temple",
    nameLocal: "ಮುರುಡೇಶ್ವರ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Uttara Kannada",
    localityName: "Murudeshwara",
    latitude: 14.0942,
    longitude: 74.4897,
    mainDeity: "Murudeshwara (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Coastal Landmark & Giant Monolith",
    tradition: ["Shaivism"],
    architecture: "Modern Dravidian with 20-Storey Raja Gopura",
    historicalPeriod: "Atmalinga Legend Origin",
    description: "Situated on the Kanduka Hill surrounded on three sides by the Arabian Sea. Renowned for the world's second tallest Shiva statue standing 123 feet high.",
    officialWebsite: "https://kstdc.co/tourist-destinations/murudeshwara/",
    sourceRecordId: "KA-MUZ-UTT-007",
    sourceName: "Karnataka Tourism & Muzrai Department",
    sourceUrl: "https://kstdc.co/tourist-destinations/murudeshwara/",
    sourceType: "government",
  },
  {
    name: "Sri Sharadamba Temple Sringeri",
    nameLocal: "ಶೃಂಗೇರಿ ಶ್ರೀ ಶಾರದಾಂಬಾ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Chikkamagaluru",
    localityName: "Sringeri",
    latitude: 13.4194,
    longitude: 75.2575,
    mainDeity: "Goddess Sharadamba (Saraswati)",
    deities: ["Sharadamba", "Vidyashankara"],
    templeType: "Dakshinamnaya Sri Sharada Peetham",
    tradition: ["Smartha", "Advaita Vedanta"],
    architecture: "Hoysala & Dravidian Architecture",
    historicalPeriod: "Established by Adi Shankara (8th Century CE)",
    description: "The first of the four cardinal Advaita Vedanta maths established by Adi Shankaracharya on the banks of the Tunga River in the Western Ghats.",
    officialWebsite: "https://sringeri.net",
    sourceRecordId: "KA-MUZ-CHK-009",
    sourceName: "Sringeri Math & Karnataka Tourism",
    sourceUrl: "https://sringeri.net",
    sourceType: "government",
  },
  {
    name: "Cheluvanarayana Swamy Temple Melukote",
    nameLocal: "ಮೇಲುಕೋಟೆ ಚೆಲುವನಾರಾಯಣ ಸ್ವಾಮಿ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Mandya",
    localityName: "Melukote",
    latitude: 12.6642,
    longitude: 76.6547,
    mainDeity: "Cheluvanarayana Swamy (Lord Vishnu)",
    deities: ["Narayana", "Yoga Narasimha"],
    templeType: "Abhimana Kshetram & Sri Vaishnava Seat",
    tradition: ["Vaishnavism", "Sri Vaishnava"],
    architecture: "Dravidian Architecture",
    historicalPeriod: "Ramanujacharya Stay (12th Century CE)",
    description: "Built on rocky hills called Yadavagiri overlooking the Cauvery valley, where Acharya Ramanuja lived for 12 years and established sacred traditions.",
    officialWebsite: "https://mandya.nic.in/tourist-place/melukote/",
    sourceRecordId: "KA-MUZ-MAN-010",
    sourceName: "Karnataka Muzrai Department",
    sourceUrl: "https://mandya.nic.in/tourist-place/melukote/",
    sourceType: "government",
  },
  {
    name: "Sri Renuka Yellamma Temple Saundatti",
    nameLocal: "ಸವದತ್ತಿ ಶ್ರೀ ರೇಣುಕಾ ಎಲ್ಲಮ್ಮ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Belagavi",
    localityName: "Saundatti",
    latitude: 15.7686,
    longitude: 75.1181,
    mainDeity: "Goddess Renuka (Yellamma)",
    deities: ["Renuka Devi", "Parashurama"],
    templeType: "Major Folk Shakti Shrine of Karnataka & Maharashtra",
    tradition: ["Shaktism", "Folk Traditions"],
    architecture: "Chalukyan & Rashtrakuta Architecture confluence",
    historicalPeriod: "Rashtrakuta Dynasty (11th Century CE)",
    description: "Located atop Yellammagudda hill near Saundatti, attracting millions of devotees across North Karnataka and Southern Maharashtra during Margashira jathra.",
    officialWebsite: "https://belagavi.nic.in/tourist-place/saundatti/",
    sourceRecordId: "KA-MUZ-BEL-012",
    sourceName: "Karnataka Muzrai Department",
    sourceUrl: "https://belagavi.nic.in/tourist-place/saundatti/",
    sourceType: "government",
  },
  {
    name: "Male Mahadeshwara Hills Temple",
    nameLocal: "ಮಲೆ ಮಹದೇಶ್ವರ ಬೆಟ್ಟ ದೇವಾಲಯ",
    stateCode: "KA",
    districtName: "Chamarajanagar",
    localityName: "MM Hills",
    latitude: 11.9961,
    longitude: 77.5622,
    mainDeity: "Lord Male Mahadeshwara (Incarnation of Shiva)",
    deities: ["Mahadeshwara"],
    templeType: "Sacred Western Ghats Hill Shrine",
    tradition: ["Shaivism", "Lingayat Traditions"],
    architecture: "Hill Dravidian Style",
    historicalPeriod: "15th Century CE Folk Saint Shrine",
    description: "Perched 3,000 feet above sea level in the dense reserve forests of the Eastern/Western Ghats junction, dedicated to saint Mahadeshwara who performed miracles.",
    officialWebsite: "https://mmhills.karnataka.gov.in",
    sourceRecordId: "KA-MUZ-CHM-013",
    sourceName: "Male Mahadeshwara Swamy Kshetra Development Authority",
    sourceUrl: "https://mmhills.karnataka.gov.in",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ KARNATAKA TEMPLE INGESTION ENGINE");
  console.log(`Source: Karnataka Muzrai Department & KSTDC`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Karnataka Muzrai Department",
    "https://kstdc.co",
    KARNATAKA_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
