/**
 * Kerala Official State Ingestion Importer
 * Authoritative Source: Travancore Devaswom Board, Cochin Devaswom Board, Malabar Devaswom & Kerala Tourism
 * Portal: https://travancoredevaswomboard.org / https://keralatourism.org
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const KERALA_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Sree Padmanabhaswamy Temple",
    nameLocal: "ശ്രീ പത്മനാഭസ്വാമി ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Thiruvananthapuram",
    localityName: "East Fort, Thiruvananthapuram",
    latitude: 8.4830,
    longitude: 76.9436,
    mainDeity: "Lord Padmanabha (Ananthasayanam Maha Vishnu)",
    deities: ["Padmanabhaswamy", "Narasimha", "Krishna"],
    templeType: "Divya Desam",
    tradition: ["Vaishnavism"],
    architecture: "Chera and Dravidian Confluence Architecture",
    historicalPeriod: "Chera & Travancore Royal Dynasty",
    description: "Enshrines Lord Vishnu in the eternal yogic sleep (Ananthasayanam) posture atop the serpent Anantha. World-renowned for its sacred vaults, stone gopuram, and intricate pillar corridors.",
    officialWebsite: "https://spst.in",
    sourceRecordId: "KL-TDB-TVM-001",
    sourceName: "Travancore Royal Trust & District Administration",
    sourceUrl: "https://spst.in",
    sourceType: "government",
  },
  {
    name: "Guruvayur Sri Krishna Temple",
    nameLocal: "ഗുരുവായൂർ ശ്രീകൃഷ്ണ ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Thrissur",
    localityName: "Guruvayur",
    latitude: 10.5944,
    longitude: 76.0394,
    mainDeity: "Guruvayurappan (Unnikrishnan / Baby Krishna)",
    deities: ["Guruvayurappan", "Ganapathi", "Sastha"],
    templeType: "Bhuloka Vaikuntham",
    tradition: ["Vaishnavism"],
    architecture: "Traditional Kerala Timber & Copper Architecture",
    historicalPeriod: "Consecrated by Guru and Vayu (Pre-16th Century)",
    description: "Revered as the Bhuloka Vaikuntham (abode of Vishnu on earth). Famous for its strict tantric pooja rituals, elephant sanctuary (Punnathurkotta), and deep cultural significance.",
    officialWebsite: "https://guruvayurdevaswom.in",
    sourceRecordId: "KL-GDB-TSR-002",
    sourceName: "Guruvayur Devaswom Managing Committee",
    sourceUrl: "https://guruvayurdevaswom.in",
    sourceType: "government",
  },
  {
    name: "Sabarimala Sree Dharma Sastha Temple",
    nameLocal: "ശബരിമല ശ്രീ ധർമ്മശാസ്താ ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Pathanamthitta",
    localityName: "Periyar Tiger Reserve, Sabarimala",
    latitude: 9.4404,
    longitude: 77.0819,
    mainDeity: "Lord Ayyappa (Dharma Sastha)",
    deities: ["Ayyappa", "Malikappurathamma"],
    templeType: "Sacred Western Ghats Forest Pilgrimage",
    tradition: ["Sastha Worship", "Smartha"],
    architecture: "Traditional Kerala Copper-Roofed Sanctum",
    historicalPeriod: "Consecrated by Lord Parashurama",
    description: "Perched atop Sabarimala hill amid dense rainforests of the Periyar Tiger Reserve, reached by millions of pilgrims observing 41-day vratham to ascend the holy 18 golden steps (Pathinettam Padi).",
    officialWebsite: "https://travancoredevaswomboard.org",
    sourceRecordId: "KL-TDB-PTA-003",
    sourceName: "Travancore Devaswom Board",
    sourceUrl: "https://travancoredevaswomboard.org",
    sourceType: "government",
  },
  {
    name: "Vadakkunnathan Temple Thrissur",
    nameLocal: "വടക്കുംനാഥൻ ക്ഷേത്രം തൃശൂർ",
    stateCode: "KL",
    districtName: "Thrissur",
    localityName: "Thrissur",
    latitude: 10.5244,
    longitude: 76.2139,
    mainDeity: "Vadakkunnathan (Lord Shiva)",
    deities: ["Lord Shiva", "Sankaranarayana", "Rama"],
    templeType: "UNESCO Award-Winning Heritage Shrine",
    tradition: ["Shaivism"],
    architecture: "Classical Kerala Wood & Granite Architecture with Koothambalam",
    historicalPeriod: "Parashurama Consecration (Over 1,000 Years Old)",
    description: "Centuries-old architectural marvel surrounded by massive stone walls atop Thekkinkadu Maidan. Renowned for its huge Shiva Lingam completely covered in centuries of ghee abhishekam without melting.",
    officialWebsite: "https://cochindevaswomboard.org",
    sourceRecordId: "KL-CDB-TSR-004",
    sourceName: "Cochin Devaswom Board",
    sourceUrl: "https://cochindevaswomboard.org",
    sourceType: "government",
  },
  {
    name: "Chottanikkara Bhagavathy Temple",
    nameLocal: "ചോറ്റാനിക്കര ഭഗവതി ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Ernakulam",
    localityName: "Chottanikkara",
    latitude: 9.9325,
    longitude: 76.3931,
    mainDeity: "Rajarajeshwari (Saraswati, Lakshmi, Durga)",
    deities: ["Chottanikkara Amma", "Bhadrakali (Keezhkavu)"],
    templeType: "Premier Shakta Kshetram",
    tradition: ["Shaktism"],
    architecture: "Kerala Wood & Laterite Shrine with Keezhkavu Complex",
    historicalPeriod: "Adi Shankara Visit",
    description: "World-famous mother goddess temple where the deity is worshipped as Saraswati in the morning, Lakshmi at noon, and Durga in the evening. Renowned for the Guruthi pooja at Keezhkavu.",
    officialWebsite: "https://cochindevaswomboard.org",
    sourceRecordId: "KL-CDB-ERN-005",
    sourceName: "Cochin Devaswom Board",
    sourceUrl: "https://cochindevaswomboard.org",
    sourceType: "government",
  },
  {
    name: "Attukal Bhagavathy Temple",
    nameLocal: "ആറ്റുകാൽ ഭഗവതി ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Thiruvananthapuram",
    localityName: "Attukal",
    latitude: 8.4697,
    longitude: 76.9536,
    mainDeity: "Goddess Kannaki (Attukalamma)",
    deities: ["Attukal Bhagavathy"],
    templeType: "Sabarimala of Women & Guinness World Record Festival",
    tradition: ["Shaktism"],
    architecture: "Kerala & Tamil Confluence Architecture with Carved Gopuram",
    historicalPeriod: "Kannaki Legend Era",
    description: "Revered as the Sabarimala of Women. Holds Guinness World Records for the largest single gathering of women in the world during the annual Attukal Pongala festival.",
    officialWebsite: "https://attukal.org",
    sourceRecordId: "KL-TDB-TVM-006",
    sourceName: "Attukal Bhagavathy Temple Trust & Kerala Tourism",
    sourceUrl: "https://attukal.org",
    sourceType: "government",
  },
  {
    name: "Ambalappuzha Sri Krishna Temple",
    nameLocal: "അമ്പലപ്പുഴ ശ്രീകൃഷ്ണ ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Alappuzha",
    localityName: "Ambalappuzha",
    latitude: 9.3833,
    longitude: 76.3556,
    mainDeity: "Parthasarathy (Lord Krishna)",
    deities: ["Krishna"],
    templeType: "Historic Temple & Birthplace of Ottamthullal",
    tradition: ["Vaishnavism"],
    architecture: "Traditional Kerala Architecture",
    historicalPeriod: "Chempakassery Rajas (15th-17th Century)",
    description: "Built during the reign of the local Chempakassery rulers, world-famous for its sweet milk porridge offering (Ambalappuzha Palpayasam) and historic association with Kunjan Nambiar.",
    officialWebsite: "https://alappuzha.nic.in/tourist-place/ambalapuzha-sri-krishna-temple/",
    sourceRecordId: "KL-TDB-ALA-007",
    sourceName: "Travancore Devaswom Board",
    sourceUrl: "https://alappuzha.nic.in/tourist-place/ambalapuzha-sri-krishna-temple/",
    sourceType: "government",
  },
  {
    name: "Ettumanoor Mahadeva Temple",
    nameLocal: "ഏറ്റുമാനൂർ മഹാദേവ ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Kottayam",
    localityName: "Ettumanoor",
    latitude: 9.6706,
    longitude: 76.5622,
    mainDeity: "Ettumanoorappan (Aghora Murthy Shiva)",
    deities: ["Lord Shiva", "Ganapathi", "Sastha"],
    templeType: "Ancient Shaivite Shrine & Ezharaponnaana Venue",
    tradition: ["Shaivism"],
    architecture: "Circular Sreekovil (Vritta) with Mural Paintings",
    historicalPeriod: "Rebuilt 1542 CE",
    description: "Famous for its circular sanctum sanctorum adorned with 16th-century murals including the renowned Pradosha Tandavam, and the golden elephant statues (Ezharaponnana).",
    officialWebsite: "https://kottayam.nic.in/tourist-place/ettumanoor-mahadeva-temple/",
    sourceRecordId: "KL-TDB-KOT-008",
    sourceName: "Travancore Devaswom Board",
    sourceUrl: "https://kottayam.nic.in/tourist-place/ettumanoor-mahadeva-temple/",
    sourceType: "government",
  },
  {
    name: "Thirunelli Temple Maha Vishnu",
    nameLocal: "തിരുനെല്ലി ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Wayanad",
    localityName: "Thirunelli",
    latitude: 11.9022,
    longitude: 75.9961,
    mainDeity: "Lord Maha Vishnu (Thirunelli Perumal)",
    deities: ["Vishnu"],
    templeType: "The Kashi of the South (Dakshina Gaya)",
    tradition: ["Vaishnavism"],
    architecture: "Granite Stone Pillars in Valley Forest",
    historicalPeriod: "Chera Dynasty & Sage Parashurama (Over 1,000 Years Old)",
    description: "Nestled in a tranquil valley surrounded by the Brahmagiri hills in Wayanad, famed for pitru-tarpan ancestral rites at the Papanasini mountain stream.",
    officialWebsite: "https://wayanad.nic.in/tourist-place/thirunelli-temple/",
    sourceRecordId: "KL-MDB-WAY-010",
    sourceName: "Malabar Devaswom Board",
    sourceUrl: "https://wayanad.nic.in/tourist-place/thirunelli-temple/",
    sourceType: "government",
  },
  {
    name: "Parassinikkadavu Muthappan Temple",
    nameLocal: "പറശ്ശിനിക്കടവ് മുത്തപ്പൻ ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Kannur",
    localityName: "Parassinikkadavu",
    latitude: 11.9861,
    longitude: 75.4019,
    mainDeity: "Sree Muthappan (Confluence of Shiva & Vishnu)",
    deities: ["Muthappan"],
    templeType: "Egalitarian Folk Deity Shrine",
    tradition: ["Theyyam", "Folk Traditions"],
    architecture: "Open Riverside Courtyard on Valapattanam River",
    historicalPeriod: "Centuries-Old Living Ritual Tradition",
    description: "A unique shrine on the banks of the Valapattanam River where daily Theyyam ritual dance performances take place and offerings include roasted fish and toddy.",
    officialWebsite: "https://kannur.nic.in/tourist-place/parassinikadavu-muthappan-temple/",
    sourceRecordId: "KL-MDB-KAN-011",
    sourceName: "Malabar Devaswom Board & Kerala Tourism",
    sourceUrl: "https://kannur.nic.in/tourist-place/parassinikadavu-muthappan-temple/",
    sourceType: "government",
  },
  {
    name: "Mannarasala Nagaraja Temple Haripad",
    nameLocal: "മണ്ണാറശാല നാഗരാജ ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Alappuzha",
    localityName: "Haripad",
    latitude: 9.2789,
    longitude: 76.5161,
    mainDeity: "Nagaraja (King of Serpents)",
    deities: ["Nagaraja", "Sarpayakshi"],
    templeType: "Principal Serpent Shrine of Kerala",
    tradition: ["Naga Worship", "Smartha"],
    architecture: "Dense Sacred Grove (Kavu) with Over 30,000 Stone Serpent Images",
    historicalPeriod: "Parashurama Era Tradition",
    description: "Nestled in a dense 16-acre sacred forest grove with over 30,000 serpent stone images, where the head priestess (Valia Amma) conducts sacred poojas.",
    officialWebsite: "https://mannarasala.org",
    sourceRecordId: "KL-TDB-ALA-014",
    sourceName: "Mannarasala Temple Trust & Kerala Tourism",
    sourceUrl: "https://mannarasala.org",
    sourceType: "government",
  },
  {
    name: "Madhur Sree Madanantheshwara Siddhivinayaka Temple",
    nameLocal: "മധൂർ ശ്രീ മദന്തേശ്വര സിദ്ധിവിനായക ക്ഷേത്രം",
    stateCode: "KL",
    districtName: "Kasaragod",
    localityName: "Madhur",
    latitude: 12.5286,
    longitude: 75.0089,
    mainDeity: "Siddhivinayaka (Lord Ganesha)",
    deities: ["Lord Shiva", "Siddhivinayaka"],
    templeType: "Prominent Heritage Shrine of North Malabar",
    tradition: ["Ganapatya", "Shaivism"],
    architecture: "Three-Tiered Gabled Copper Roofing Structure",
    historicalPeriod: "Mayipadi Rajas of Kumbla (10th Century CE)",
    description: "Situated on the banks of the Madhuvahini River, famed for its towering copper-roofed three-tiered dome and the colossal swayambhu Ganapathi image.",
    officialWebsite: "https://kasargod.nic.in/tourist-place/madhur-temple/",
    sourceRecordId: "KL-MDB-KAS-017",
    sourceName: "Malabar Devaswom Board",
    sourceUrl: "https://kasargod.nic.in/tourist-place/madhur-temple/",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ KERALA TEMPLE INGESTION ENGINE");
  console.log(`Source: Travancore & Cochin Devaswom Boards`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Travancore Devaswom Board & Kerala Tourism",
    "https://keralatourism.org",
    KERALA_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
