/**
 * Madhya Pradesh Official State Ingestion Importer
 * Authoritative Source: Shri Mahakaleshwar Temple Management Committee, Shri Omkareshwar Temple Trust, MP Tourism, Archaeological Survey of India
 * Portal: https://shrimahakaleshwar.com / https://shriomkareshwar.org / https://mptourism.com
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const MADHYA_PRADESH_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Mahakaleshwar Jyotirlinga Temple Ujjain",
    nameLocal: "महाकालेश्वर ज्योतिर्लिंग मंदिर उज्जैन",
    stateCode: "MP",
    districtName: "Ujjain",
    localityName: "Jaisinghpura, Ujjain",
    latitude: 23.1828,
    longitude: 75.7681,
    mainDeity: "Mahakaleshwar (Dakshinmukhi Lord Shiva)",
    deities: ["Lord Shiva", "Omkareshwar (Second Tier)", "Nagchandreshwar (Third Tier)"],
    templeType: "Sacred Jyotirlinga & Mahakal Lok",
    tradition: ["Shaivism", "Tantra"],
    architecture: "Three-Storeyed Bhumija & Maratha Stone Architecture on Rudra Sagar",
    historicalPeriod: "Ancient Avantika Era / Rebuilt by Ranoji Shinde (1734 CE)",
    description: "The only south-facing (Dakshinmukhi) Jyotirlinga among the twelve holy shrines, world-renowned for its daily Bhasma Aarti (sacred ash ceremony) and the sprawling Mahakal Lok corridor.",
    officialWebsite: "https://shrimahakaleshwar.com",
    sourceRecordId: "MP-MAHA-UJJ-001",
    sourceName: "Shri Mahakaleshwar Temple Management Committee",
    sourceUrl: "https://shrimahakaleshwar.com",
    sourceType: "government",
  },
  {
    name: "Maa Harsiddhi Temple Ujjain",
    nameLocal: "माँ हरसिद्धि मंदिर उज्जैन",
    stateCode: "MP",
    districtName: "Ujjain",
    localityName: "Ujjain",
    latitude: 23.1808,
    longitude: 75.7644,
    mainDeity: "Goddess Harsiddhi (Mangal Chandika)",
    deities: ["Harsiddhi Mata", "Mahalakshmi", "Mahasaraswati"],
    templeType: "13th Maha Shakti Peetha (Koorpara Peetha)",
    tradition: ["Shaktism"],
    architecture: "Maratha Style Sanctum with Twin 50-Foot Deepasthambhas (1,011 Lamps)",
    historicalPeriod: "King Vikramaditya Patronage (Ancient)",
    description: "One of the 51 Shakti Peethas where Goddess Sati's elbow (Koorpara) fell. Famed as the tutelary deity of legendary Emperor Vikramaditya, with two towering pillar-towers lit with over 1,000 oil lamps during Navratri.",
    officialWebsite: "https://ujjain.nic.in/tourist-place/harsiddhi-temple/",
    sourceRecordId: "MP-MAHA-UJJ-002",
    sourceName: "Ujjain District Administration & MP Tourism",
    sourceUrl: "https://ujjain.nic.in/tourist-place/harsiddhi-temple/",
    sourceType: "government",
  },
  {
    name: "Shri Omkareshwar Jyotirlinga Temple",
    nameLocal: "श्री ओंकारेश्वर ज्योतिર્લિંગ મંદિર",
    stateCode: "MP",
    districtName: "Khandwa",
    localityName: "Mandhata Island, Omkareshwar",
    latitude: 22.2464,
    longitude: 76.1508,
    mainDeity: "Omkareshwar (Lord Shiva)",
    deities: ["Omkareshwar", "Mamleshwar (Amareshwar)"],
    templeType: "Sacred Jyotirlinga on Sacred Narmada Island",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Five-Storeyed Sandstone Temple on Om-Shaped Island",
    historicalPeriod: "Paramara Dynasty (11th Century CE)",
    description: "Situated on the Om-shaped river island of Mandhata in the sacred Narmada River, one of the 12 revered Jyotirlingas. Pilgrims complete the sacred circuit by worshipping both Omkareshwar and Mamleshwar on opposite banks.",
    officialWebsite: "https://shriomkareshwar.org",
    sourceRecordId: "MP-OMK-KHA-003",
    sourceName: "Shri Omkareshwar Temple Trust & Khandwa Administration",
    sourceUrl: "https://shriomkareshwar.org",
    sourceType: "government",
  },
  {
    name: "Kandariya Mahadeva Temple Khajuraho",
    nameLocal: "कंदारिया महादेव मंदिर खजुराहो",
    stateCode: "MP",
    districtName: "Chhatarpur",
    localityName: "Western Group of Temples, Khajuraho",
    latitude: 24.8536,
    longitude: 79.9197,
    mainDeity: "Lord Shiva (Marble Lingam)",
    deities: ["Lord Shiva"],
    templeType: "UNESCO World Heritage Site",
    tradition: ["Shaivism"],
    architecture: "Sandstone Nagara Shikhara with 84 Miniature Shrines (Urushringas)",
    historicalPeriod: "Chandela Dynasty / King Vidyadhara (1030 CE)",
    description: "The largest and most ornate temple of the Western Group in Khajuraho, rising 31 meters into the sky. Celebrated as the zenith of medieval Indian temple architecture with over 800 exquisitely carved sculptures.",
    officialWebsite: "https://asi.nic.in/world-heritage-sites-khajuraho/",
    sourceRecordId: "ASI-MP-C-MP-C1",
    sourceName: "Archaeological Survey of India & MP Tourism",
    sourceUrl: "https://asi.nic.in/world-heritage-sites-khajuraho/",
    sourceType: "government",
  },
  {
    name: "Maa Sharda Devi Temple Maihar",
    nameLocal: "माँ शारदा देवी मंदिर मैहर",
    stateCode: "MP",
    districtName: "Satna",
    localityName: "Trikuta Hill, Maihar",
    latitude: 24.2667,
    longitude: 80.7583,
    mainDeity: "Goddess Sharda (Saraswati)",
    deities: ["Maa Sharda", "Narasimha"],
    templeType: "Prominent Shakta Pilgrimage (Maihar Devi)",
    tradition: ["Shaktism"],
    architecture: "Hilltop Temple Complex reached by 1,063 Stone Steps or Ropeway",
    historicalPeriod: "Historic Alha-Udal Tradition (12th Century CE)",
    description: "Perched atop the 600-foot Trikuta hill in Maihar, where the necklace (Haar) of Goddess Sati is believed to have fallen. Famous for the legendary warrior Alha who was granted immortality by Maa Sharda.",
    officialWebsite: "https://satna.nic.in/tourist-place/maihar-sharda-devi-temple/",
    sourceRecordId: "MP-TOUR-SAT-004",
    sourceName: "Maa Sharda Devi Temple Management Committee & Satna District",
    sourceUrl: "https://satna.nic.in/tourist-place/maihar-sharda-devi-temple/",
    sourceType: "government",
  },
  {
    name: "Shri Pitambara Peeth Datia",
    nameLocal: "श्री पीताम्बरा पीठ दतिया",
    stateCode: "MP",
    districtName: "Datia",
    localityName: "Datia",
    latitude: 25.6667,
    longitude: 78.4611,
    mainDeity: "Goddess Bagalamukhi (Pitambara)",
    deities: ["Bagalamukhi", "Dhumavati", "Vankhandeshwar Shiva"],
    templeType: "Premier Tantric Siddha Peetha of Northern India",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Marble-Enclosed Courtyard Complex with Mahabharata-Era Lingam",
    historicalPeriod: "Swami Ji Maharaj (Established 1935 CE)",
    description: "One of the most famous Shakti Peethas dedicated to Goddess Bagalamukhi, associated with golden-yellow offerings and intense spiritual penance. Contains the ancient Mahabharata-era Vankhandeshwar Shiva Lingam.",
    officialWebsite: "https://datia.nic.in/tourist-place/pitambara-peeth/",
    sourceRecordId: "MP-TOUR-DAT-005",
    sourceName: "Shri Pitambara Peeth Trust & Datia District Administration",
    sourceUrl: "https://datia.nic.in/tourist-place/pitambara-peeth/",
    sourceType: "government",
  },
  {
    name: "Pashupatinath Temple Mandsaur",
    nameLocal: "पशुपतिनाथ मंदिर मंदसौर",
    stateCode: "MP",
    districtName: "Mandsaur",
    localityName: "River Shivna Bank, Mandsaur",
    latitude: 24.0667,
    longitude: 75.0833,
    mainDeity: "Ashtamukhi Pashupatinath (Eight-Faced Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Unique Eight-Faced Monolithic Shiva Shrine",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Temple with Four Entrance Portals on River Shivna",
    historicalPeriod: "5th-6th Century CE Inscription (Consecrated 1961)",
    description: "The only eight-faced (Ashtamukhi) Shiva lingam in the world, carved from smooth dark stone depicting Lord Shiva's eight cosmic aspects, situated on the banks of River Shivna in Mandsaur.",
    officialWebsite: "https://mandsaur.nic.in/tourist-place/pashupatinath-temple/",
    sourceRecordId: "MP-TOUR-MAN-006",
    sourceName: "Shri Pashupatinath Temple Trust & Mandsaur Administration",
    sourceUrl: "https://mandsaur.nic.in/tourist-place/pashupatinath-temple/",
    sourceType: "government",
  },
  {
    name: "Bhojeshwar Shiva Temple Bhojpur",
    nameLocal: "भोजेश्वर शिव मंदिर भोजपुर",
    stateCode: "MP",
    districtName: "Raisen",
    localityName: "Bhojpur",
    latitude: 23.1039,
    longitude: 77.5819,
    mainDeity: "Bhojeshwar (Colossal Shiva Lingam)",
    deities: ["Lord Shiva"],
    templeType: "ASI Monument of National Importance (Somnath of North)",
    tradition: ["Shaivism"],
    architecture: "Monumental Unfinished 11th-Century Paramara Stone Architecture",
    historicalPeriod: "Paramara King Bhoja (1010–1053 CE)",
    description: "Built by the polymath King Bhoja of Dhar, housing one of the largest Shiva lingas in India carved from a single polished limestone rock rising 7.5 feet high atop an 18-foot platform.",
    officialWebsite: "https://asi.nic.in/monuments-bhojpur/",
    sourceRecordId: "ASI-MP-C-MP-C2",
    sourceName: "Archaeological Survey of India & MP Tourism",
    sourceUrl: "https://asi.nic.in/monuments-bhojpur/",
    sourceType: "government",
  },
  {
    name: "Chausath Yogini Temple Bhedaghat",
    nameLocal: "चौंसठ योगिनी मंदिर भेड़ाघाट",
    stateCode: "MP",
    districtName: "Jabalpur",
    localityName: "Bhedaghat, Jabalpur",
    latitude: 23.1308,
    longitude: 79.7994,
    mainDeity: "Gauri Shankar & 64 Yoginis",
    deities: ["Gauri Shankar (Shiva-Parvati on Nandi)", "64 Yoginis"],
    templeType: "Ancient Hypaethral Yogini Pitha overlooking Marble Rocks",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Circular Hypaethral (Open-Sky) Granite Cloister with 81 Shrines",
    historicalPeriod: "Kalachuri Dynasty / King Yuvarajadeva I (10th Century CE)",
    description: "Perched on a scenic hillock above the famous Marble Rocks gorge and Dhuandhar Falls on the Narmada River, enshrining 64 distinct carved yogini statues within a circular open-air cloister.",
    officialWebsite: "https://jabalpur.nic.in/tourist-place/chausath-yogini-temple/",
    sourceRecordId: "MP-TOUR-JAB-007",
    sourceName: "Archaeological Survey of India & Jabalpur Administration",
    sourceUrl: "https://jabalpur.nic.in/tourist-place/chausath-yogini-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Chamunda & Tulja Bhavani Tekri Dewas",
    nameLocal: "माँ चामुंडा व तुलजा भवानी टेकरी देवास",
    stateCode: "MP",
    districtName: "Dewas",
    localityName: "Dewas Tekri",
    latitude: 22.9667,
    longitude: 76.0583,
    mainDeity: "Maa Chamunda Devi & Maa Tulja Bhavani",
    deities: ["Chamunda Devi", "Tulja Bhavani"],
    templeType: "Prominent Shakta Conical Hill Pilgrimage",
    tradition: ["Shaktism"],
    architecture: "Twin Mountain Hill Shrines reached by 300 Steps or Ropeway",
    historicalPeriod: "Pawar Maratha Dynasty Patronage (18th Century)",
    description: "Located atop the 300-foot conical hill (Tekri) dominating the skyline of Dewas. Pilgrims worship both the elder sister (Badi Mata - Tulja Bhavani) and the younger sister (Chhoti Mata - Chamunda Devi).",
    officialWebsite: "https://dewas.nic.in/tourist-place/dewas-tekri/",
    sourceRecordId: "MP-TOUR-DEW-008",
    sourceName: "Dewas District Administration & Devasthan Samiti",
    sourceUrl: "https://dewas.nic.in/tourist-place/dewas-tekri/",
    sourceType: "government",
  },
  {
    name: "Udayeshwara Temple Udaipur",
    nameLocal: "उदयेश्वर नीलकंठ मंदिर उदयपुर",
    stateCode: "MP",
    districtName: "Vidisha",
    localityName: "Udaipur, Basoda",
    latitude: 23.9011,
    longitude: 78.0589,
    mainDeity: "Neelkanth (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "ASI Monument of National Importance",
    tradition: ["Shaivism"],
    architecture: "Exquisite 11th-Century Bhumija Style Red Sandstone Temple",
    historicalPeriod: "Paramara King Udayaditya (1059–1080 CE)",
    description: "Considered the finest and most intact example of Bhumija temple architecture in India, celebrated for its star-shaped sanctum plan, intricate figural reliefs, and preserved Sanskrit inscriptions.",
    officialWebsite: "https://asi.nic.in/monuments-udaipur-vidisha/",
    sourceRecordId: "ASI-MP-C-MP-C3",
    sourceName: "Archaeological Survey of India & Vidisha Administration",
    sourceUrl: "https://asi.nic.in/monuments-udaipur-vidisha/",
    sourceType: "government",
  },
  {
    name: "Sas Bahu Temples Gwalior Fort",
    nameLocal: "सास बहू मंदिर ग्वालियर किला",
    stateCode: "MP",
    districtName: "Gwalior",
    localityName: "Gwalior Fort",
    latitude: 26.2308,
    longitude: 78.1722,
    mainDeity: "Sahastrabahu (Lord Vishnu)",
    deities: ["Lord Vishnu", "Lord Shiva"],
    templeType: "Monumental Fort Sanctum & ASI Monument",
    tradition: ["Vaishnavism", "Shaivism"],
    architecture: "Three-Storeyed Open-Pillared Red Sandstone Architecture",
    historicalPeriod: "Kachchhapaghata Dynasty / King Mahipala (1093 CE)",
    description: "Originally called Sahastrabahu (meaning hundred-armed Vishnu), situated inside Gwalior Fort. Comprises twin temples built without mortar with massive load-bearing beams adorned with lotus ceilings.",
    officialWebsite: "https://asi.nic.in/monuments-gwalior/",
    sourceRecordId: "ASI-MP-C-MP-C4",
    sourceName: "Archaeological Survey of India & MP Tourism",
    sourceUrl: "https://asi.nic.in/monuments-gwalior/",
    sourceType: "government",
  },
  {
    name: "Maha Mrityunjaya Temple Rewa",
    nameLocal: "महामृत्युंजय मंदिर रीवा",
    stateCode: "MP",
    districtName: "Rewa",
    localityName: "Rewa Fort Complex, Rewa",
    latitude: 24.5367,
    longitude: 81.2983,
    mainDeity: "Maha Mrityunjaya Shiva (1,001 Eyes)",
    deities: ["Lord Shiva"],
    templeType: "Unique 1,001-Eyed Shiva Kshetra (Healing Shrine)",
    tradition: ["Shaivism"],
    architecture: "White Limestone Sanctum inside Rewa Royal Fort",
    historicalPeriod: "Baghel Dynasty Royalty (Ancient)",
    description: "Located within the Rewa Fort premises, enshrining a unique white Shiva Lingam carved with 1,001 distinct eyes (Sahasrachakshu). Devotees recite the Maha Mrityunjaya mantra here for protection and longevity.",
    officialWebsite: "https://rewa.nic.in/tourist-place/maha-mrityunjay-temple/",
    sourceRecordId: "MP-TOUR-REW-009",
    sourceName: "Rewa District Administration & MP Tourism",
    sourceUrl: "https://rewa.nic.in/tourist-place/maha-mrityunjay-temple/",
    sourceType: "government",
  },
  {
    name: "Sethani Ghat Shrines Narmadapuram",
    nameLocal: "सेठानी घाट मंदिर परिसर नर्मदापुरम",
    stateCode: "MP",
    districtName: "Narmadapuram",
    localityName: "Narmadapuram (Hoshangabad)",
    latitude: 22.7514,
    longitude: 77.7289,
    mainDeity: "Maa Narmada & Lord Shiva",
    deities: ["Maa Narmada", "Lord Shiva"],
    templeType: "Premier Narmada River Ghat & Temple Complex",
    tradition: ["Smartha", "Shaivism"],
    architecture: "Grand 19th-Century Stepped Stone Riverside Ghat Architecture",
    historicalPeriod: "Jankibai Sethani (19th Century CE)",
    description: "One of the largest ghat complexes in India on the sacred Narmada River, lined with centuries-old temples where daily Narmada Maha Aarti takes place at dusk, drawing thousands of pilgrims.",
    officialWebsite: "https://narmadapuram.nic.in/tourist-place/sethani-ghat/",
    sourceRecordId: "MP-TOUR-NAR-010",
    sourceName: "Narmadapuram District Administration & MP Tourism",
    sourceUrl: "https://narmadapuram.nic.in/tourist-place/sethani-ghat/",
    sourceType: "government",
  },
  {
    name: "Nilkanth Mahadev Temple Mandu",
    nameLocal: "नीलकंठ महादेव मंदिर मांडू",
    stateCode: "MP",
    districtName: "Dhar",
    localityName: "Mandu (Mandavgad)",
    latitude: 22.3397,
    longitude: 75.3858,
    mainDeity: "Neelkanth (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Historic Forest Ravine Shiva Shrine",
    tradition: ["Shaivism"],
    architecture: "Paramara Period Water-Engineered Temple carved into Cliff Valley",
    historicalPeriod: "Paramara Dynasty & Mughal Era Inscriptions",
    description: "Built into the side of a deep gorge in Mandu with perennial mountain springs channeled directly over the sacred Shiva Lingam, combining Paramara stone carvings with tranquil forest seclusion.",
    officialWebsite: "https://dhar.nic.in/tourist-place/nilkanth-temple/",
    sourceRecordId: "ASI-MP-C-MP-C5",
    sourceName: "Archaeological Survey of India & Dhar Administration",
    sourceUrl: "https://dhar.nic.in/tourist-place/nilkanth-temple/",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ MADHYA PRADESH TEMPLE INGESTION ENGINE");
  console.log(`Source: Mahakaleshwar Management Committee, Omkareshwar Trust & MP Tourism`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Shri Mahakaleshwar & Omkareshwar Trusts & MP Tourism",
    "https://mptourism.com",
    MADHYA_PRADESH_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
