/**
 * Maharashtra Official State Ingestion Importer
 * Authoritative Source: Maharashtra Tourism (MTDC) & Official Temple Trusts
 * Portal: https://maharashtratourism.gov.in / https://sai.org.in / https://trimbakeshwartemple.org
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const MAHARASHTRA_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Shri Saibaba Sansthan Temple Shirdi",
    nameLocal: "श्री साईबाबा संस्थान शिर्डी",
    stateCode: "MH",
    districtName: "Ahmednagar",
    localityName: "Shirdi",
    latitude: 19.7667,
    longitude: 74.4764,
    mainDeity: "Shri Shirdi Sai Baba",
    deities: ["Sai Baba"],
    templeType: "Samadhi Mandir & Global Pilgrimage Shrine",
    tradition: ["Smartha", "Universal Spiritual"],
    architecture: "Modern Indo-Saracenic Marble Shrine",
    historicalPeriod: "20th Century (Mahasamadhi 1918)",
    description: "The Samadhi Mandir of Sai Baba of Shirdi, drawing millions of pilgrims across faiths from across the world with continuous community feeding (Prasadalaya).",
    officialWebsite: "https://sai.org.in",
    sourceRecordId: "MH-SAI-SHI-001",
    sourceName: "Shri Saibaba Sansthan Trust",
    sourceUrl: "https://sai.org.in",
    sourceType: "government",
  },
  {
    name: "Trimbakeshwar Shiva Temple",
    nameLocal: "त्र्यंबकेश्वर ज्योतिर्लिंग मंदिर",
    stateCode: "MH",
    districtName: "Nashik",
    localityName: "Trimbak",
    latitude: 19.9324,
    longitude: 73.5308,
    mainDeity: "Trimbakeshwar (Lord Shiva)",
    deities: ["Trimbakeshwar (Brahma, Vishnu, Maheshwara three faces)"],
    templeType: "Jyotirlinga & Kumbh Mela Venue",
    tradition: ["Shaivism"],
    architecture: "Hemadpanthi Black Basalt Stone Architecture",
    historicalPeriod: "Peshwa Balaji Baji Rao (1755-1786)",
    description: "One of the 12 sacred Jyotirlingas, situated at the source of the holy Godavari River nestled between Brahmagiri, Nilgiri, and Kalagiri hills.",
    officialWebsite: "https://trimbakeshwartemple.org",
    sourceRecordId: "MH-TRIM-NAS-002",
    sourceName: "Shri Trimbakeshwar Sansthan Trust",
    sourceUrl: "https://trimbakeshwartemple.org",
    sourceType: "government",
  },
  {
    name: "Shri Siddhivinayak Ganapati Mandir",
    nameLocal: "श्री सिद्धिविनायक गणपती मंदिर",
    stateCode: "MH",
    districtName: "Mumbai Suburban",
    localityName: "Prabhadevi, Mumbai",
    latitude: 19.0169,
    longitude: 72.8304,
    mainDeity: "Lord Ganesha (Siddhivinayak)",
    deities: ["Ganesha", "Riddhi", "Siddhi"],
    templeType: "Prominent Metropolitan Shrine",
    tradition: ["Ganapatya"],
    architecture: "Multi-Tiered Gold-Plated Sanctum Dome",
    historicalPeriod: "Laxman Vithu & Deubai Patil (1801 CE)",
    description: "One of the most visited temples in Mumbai, enshrining Lord Ganesha with four arms and trunk turned towards the right, flanked by goddesses Riddhi and Siddhi.",
    officialWebsite: "https://siddhivinayak.org",
    sourceRecordId: "MH-SID-MUM-003",
    sourceName: "Shree Siddhivinayak Ganapati Temple Trust",
    sourceUrl: "https://siddhivinayak.org",
    sourceType: "government",
  },
  {
    name: "Mahalakshmi Temple Kolhapur",
    nameLocal: "श्री महालक्ष्मी अंबाबाई मंदिर कोल्हापूर",
    stateCode: "MH",
    districtName: "Kolhapur",
    localityName: "Kolhapur",
    latitude: 16.6942,
    longitude: 74.2239,
    mainDeity: "Goddess Ambabai (Mahalakshmi)",
    deities: ["Mahalakshmi", "Mahakali", "Mahasaraswati"],
    templeType: "Maha Shakti Peetha & Karveer Nivasini",
    tradition: ["Shaktism"],
    architecture: "Hemadpanthi Chalukya Basalt Architecture",
    historicalPeriod: "Chalukya Dynasty (7th Century CE)",
    description: "One of the celebrated 18 Maha Shakti Peethas where both Vishnu and Shiva deities surround Goddess Ambabai. Famous for Kiranotsav when sun rays illuminate the deity.",
    officialWebsite: "https://mahalaxmikolhapur.com",
    sourceRecordId: "MH-MAH-KOL-004",
    sourceName: "Paschim Maharashtra Devasthan Samiti",
    sourceUrl: "https://mahalaxmikolhapur.com",
    sourceType: "government",
  },
  {
    name: "Grishneshwar Jyotirlinga Temple",
    nameLocal: "घृष्णेश्वर ज्योतिर्लिंग मंदिर",
    stateCode: "MH",
    districtName: "Chhatrapati Sambhajinagar",
    localityName: "Verul (Ellora)",
    latitude: 20.0247,
    longitude: 75.1714,
    mainDeity: "Grishneshwar (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Twelfth Jyotirlinga Shrine",
    tradition: ["Shaivism"],
    architecture: "Red Basalt Stone Maratha / Hemadpanthi Architecture",
    historicalPeriod: "Reconstructed by Ahilyabai Holkar (18th Century CE)",
    description: "The 12th and last of the sacred Jyotirlinga shrines in India, situated less than a kilometer from the UNESCO World Heritage Ellora Caves.",
    officialWebsite: "https://aurangabad.nic.in/tourist-place/grishneshwar-temple/",
    sourceRecordId: "MH-GRI-AUR-005",
    sourceName: "Maharashtra Tourism & Trust Board",
    sourceUrl: "https://aurangabad.nic.in/tourist-place/grishneshwar-temple/",
    sourceType: "government",
  },
  {
    name: "Bhimashankar Jyotirlinga Temple",
    nameLocal: "भीमाशंकर ज्योतिर्लिंग मंदिर",
    stateCode: "MH",
    districtName: "Pune",
    localityName: "Bhimashankar",
    latitude: 19.0722,
    longitude: 73.5358,
    mainDeity: "Bhimashankar (Lord Shiva)",
    deities: ["Lord Shiva", "Kamalaja Devi"],
    templeType: "Jyotirlinga & Source of Bhima River",
    tradition: ["Shaivism"],
    architecture: "Nagara & Hemadpanthi Black Basalt Architecture",
    historicalPeriod: "Nana Phadnavis (18th Century Additions)",
    description: "One of the 12 sacred Jyotirlingas situated in the Sahyadri mountains surrounded by dense Bhimashankar Wildlife Sanctuary, source of the sacred Bhima River.",
    officialWebsite: "https://pune.nic.in/tourist-place/bhimashankar-temple/",
    sourceRecordId: "MH-DEV-PUN-006",
    sourceName: "Maharashtra Tourism Development Corporation",
    sourceUrl: "https://pune.nic.in/tourist-place/bhimashankar-temple/",
    sourceType: "government",
  },
  {
    name: "Aundha Nagnath Jyotirlinga Temple",
    nameLocal: "औंढा नागनाथ ज्योतिर्लिंग",
    stateCode: "MH",
    districtName: "Hingoli",
    localityName: "Aundha Nagnath",
    latitude: 19.5447,
    longitude: 77.0422,
    mainDeity: "Nagnath (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Ancient Jyotirlinga Shrine",
    tradition: ["Shaivism"],
    architecture: "Intricate Hemadpanthi Stone Architecture",
    historicalPeriod: "Seuna (Yadava) Dynasty (13th Century CE)",
    description: "Revered as the eighth of the twelve Jyotirlingas, where saint Namdev sang bhajans. The temple displays exquisite stone carvings of mythological narratives.",
    officialWebsite: "https://hingoli.nic.in/tourist-place/aundha-nagnath/",
    sourceRecordId: "MH-DEV-HIN-007",
    sourceName: "Hingoli District Administration & MTDC",
    sourceUrl: "https://hingoli.nic.in/tourist-place/aundha-nagnath/",
    sourceType: "government",
  },
  {
    name: "Parli Vaijnath Jyotirlinga Temple",
    nameLocal: "परळी वैजनाथ ज्योतिर्लिंग",
    stateCode: "MH",
    districtName: "Beed",
    localityName: "Parli",
    latitude: 18.8497,
    longitude: 76.5367,
    mainDeity: "Vaijnath (Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Jyotirlinga & Healing Shrine (Vaidyanatha)",
    tradition: ["Shaivism"],
    architecture: "Hemadpanthi Stone Architecture on Meru Mountain",
    historicalPeriod: "Renovated by Rani Ahilyabai Holkar (1706 CE)",
    description: "Situated on a small hillock in Parli, venerated as the healing physician deity (Vaidyanath) with a grand stone stairway and fortified enclosure.",
    officialWebsite: "https://beed.nic.in/tourist-place/parli-vaijnath/",
    sourceRecordId: "MH-DEV-BEE-008",
    sourceName: "Beed District Administration & MTDC",
    sourceUrl: "https://beed.nic.in/tourist-place/parli-vaijnath/",
    sourceType: "government",
  },
  {
    name: "Vitthal Rukmini Mandir Pandharpur",
    nameLocal: "श्री विठ्ठल रुक्मिणी मंदिर पंढरपूर",
    stateCode: "MH",
    districtName: "Solapur",
    localityName: "Pandharpur",
    latitude: 17.6775,
    longitude: 75.3267,
    mainDeity: "Lord Vithoba (Panduranga / Krishna)",
    deities: ["Vithoba", "Rukmini Devi"],
    templeType: "Supreme Pilgrimage Shrine of Varkari Sampradaya",
    tradition: ["Vaishnavism", "Varkari"],
    architecture: "Hemadpanthi & Maratha Confluence Style",
    historicalPeriod: "Hoysala & Yadava Dynasties (12th-13th Century)",
    description: "Located on the banks of the sacred Chandrabhaga River, the heart of Maharashtra's devotional movement where millions join the annual Pandharpur Wari pilgrimage.",
    officialWebsite: "https://vitthalrukminimandir.org",
    sourceRecordId: "MH-DEV-SOL-009",
    sourceName: "Shree Vitthal Rukmini Mandir Samiti",
    sourceUrl: "https://vitthalrukminimandir.org",
    sourceType: "government",
  },
  {
    name: "Tulja Bhavani Temple Tuljapur",
    nameLocal: "तुळजाभवानी मंदिर तुळजापूर",
    stateCode: "MH",
    districtName: "Osmanabad",
    localityName: "Tuljapur",
    latitude: 18.0039,
    longitude: 76.1264,
    mainDeity: "Goddess Tulja Bhavani",
    deities: ["Tulja Bhavani"],
    templeType: "Kuladaivat of Chhatrapati Shivaji Maharaj",
    tradition: ["Shaktism"],
    architecture: "Hemadpanthi Style with Kallol & Gomukh Tirthas",
    historicalPeriod: "12th Century CE (Kadamba & Maratha Patronage)",
    description: "The family deity (Kuladevi) of the Bhosale royal dynasty and Chhatrapati Shivaji Maharaj, who was gifted the divine Bhavani Talwar according to regional history.",
    officialWebsite: "https://tuljabhavani.in",
    sourceRecordId: "MH-DEV-OSM-010",
    sourceName: "Shri Tuljabhavani Temple Trust",
    sourceUrl: "https://tuljabhavani.in",
    sourceType: "government",
  },
  {
    name: "Kailash Temple Ellora",
    nameLocal: "कैलास मंदिर वेरुळ",
    stateCode: "MH",
    districtName: "Chhatrapati Sambhajinagar",
    localityName: "Ellora",
    latitude: 20.0239,
    longitude: 75.1792,
    mainDeity: "Lord Shiva (Mount Kailash representation)",
    deities: ["Lord Shiva"],
    templeType: "UNESCO World Heritage Site (Cave 16)",
    tradition: ["Shaivism"],
    architecture: "World's Largest Monolithic Rock-Cut Architecture",
    historicalPeriod: "Rashtrakuta King Krishna I (756–773 CE)",
    description: "Carved from top to bottom out of a single volcanic basalt cliff, excavating over 200,000 tonnes of rock. Widely considered one of the greatest architectural triumphs of mankind.",
    officialWebsite: "https://asi.nic.in/ellora-caves/",
    sourceRecordId: "ASI-MH-N-MH-E1",
    sourceName: "Archaeological Survey of India & MTDC",
    sourceUrl: "https://asi.nic.in/ellora-caves/",
    sourceType: "government",
  },
  {
    name: "Shree Sant Gajanan Maharaj Sansthan Shegaon",
    nameLocal: "संत गजानन महाराज संस्थान शेगाव",
    stateCode: "MH",
    districtName: "Buldhana",
    localityName: "Shegaon",
    latitude: 20.7933,
    longitude: 76.6917,
    mainDeity: "Sant Gajanan Maharaj",
    deities: ["Gajanan Maharaj", "Rama", "Shiva"],
    templeType: "Premier Samadhi Mandir & Seva Complex",
    tradition: ["Universal Spiritual", "Varkari"],
    architecture: "Immaculate Marble Samadhi Complex with Anand Sagar",
    historicalPeriod: "1910 CE Mahasamadhi",
    description: "Often called the Pandharpur of Vidarbha, renowned worldwide for impeccable cleanliness, disciplined crowd management, and massive educational and philanthropic service.",
    officialWebsite: "https://gajananmaharaj.org",
    sourceRecordId: "MH-DEV-BUL-016",
    sourceName: "Shri Sant Gajanan Maharaj Sansthan Trust",
    sourceUrl: "https://gajananmaharaj.org",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ MAHARASHTRA TEMPLE INGESTION ENGINE");
  console.log(`Source: MTDC & Official Temple Trusts`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Maharashtra Tourism & Temple Trusts",
    "https://maharashtratourism.gov.in",
    MAHARASHTRA_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
