/**
 * Northeast Official State Ingestion Importer
 * Authoritative Sources:
 * - Kamakhya Devalaya Management Committee (https://maakamakhya.org)
 * - Assam Tourism Development Corporation (https://assamtourism.gov.in)
 * - Tripura Tourism & Matabari Temple Trust (https://tripuratourism.gov.in)
 * - Manipur Tourism & Arts (https://manipurtourism.gov.in)
 * - Archaeological Survey of India (Guwahati Circle) (https://asiguwahaticircle.gov.in)
 * - District Administrations across Assam, Tripura, Manipur, Meghalaya, and Arunachal Pradesh
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const NORTHEAST_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  // ASSAM
  {
    name: "Maa Kamakhya Devalaya Nilachal",
    nameLocal: "মা কামাখ্যা দেৱালয় গুৱাহাটী",
    stateCode: "AS",
    districtName: "Kamrup Metropolitan",
    localityName: "Nilachal Hill, Guwahati",
    latitude: 26.1664,
    longitude: 91.7058,
    mainDeity: "Maa Kamakhya (Supreme Yoni Peetha)",
    deities: ["Maa Kamakhya", "Ten Mahavidyas (Tara, Tripura Sundari, Bhuvaneshwari, etc.)"],
    templeType: "Supreme 51 Maha Shakti Peethas & Tantra Peetha of Bharat",
    tradition: ["Shaktism", "Tantra", "Kaula Tradition"],
    architecture: "Nilachal Style Beehive Dome (Hybrid Indigenous Assamese and Nagara)",
    historicalPeriod: "Koch King Naranarayan / Chilarai (1565 CE) / Ancient Antiquity",
    description: "The supreme seat of Shakta Tantra in India, where Goddess Sati's yoni (creative organ) fell atop Nilachal Hill above the Brahmaputra River. Center of the annual Ambubachi Mela.",
    officialWebsite: "https://maakamakhya.org",
    sourceRecordId: "AS-KAM-KMET-001",
    sourceName: "Kamakhya Devalaya Management Committee & Assam Tourism",
    sourceUrl: "https://maakamakhya.org",
    sourceType: "official",
  },
  {
    name: "Umananda Island Temple Peacock Island",
    nameLocal: "উমানন্দ দেৱালয় ময়ূৰ দ্বীপ",
    stateCode: "AS",
    districtName: "Kamrup Metropolitan",
    localityName: "Peacock Island, Brahmaputra River, Guwahati",
    latitude: 26.1919,
    longitude: 91.7486,
    mainDeity: "Umananda (Lord Shiva with Uma)",
    deities: ["Lord Shiva", "Maa Uma"],
    templeType: "Smallest Inhabited River Island Shiva Temple in the World",
    tradition: ["Shaivism"],
    architecture: "Ahom Royal Stone and Brick Architecture on Natural Granite Island",
    historicalPeriod: "Ahom King Gadadhar Singha (1694 CE)",
    description: "Built upon the smallest inhabited riverine island in the world (Bhasmachal / Peacock Island) amidst the majestic Brahmaputra River. Reached only by ferry boats from Guwahati.",
    officialWebsite: "https://kamrupmetro.assam.gov.in/tourist-place/umananda-temple/",
    sourceRecordId: "AS-TOUR-KMET-002",
    sourceName: "Kamrup Metropolitan Administration & Assam Tourism",
    sourceUrl: "https://kamrupmetro.assam.gov.in/tourist-place/umananda-temple/",
    sourceType: "government",
  },
  {
    name: "Hayagriva Madhava Temple Hajo",
    nameLocal: "হয়গ্ৰীৱ মাধৱ মন্দিৰ হাজো",
    stateCode: "AS",
    districtName: "Kamrup",
    localityName: "Monikut Hill, Hajo",
    latitude: 26.2483,
    longitude: 91.5272,
    mainDeity: "Hayagriva Madhava (Horse-Faced Vishnu)",
    deities: ["Lord Vishnu", "Garuda", "Buddha"],
    templeType: "Unique Hindu-Buddhist Syncretic Pilgrimage Shrine",
    tradition: ["Vaishnavism", "Tibetan Buddhism"],
    architecture: "Stone Temple with Continuous Row of Carved Elephant Friezes",
    historicalPeriod: "Koch King Raghudeva Narayan (1583 CE) / Pala Dynasty Foundations",
    description: "Located on Monikut Hill in historic Hajo. Venerated by Hindus as the horse-necked avatar of Lord Vishnu, and by Tibetan Buddhists who revere the shrine as the Mahaparinirvana site of Lord Buddha.",
    officialWebsite: "https://kamrup.assam.gov.in/tourist-place/hayagriva-madhava-temple/",
    sourceRecordId: "AS-TOUR-KAM-003",
    sourceName: "Kamrup District Administration & Hajo Temple Management",
    sourceUrl: "https://kamrup.assam.gov.in/tourist-place/hayagriva-madhava-temple/",
    sourceType: "government",
  },
  {
    name: "Barpeta Satra",
    nameLocal: "বৰপেটা সত্ৰ",
    stateCode: "AS",
    districtName: "Barpeta",
    localityName: "Barpeta Town",
    latitude: 26.3208,
    longitude: 91.0083,
    mainDeity: "Lord Krishna / Govinda (Bhagavat Purana)",
    deities: ["Bhagavat Purana", "Mahapurush Srimanta Sankardeva", "Madhavdeva"],
    templeType: "Premier Neo-Vaishnavite Monastic Center of Assam",
    tradition: ["Ekasarana Dharma", "Neo-Vaishnavism"],
    architecture: "Monumental Kirtan Ghar with Carved Wooden Pillars and Brass Works",
    historicalPeriod: "Established by Mahapurush Madhavdeva (1583 CE)",
    description: "The holiest monastery of Ekasarana Dharma in Lower Assam, founded by Sri Madhavdeva. The grand Kirtan Ghar is world-renowned for its traditional Doul Utsav (Holi) and Dihanaam chants.",
    officialWebsite: "https://barpeta.assam.gov.in/tourist-place/barpeta-satra/",
    sourceRecordId: "AS-TOUR-BAR-004",
    sourceName: "Barpeta Satra Management Committee & Barpeta Administration",
    sourceUrl: "https://barpeta.assam.gov.in/tourist-place/barpeta-satra/",
    sourceType: "government",
  },
  {
    name: "Mahamaya Dham Bogribari",
    nameLocal: "মহামায়া ধাম বগৰীবাৰী ধুবুৰী",
    stateCode: "AS",
    districtName: "Dhubri",
    localityName: "Bogribari, Parbatjhora, Dhubri",
    latitude: 26.1833,
    longitude: 90.2333,
    mainDeity: "Maa Mahamaya (Goddess Kali / Durga)",
    deities: ["Maa Mahamaya"],
    templeType: "Historic Shakti Peetha of Western Assam",
    tradition: ["Shaktism", "Koch Royal Tradition"],
    architecture: "Traditional Assamese Temple Complex in Sacred Mountain Forest",
    historicalPeriod: "Koch Dynasty & Zamindars of Bagribari (400+ Years Old)",
    description: "Considered on par with Kamakhya and Umatara in spiritual potency in Lower Assam. Devotees flock here during Durga Puja and Kati Bihu for blessings of divine protection.",
    officialWebsite: "https://dhubri.assam.gov.in/tourist-place/mahamaya-dham/",
    sourceRecordId: "AS-TOUR-DHU-005",
    sourceName: "Dhubri District Administration & Mahamaya Trust",
    sourceUrl: "https://dhubri.assam.gov.in/tourist-place/mahamaya-dham/",
    sourceType: "government",
  },
  {
    name: "Kachakanti Temple Silchar",
    nameLocal: "কাঁচাকান্তি মন্দির শিলচর",
    stateCode: "AS",
    districtName: "Cachar",
    localityName: "Udharbond, Silchar, Cachar",
    latitude: 24.8967,
    longitude: 92.7917,
    mainDeity: "Maa Kachakanti (Mother Durga and Kali Combined)",
    deities: ["Maa Kachakanti"],
    templeType: "Syncretic Shakta Guardian Shrine of Barak Valley",
    tradition: ["Shaktism", "Kachari Kingdom Tradition"],
    architecture: "Traditional Bengali-Assamese Temple Architecture in Barak Valley",
    historicalPeriod: "Kachari King Raja Suradarpa Narayan (1844 CE / Rebuilt 1978)",
    description: "Located 11 km from Silchar, this historic shrine is dedicated to a four-armed golden goddess who combines the iconography of Goddess Durga and Goddess Kali. Spiritual heart of Cachar district.",
    officialWebsite: "https://cachar.assam.gov.in/tourist-place/kachakanti-temple/",
    sourceRecordId: "AS-TOUR-CAC-006",
    sourceName: "Cachar District Administration & Barak Valley Tourism",
    sourceUrl: "https://cachar.assam.gov.in/tourist-place/kachakanti-temple/",
    sourceType: "government",
  },
  {
    name: "Sri Surya Pahar Archaeological Site",
    nameLocal: "শ্ৰী সূৰ্য্য পাহাৰ গোৱালপাৰা",
    stateCode: "AS",
    districtName: "Goalpara",
    localityName: "Bhairabkunda, Goalpara",
    latitude: 26.1133,
    longitude: 90.7103,
    mainDeity: "Surya Narayana & 99,999 Rock-Cut Shivalingas",
    deities: ["Lord Surya", "Lord Shiva", "Lord Vishnu", "Ganesha"],
    templeType: "Vast Ancient Solar & Shaivite Rock-Cut Monument (ASI Protected)",
    tradition: ["Saura Tradition", "Shaivism", "Buddhism", "Jainism"],
    architecture: "Ancient Rock-Cut Circular Sun Medallion with 99,999 Carved Shivalingas",
    historicalPeriod: "Pre-Ahom Antiquity (9th to 12th Century CE) / ASI National Monument",
    description: "Often called the Sun Temple complex of Assam, famous for hundreds of rock-cut Shivalingas, stupas, and a magnificent carved circular solar medallion atop Surya Pahar hill.",
    officialWebsite: "https://asiguwahaticircle.gov.in",
    sourceRecordId: "AS-ASI-GOA-007",
    sourceName: "Archaeological Survey of India (Guwahati Circle) & Goalpara Admin",
    sourceUrl: "https://asiguwahaticircle.gov.in",
    sourceType: "asi",
  },
  {
    name: "Dakhinpat Satra Majuli Island",
    nameLocal: "দখিনপাট সত্ৰ মাজুলী",
    stateCode: "AS",
    districtName: "Majuli",
    localityName: "Dakhinpat, Majuli River Island",
    latitude: 26.8508,
    longitude: 94.2508,
    mainDeity: "Sri Sri Jadavrai (Lord Krishna)",
    deities: ["Lord Krishna (Jadavrai)", "Ras Leela Tradition"],
    templeType: "Royal Neo-Vaishnavite Island Monastery of Majuli",
    tradition: ["Ekasarana Dharma", "Bhakti Tradition"],
    architecture: "Majestic Wooden Monastic Complex with Intricately Carved Toranas",
    historicalPeriod: "Ahom King Jayadhwaj Singha & Sri Vanamalidev (1654 CE)",
    description: "Located on Majuli, the world's largest river island on the Brahmaputra. Famous for its sacred idol of Jadavrai and the spectacular annual Ras Leela performances that draw thousands from worldwide.",
    officialWebsite: "https://majuli.assam.gov.in/tourist-place/dakhinpat-satra/",
    sourceRecordId: "AS-TOUR-MAJ-008",
    sourceName: "Majuli District Administration & Dakhinpat Satra Board",
    sourceUrl: "https://majuli.assam.gov.in/tourist-place/dakhinpat-satra/",
    sourceType: "government",
  },
  {
    name: "Mahabhairav Temple Tezpur",
    nameLocal: "মহাভৈৰৱ মন্দিৰ তেজপুৰ",
    stateCode: "AS",
    districtName: "Sonitpur",
    localityName: "Tezpur Hill, Sonitpur",
    latitude: 26.6347,
    longitude: 92.7936,
    mainDeity: "Mahabhairav (Lord Shiva)",
    deities: ["Lord Shiva (Bhairav)", "Nandi"],
    templeType: "King Banasura Ancient Shivalinga Pilgrimage",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Temple Housing Gigantic Ancient Stone Shivalinga",
    historicalPeriod: "Demon King Banasura / Consecrated Modern Temple (Tungkhungia Ahoms)",
    description: "Believed to have been originally established by demon king Banasura, father of Usha. The enormous living Shivalinga is among the oldest worshiped stone lingas in the Brahmaputra Valley.",
    officialWebsite: "https://sonitpur.assam.gov.in/tourist-place/mahabhairab-temple/",
    sourceRecordId: "AS-TOUR-SON-009",
    sourceName: "Sonitpur District Administration & Mahabhairav Temple Management",
    sourceUrl: "https://sonitpur.assam.gov.in/tourist-place/mahabhairab-temple/",
    sourceType: "government",
  },
  {
    name: "Tilinga Mandir (Bell Temple) Bordubi",
    nameLocal: "টিলিঙা মন্দিৰ তিনিচুকীয়া",
    stateCode: "AS",
    districtName: "Tinsukia",
    localityName: "Bordubi, Tinsukia",
    latitude: 27.4208,
    longitude: 95.3333,
    mainDeity: "Lord Shiva (Swayambhu)",
    deities: ["Lord Shiva"],
    templeType: "Famous Vow-Fulfilling Bell Shrine of Upper Assam",
    tradition: ["Shaivism"],
    architecture: "Sacred Peepal Tree Complex Hung with Hundreds of Thousands of Brass Bells",
    historicalPeriod: "Discovered 1965 CE (Banyan Tree Shivalinga)",
    description: "Famous across the world as the Bell Temple, where hundreds of thousands of brass and bronze bells of all sizes are tied to a massive sacred banyan tree by devotees whose prayers were answered.",
    officialWebsite: "https://tinsukia.assam.gov.in/tourist-place/tilinga-mandir/",
    sourceRecordId: "AS-TOUR-TIN-010",
    sourceName: "Tinsukia District Administration & Tilinga Mandir Committee",
    sourceUrl: "https://tinsukia.assam.gov.in/tourist-place/tilinga-mandir/",
    sourceType: "government",
  },
  {
    name: "Sivasagar Shiva Dol",
    nameLocal: "শিৱ দৌল শিৱসাগৰ",
    stateCode: "AS",
    districtName: "Sivasagar",
    localityName: "Sivasagar Town, Sivasagar Borpukhuri",
    latitude: 26.9883,
    longitude: 94.6319,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Vishnu", "Durga (Twin Shrines)"],
    templeType: "Tallest Historic Shiva Temple Spire in India (ASI Monument)",
    tradition: ["Shaivism"],
    architecture: "104-Foot Ahom Style Shikhara Crowned by 8-Foot Pure Gold Mastaka Dome",
    historicalPeriod: "Ahom Queen Ambika (1734 CE) / ASI National Monument",
    description: "Standing on the banks of the vast man-made Sivasagar Tank (Borpukhuri), this 104-foot stone Shikhara is the tallest temple spire built by the Ahom dynasty, capped by an eight-foot solid gold dome.",
    officialWebsite: "https://asiguwahaticircle.gov.in",
    sourceRecordId: "AS-ASI-SIV-011",
    sourceName: "Archaeological Survey of India (Guwahati Circle) & Sivasagar Admin",
    sourceUrl: "https://asiguwahaticircle.gov.in",
    sourceType: "asi",
  },

  // TRIPURA
  {
    name: "Unakoti Shaiva Rock Carvings",
    nameLocal: "উনকোটি শৈল ভাস্কৰ্য্য ত্ৰিপুৰা",
    stateCode: "TR",
    districtName: "Unakoti",
    localityName: "Unakoti Hill, Kailashahar",
    latitude: 24.3217,
    longitude: 92.0667,
    mainDeity: "Unakotiswara Kal Bhairava (Colossal Rock-Hewn Shiva)",
    deities: ["Lord Shiva", "Ganga", "Ganesha", "Durga"],
    templeType: "Ancient Bas-Relief Colossal Rock-Cut Shaivite Sanctuary (ASI)",
    tradition: ["Shaivism", "Tantra"],
    architecture: "30-Foot Bas-Relief Rock-Cut Colossus in Lush Hill Valley with Natural Waterfall",
    historicalPeriod: "7th to 9th Century CE / ASI Tentative UNESCO World Heritage",
    description: "Celebrated in legend as having 'one less than a crore' (Unakoti) divine rock-cut images carved across a lush forest ravine. The 30-foot head of Shiva (Unakotiswara) is an Indian archaeological marvel.",
    officialWebsite: "https://unakoti.nic.in/tourist-place/unakoti-heritage-site/",
    sourceRecordId: "TR-ASI-UNA-012",
    sourceName: "Archaeological Survey of India & Tripura Tourism",
    sourceUrl: "https://unakoti.nic.in/tourist-place/unakoti-heritage-site/",
    sourceType: "asi",
  },
  {
    name: "Tripura Sundari Temple Matabari",
    nameLocal: "ত্ৰিপুৰা সুন্দৰী মন্দিৰ মাতাবাৰী",
    stateCode: "TR",
    districtName: "Gomati",
    localityName: "Udaipur, Gomati",
    latitude: 23.5139,
    longitude: 91.4989,
    mainDeity: "Maa Tripura Sundari (Soroshi)",
    deities: ["Maa Tripura Sundari", "Chhoti Ma"],
    templeType: "51 Maha Shakti Peethas (Right Foot / Kurma Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Traditional Bengali Chala Roof Shape Built on Tortoise-Shaped Hillock",
    historicalPeriod: "Maharaja Dhanya Manikya (1501 CE)",
    description: "One of the 51 Shakti Peethas where Goddess Sati's right foot fell. Built on a hillock shaped like a tortoise (Kurmapitha) beside the Kalyan Sagar lake, famous for its sacred tortoise sanctuary.",
    officialWebsite: "https://tripuratourism.gov.in",
    sourceRecordId: "TR-TOUR-GOM-013",
    sourceName: "Tripura Tourism Development Corporation & Matabari Trust",
    sourceUrl: "https://tripuratourism.gov.in",
    sourceType: "government",
  },

  // MANIPUR
  {
    name: "Shri Govindajee Temple Imphal",
    nameLocal: "শ্রী গোবিন্দজী মন্দির ইম্ফল",
    stateCode: "MN",
    districtName: "Imphal East",
    localityName: "Palace Compound, Imphal",
    latitude: 24.8028,
    longitude: 93.9536,
    mainDeity: "Shri Govindajee (Lord Krishna)",
    deities: ["Govindajee", "Radha", "Jagannath", "Subhadra", "Balarama"],
    templeType: "Royal Meitei Vaishnavite Sanctuary of Manipur Kingdom",
    tradition: ["Gaudiya Vaishnavism", "Manipuri Vaishnava Tradition"],
    architecture: "Twin Golden Domes, Expansive Marble Paved Mandapa and Chhatri Roof",
    historicalPeriod: "Maharaja Nara Singh (1846 CE) / Rebuilt by Maharaja Chandrakirti (1876 CE)",
    description: "The supreme Vaishnavite temple of Manipur, located adjacent to the royal palace in Imphal. Famous for its classical Manipuri Ras Leela dance performances and Janmashtami festivities.",
    officialWebsite: "https://manipurtourism.gov.in",
    sourceRecordId: "MN-TOUR-IME-014",
    sourceName: "Manipur Tourism Development Corp & Shri Govindajee Temple Board",
    sourceUrl: "https://manipurtourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Vishnu Temple Bishnupur",
    nameLocal: "বিষ্ণু মন্দির বিষ্ণুপুর মণিপুর",
    stateCode: "MN",
    districtName: "Bishnupur",
    localityName: "Bishnupur Town",
    latitude: 24.6317,
    longitude: 93.7592,
    mainDeity: "Lord Vishnu",
    deities: ["Lord Vishnu"],
    templeType: "Oldest Surviving Brick Temple in Manipur (1467 CE / ASI Protected)",
    tradition: ["Vaishnavism"],
    architecture: "Unique Conical Brick and Mud Pagoda Style with Chinese Influence",
    historicalPeriod: "King Kyamba of Manipur (1467 CE) / ASI National Monument",
    description: "A protected national monument and the oldest brick structure in Manipur, built during the reign of King Kyamba to house an idol of Lord Vishnu presented by the King of Pong (Burma).",
    officialWebsite: "https://asiguwahaticircle.gov.in",
    sourceRecordId: "MN-ASI-BIS-015",
    sourceName: "Archaeological Survey of India (Guwahati Circle) & Bishnupur Admin",
    sourceUrl: "https://asiguwahaticircle.gov.in",
    sourceType: "asi",
  },

  // MEGHALAYA
  {
    name: "Nartiang Durga Temple Jaintia Hills",
    nameLocal: "নার্তিয়াং দুর্গা মন্দির",
    stateCode: "ML",
    districtName: "Jaintia Hills",
    localityName: "Nartiang, West Jaintia Hills",
    latitude: 25.5714,
    longitude: 92.2189,
    mainDeity: "Maa Jainteshwari (Goddess Durga)",
    deities: ["Maa Durga", "Bhairava"],
    templeType: "51 Maha Shakti Peethas (Left Thigh / Jaintia Peetha)",
    tradition: ["Shaktism", "Jaintia Royal Tradition"],
    architecture: "Traditional Khasi Thatched Roof Over Stone Sanctum Housing 500-Year-Old Idols",
    historicalPeriod: "Jaintia King Jaso Manik (16th Century CE)",
    description: "One of the 51 sacred Shakti Peethas where Goddess Sati's left thigh fell. Consecrated by the Jaintia kings who converted to Hinduism and made Nartiang their summer capital.",
    officialWebsite: "https://westjaintiahills.gov.in/tourist-place/nartiang-monoliths-and-durga-temple/",
    sourceRecordId: "ML-TOUR-JAI-016",
    sourceName: "West Jaintia Hills Administration & Meghalaya Tourism",
    sourceUrl: "https://westjaintiahills.gov.in/tourist-place/nartiang-monoliths-and-durga-temple/",
    sourceType: "government",
  },

  // ARUNACHAL PRADESH
  {
    name: "Parshuram Kund Lohit",
    nameLocal: "परशुराम कुंड लोहित",
    stateCode: "AR",
    districtName: "Lohit",
    localityName: "Telu Sati, Lower Reaches of Lohit River, Wakro",
    latitude: 27.8767,
    longitude: 96.3533,
    mainDeity: "Bhagwan Parshurama",
    deities: ["Lord Parshurama", "Lord Shiva"],
    templeType: "Maha Holy Puranic River Pilgrimage of Northeast India",
    tradition: ["Vaishnavism", "Shaivism", "Puranic Tradition"],
    architecture: "Natural Riverine Kund Gorge Sanctuary in Himalayan Foothills",
    historicalPeriod: "Ancient Kalika Purana Antiquity",
    description: "A holy shrine in the lower reaches of the Lohit River where Lord Parshurama washed away his sin of matricide in the river's icy waters. Site of the celebrated annual Makar Sankranti mela.",
    officialWebsite: "https://lohit.nic.in/tourist-place/parshuram-kund/",
    sourceRecordId: "AR-TOUR-LOH-017",
    sourceName: "Lohit District Administration & Arunachal Tourism",
    sourceUrl: "https://lohit.nic.in/tourist-place/parshuram-kund/",
    sourceType: "government",
  },
];

export async function importNortheastTemples(options = {}) {
  return processStateBatch(
    "Northeast Tourism, ASI & Devalaya Trusts",
    "https://assamtourism.gov.in",
    NORTHEAST_AUTHORITATIVE_TEMPLES,
    options
  );
}

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ NORTHEAST TEMPLE INGESTION ENGINE");
  console.log("Source: Northeast Tourism, ASI & Devalaya Trusts");
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await importNortheastTemples({
    dryRun: isDryRun,
    parserVersion: "v1.0.0",
  });

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);

