/**
 * Odisha Official State Ingestion Importer
 * Authoritative Source: Shree Jagannath Temple Administration (SJTA), Odisha State Endowment Commission, OTDC
 * Portal: https://shreejagannath.odisha.gov.in / https://endowments.odisha.gov.in
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const ODISHA_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Shree Jagannath Temple Puri",
    nameLocal: "ଶ୍ରୀ ଜଗନ୍ନାଥ ମନ୍ଦିର ପୁରୀ",
    stateCode: "OD",
    districtName: "Puri",
    localityName: "Grand Road (Bada Danda), Puri",
    latitude: 19.8047,
    longitude: 85.8179,
    mainDeity: "Lord Jagannath (with Balabhadra and Subhadra)",
    deities: ["Jagannath", "Balabhadra", "Subhadra", "Sudarshana"],
    templeType: "Maha Char Dham & Srikhetra",
    tradition: ["Vaishnavism", "Sanatana"],
    architecture: "Classical Kalinga Rekha Deula Architecture",
    historicalPeriod: "Eastern Ganga Dynasty / King Anantavarman Chodaganga (12th Century CE)",
    description: "One of the four cardinal Char Dham pilgrimage shrines in India. Globally revered for the sacred Rath Yatra (Chariot Festival), the sacred kitchen (Rosaghara), and Nilachakra atop its 65-meter vimana.",
    officialWebsite: "https://shreejagannath.odisha.gov.in",
    sourceRecordId: "OD-SJTA-PUR-001",
    sourceName: "Shree Jagannath Temple Administration (SJTA)",
    sourceUrl: "https://shreejagannath.odisha.gov.in",
    sourceType: "government",
  },
  {
    name: "Gundicha Temple Puri",
    nameLocal: "ଗୁଣ୍ଡିଚା ମନ୍ଦିର",
    stateCode: "OD",
    districtName: "Puri",
    localityName: "Puri",
    latitude: 19.8258,
    longitude: 85.8361,
    mainDeity: "Lord Jagannath (Annual Yatra Residence)",
    deities: ["Jagannath", "Balabhadra", "Subhadra"],
    templeType: "Garden House of Lord Jagannath (Janmapitha)",
    tradition: ["Vaishnavism"],
    architecture: "Kalinga Deula Architecture",
    historicalPeriod: "Eastern Ganga Dynasty Era",
    description: "Known as the Garden House of Lord Jagannath, where the Holy Trinity resides for nine days during the annual Rath Yatra festival in the sacred month of Ashadha.",
    officialWebsite: "https://puri.nic.in/tourist-place/gundicha-temple/",
    sourceRecordId: "OD-SJTA-PUR-002",
    sourceName: "Shree Jagannath Temple Administration & Puri District Administration",
    sourceUrl: "https://puri.nic.in/tourist-place/gundicha-temple/",
    sourceType: "government",
  },
  {
    name: "Lingaraj Temple Bhubaneswar",
    nameLocal: "ଲିଙ୍ଗରାଜ ମନ୍ଦିର ଭୁବନେଶ୍ୱର",
    stateCode: "OD",
    districtName: "Khordha",
    localityName: "Old Town, Bhubaneswar",
    latitude: 20.2381,
    longitude: 85.8336,
    mainDeity: "Harihara (Confluence of Lord Shiva & Vishnu)",
    deities: ["Lord Shiva", "Vishnu", "Goddess Bhubaneswari"],
    templeType: "Principal Ekamra Kshetra Shrine",
    tradition: ["Shaivism", "Harihara"],
    architecture: "Monumental Kalinga Rekha and Pidha Deula",
    historicalPeriod: "Somavamshi Dynasty / King Jajati Keshari (11th Century CE)",
    description: "The largest and most prominent temple in Bhubaneswar, embodying the Harihara syncretism. Features a towering 55-meter granite deula adorned with thousands of intricate sculptures.",
    officialWebsite: "https://endowments.odisha.gov.in",
    sourceRecordId: "OD-ENDOW-KHO-003",
    sourceName: "Odisha State Endowment Commission & Khordha Administration",
    sourceUrl: "https://endowments.odisha.gov.in",
    sourceType: "government",
  },
  {
    name: "Sun Temple Konark",
    nameLocal: "କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର",
    stateCode: "OD",
    districtName: "Puri",
    localityName: "Konark",
    latitude: 19.8876,
    longitude: 86.0945,
    mainDeity: "Surya (Sun God)",
    deities: ["Surya Deva"],
    templeType: "UNESCO World Heritage Site",
    tradition: ["Saurism", "Smartha"],
    architecture: "Colossal Chariot-Form Kalinga Stone Architecture",
    historicalPeriod: "Eastern Ganga Dynasty / King Narasimhadeva I (1250 CE)",
    description: "Designed in the shape of a colossal chariot for the Sun God, with 24 carved stone wheels serving as sundials and pulled by seven stone horses. World-renowned for its artistic mastery.",
    officialWebsite: "https://asi.nic.in/world-heritage-sites-konark-sun-temple/",
    sourceRecordId: "ASI-OD-E-OD-C1",
    sourceName: "Archaeological Survey of India & Odisha Tourism",
    sourceUrl: "https://asi.nic.in/world-heritage-sites-konark-sun-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Biraja Devi Temple Jajpur",
    nameLocal: "ବିରଜା ମନ୍ଦିର ଯାଜପୁର",
    stateCode: "OD",
    districtName: "Jajpur",
    localityName: "Jajpur",
    latitude: 20.8525,
    longitude: 86.3333,
    mainDeity: "Goddess Biraja (Dvibhuji Mahishasuramardini)",
    deities: ["Biraja Devi"],
    templeType: "Maha Shakti Peetha (Nabhi Gaya Kshetra)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Ancient Kalinga Pidha Architecture",
    historicalPeriod: "Gupta & Somavamshi Eras (Circa 5th-10th Century CE)",
    description: "One of the most sacred Shakta shrines of Bharat, where Goddess Sati's naval (Nabhi) fell. Unique for its two-armed idol of Mahishasuramardini and annual chariot procession (Bijaya Ratha).",
    officialWebsite: "https://jajpur.nic.in/tourist-place/biraja-temple/",
    sourceRecordId: "OD-ENDOW-JAJ-004",
    sourceName: "Odisha State Endowment Commission & Jajpur District",
    sourceUrl: "https://jajpur.nic.in/tourist-place/biraja-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Samaleswari Temple Sambalpur",
    nameLocal: "ମାଁ ସମଲେଶ୍ୱରୀ ମନ୍ଦିର ସମ୍ବଲପୁର",
    stateCode: "OD",
    districtName: "Sambalpur",
    localityName: "Sambalpur",
    latitude: 21.4647,
    longitude: 83.9619,
    mainDeity: "Goddess Samaleswari (Shree Shree Jagatjanani)",
    deities: ["Samaleswari"],
    templeType: "Presiding Mother Goddess of Western Odisha",
    tradition: ["Shaktism"],
    architecture: "Chaukhandi Stone Architecture on River Mahanadi",
    historicalPeriod: "Chauhan Dynasty / King Balaram Dev (16th Century CE)",
    description: "Situated on the banks of the sacred Mahanadi River, the spiritual epicenter of Western Odisha and the venue of the Nuakhai harvest festival, recently enhanced with a heritage corridor.",
    officialWebsite: "https://sambalpur.nic.in/tourist-place/samaleswari-temple/",
    sourceRecordId: "OD-ENDOW-SAM-005",
    sourceName: "Maa Samaleswari Temple Trust & Odisha Tourism",
    sourceUrl: "https://sambalpur.nic.in/tourist-place/samaleswari-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Taratarini Temple Purushottampur",
    nameLocal: "ମାଁ ତାରାତାରିଣୀ ମନ୍ଦିର",
    stateCode: "OD",
    districtName: "Ganjam",
    localityName: "Purushottampur",
    latitude: 19.4939,
    longitude: 84.8967,
    mainDeity: "Maa Tara & Maa Tarini",
    deities: ["Tara", "Tarini"],
    templeType: "Ancient Adi Shakti Stana Peetha",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Modern Kalinga Granite Temple atop Taratarini Hill",
    historicalPeriod: "Ancient Vedic and Kalinga Tradition",
    description: "Perched atop the sacred Purnagiri / Taratarini Hill on the banks of the holy Rushikulya River, venerated as the breast shrine (Stana Peetha) of Adi Shakti Sati.",
    officialWebsite: "https://ganjam.nic.in/tourist-place/taratarini-temple/",
    sourceRecordId: "OD-ENDOW-GAN-006",
    sourceName: "Maa Taratarini Temple Development Board & Ganjam Administration",
    sourceUrl: "https://ganjam.nic.in/tourist-place/taratarini-temple/",
    sourceType: "government",
  },
  {
    name: "Dhabaleswar Shiva Temple Cuttack",
    nameLocal: "ଧବଳେଶ୍ୱର ମନ୍ଦିର କଟକ",
    stateCode: "OD",
    districtName: "Cuttack",
    localityName: "Dhabaleswar Island, Athagarh",
    latitude: 20.5256,
    longitude: 85.8367,
    mainDeity: "Lord Shiva (Dhabaleswar)",
    deities: ["Lord Shiva"],
    templeType: "River Island Pilgrimage Shrine",
    tradition: ["Shaivism"],
    architecture: "10th Century Kalinga Temple Architecture",
    historicalPeriod: "Somavamshi Dynasty (Reconstructed 1153 CE)",
    description: "Situated on an island in the middle of the holy Mahanadi River near Cuttack, reached by boat or suspension bridge. Famous for the Bada Osha fasting celebration.",
    officialWebsite: "https://cuttack.nic.in/tourist-place/dhabaleswar-temple/",
    sourceRecordId: "OD-ENDOW-CUT-007",
    sourceName: "Odisha State Endowment Commission & Cuttack Administration",
    sourceUrl: "https://cuttack.nic.in/tourist-place/dhabaleswar-temple/",
    sourceType: "government",
  },
  {
    name: "Sri Nrusinghanath Temple Paikmal",
    nameLocal: "ନୃସିଂହନାଥ ମନ୍ଦିର ପାଇକମାଳ",
    stateCode: "OD",
    districtName: "Bargarh",
    localityName: "Gandhamardan Hills, Paikmal",
    latitude: 20.8997,
    longitude: 82.8364,
    mainDeity: "Marjara Keshari (Cat-Faced Lord Narasimha)",
    deities: ["Narasimha (Marjara Keshari)"],
    templeType: "Historic Gandhamardan Forest Shrine",
    tradition: ["Vaishnavism"],
    architecture: "14th Century Kalinga Stone Temple with Natural Waterfall Streams",
    historicalPeriod: "Patna King Baijal Singh Dev (1313 CE)",
    description: "Located at the northern foothills of the medicinal Gandhamardan mountain in Bargarh district, enshrining a unique cat-faced manifestation of Lord Narasimha beside perennial springs.",
    officialWebsite: "https://bargarh.nic.in/tourist-place/nrusinghanath-temple/",
    sourceRecordId: "OD-ENDOW-BAR-008",
    sourceName: "Odisha State Endowment Commission & Bargarh District",
    sourceUrl: "https://bargarh.nic.in/tourist-place/nrusinghanath-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Tarini Temple Ghatgaon",
    nameLocal: "ମାଁ ତାରିଣୀ ମନ୍ଦିର ଘଟଗାଁ",
    stateCode: "OD",
    districtName: "Kendujhar",
    localityName: "Ghatgaon",
    latitude: 21.4933,
    longitude: 85.9189,
    mainDeity: "Maa Tarini (Vanadurga / Mother Goddess)",
    deities: ["Maa Tarini"],
    templeType: "Prominent Tribal & Folk Shakta Kshetra",
    tradition: ["Shaktism", "Folk Traditions"],
    architecture: "Kalinga Style Shrine surrounded by Dense Sal Forests",
    historicalPeriod: "Puri King Purushottama Dev & Govinda Bhanja (1480 CE)",
    description: "Surrounded by ancient Sal forests in Kendujhar district, famed across eastern India for the unique custom where commuters on the highway offer coconuts to Maa Tarini for safe journey.",
    officialWebsite: "https://kendujhar.nic.in/tourist-place/maa-tarini-temple-ghatgaon/",
    sourceRecordId: "OD-ENDOW-KEN-009",
    sourceName: "Maa Tarini Temple Trust & Kendujhar Administration",
    sourceUrl: "https://kendujhar.nic.in/tourist-place/maa-tarini-temple-ghatgaon/",
    sourceType: "government",
  },
  {
    name: "Vedvyas Temple & Peeth Rourkela",
    nameLocal: "ବେଦବ୍ୟାସ ମନ୍ଦିର ରାଉରକେଲା",
    stateCode: "OD",
    districtName: "Sundargarh",
    localityName: "Vedvyas, Rourkela",
    latitude: 22.2411,
    longitude: 84.7872,
    mainDeity: "Lord Shiva & Sage Vedavyasa",
    deities: ["Lord Shiva", "Vedavyasa"],
    templeType: "Sacred River Confluence Pilgrimage (Triveni Sangam)",
    tradition: ["Smartha", "Shaivism"],
    architecture: "Riverside Ghat Shrines with Ancient Cave Hermitage",
    historicalPeriod: "Epic Mahabharata Era Hermitage Tradition",
    description: "Situated at the sacred confluence of the Shankha, Koel, and subterranean Saraswati rivers forming the Brahmani River, where Maharshi Vedavyasa is believed to have compiled the Mahabharata.",
    officialWebsite: "https://sundergarh.nic.in/tourist-place/vedvyas/",
    sourceRecordId: "OD-ENDOW-SUN-010",
    sourceName: "Vedvyas Trust Board & Sundargarh Administration",
    sourceUrl: "https://sundergarh.nic.in/tourist-place/vedvyas/",
    sourceType: "government",
  },
  {
    name: "Kapilash Chandrasekhar Jew Temple",
    nameLocal: "କପିଳାସ ଚନ୍ଦ୍ରଶେଖର ଜିଉ ମନ୍ଦିର",
    stateCode: "OD",
    districtName: "Dhenkanal",
    localityName: "Kapilash Hill",
    latitude: 20.6869,
    longitude: 85.7667,
    mainDeity: "Lord Chandrasekhar (Shiva)",
    deities: ["Chandrasekhar Jew"],
    templeType: "The Kailash of Odisha (Hilltop Mahapitha)",
    tradition: ["Shaivism"],
    architecture: "60-Foot Kalinga Rekha Deula on Mountain Summit",
    historicalPeriod: "Ganga King Narasinghdeva I (1246 CE)",
    description: "Perched 2,239 feet above sea level atop Kapilash hill in Dhenkanal, reached by 1,352 stone steps. Renowned as the second Kailash of eastern India with panoramic forest vistas.",
    officialWebsite: "https://dhenkanal.nic.in/tourist-place/kapilash/",
    sourceRecordId: "OD-ENDOW-DHE-011",
    sourceName: "Odisha State Endowment Commission & Dhenkanal Administration",
    sourceUrl: "https://dhenkanal.nic.in/tourist-place/kapilash/",
    sourceType: "government",
  },
  {
    name: "Khirachora Gopinatha Temple Remuna",
    nameLocal: "କ୍ଷୀରଚୋରା ଗୋପୀନାଥ ମନ୍ଦିର ରେମୁଣା",
    stateCode: "OD",
    districtName: "Balasore",
    localityName: "Remuna",
    latitude: 21.5281,
    longitude: 86.8722,
    mainDeity: "Gopinatha (Lord Krishna)",
    deities: ["Gopinatha", "Govinda", "Madanamohana"],
    templeType: "Vaishnavite Heritage Kshetra & Chaitanya Pilgrimage",
    tradition: ["Gaudiya Vaishnavism"],
    architecture: "Classical Medieval Kalinga Deula",
    historicalPeriod: "King Langula Narasimhadeva (13th Century CE)",
    description: "Famous for the historic legend of Lord Krishna stealing condensed milk (Amruta Keli Khira) for His pure devotee Madhavendra Puri. Revered stop for Sri Chaitanya Mahaprabhu.",
    officialWebsite: "https://balasore.nic.in/tourist-place/khirachora-gopinath-temple/",
    sourceRecordId: "OD-ENDOW-BAL-012",
    sourceName: "Odisha State Endowment Commission & Balasore Administration",
    sourceUrl: "https://balasore.nic.in/tourist-place/khirachora-gopinath-temple/",
    sourceType: "government",
  },
  {
    name: "Akhandalamani Shiva Temple Aradi",
    nameLocal: "ଅଖଣ୍ଡଳମଣି ମନ୍ଦିର ଆରଡ଼ି",
    stateCode: "OD",
    districtName: "Bhadrak",
    localityName: "Aradi",
    latitude: 20.8931,
    longitude: 86.6842,
    mainDeity: "Baba Akhandalamani (Lord Shiva)",
    deities: ["Akhandalamani"],
    templeType: "Principal Healing Shiva Kshetra of Coastal Odisha",
    tradition: ["Shaivism"],
    architecture: "Kalinga Style Shrine on River Baitarani",
    historicalPeriod: "King Niladri Narayan Bhanja of Kanika (17th Century)",
    description: "Located on the banks of the sacred Baitarani River in Bhadrak district. Pilgrims from all over Eastern India travel here to pray for relief from difficult illnesses through sacred water (Pahada Jal).",
    officialWebsite: "https://bhadrak.nic.in/tourist-place/baba-akhandalamani-temple/",
    sourceRecordId: "OD-ENDOW-BHA-013",
    sourceName: "Akhandalamani Temple Trust & Bhadrak Administration",
    sourceUrl: "https://bhadrak.nic.in/tourist-place/baba-akhandalamani-temple/",
    sourceType: "government",
  },
  {
    name: "Gupteswar Cave Shiva Temple",
    nameLocal: "ଗୁପ୍ତେଶ୍ୱର ମନ୍ଦିର କୋରାପୁଟ",
    stateCode: "OD",
    districtName: "Koraput",
    localityName: "Jeypore, Koraput",
    latitude: 18.8258,
    longitude: 82.1647,
    mainDeity: "Gupteswar (Hidden Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Subterranean Limestone Cave Pilgrimage",
    tradition: ["Shaivism"],
    architecture: "Natural Limestone Karst Cave Sanctum on River Kolab",
    historicalPeriod: "King Vikram Dev of Jeypore (Ancient Tradition)",
    description: "Situated in deep forest hills on the banks of the Kolab River in southern Odisha. Features a colossal limestone swayambhu lingam that continuously increases in size according to regional belief.",
    officialWebsite: "https://koraput.nic.in/tourist-place/gupteswar-temple/",
    sourceRecordId: "OD-ENDOW-KOR-014",
    sourceName: "Odisha Tourism & Koraput District Administration",
    sourceUrl: "https://koraput.nic.in/tourist-place/gupteswar-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Hingula Temple Gopalprasad",
    nameLocal: "ମାଁ ହିଙ୍ଗୁଳା ମନ୍ଦିର ଗୋପାଳପ୍ରସାଦ",
    stateCode: "OD",
    districtName: "Angul",
    localityName: "Gopalprasad, Talcher",
    latitude: 20.9631,
    longitude: 85.0689,
    mainDeity: "Maa Hingula (Agni Rupa Goddess)",
    deities: ["Maa Hingula"],
    templeType: "Fire-Manifestation Shakta Pitha of Coal Country",
    tradition: ["Shaktism"],
    architecture: "Traditional Odishan Temple Complex with Sacred Fire Pit",
    historicalPeriod: "Centuries-Old Vidarbha & Talcher Patronage",
    description: "Located near Talcher in Angul district, where Goddess Hingula manifests in the form of a burning flame from the earth during the annual Hingula Yatra in Chaitra month.",
    officialWebsite: "https://angul.nic.in/tourist-place/maa-hingula-temple/",
    sourceRecordId: "OD-ENDOW-ANG-015",
    sourceName: "Maa Hingula Trust & Angul District Administration",
    sourceUrl: "https://angul.nic.in/tourist-place/maa-hingula-temple/",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ ODISHA TEMPLE INGESTION ENGINE");
  console.log(`Source: Shree Jagannath Temple Administration & Endowments`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Shree Jagannath Temple Administration & Odisha Endowments",
    "https://shreejagannath.odisha.gov.in",
    ODISHA_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
