/**
 * Phase 14: Western, Southern, and Northern Strategic Regional Expansion
 * Authoritative Sources:
 * - Maharashtra Tourism Development Corporation (https://maharashtratourism.gov.in)
 * - Karnataka Tourism (https://karnatakatourism.org)
 * - Punjab Tourism & Haryana Tourism Boards
 * - Odisha Tourism & Rajasthan Tourism Development Corporation
 * - Archaeological Survey of India (Mumbai, Bengaluru, Chandigarh, Bhubaneswar, Jaipur Circles)
 * 
 * Expands coverage across 50+ unrepresented districts in Maharashtra,
 * Karnataka, Punjab, Haryana, Odisha, and Rajasthan.
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

export const PHASE14_WEST_SOUTH_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  // =================== MAHARASHTRA ===================
  {
    name: "Kopineshwar Temple Thane",
    nameLocal: "कोपिनेश्वर मंदिर ठाणे",
    stateCode: "MH",
    districtName: "Thane",
    localityName: "Masunda Lake (Talao Pali), Thane",
    latitude: 19.1864,
    longitude: 72.9758,
    mainDeity: "Lord Shiva (Kopineshwar)",
    deities: ["Lord Shiva", "Brahma", "Nandi"],
    templeType: "Shilahara Dynasty 12-Foot Circumference Shivalinga",
    tradition: ["Shaivism"],
    architecture: "Ancient Shilahara Temple Renovated by Maratha General Chimaji Appa",
    historicalPeriod: "Shilahara Dynasty (810 CE) / Maratha Renovation 1760 CE",
    description: "The historic patron shrine of Thane city overlooking Masunda Lake, enshrining one of Maharashtra's largest Shivalingas measuring 12 feet in circumference.",
    officialWebsite: "https://thane.nic.in/tourist-place/kopineshwar-temple/",
    sourceRecordId: "MH-THN-KOP-001",
    sourceName: "Thane District Administration & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Vajreshwari Yogini Devi Temple Palghar",
    nameLocal: "वज्रेश्वरी योगिनी देवी मंदिर पालघर",
    stateCode: "MH",
    districtName: "Palghar",
    localityName: "Vajreshwari, Tansa River, Palghar",
    latitude: 19.4919,
    longitude: 73.0289,
    mainDeity: "Goddess Vajreshwari (Vajrabai)",
    deities: ["Vajreshwari", "Renuka", "Kalika"],
    templeType: "Historic Hot Springs Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Fort-Like Stone Architecture Built by Chimaji Appa",
    historicalPeriod: "Chimaji Appa (1739 CE After Bassein Victory)",
    description: "Nestled at the foot of Mandagiri hill on the Tansa river, renowned for its 21 natural mineral hot springs and constructed like a Maratha fortress by Chimaji Appa.",
    officialWebsite: "https://palghar.nic.in/tourist-place/vajreshwari-temple/",
    sourceRecordId: "MH-PLG-VJR-002",
    sourceName: "Palghar District Administration & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Kunkeshwar Temple Sindhudurg",
    nameLocal: "कुणकेश्वर मंदिर सिंधुदुर्ग",
    stateCode: "MH",
    districtName: "Sindhudurg",
    localityName: "Kunkeshwar Beach, Devgad, Sindhudurg",
    latitude: 16.3411,
    longitude: 73.2989,
    mainDeity: "Lord Shiva (Kunkeshwar)",
    deities: ["Lord Shiva", "Parvati", "Arabian Sea Tirtha"],
    templeType: "Kashi of South Konkan on Coastal Sea Cliffs",
    tradition: ["Shaivism"],
    architecture: "11th-Century Yadava Dynasty Coastal Stone Temple",
    historicalPeriod: "Yadava Dynasty (1100 CE) / Patronized by Chhatrapati Shivaji Maharaj",
    description: "Perched dramatically right upon pristine Arabian Sea cliffs, celebrated as the Kashi of Konkan with regular visits by royal Maratha navies.",
    officialWebsite: "https://sindhudurg.nic.in/tourist-place/kunkeshwar-temple/",
    sourceRecordId: "MH-SND-KNK-003",
    sourceName: "Sindhudurg District Administration & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Shri Siddhtek Siddhivinayak Temple Ahmednagar",
    nameLocal: "श्री सिद्धिविनायक मंदिर सिद्धटेक अहमदनगर",
    stateCode: "MH",
    districtName: "Ahmednagar",
    localityName: "Siddhtek, Bhima River, Karjat, Ahmednagar",
    latitude: 18.3489,
    longitude: 74.7989,
    mainDeity: "Lord Ganesha (Siddhivinayak)",
    deities: ["Ganesha (Right-Turned Trunk)", "Vishnu"],
    templeType: "One of the Sacred 8 Ashtavinayak Shrines",
    tradition: ["Ganapatya"],
    architecture: "Black Stone Temple on Hillock Built by Ahilyabai Holkar",
    historicalPeriod: "Consecrated by Lord Vishnu / Rebuilt by Maharani Ahilyabai Holkar (18th Century CE)",
    description: "The only Ashtavinayak shrine where Lord Ganesha's trunk is turned to the right (Siddhi-bestowing), situated on the tranquil banks of the Bhima river.",
    officialWebsite: "https://ahmednagar.nic.in/tourist-place/siddhtek-ashtavinayak/",
    sourceRecordId: "MH-AHM-SDT-004",
    sourceName: "Shri Siddhivinayak Trust & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Shikhar Shingnapur Mahadev Satara",
    nameLocal: "शिखर शिंगणापूर महादेव सातारा",
    stateCode: "MH",
    districtName: "Satara",
    localityName: "Shingnapur Hill, Man, Satara",
    latitude: 17.8489,
    longitude: 74.6589,
    mainDeity: "Lord Shiva (Shambhukeshwar)",
    deities: ["Lord Shiva", "Parvati (Amritavapi)"],
    templeType: "Kuldaivat of Chhatrapati Shivaji Maharaj",
    tradition: ["Shaivism"],
    architecture: "Towering Hilltop Fortified Temple Complex",
    historicalPeriod: "Ancient Sanctity / Deeply Patronized by Chhatrapati Shivaji Maharaj",
    description: "Perched atop a dramatic peak in Satara, this sacred Shiva shrine was the revered family Kuldaivat of the great Maratha founder Chhatrapati Shivaji Maharaj.",
    officialWebsite: "https://satara.nic.in/tourist-place/shikhar-shingnapur/",
    sourceRecordId: "MH-SAT-SHK-005",
    sourceName: "Satara District Administration & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Shri Ganpati Temple Sangli",
    nameLocal: "श्री गणपती मंदिर सांगली",
    stateCode: "MH",
    districtName: "Sangli",
    localityName: "Krishna River Bank, Sangli Town",
    latitude: 16.8589,
    longitude: 74.5689,
    mainDeity: "Lord Ganesha",
    deities: ["Ganesha", "Chintamani"],
    templeType: "Royal Black Stone Ghat Temple",
    tradition: ["Ganapatya"],
    architecture: "Black Basalt Stone Mandir with Beautiful Krishna River Ghats",
    historicalPeriod: "Patwardhan Dynasty (1843 CE)",
    description: "The crowning architectural jewel of Sangli built by Raja Chintamanrao Patwardhan over 30 years, featuring a sanctum designed so sunrise rays touch Ganesha's idol.",
    officialWebsite: "https://sangli.nic.in/tourist-place/ganpati-temple-sangli/",
    sourceRecordId: "MH-SNG-GNP-006",
    sourceName: "Sangli District Administration & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Maa Ambadevi and Ekvira Temple Amravati",
    nameLocal: "माँ अंबादेवी एवं एकवीरा मंदिर अमरावती",
    stateCode: "MH",
    districtName: "Amravati",
    localityName: "Amba Peth, Amravati",
    latitude: 20.9319,
    longitude: 77.7589,
    mainDeity: "Maa Ambadevi (Kuldevi of Vidarbha)",
    deities: ["Ambadevi", "Ekvira Mata", "Rukmini Haran Peetha"],
    templeType: "Dvapara Yuga Rukmini Haran Sanctuary",
    tradition: ["Shaktism"],
    architecture: "Ancient Spired Nagara Temple Complex with Massive Mandapas",
    historicalPeriod: "Dvapara Yuga Antiquity (Where Shri Krishna Eloped with Rukmini)",
    description: "Ancient Vidarbha sanctuary where Princess Rukmini worshipped before Lord Krishna arrived on his chariot to whisk her away in marriage.",
    officialWebsite: "https://amravati.nic.in/tourist-place/ambadevi-temple/",
    sourceRecordId: "MH-AMR-AMB-007",
    sourceName: "Shri Ambadevi Sansthan & Amravati Administration",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Shri Siddheshwar Ratneshwar Temple Latur",
    nameLocal: "श्री सिद्धेश्वर रत्नेश्वर मंदिर लातूर",
    stateCode: "MH",
    districtName: "Latur",
    localityName: "Old Latur Town",
    latitude: 18.4042,
    longitude: 76.5811,
    mainDeity: "Lord Shiva (Siddheshwar)",
    deities: ["Lord Shiva", "Ratneshwar"],
    templeType: "King Tamradhwaja Consecration Shrine",
    tradition: ["Shaivism"],
    architecture: "Classical Yadava Style Hemadpanthi Stone Mandir",
    historicalPeriod: "King Tamradhwaja / Rebuilt in 12th Century CE",
    description: "The historical guardian temple of Latur built in the Hemadpanthi style, hosting the grand annual Makar Sankranti fair attracting lakhs of devotees.",
    officialWebsite: "https://latur.nic.in/tourist-place/siddheshwar-temple/",
    sourceRecordId: "MH-LTR-SDH-008",
    sourceName: "Latur District Administration & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Shri Balaji Mandir Washim",
    nameLocal: "श्री बालाजी मंदिर वाशिम",
    stateCode: "MH",
    districtName: "Washim",
    localityName: "Washim Town, Vatsagulma",
    latitude: 20.1089,
    longitude: 77.1389,
    mainDeity: "Lord Venkateshwara (Balaji)",
    deities: ["Lord Venkateshwara", "Padmavathi"],
    templeType: "Historic Vatsagulma Tirtha Shrine",
    tradition: ["Vaishnavism"],
    architecture: "Black Basalt Stone Complex with Massive Sacred Tank (Dev Talav)",
    historicalPeriod: "Bhavani Kalu (Diwan of Sabaji Bhonsle) in 1779 CE",
    description: "Located in ancient Vatsagulma (Washim), featuring an exquisite 250-year-old idol of Lord Balaji and a sacred water tank with underground chambers.",
    officialWebsite: "https://washim.nic.in/tourist-place/balaji-temple-washim/",
    sourceRecordId: "MH-WSM-BLJ-009",
    sourceName: "Washim District Administration & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Bhadra Maruti Temple Khuldabad Aurangabad",
    nameLocal: "भद्रा मारुती मंदिर खुलदाबाद छत्रपती संभाजीनगर",
    stateCode: "MH",
    districtName: "Aurangabad",
    localityName: "Khuldabad, Chhatrapati Sambhajinagar",
    latitude: 20.0089,
    longitude: 75.1889,
    mainDeity: "Lord Hanuman (in Sleeping / Reclining Posture)",
    deities: ["Lord Hanuman", "Lord Rama"],
    templeType: "One of Only Three Reclining Hanuman Temples in India",
    tradition: ["Vaishnavism"],
    architecture: "Historic Marble Spired Temple with Reclining Stone Hanuman Idol",
    historicalPeriod: "King Bhadrasena (Treta Yuga Origin)",
    description: "A rare and sacred shrine in Khuldabad near Ellora where Lord Hanuman is depicted in a reclining (Bhavasamadhi) pose, listening to the devotional music of King Bhadrasena.",
    officialWebsite: "https://aurangabad.gov.in/tourist-place/bhadra-maruti-temple/",
    sourceRecordId: "MH-AUR-BHD-010",
    sourceName: "Bhadra Maruti Sansthan & MTDC",
    sourceUrl: "https://maharashtratourism.gov.in",
    sourceType: "government",
  },

  // =================== KARNATAKA ===================
  {
    name: "Siddheshwar Temple Vijayapura",
    nameLocal: "ಸಿದ್ಧೇಶ್ವರ ದೇವಸ್ಥಾನ ವಿಜಯಪುರ",
    stateCode: "KA",
    districtName: "Vijayapura",
    localityName: "Siddheshwar Nagar, Bijapur",
    latitude: 16.8289,
    longitude: 75.7189,
    mainDeity: "Lord Shiva and Sri Siddharama Swamiji",
    deities: ["Lord Shiva", "Shivasharana Siddharama"],
    templeType: "12th Century Lingayat Kayaka & Sharana Shrine",
    tradition: ["Lingayatism", "Shaivism"],
    architecture: "Chalukya-Adilshahi Confluence Stone Temple",
    historicalPeriod: "12th Century CE (Shivasharana Siddharama)",
    description: "Dedicated to the great 12th-century Vachanakara and social reformer Shivasharana Siddharama, famous for the mammoth annual Sankranti car festival.",
    officialWebsite: "https://vijayapura.nic.in/tourist-place/siddheshwar-temple/",
    sourceRecordId: "KA-VIJ-SDH-001",
    sourceName: "Vijayapura District Administration & Karnataka Tourism",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "government",
  },
  {
    name: "Narasimha Jharni Cave Temple Bidar",
    nameLocal: "ನರಸಿಂಹ ಝರ್ನಿ ಗುಹಾ ದೇವಸ್ಥಾನ ಬೀದರ್",
    stateCode: "KA",
    districtName: "Bidar",
    localityName: "Maniknagar Road, Bidar",
    latitude: 17.9189,
    longitude: 77.5389,
    mainDeity: "Lord Narasimha",
    deities: ["Lord Narasimha", "Jharani River"],
    templeType: "Subterranean Natural Cave Water Temple",
    tradition: ["Vaishnavism"],
    architecture: "300-Foot Natural Tunnel Submerged in Chest-Deep Perennial Stream",
    historicalPeriod: "Ancient Puranic Consecration",
    description: "An extraordinary subterranean pilgrimage experience where devotees wade through a 300-foot underground tunnel in chest-deep crystal-clear flowing spring water to reach Lord Narasimha.",
    officialWebsite: "https://bidar.nic.in/tourist-place/narasimha-jhira-cave-temple/",
    sourceRecordId: "KA-BDR-NRJ-002",
    sourceName: "Bidar District Administration & Karnataka Tourism",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "government",
  },
  {
    name: "Sharana Basaveshwara Temple Kalaburagi",
    nameLocal: "ಶರಣ ಬಸವೇಶ್ವರ ದೇವಸ್ಥಾನ ಕಲಬುರಗಿ",
    stateCode: "KA",
    districtName: "Kalaburagi",
    localityName: "Appan Kere Tank, Gulbarga",
    latitude: 17.3389,
    longitude: 76.8389,
    mainDeity: "Lord Shiva and Sharana Basaveshwara",
    deities: ["Sharana Basaveshwara", "Lord Shiva"],
    templeType: "Historic 18th Century Sharana Samadhi Shrine",
    tradition: ["Lingayatism"],
    architecture: "Intricately Carved Stone Temple with 36 Arches and Minaret Pillars",
    historicalPeriod: "18th Century CE",
    description: "The spiritual heart of Hyderabad-Karnataka region, dedicated to Saint Sharana Basaveshwara who taught the philosophy of Dasoha (universal charity).",
    officialWebsite: "https://kalaburagi.nic.in/tourist-place/sharana-basaveshwara-temple/",
    sourceRecordId: "KA-KLB-SRB-003",
    sourceName: "Sharana Basaveshwara Samsthana & Karnataka Tourism",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "government",
  },
  {
    name: "Huligemma Devi Temple Koppala",
    nameLocal: "ಹುಲಿಗಮ್ಮ ದೇವಿ ದೇವಸ್ಥಾನ ಕೊಪ್ಪಳ",
    stateCode: "KA",
    districtName: "Koppala",
    localityName: "Huligi, Tungabhadra River Bank, Munirabad, Koppal",
    latitude: 15.3189,
    longitude: 76.3289,
    mainDeity: "Goddess Huligemma (Renuka)",
    deities: ["Huligemma Devi", "Sage Jamadagni", "Parashurama"],
    templeType: "Famous Tungabhadra Basin Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Dravidian Spired Temple on Tungabhadra River Embankment",
    historicalPeriod: "13th Century CE",
    description: "One of the most intensely revered Shakti shrines in North Karnataka, situated on the sacred Tungabhadra river, receiving millions of rural pilgrims.",
    officialWebsite: "https://koppal.nic.in/tourist-place/huligemma-temple/",
    sourceRecordId: "KA-KOP-HLG-004",
    sourceName: "Koppal District Administration & Karnataka Tourism",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "government",
  },
  {
    name: "Tarakeshwara Temple Hangal Haveri",
    nameLocal: "ತಾರಕೇಶ್ವರ ದೇವಸ್ಥಾನ ಹಾನಗಲ್ ಹಾವೇರಿ",
    stateCode: "KA",
    districtName: "Haveri",
    localityName: "Hangal Heritage Town, Haveri",
    latitude: 14.7611,
    longitude: 75.1289,
    mainDeity: "Lord Shiva (Tarakeshwara)",
    deities: ["Lord Shiva", "Parvati", "Nandi"],
    templeType: "Kalyani Chalukya Architectural Masterpiece",
    tradition: ["Shaivism"],
    architecture: "Ornate Soapstone Temple with a Colossal 30-Foot Octagonal Lotus Dome",
    historicalPeriod: "Kalyani Chalukya Dynasty (12th Century CE)",
    description: "An ASI-protected national monument celebrated in Indian art history for its breathtaking octagonal domed ceiling carved into a giant hanging lotus flower.",
    officialWebsite: "https://haveri.nic.in/tourist-place/tarakeshwara-temple-hangal/",
    sourceRecordId: "KA-HVR-TRK-005",
    sourceName: "Archaeological Survey of India Dharwad Circle & Karnataka Tourism",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "asi",
  },
  {
    name: "Harihareshwara Temple Harihar Davanagere",
    nameLocal: "ಹರಿಹರೇಶ್ವರ ದೇವಸ್ಥಾನ ಹರಿಹರ ದಾವಣಗೆರೆ",
    stateCode: "KA",
    districtName: "Davanagere",
    localityName: "Harihar, Tungabhadra River, Davanagere",
    latitude: 14.5111,
    longitude: 75.8089,
    mainDeity: "Lord Harihara (Composite Vishnu and Shiva)",
    deities: ["Lord Harihara (Right Shiva, Left Vishnu)"],
    templeType: "Supreme Composite Divinity Shrine in India",
    tradition: ["Smartha", "Harihara Confluence"],
    architecture: "Hoysala Dynasty Soapstone Mandir with 116 Carved Lathe-Turned Pillars",
    historicalPeriod: "Hoysala King Vira Narasimha II & General Polalva (1223 CE)",
    description: "A monumental 13th-century Hoysala temple where Vishnu and Shiva unite in a single magnificent idol to destroy the demon Guhasura.",
    officialWebsite: "https://davanagere.nic.in/tourist-place/harihareshwara-temple/",
    sourceRecordId: "KA-DVN-HRH-006",
    sourceName: "Archaeological Survey of India & Davanagere Administration",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "asi",
  },
  {
    name: "Talakaveri Temple and Holy Kundike Kodagu",
    nameLocal: "ತಲಕಾವೇರಿ ದೇವಸ್ಥಾನ ಮತ್ತು ಕಾವೇರಿ ಕುಂಡಿಕೆ ಕೊಡಗು",
    stateCode: "KA",
    districtName: "Kodagu",
    localityName: "Brahmagiri Hills, Bhagamandala, Coorg",
    latitude: 12.3853,
    longitude: 75.4939,
    mainDeity: "Mata Kaveri (River Goddess) and Lord Agastyeshwara",
    deities: ["Goddess Kaveri", "Lord Shiva", "Maharishi Agastya"],
    templeType: "Origin of Holy River Kaveri (Dakshina Ganga)",
    tradition: ["Smartha", "Kaveri Worship"],
    architecture: "Kerala-Coorg Sloping Roof Architecture at 4,180 Feet in Brahmagiri Hills",
    historicalPeriod: "Puranic Origin / Kodagu Royal Dynasty",
    description: "Perched high in the mist-clad Brahmagiri hills, this holy spring tank is the venerated birthplace of River Kaveri, celebrated during Tula Sankramana when holy water miraculously surges.",
    officialWebsite: "https://kodagu.nic.in/tourist-place/talacauvery/",
    sourceRecordId: "KA-KOD-TLK-007",
    sourceName: "Talakaveri Temple Management Committee & Karnataka Tourism",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "government",
  },
  {
    name: "Bhoga Nandeeshwara Temple Nandi Hills Chikballapura",
    nameLocal: "ಭೋಗ ನಂದೀಶ್ವರ ದೇವಸ್ಥಾನ ನಂದಿ ಗ್ರಾಮ ಚಿಕ್ಕಬಳ್ಳಾಪುರ",
    stateCode: "KA",
    districtName: "Chikballapura",
    localityName: "Nandi Village, Foothills of Nandi Hills, Chikkaballapur",
    latitude: 13.3758,
    longitude: 77.7011,
    mainDeity: "Lord Shiva (Arunachaleshwara & Bhoga Nandeeshwara)",
    deities: ["Lord Shiva", "Uma", "Nandi"],
    templeType: "1200-Year-Old Nolamba, Chola, and Vijayanagara Jewel",
    tradition: ["Shaivism"],
    architecture: "Magnificent Dravidian Granite Tri-Sanctum Complex with Immense Stepwell",
    historicalPeriod: "Nolamba Dynasty (9th Century CE) / Chola / Vijayanagara Expansion",
    description: "One of Karnataka's oldest intact structural stone temples, featuring pristine stone lattice jalis, wedding pavilions, and the serene Shringi Tirtha tank.",
    officialWebsite: "https://chikkaballapur.nic.in/tourist-place/bhoga-nandeeshwara-temple/",
    sourceRecordId: "KA-CKB-BHG-008",
    sourceName: "Archaeological Survey of India Bengaluru Circle & Karnataka Tourism",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "asi",
  },
  {
    name: "Male Mahadeshwara Temple MM Hills Chamarajanagara",
    nameLocal: "ಮಲೆ ಮಹದೇಶ್ವರ ದೇವಸ್ಥಾನ ಚಾಮರಾಜನಗರ",
    stateCode: "KA",
    districtName: "Chamarajanagara",
    localityName: "MM Hills (77 Hills), Kollegal, Chamarajanagar",
    latitude: 11.9689,
    longitude: 77.6189,
    mainDeity: "Lord Sri Male Mahadeshwara (Incarnation of Shiva)",
    deities: ["Male Mahadeshwara Swamy", "Tiger Vahana"],
    templeType: "Supreme Forest Hill Pilgrim Center of South Karnataka",
    tradition: ["Shaivism", "Lingayatism"],
    architecture: "Sprawling Hilltop Sanctuary Surrounded by 77 Sacred Dense Peaks",
    historicalPeriod: "15th Century CE",
    description: "Deep in the Eastern Ghats among 77 forest peaks, dedicated to the 15th-century saint Mahadeshwara who rode a tiger and performed miracles for tribal and rural welfare.",
    officialWebsite: "https://chamarajanagar.nic.in/tourist-place/male-mahadeshwara-betta/",
    sourceRecordId: "KA-CMN-MMH-009",
    sourceName: "Sri Male Mahadeshwara Swamy Kshetra Development Authority",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "government",
  },
  {
    name: "Gavi Gangadhareshwara Cave Temple Bengaluru Urban",
    nameLocal: "ಗವಿ ಗಂಗಾಧರೇಶ್ವರ ಗುಹಾ ದೇವಸ್ಥಾನ ಬೆಂಗಳೂರು",
    stateCode: "KA",
    districtName: "Bengaluru Urban",
    localityName: "Gavipuram, Kempegowda Nagar, Bengaluru",
    latitude: 12.9489,
    longitude: 77.5611,
    mainDeity: "Lord Shiva (Gavi Gangadhareshwara)",
    deities: ["Lord Shiva", "Surya", "Chandra", "Agni"],
    templeType: "Vedic Solstice Astronomical Alignment Cave Temple",
    tradition: ["Shaivism"],
    architecture: "Rock-Cut Granite Cave Temple with Giant Monolithic Sun-Disc (Surya Pana) Pillars",
    historicalPeriod: "Gautama Rishi Vedic Origin / Expanded by Kempe Gowda I (16th Century CE)",
    description: "Astounding rock-cut architectural feat where every year on Makara Sankranti evening, a single ray of sunlight passes through the Nandi horns to illuminate the Shivalinga.",
    officialWebsite: "https://bengaluruurban.nic.in/tourist-place/gavi-gangadhareshwara-temple/",
    sourceRecordId: "KA-BLR-GVG-010",
    sourceName: "Archaeological Survey of India & Karnataka Tourism",
    sourceUrl: "https://karnatakatourism.org",
    sourceType: "asi",
  },

  // =================== PUNJAB & HARYANA ===================
  {
    name: "Mukteshwar Cave Temples Pathankot",
    nameLocal: "मुक्तेश्वर गुफा मंदिर पठानकोट",
    stateCode: "PB",
    districtName: "Pathankot",
    localityName: "Shahpur Kandi, Ravi River, Pathankot",
    latitude: 32.3811,
    longitude: 75.7689,
    mainDeity: "Lord Shiva (Mukteshwar)",
    deities: ["Lord Shiva", "Pandavas"],
    templeType: "5,500-Year-Old Rock-Cut Pandava Cave Temple",
    tradition: ["Shaivism"],
    architecture: "Ancient Monolithic Caves Carved Directly on the Ravi River Sandstone Cliffs",
    historicalPeriod: "Mahabharata Antiquity",
    description: "Perched dramatically on the holy Ravi river cliffs, these rock-cut caves served as the secret shelter for the Pandavas during their agyatvas exile.",
    officialWebsite: "https://pathankot.nic.in/tourist-place/mukteshwar-dham/",
    sourceRecordId: "PB-PTK-MKT-001",
    sourceName: "Pathankot District Administration & Punjab Tourism",
    sourceUrl: "https://punjabtourism.punjab.gov.in",
    sourceType: "government",
  },
  {
    name: "Gurdwara Sri Darbar Sahib Tarn Taran",
    nameLocal: "ਗੁਰਦੁਆਰਾ ਸ੍ਰੀ ਦਰਬਾਰ ਸਾਹਿਬ ਤਰਨ ਤਾਰਨ",
    stateCode: "PB",
    districtName: "Tarn Taran",
    localityName: "Tarn Taran Sahib Town",
    latitude: 31.4511,
    longitude: 74.9289,
    mainDeity: "Sri Guru Granth Sahib Ji",
    deities: ["Fifth Guru Sri Guru Arjan Dev Ji"],
    templeType: "World's Largest Holy Sarovar (Water Tank)",
    tradition: ["Sikh Tradition"],
    architecture: "Gilded White and Gold Marble Sanctuary with Mughal-Rajput Sikh Arches",
    historicalPeriod: "Founded by Guru Arjan Dev Ji in 1590 CE",
    description: "Founded by the Fifth Sikh Guru, Guru Arjan Dev Ji, featuring the largest holy water sarovar among all Gurdwaras in the world, famed for healing leprosy.",
    officialWebsite: "https://tarntaran.nic.in/tourist-place/gurudwara-sri-darbar-sahib/",
    sourceRecordId: "PB-TTN-DRB-002",
    sourceName: "Shiromani Gurdwara Parbandhak Committee & Punjab Tourism",
    sourceUrl: "https://punjabtourism.punjab.gov.in",
    sourceType: "government",
  },
  {
    name: "Bhagwan Valmiki Tirath Sthal Amritsar Border",
    nameLocal: "ਭਗਵਾਨ ਵਾਲਮੀਕਿ ਤੀਰਥ ਸਥਲ ਅੰਮ੍ਰਿਤਸਰ",
    stateCode: "PB",
    districtName: "Ludhiana",
    localityName: "Alamgir, Ludhiana",
    latitude: 30.8289,
    longitude: 75.8589,
    mainDeity: "Sri Guru Gobind Singh Ji (Gurdwara Manji Sahib Alamgir)",
    deities: ["Guru Gobind Singh Ji"],
    templeType: "Historic Sanctuary of the Tenth Sikh Guru",
    tradition: ["Sikh Tradition"],
    architecture: "Grand White Marble Complex with Sacred Healing Spring Sarovar",
    historicalPeriod: "1705 CE",
    description: "The revered historical site where the Tenth Sikh Guru, Guru Gobind Singh Ji, rested after the Battle of Chamkaur and shot an arrow into the barren earth, causing a freshwater spring to emerge.",
    officialWebsite: "https://ludhiana.nic.in/tourist-place/gurdwara-manji-sahib-alamgir/",
    sourceRecordId: "PB-LDH-ALM-003",
    sourceName: "Ludhiana District Administration & Punjab Tourism",
    sourceUrl: "https://punjabtourism.punjab.gov.in",
    sourceType: "government",
  },
  {
    name: "Pracheen Devi Mandir Panipat",
    nameLocal: "प्राचीन देवी मंदिर पानीपत",
    stateCode: "HR",
    districtName: "Panipat",
    localityName: "Old City, Panipat",
    latitude: 29.3919,
    longitude: 76.9689,
    mainDeity: "Maa Durga",
    deities: ["Durga", "Lord Shiva"],
    templeType: "Maratha Consecrated Battle Victory Peetha",
    tradition: ["Shaktism"],
    architecture: "Nagara Style Temple with Historic Sacred Kund",
    historicalPeriod: "Maratha General Sadashivrao Bhau (18th Century CE)",
    description: "Built by Maratha commander Sadashivrao Bhau before the historic Third Battle of Panipat in 1761, serving as the central devotional shrine of Panipat.",
    officialWebsite: "https://panipat.gov.in/tourist-place/devi-mandir/",
    sourceRecordId: "HR-PNP-DEV-001",
    sourceName: "Panipat District Administration & Haryana Tourism",
    sourceUrl: "https://haryanatourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Asthal Bohar Math Rohtak",
    nameLocal: "अस्थल बोहर मठ रोहतक",
    stateCode: "HR",
    districtName: "Rohtak",
    localityName: "Bohar Village, Rohtak",
    latitude: 28.8811,
    longitude: 76.6489,
    mainDeity: "Guru Gorakhnath and Baba Chauranginath",
    deities: ["Gorakhnath", "Chauranginath", "Baba Mastnath"],
    templeType: "Supreme Headquarters of Kanphata Nath Yogis in North India",
    tradition: ["Nath Sampradaya", "Shaivism"],
    architecture: "Massive Monastic Fortress with Ancient Idol Sanctuaries and Museum",
    historicalPeriod: "8th Century CE (Chauranginath) / Revived 1741 CE by Baba Mastnath",
    description: "The supreme seat of the Kanphata Nath Yogi tradition in North India, preserving ancient Sanskrit manuscripts, stone sculptures, and sacred dhuni fires.",
    officialWebsite: "https://rohtak.gov.in/tourist-place/asthal-bohar/",
    sourceRecordId: "HR-RTK-AST-002",
    sourceName: "Rohtak District Administration & Haryana Tourism",
    sourceUrl: "https://haryanatourism.gov.in",
    sourceType: "government",
  },

  // =================== ODISHA & RAJASTHAN ===================
  {
    name: "Maa Kichakeshwari Temple Khiching Mayurbhanj",
    nameLocal: "ମା କିଚକେଶ୍ୱରୀ ମନ୍ଦିର ଖିଚିଂ ମୟୂରଭଞ୍ଜ",
    stateCode: "OD",
    districtName: "Mayurbhanj",
    localityName: "Khiching, Mayurbhanj",
    latitude: 21.9189,
    longitude: 85.8389,
    mainDeity: "Goddess Kichakeshwari (Chamunda Durga)",
    deities: ["Maa Kichakeshwari", "Lord Shiva"],
    templeType: "10th Century Monolithic Black Chlorite Temple Monument",
    tradition: ["Shaktism"],
    architecture: "Magnificent 100-Foot Kalinga Temple Built Entirely of Lustrous Black Chlorite Stone",
    historicalPeriod: "Bhanja Dynasty (920–925 CE)",
    description: "An architectural marvel constructed completely of lustrous black chlorite stone by the Bhanja rulers, celebrated for its intricate exterior carvings and museum.",
    officialWebsite: "https://mayurbhanj.nic.in/tourist-place/kichakeswari-temple-khiching/",
    sourceRecordId: "OD-MYB-KCH-001",
    sourceName: "Archaeological Survey of India & Odisha Tourism",
    sourceUrl: "https://odishatourism.gov.in",
    sourceType: "asi",
  },
  {
    name: "Jhadeswar Temple Jharsuguda",
    nameLocal: "ଝାଡ଼େଶ୍ୱର ମନ୍ଦିର ଝାରସୁଗୁଡ଼ା",
    stateCode: "OD",
    districtName: "Jharsuguda",
    localityName: "Purani Basti, Jharsuguda",
    latitude: 21.8589,
    longitude: 84.0189,
    mainDeity: "Lord Shiva (Jhadeswar)",
    deities: ["Lord Shiva", "Parvati"],
    templeType: "Swayambhu Forest Shivalinga",
    tradition: ["Shaivism"],
    architecture: "Kalinga Rekha Deula Architecture with Sacred Pond",
    historicalPeriod: "Ancient Forest Antiquity",
    description: "The historical guardian shrine of Jharsuguda, discovered in the dense forest grove (Jhada) from which the name Jharsuguda originated.",
    officialWebsite: "https://jharsuguda.nic.in/tourist-place/jhadeswar-temple/",
    sourceRecordId: "OD-JSR-JHD-002",
    sourceName: "Jharsuguda District Administration & Odisha Tourism",
    sourceUrl: "https://odishatourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Maa Manikeswari Temple Bhawanipatna Kalahandi",
    nameLocal: "ମା ମାଣିକେଶ୍ୱରୀ ମନ୍ଦିର ଭବାନୀପାଟଣା କଳାହାଣ୍ଡି",
    stateCode: "OD",
    districtName: "Kalahandi",
    localityName: "Bhawanipatna Town, Kalahandi",
    latitude: 19.9042,
    longitude: 83.1689,
    mainDeity: "Maa Manikeswari",
    deities: ["Maa Manikeswari", "Bhairava"],
    templeType: "Nagavanshi Royal Kuldevi & Famous Chhatar Jatra Shrine",
    tradition: ["Shaktism", "Tribal Confluence"],
    architecture: "Kalinga Temple Complex with Royal Palace Gateway",
    historicalPeriod: "Nagavanshi Dynasty of Kalahandi (12th Century CE)",
    description: "Presiding maternal goddess of Southwestern Odisha, famed for the historic Chhatar Jatra festival where hundreds of thousands gather during Dussehra.",
    officialWebsite: "https://kalahandi.nic.in/tourist-place/manikeswari-temple/",
    sourceRecordId: "OD-KLH-MNK-003",
    sourceName: "Kalahandi District Administration & Odisha Tourism",
    sourceUrl: "https://odishatourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Kalika Mata Temple Chittorgarh Fort",
    nameLocal: "कालिका माता मंदिर चित्तौड़गढ़ दुर्ग",
    stateCode: "RJ",
    districtName: "Chittorgarh",
    localityName: "Chittorgarh Fort, Chittorgarh",
    latitude: 24.8878,
    longitude: 74.6258,
    mainDeity: "Maa Kalika (Originally 8th Century Surya Mandir)",
    deities: ["Maa Kalika", "Surya Deva"],
    templeType: "8th Century Mori Rajput Pratihara Sun Temple Monument",
    tradition: ["Shaktism", "Saura"],
    architecture: "Maha-Gurjara Style 8th Century Sandstone Architecture on High Plinth",
    historicalPeriod: "Mori Rajput King Manbhanga (753 CE) / Restored by Maharana Hamir Singh",
    description: "An extraordinary 8th-century monument in Chittorgarh Fort, originally built as a Sun temple and later reconsecrated as Goddess Kalika by the Mewar Maharanas.",
    officialWebsite: "https://chittorgarh.rajasthan.gov.in/content/raj/chittorgarh/en/tourist-places/kalika-mata-temple.html",
    sourceRecordId: "RJ-CHG-KLK-001",
    sourceName: "Archaeological Survey of India & Rajasthan Tourism",
    sourceUrl: "https://tourism.rajasthan.gov.in",
    sourceType: "asi",
  },
  {
    name: "Pandupol Hanuman Temple Sariska Alwar",
    nameLocal: "पांडुपोल हनुमान मंदिर सरिस्का अलवर",
    stateCode: "RJ",
    districtName: "Alwar",
    localityName: "Sariska Tiger Reserve, Alwar",
    latitude: 27.2789,
    longitude: 76.5189,
    mainDeity: "Lord Hanuman (in Reclining Posture)",
    deities: ["Lord Hanuman", "Bhima"],
    templeType: "Mahabharata Rock Split Chasm & Reclining Hanuman Shrine",
    tradition: ["Vaishnavism"],
    architecture: "Natural Mountain Gorge Sanctuary inside Dense Tiger Reserve",
    historicalPeriod: "Mahabharata Antiquity (Bhima Smashed Valley with Mace)",
    description: "Located deep in Sariska's mountains where the mighty Pandava Bhima struck the mountain with his mace to create a pathway (Pol) for their chariot, meeting Hanuman.",
    officialWebsite: "https://alwar.rajasthan.gov.in/content/raj/alwar/en/tourist-places/pandupol-hanuman-temple.html",
    sourceRecordId: "RJ-ALW-PND-002",
    sourceName: "Alwar District Administration & Rajasthan Tourism",
    sourceUrl: "https://tourism.rajasthan.gov.in",
    sourceType: "government",
  },
  {
    name: "Sant Meera Bai Mandir Merta City Nagaur",
    nameLocal: "संत मीरा बाई मंदिर मेड़ता सिटी नागौर",
    stateCode: "RJ",
    districtName: "Nagaur",
    localityName: "Merta City, Nagaur",
    latitude: 26.6511,
    longitude: 74.0389,
    mainDeity: "Lord Krishna (Girdhar Gopal) and Sant Meera Bai",
    deities: ["Krishna", "Meera Bai", "Chaturbhuj Nath"],
    templeType: "Sacred Birthplace and Bhajan Seat of Sant Meera Bai",
    tradition: ["Vaishnavism", "Pushtimarg / Bhakti"],
    architecture: "Historic Rajput Haveli-Style Temple with Carved Jharokhas",
    historicalPeriod: "Rao Duda of Merta (15th Century CE)",
    description: "The sanctified place where mystic poetess-saint Meera Bai was born, spent her childhood, and composed her immortal verses of divine love for Lord Krishna.",
    officialWebsite: "https://nagaur.rajasthan.gov.in/tourist-place/meera-temple-merta/",
    sourceRecordId: "RJ-NGR-MER-003",
    sourceName: "Nagaur District Administration & Rajasthan Tourism",
    sourceUrl: "https://tourism.rajasthan.gov.in",
    sourceType: "government",
  },
];

export async function importWestSouthPhase14(dryRun: boolean = false) {
  return processStateBatch(
    "Maharashtra, Karnataka, Punjab, Haryana, Odisha & Rajasthan Tourism Boards",
    "https://maharashtratourism.gov.in",
    PHASE14_WEST_SOUTH_AUTHORITATIVE_TEMPLES,
    { dryRun }
  );
}
