/**
 * Phase 14: Bihar and Assam Strategic Regional Expansion
 * Authoritative Sources:
 * - Bihar State Tourism Development Corporation (https://tourism.bihar.gov.in)
 * - Assam Tourism Development Corporation (https://assamtourism.gov.in)
 * - Archaeological Survey of India (Patna & Guwahati Circles)
 * - District Administrations of Bihar & Assam
 * 
 * Expands coverage to 22 unrepresented districts across Bihar
 * and 21 unrepresented districts across Assam.
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

export const PHASE14_BIHAR_ASSAM_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  // =================== BIHAR (22 DISTRICTS) ===================
  {
    name: "Valmiki Ashram and Nar-Narayan Temple",
    nameLocal: "वाल्मीकि आश्रम एवं नर-नारायण मंदिर वाल्मीकिनगर",
    stateCode: "BR",
    districtName: "Pashchim Champaran",
    localityName: "Valmikinagar, Gandak River, West Champaran",
    latitude: 27.4333,
    longitude: 83.9167,
    mainDeity: "Maharishi Valmiki and Mata Sita",
    deities: ["Valmiki", "Sita", "Luv", "Kush"],
    templeType: "Ramayana Holy Hermitage & Confluence Teertha",
    tradition: ["Vaishnavism", "Rishi Heritage"],
    architecture: "Ancient Forest Hermitage on the Sacred Triveni Sangam",
    historicalPeriod: "Treta Yuga Antiquity",
    description: "The sanctified ashram where Maharishi Valmiki composed the immortal epic Ramayana and where Mata Sita gave birth to Luv and Kush.",
    officialWebsite: "https://westchamparan.nic.in/tourist-place/valmiki-nagar/",
    sourceRecordId: "BR-WCH-VAL-001",
    sourceName: "Bihar Tourism & West Champaran Administration",
    sourceUrl: "https://tourism.bihar.gov.in",
    sourceType: "government",
  },
  {
    name: "Areraj Someshwar Nath Mahadev Mandir",
    nameLocal: "सोमेश्वर नाथ महादेव मंदिर अरेराज",
    stateCode: "BR",
    districtName: "Purba Champaran",
    localityName: "Areraj, East Champaran",
    latitude: 26.5514,
    longitude: 84.9125,
    mainDeity: "Lord Shiva (Someshwar Nath)",
    deities: ["Lord Shiva", "Chandra Deva"],
    templeType: "Puranic Chandra Taposthali Shivalinga",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Temple Complex with Sacred Jal Sarovar",
    historicalPeriod: "Treta Yuga Antiquity",
    description: "Revered Panchamukhi Shivalinga where Moon God Chandra performed penance to be cured of King Daksha's curse.",
    officialWebsite: "https://eastchamparan.nic.in/tourist-place/someshwarnath-temple-areraj/",
    sourceRecordId: "BR-ECH-SOM-002",
    sourceName: "Bihar Tourism & East Champaran Administration",
    sourceUrl: "https://tourism.bihar.gov.in",
    sourceType: "government",
  },
  {
    name: "Devkuli Dham Bhuvaneshwar Nath Mandir",
    nameLocal: "देवकली धाम भुवनेश्वर नाथ मंदिर शिवहर",
    stateCode: "BR",
    districtName: "Sheohar",
    localityName: "Devkuli, Bagmati River, Sheohar",
    latitude: 26.5189,
    longitude: 85.2989,
    mainDeity: "Lord Shiva (Bhuvaneshwar Nath)",
    deities: ["Lord Shiva", "Drupada"],
    templeType: "Mahabharata Draupadi Birthplace Tradition Shrine",
    tradition: ["Shaivism"],
    architecture: "Ancient Temple on Sacred Embankment",
    historicalPeriod: "Mahabharata Antiquity",
    description: "According to Mithila folk tradition, King Drupada performed the Putrakameshti yajna here from which Draupadi and Dhrishtadyumna emerged.",
    officialWebsite: "https://sheohar.nic.in/tourist-place/devkuli-dham/",
    sourceRecordId: "BR-SHR-DVK-003",
    sourceName: "Sheohar District Administration & Bihar Tourism",
    sourceUrl: "https://sheohar.nic.in",
    sourceType: "government",
  },
  {
    name: "Kapileshwar Asthan Mandir Supaul",
    nameLocal: "कपलेश्वर स्थान मंदिर सुपौल",
    stateCode: "BR",
    districtName: "Supaul",
    localityName: "Pipra, Supaul",
    latitude: 26.1189,
    longitude: 86.6042,
    mainDeity: "Lord Shiva (Kapileshwar)",
    deities: ["Lord Shiva", "Sage Kapila"],
    templeType: "Sage Kapila Consecrated Lingam",
    tradition: ["Shaivism"],
    architecture: "Traditional Mithila Spired Mandir with Sacred Pokhari",
    historicalPeriod: "Vedic Antiquity",
    description: "Dedicated to Lord Shiva, established by Maharishi Kapila, the proponent of Sankhya philosophy, in the Mithila-Kosi basin.",
    officialWebsite: "https://supaul.nic.in/culture-heritage/",
    sourceRecordId: "BR-SUP-KPL-004",
    sourceName: "Supaul District Administration & Bihar Tourism",
    sourceUrl: "https://supaul.nic.in",
    sourceType: "government",
  },
  {
    name: "Madaneshwar Asthan Shiv Mandir Madanpur",
    nameLocal: "मदनेश्वर स्थान शिव मंदिर मदनपुर अररिया",
    stateCode: "BR",
    districtName: "Araria",
    localityName: "Madanpur, Araria",
    latitude: 26.1511,
    longitude: 87.5189,
    mainDeity: "Lord Shiva (Madaneshwar)",
    deities: ["Lord Shiva", "Kamadeva"],
    templeType: "Puranic Kamadeva Tapobhumi Lingam",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Brick and Stone Temple",
    historicalPeriod: "Medieval Origin",
    description: "The primary pilgrimage destination of Araria district, visited by tens of thousands of pilgrims during Mahashivratri and Shravan.",
    officialWebsite: "https://araria.nic.in/culture-heritage/",
    sourceRecordId: "BR-ARR-MDN-005",
    sourceName: "Araria District Administration & Bihar Tourism",
    sourceUrl: "https://araria.nic.in",
    sourceType: "government",
  },
  {
    name: "Har Gauri Mandir Thakurganj Kishanganj",
    nameLocal: "हर-गौरी मंदिर ठाकुरगंज किशनगंज",
    stateCode: "BR",
    districtName: "Kishanganj",
    localityName: "Thakurganj, Kishanganj",
    latitude: 26.4489,
    longitude: 88.1389,
    mainDeity: "Lord Shiva and Goddess Parvati (Har Gauri)",
    deities: ["Shiva", "Parvati"],
    templeType: "Historic Composite Stone Sculpture Shrine",
    tradition: ["Shaivism"],
    architecture: "Historic Mandir Housing a 1000-Year-Old Composite Basalt Vigraha",
    historicalPeriod: "Pala Dynasty (10th–11th Century CE)",
    description: "Houses an ancient black stone sculpture of Har-Gauri dating back to the Pala era, unearthed during agricultural excavations.",
    officialWebsite: "https://kishanganj.nic.in/tourist-place/har-gauri-mandir/",
    sourceRecordId: "BR-KSG-HRG-006",
    sourceName: "Kishanganj District Administration & Bihar Tourism",
    sourceUrl: "https://kishanganj.nic.in",
    sourceType: "government",
  },
  {
    name: "Maa Puran Devi Mandir Purnia",
    nameLocal: "माँ पूरण देवी मंदिर पूर्णिया",
    stateCode: "BR",
    districtName: "Purnia",
    localityName: "Purnia City, Saura River",
    latitude: 25.7789,
    longitude: 87.4758,
    mainDeity: "Maa Puran Devi (Goddess of Purnia)",
    deities: ["Puran Devi", "Durga", "Kali"],
    templeType: "City Eponymous Ancient Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Ancient Spired Temple on the Sacred Saura River",
    historicalPeriod: "Ancient Sanctity / Rebuilt by Maharaja of Darbhanga",
    description: "The historical patron deity of Purnia, from whose holy name the entire historic city and district of Purnia originates.",
    officialWebsite: "https://purnea.nic.in/tourist-place/puran-devi-temple/",
    sourceRecordId: "BR-PUR-PRN-007",
    sourceName: "Purnia District Administration & Bihar Tourism",
    sourceUrl: "https://purnea.nic.in",
    sourceType: "government",
  },
  {
    name: "Gorakhnath Dham Mandir Katihar",
    nameLocal: "गोरखनाथ धाम मंदिर कटिहार",
    stateCode: "BR",
    districtName: "Katihar",
    localityName: "Gorakhnath, Katihar",
    latitude: 25.5411,
    longitude: 87.5719,
    mainDeity: "Lord Shiva and Baba Gorakhnath",
    deities: ["Lord Shiva", "Gorakhnath"],
    templeType: "Nath Tradition Swayambhu Lingam",
    tradition: ["Shaivism", "Nath Panth"],
    architecture: "Spacious Temple Complex with Sacred Sarovar",
    historicalPeriod: "Medieval Nath Period",
    description: "Celebrated Shiva sanctuary on the eastern border of Bihar, attracting pilgrims from Bihar, Bengal, and Nepal during Shivratri.",
    officialWebsite: "https://katihar.nic.in/culture-heritage/",
    sourceRecordId: "BR-KTH-GRK-008",
    sourceName: "Katihar District Administration & Bihar Tourism",
    sourceUrl: "https://katihar.nic.in",
    sourceType: "government",
  },
  {
    name: "Singheshwar Asthan Dham Madhepura",
    nameLocal: "सिंहेश्वर स्थान धाम मधेपुरा",
    stateCode: "BR",
    districtName: "Madhepura",
    localityName: "Singheshwar, Madhepura",
    latitude: 26.0111,
    longitude: 86.8189,
    mainDeity: "Lord Shiva (Singheshwar Nath)",
    deities: ["Lord Shiva", "Rishi Shringi"],
    templeType: "Sage Shringi Consecrated Putrakameshti Peetha",
    tradition: ["Shaivism"],
    architecture: "Towering White Spired Mandir with Vast Mela Grounds",
    historicalPeriod: "Treta Yuga Antiquity (Sage Shringi)",
    description: "One of the most sacred Shiva pilgrimage centers in Bihar, consecrated by Sage Shringi who performed the Putrakameshti yajna for King Dasharatha.",
    officialWebsite: "https://madhepura.nic.in/tourist-place/singheshwar-temple/",
    sourceRecordId: "BR-MDP-SNG-009",
    sourceName: "Singheshwar Temple Trust & Bihar Tourism",
    sourceUrl: "https://madhepura.nic.in",
    sourceType: "government",
  },
  {
    name: "Maa Chandika Sthan and Matsyagandha Mandir",
    nameLocal: "माँ चंडिका स्थान एवं मत्स्यगंधा मंदिर सहरसा",
    stateCode: "BR",
    districtName: "Saharsa",
    localityName: "Matsyagandha Complex, Saharsa Town",
    latitude: 25.8833,
    longitude: 86.6000,
    mainDeity: "Maa Chandika and 64 Yoginis",
    deities: ["Chandika Devi", "64 Yoginis", "Lord Shiva"],
    templeType: "Unique 64 Yogini Spired Temple over Sacred Lake",
    tradition: ["Shaktism", "Tantric Heritage"],
    architecture: "Circular 64 Yogini Complex Overlooking Matsyagandha Lake",
    historicalPeriod: "Ancient Tantric Sthan / Modern Architectural Revival",
    description: "A prominent pilgrimage site in the Kosi region featuring an extraordinary temple dedicated to the 64 Yoginis situated amidst a lotus-filled lake.",
    officialWebsite: "https://saharsa.nic.in/tourist-place/matsyagandha-mandir/",
    sourceRecordId: "BR-SHS-MTS-010",
    sourceName: "Saharsa District Administration & Bihar Tourism",
    sourceUrl: "https://saharsa.nic.in",
    sourceType: "government",
  },
  {
    name: "Baba Garib Nath Dham Muzaffarpur",
    nameLocal: "बाबा गरीब नाथ धाम मुज़फ़्फ़रपुर",
    stateCode: "BR",
    districtName: "Muzaffarpur",
    localityName: "Purani Bazar, Muzaffarpur",
    latitude: 26.1219,
    longitude: 85.3911,
    mainDeity: "Lord Shiva (Garib Nath)",
    deities: ["Lord Shiva", "Parvati", "Ganga Maiya"],
    templeType: "Deoghar of North Bihar (Prime Kanwar Tirtha)",
    tradition: ["Shaivism"],
    architecture: "Nagara Marble Temple with Silver Canopy",
    historicalPeriod: "Swayambhu Emergence in Banyan Tree (300+ Years)",
    description: "Revered as the Deoghar of North Bihar, receiving millions of Kanwariyas who carry holy Ganga water from Pahleza Ghat across 70 kilometers on foot.",
    officialWebsite: "https://muzaffarpur.nic.in/tourist-place/baba-garibnath-temple/",
    sourceRecordId: "BR-MZF-GRB-011",
    sourceName: "Baba Garib Nath Mandir Trust & Muzaffarpur Administration",
    sourceUrl: "https://muzaffarpur.nic.in",
    sourceType: "government",
  },
  {
    name: "Baba Mahendra Nath Dham Mehandar Siwan",
    nameLocal: "बाबा महेन्द्र नाथ धाम मेहंदार सीवान",
    stateCode: "BR",
    districtName: "Siwan",
    localityName: "Mehandar, Siswan, Siwan",
    latitude: 25.9989,
    longitude: 84.4419,
    mainDeity: "Lord Shiva (Mahendra Nath)",
    deities: ["Lord Shiva", "Goddess Vishwakarma"],
    templeType: "King Mahendra Leprosy Cure Teertha with 551-Bigha Pond",
    tradition: ["Shaivism"],
    architecture: "Nagara Spired Complex on Immense Kamaladah Sarovar",
    historicalPeriod: "King Mahendradeva / Dvapara Yuga Legend",
    description: "Famous for its mammoth 551-bigha sacred pond Kamaladah, where King Mahendra was cured of illness after bathing and consecrating the Shivalinga.",
    officialWebsite: "https://siwan.nic.in/tourist-place/mahendra-nath-temple/",
    sourceRecordId: "BR-SWN-MHN-012",
    sourceName: "Siwan District Administration & Bihar Tourism",
    sourceUrl: "https://siwan.nic.in",
    sourceType: "government",
  },
  {
    name: "Aami Mandir Ambika Bhavani Sthan",
    nameLocal: "आमी मंदिर अम्बिका भवानी स्थान सारण",
    stateCode: "BR",
    districtName: "Saran",
    localityName: "Aami, Dighwara, Saran (Chhapra)",
    latitude: 25.7289,
    longitude: 85.0111,
    mainDeity: "Maa Ambika Bhavani",
    deities: ["Maa Ambika", "Lord Shiva"],
    templeType: "51 Maha Shakti Peethas (Sati Yajna Kunda)",
    tradition: ["Shaktism"],
    architecture: "Ancient Fortified Temple on Sacred Ganga Basin",
    historicalPeriod: "Puranic Daksha Yajna Site",
    description: "One of the most sacred Shakti Peethas in Eastern India, revered as the site of King Daksha's sacrificial yajna fire where Sati immolated herself.",
    officialWebsite: "https://saran.nic.in/tourist-place/aami-ambika-sthan/",
    sourceRecordId: "BR-SRN-AAM-013",
    sourceName: "Ambika Bhavani Mandir Trust & Saran Administration",
    sourceUrl: "https://saran.nic.in",
    sourceType: "government",
  },
  {
    name: "Vidyapati Dham Vidyapatinaagar Samastipur",
    nameLocal: "विद्यापति धाम विद्यापतिनगर समस्तीपुर",
    stateCode: "BR",
    districtName: "Samastipur",
    localityName: "Vidyapatinaagar, Samastipur",
    latitude: 25.6489,
    longitude: 85.7489,
    mainDeity: "Lord Shiva (Ugna) and Mahakavi Vidyapati",
    deities: ["Lord Shiva", "Kavi Vidyapati"],
    templeType: "Lord Shiva Servanthood (Ugna) Miracle Peetha",
    tradition: ["Shaivism", "Mithila Bhakti"],
    architecture: "Nagara Style Temple Built over the Mahasamadhi of Vidyapati",
    historicalPeriod: "15th Century CE",
    description: "The hallowed site where Lord Shiva served as a humble domestic servant named Ugna to the great Maithili poet Vidyapati out of boundless love for his poetry.",
    officialWebsite: "https://samastipur.nic.in/tourist-place/vidyapati-dham/",
    sourceRecordId: "BR-SMP-VDY-014",
    sourceName: "Samastipur District Administration & Bihar Tourism",
    sourceUrl: "https://samastipur.nic.in",
    sourceType: "government",
  },
  {
    name: "Maa Katyayani Sthan Dham Khagaria",
    nameLocal: "माँ कात्यायनी स्थान धाम खगड़िया",
    stateCode: "BR",
    districtName: "Khagaria",
    localityName: "Chautham, Bagmati River, Khagaria",
    latitude: 25.5989,
    longitude: 86.6489,
    mainDeity: "Maa Katyayani (Sixth Form of Navadurga)",
    deities: ["Maa Katyayani", "Lord Shiva"],
    templeType: "Puranic Forest Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Spired Red Temple Amid River Waters",
    historicalPeriod: "Puranic Antiquity",
    description: "Surrounded by rivers and sacred groves, this revered temple dedicated to Goddess Katyayani is one of the premier Shakti shrines of Central Bihar.",
    officialWebsite: "https://khagaria.nic.in/tourist-place/katyayani-mandir/",
    sourceRecordId: "BR-KHG-KTY-015",
    sourceName: "Khagaria District Administration & Bihar Tourism",
    sourceUrl: "https://khagaria.nic.in",
    sourceType: "government",
  },
  {
    name: "Baba Gidheshwar Mahadev Mandir Jamui",
    nameLocal: "बाबा गिद्धेश्वर महादेव मंदिर जमुई",
    stateCode: "BR",
    districtName: "Jamui",
    localityName: "Gidheshwar Hills, Gidhaur, Jamui",
    latitude: 24.8589,
    longitude: 86.1989,
    mainDeity: "Lord Shiva (Gidheshwar)",
    deities: ["Lord Shiva", "Jatayu (Giddha Raj)"],
    templeType: "Ramayana Jatayu Battleground Shrine",
    tradition: ["Shaivism"],
    architecture: "Cave and Stone Temple Atop Rocky Forest Hill",
    historicalPeriod: "Treta Yuga Puranic Consecration",
    description: "Perched atop scenic rocky hills where according to local tradition the heroic bird Jatayu fought demon king Ravana to protect Mata Sita.",
    officialWebsite: "https://jamui.nic.in/tourist-place/gidheshwar-temple/",
    sourceRecordId: "BR-JMJ-GDH-016",
    sourceName: "Jamui District Administration & Bihar Tourism",
    sourceUrl: "https://jamui.nic.in",
    sourceType: "government",
  },
  {
    name: "Girhinda Pahari Shiv Mandir Sheikhpura",
    nameLocal: "गिरहिंडा पहाड़ी शिव मंदिर शेखपुरा",
    stateCode: "BR",
    districtName: "Sheikhpura",
    localityName: "Girhinda Hill, Sheikhpura Town",
    latitude: 25.1389,
    longitude: 85.8589,
    mainDeity: "Lord Shiva (Girhindeshwar)",
    deities: ["Lord Shiva", "Parvati"],
    templeType: "Ancient Hilltop Swayambhu Lingam",
    tradition: ["Shaivism"],
    architecture: "White Spired Temple with Flight of Stone Steps Atop Granitic Hill",
    historicalPeriod: "Medieval Origin",
    description: "Crowning a prominent rocky outcrop in Sheikhpura, offering sweeping views of the Magadh plains and receiving thousands during Shravan.",
    officialWebsite: "https://sheikhpura.nic.in/tourist-place/girhinda-pahari/",
    sourceRecordId: "BR-SHK-GRH-017",
    sourceName: "Sheikhpura District Administration & Bihar Tourism",
    sourceUrl: "https://sheikhpura.nic.in",
    sourceType: "government",
  },
  {
    name: "Maa Aranya Devi Temple Ara Bhojpur",
    nameLocal: "माँ आरण्य देवी मंदिर आरा भोजपुर",
    stateCode: "BR",
    districtName: "Bhojpur",
    localityName: "Sheesh Mahal Chowk, Ara",
    latitude: 25.5583,
    longitude: 84.6644,
    mainDeity: "Maa Aranya Devi (Goddess of the Forest)",
    deities: ["Maa Aranya", "Maa Durga"],
    templeType: "City Eponymous Mahabharata Peetha",
    tradition: ["Shaktism"],
    architecture: "Historic North Indian Spired Temple with Two Stone Goddess Idols",
    historicalPeriod: "Mahabharata Antiquity (Associated with Pandavas)",
    description: "The historical patron deity of Ara, from whose name the city of Ara is derived. Established by King Mayuradhwaja during the Mahabharata era.",
    officialWebsite: "https://bhojpur.nic.in/tourist-place/aranya-devi-temple/",
    sourceRecordId: "BR-BHJ-ARN-018",
    sourceName: "Bhojpur District Administration & Bihar Tourism",
    sourceUrl: "https://bhojpur.nic.in",
    sourceType: "government",
  },
  {
    name: "Deo Surya Mandir Aurangabad",
    nameLocal: "देव सूर्य मंदिर औरंगाबाद (बिहार)",
    stateCode: "BR",
    districtName: "Aurangabad",
    localityName: "Deo Town, Aurangabad",
    latitude: 24.6558,
    longitude: 84.4361,
    mainDeity: "Bhagwan Surya (Sun God)",
    deities: ["Lord Surya", "Usha", "Pratyusha"],
    templeType: "India's Rarest 100-Foot West-Facing Sun Temple",
    tradition: ["Saura", "Smartha"],
    architecture: "100-Foot Monolithic Black and Red Stone Nagara Shikhara Facing West",
    historicalPeriod: "King Ila (Treta Yuga Origin / 6th–8th Century CE Stone Work)",
    description: "Architectural wonder and the supreme epicentre of Chhath Puja in India. Unlike almost all Sun temples that face east, this 100-foot stone marvel faces west.",
    officialWebsite: "https://aurangabad.bih.nic.in/tourist-place/deo-temple/",
    sourceRecordId: "BR-AUR-DEO-019",
    sourceName: "Deo Temple Trust & Bihar Tourism",
    sourceUrl: "https://aurangabad.bih.nic.in",
    sourceType: "government",
  },
  {
    name: "Sobhnath Mandir Kakolat Nawada",
    nameLocal: "शोभनाथ मंदिर ककोलत नवादा",
    stateCode: "BR",
    districtName: "Nawada",
    localityName: "Kakolat Waterfall Valley, Nawada",
    latitude: 24.6989,
    longitude: 85.6189,
    mainDeity: "Lord Shiva (Sobhnath)",
    deities: ["Lord Shiva", "Rishi Markandeya"],
    templeType: "Mahabharata Waterway Sanctuary",
    tradition: ["Shaivism"],
    architecture: "Ancient Temple Beside Kakolat Natural Waterfall",
    historicalPeriod: "Mahabharata Antiquity",
    description: "Nestled beneath the roaring waters of Kakolat waterfall, where according to legend King Nahusha was liberated from a serpent curse by Sage Agastya.",
    officialWebsite: "https://nawada.nic.in/tourist-place/kakolat-waterfall/",
    sourceRecordId: "BR-NWD-SBH-020",
    sourceName: "Nawada District Administration & Bihar Tourism",
    sourceUrl: "https://nawada.nic.in",
    sourceType: "government",
  },
  {
    name: "Baba Siddhnath Temple Barabar Vanawar Hills",
    nameLocal: "बाबा सिद्धनाथ मंदिर बराबर (वनावर पहाड़ी) जहानाबाद",
    stateCode: "BR",
    districtName: "Jehanabad",
    localityName: "Barabar Hills Peak, Jehanabad",
    latitude: 25.0089,
    longitude: 85.0611,
    mainDeity: "Lord Shiva (Siddhnath / Banasura Mahadev)",
    deities: ["Lord Shiva", "Banasura"],
    templeType: "Puranic Peak Sanctuary Adjacent to Ashokan Caves",
    tradition: ["Shaivism"],
    architecture: "Gupta Period Stone Temple on Highest Granite Peak of Barabar",
    historicalPeriod: "Gupta Era (6th Century CE)",
    description: "Perched atop the highest granite crest of the historic Barabar hills adjacent to Emperor Ashoka's rock-cut caves, consecrated by King Banasura.",
    officialWebsite: "https://jehanabad.nic.in/tourist-place/barabar-hills/",
    sourceRecordId: "BR-JHN-SDH-021",
    sourceName: "Jehanabad District Administration & Bihar Tourism",
    sourceUrl: "https://jehanabad.nic.in",
    sourceType: "government",
  },
  {
    name: "Madhusudan Mandir Kurtha Arwal",
    nameLocal: "मधुसूदन मंदिर कुर्था अरवल",
    stateCode: "BR",
    districtName: "Arwal",
    localityName: "Kurtha, Son River Basin, Arwal",
    latitude: 25.1489,
    longitude: 84.7189,
    mainDeity: "Lord Vishnu (Madhusudan)",
    deities: ["Madhusudan", "Lakshmi"],
    templeType: "Historic Magadh Vaishnava Shrine",
    tradition: ["Vaishnavism"],
    architecture: "Traditional North Indian Spired Temple",
    historicalPeriod: "18th Century CE",
    description: "The prominent Vaishnava pilgrimage destination of Arwal district, visited by thousands of devotees during Janmashtami and Kartik Purnima.",
    officialWebsite: "https://arwal.nic.in/culture-heritage/",
    sourceRecordId: "BR-ARW-MDS-022",
    sourceName: "Arwal District Administration & Bihar Tourism",
    sourceUrl: "https://arwal.nic.in",
    sourceType: "government",
  },

  // =================== ASSAM (21 DISTRICTS) ===================
  {
    name: "Shri Jagannath Temple Dibrugarh",
    nameLocal: "শ্ৰী জগন্নাথ মন্দিৰ ডিব্ৰুগড়",
    stateCode: "AS",
    districtName: "Dibrugarh",
    localityName: "Khanikar, Dibrugarh",
    latitude: 27.4489,
    longitude: 94.9489,
    mainDeity: "Lord Jagannath, Balabhadra, Subhadra",
    deities: ["Jagannath", "Balabhadra", "Subhadra"],
    templeType: "Supreme Jagannath Kalinga Monument of Upper Assam",
    tradition: ["Vaishnavism"],
    architecture: "Magnificent 85-Foot Kalinga Nagara Architecture in Red Sandstone",
    historicalPeriod: "2014 CE (Replicating Puri Architecture)",
    description: "An architectural marvel in Upper Assam, replicating the grand Kalinga style of Puri Jagannath Temple amidst verdant tea estates.",
    officialWebsite: "https://dibrugarh.assam.gov.in/tourist-place/jagannath-temple/",
    sourceRecordId: "AS-DIB-JGN-001",
    sourceName: "Dibrugarh District Administration & Assam Tourism",
    sourceUrl: "https://assamtourism.gov.in",
    sourceType: "government",
  },
  {
    name: "Dhekiakhowa Bornamghar Jorhat",
    nameLocal: "ঢেকীয়াখোৱা বৰনামঘৰ যোৰহাট",
    stateCode: "AS",
    districtName: "Jorhat",
    localityName: "Dhekiakhowa, Jorhat",
    latitude: 26.7411,
    longitude: 94.2989,
    mainDeity: "Namghar (Ekasarana Dharma — Holy Bhagavata Text)",
    deities: ["Bhagavata Purana", "Mahapurush Madhavdeva"],
    templeType: "Historic 500-Year Perpetual Flame Bornamghar",
    tradition: ["Ekasarana Dharma", "Neo-Vaishnavism"],
    architecture: "Traditional Assamese Wooden Namghar with Intricate Carved Pillars",
    historicalPeriod: "Founded by Sri Sri Madhavdeva in 1461 CE (Burns Continuous Flame)",
    description: "Founded by Mahapurusha Madhavdeva in 1461 CE; holds an unbroken, burning earthen lamp (Akhand Pradeep) recognized as one of the world's longest-burning flames.",
    officialWebsite: "https://jorhat.assam.gov.in/tourist-place/dhekiakhowa-bornamghar/",
    sourceRecordId: "AS-JOR-DHK-002",
    sourceName: "Bornamghar Management Committee & Assam Tourism",
    sourceUrl: "https://jorhat.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Basudev Than Naruwa Xatra Lakhimpur",
    nameLocal: "বাসুদেৱ থান নৰোৱা সত্ৰ লখিমপুৰ",
    stateCode: "AS",
    districtName: "Lakhimpur",
    localityName: "Dhakuakhana, Lakhimpur",
    latitude: 27.2189,
    longitude: 94.4489,
    mainDeity: "Lord Krishna (Basudev)",
    deities: ["Lord Krishna", "Rukmini"],
    templeType: "Historic Damodariya Neo-Vaishnava Xatra",
    tradition: ["Ekasarana Dharma"],
    architecture: "Historic Assamese Xatra Complex with Grand Manikut",
    historicalPeriod: "14th Century Origin / Established by King Jayadhwaj Singha (1663 CE)",
    description: "One of the most sacred Vaishnava pilgrimage centers of Upper Assam, possessing sacred stone idols dating back to ancient Vidarbha-Chutia kingdom antiquity.",
    officialWebsite: "https://lakhimpur.assam.gov.in/tourist-place/basudev-than-naruwa-satra/",
    sourceRecordId: "AS-LKP-BSD-003",
    sourceName: "Lakhimpur District Administration & Assam Tourism",
    sourceUrl: "https://lakhimpur.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Malinithan Temple Dhemaji Border",
    nameLocal: "মালিনীথান দেৱালয় ধেমাজি সীমান্ত",
    stateCode: "AS",
    districtName: "Dhemaji",
    localityName: "Likabali Border, Dhemaji",
    latitude: 27.6589,
    longitude: 94.7189,
    mainDeity: "Goddess Durga (Malini)",
    deities: ["Durga", "Krishna", "Rukmini"],
    templeType: "14th Century Chutia Kingdom Granite Archaeological Monument",
    tradition: ["Shaktism"],
    architecture: "Intricately Sculpted Black Granite Stone Reliefs and Temple Ruins",
    historicalPeriod: "Chutia Dynasty (14th Century CE)",
    description: "An extraordinary archaeological complex containing exquisitely sculpted granite images of Durga, Surya, and Ganesha where Lord Krishna welcomed Rukmini.",
    officialWebsite: "https://dhemaji.assam.gov.in/tourist-place/malini-than/",
    sourceRecordId: "AS-DHJ-MLN-004",
    sourceName: "Archaeological Survey of India & Dhemaji Administration",
    sourceUrl: "https://dhemaji.assam.gov.in",
    sourceType: "asi",
  },
  {
    name: "Mahabhairav Temple Tezpur Sonitpur",
    nameLocal: "মহাভৈৰৱ মন্দিৰ তেজপুৰ শোণিতপুৰ",
    stateCode: "AS",
    districtName: "Sonitpur",
    localityName: "Tezpur Town Hill, Sonitpur",
    latitude: 26.6389,
    longitude: 92.7989,
    mainDeity: "Lord Shiva (Mahabhairav)",
    deities: ["Lord Shiva", "Banasura"],
    templeType: "Prehistoric King Banasura Consecrated Lingam",
    tradition: ["Shaivism"],
    architecture: "Spired Ahom Nagara Architecture with Colossal Living Shivalinga",
    historicalPeriod: "Treta/Dvapara Antiquity / Rebuilt by Tungkhungia Ahom Kings",
    description: "Legend holds this temple was built by the Asura King Banasura, whose capital was ancient Sonitpur. Houses one of the largest living Shiva lingams in Northeast India.",
    officialWebsite: "https://sonitpur.assam.gov.in/tourist-place/mahabhairab-temple/",
    sourceRecordId: "AS-SNP-MHB-005",
    sourceName: "Sonitpur District Administration & Assam Tourism",
    sourceUrl: "https://sonitpur.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Biswanath Ghat Gupta Kashi Temple",
    nameLocal: "বিশ্বনাথ ঘাট গুপ্ত কাশী মন্দিৰ বিশ্বনাথ",
    stateCode: "AS",
    districtName: "Biswanath",
    localityName: "Biswanath Ghat, Brahmaputra River, Biswanath",
    latitude: 26.6611,
    longitude: 93.1611,
    mainDeity: "Lord Shiva (Biswanath)",
    deities: ["Lord Shiva", "Brahmaputra"],
    templeType: "Gupta Kashi of Assam — Submerged Monsoon Shivalinga",
    tradition: ["Shaivism"],
    architecture: "Ancient Stone Ghat with Submerged Sanctum Emerging in Winter",
    historicalPeriod: "Puranic Origin / Ahom Dynasty Rebuilding",
    description: "Celebrated as the Gupta Kashi of Northeast India on the Brahmaputra banks, where an ensemble of 27 ancient stone temples emerges during winter waters.",
    officialWebsite: "https://biswanath.assam.gov.in/tourist-place/biswanath-ghat/",
    sourceRecordId: "AS-BSN-BSW-006",
    sourceName: "Biswanath District Administration & Assam Tourism",
    sourceUrl: "https://biswanath.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Charaideo Sukaphaa Heritage Shrine and Maidams",
    nameLocal: "চৰাইদেউ চুকফা ঐতিহ্য ক্ষেত্ৰ চৰাইদেউ",
    stateCode: "AS",
    districtName: "Charaideo",
    localityName: "Charaideo Hillock, Sonari",
    latitude: 26.9489,
    longitude: 94.8689,
    mainDeity: "Chao-Pha Ancestral Deities & Lord Shiva",
    deities: ["Ahom Ancestral Spirits", "Lord Shiva"],
    templeType: "UNESCO World Heritage Ahom Royal Sacred Capital",
    tradition: ["Tai-Ahom Sacred Tradition", "Shaivism"],
    architecture: "Pyramidal Mounds (Maidams) and Ancient Stone Shrines",
    historicalPeriod: "Chaolung Sukaphaa (1253 CE) / 13th–18th Century CE",
    description: "The sacred ancestral resting place of the Ahom Kings and a UNESCO World Heritage site, consecrated on the auspicious foothills by founder King Sukaphaa.",
    officialWebsite: "https://charaideo.assam.gov.in/tourist-place/charaideo-maidam/",
    sourceRecordId: "AS-CRD-SKP-007",
    sourceName: "Archaeological Survey of India & Charaideo Administration",
    sourceUrl: "https://charaideo.assam.gov.in",
    sourceType: "asi",
  },
  {
    name: "Negheriting Shiva Temple Golaghat",
    nameLocal: "নেঘেৰিটিং শিৱ দৌল গোলাঘাট",
    stateCode: "AS",
    districtName: "Golaghat",
    localityName: "Dergaon, Golaghat",
    latitude: 26.7119,
    longitude: 93.9911,
    mainDeity: "Lord Shiva (Negheriting Doul)",
    deities: ["Lord Shiva", "Vishnu", "Ganesha", "Surya", "Durga"],
    templeType: "Panchayatana Style Ahom Royal Doul",
    tradition: ["Shaivism"],
    architecture: "Nagara Ahom Brick Architecture atop Isolated Hillock with 4 Subsidiary Douls",
    historicalPeriod: "Ahom King Rajeswar Singha (1765 CE)",
    description: "One of Assam's finest surviving Panchayatana temple complexes built on a hillock by King Rajeswar Singha, home to hundreds of sacred rhesus monkeys.",
    officialWebsite: "https://golaghat.assam.gov.in/tourist-place/negheriting-siva-doul/",
    sourceRecordId: "AS-GLG-NGH-008",
    sourceName: "Golaghat District Administration & Assam Tourism",
    sourceUrl: "https://golaghat.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Deopani Archaeological Shiva Temple Karbi Anglong",
    nameLocal: "দেওপানী পুৰাতাত্ত্বিক শিৱ মন্দিৰ কাৰ্বি আংলং",
    stateCode: "AS",
    districtName: "Karbi Anglong",
    localityName: "Deopani, Bokajan, Karbi Anglong",
    latitude: 26.1989,
    longitude: 93.7889,
    mainDeity: "Lord Shiva and Goddess Chamunda",
    deities: ["Lord Shiva", "Chamunda", "Vishnu"],
    templeType: "9th Century Pre-Ahom Stone Sculpture Monument",
    tradition: ["Shaivism", "Tribal-Sanatana Confluence"],
    architecture: "Ancient Carved Basalt Pillars and Sculptures",
    historicalPeriod: "9th–10th Century CE",
    description: "Protected archaeological site holding ancient stone sculptures and inscriptions depicting the syncretism of tribal and classical Sanatana iconography.",
    officialWebsite: "https://karbianglong.assam.gov.in/culture-heritage/",
    sourceRecordId: "AS-KRA-DOP-009",
    sourceName: "Archaeological Directorate of Assam & Karbi Anglong Council",
    sourceUrl: "https://karbianglong.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Ranachandi Monolithic Rock Temple Maibang",
    nameLocal: "ৰণচণ্ডী একাশ্ম মন্দিৰ মাইবাং ডিমা হাছাও",
    stateCode: "AS",
    districtName: "Dima Hasao",
    localityName: "Maibang, Mahur River Bank, Dima Hasao",
    latitude: 25.3011,
    longitude: 93.1611,
    mainDeity: "Goddess Ranachandi",
    deities: ["Ranachandi", "Lord Shiva"],
    templeType: "Monolithic Rock-Cut Dimasa Kingdom Temple",
    tradition: ["Shaktism", "Dimasa Royal Heritage"],
    architecture: "Carved Directly from a Single Giant Boulder beside River Mahur",
    historicalPeriod: "Dimasa King Harishchandra Narayan (1761 CE)",
    description: "An extraordinary monolithic two-roofed stone temple carved entirely out of a single living rock boulder by the Dimasa rulers in their ancient hill capital of Maibang.",
    officialWebsite: "https://dimahasao.assam.gov.in/tourist-place/maibang-monolithic-temple/",
    sourceRecordId: "AS-DMH-RNC-010",
    sourceName: "Archaeological Survey of India & Dima Hasao Autonomous Council",
    sourceUrl: "https://dimahasao.assam.gov.in",
    sourceType: "asi",
  },
  {
    name: "Shiv Bari Mandir Lanka Hojai",
    nameLocal: "শিৱ বাৰী মন্দিৰ লংকা হোজাই",
    stateCode: "AS",
    districtName: "Hojai",
    localityName: "Lanka, Hojai",
    latitude: 25.9289,
    longitude: 92.9489,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Parvati"],
    templeType: "Regional Swayambhu Shiva Peetha",
    tradition: ["Shaivism"],
    architecture: "Traditional Spired Assam Nagara Temple",
    historicalPeriod: "Medieval Sanctity",
    description: "The primary pilgrimage destination of Hojai district, consecrated on the ancient Kapili river basin.",
    officialWebsite: "https://hojai.assam.gov.in/culture-heritage/",
    sourceRecordId: "AS-HOJ-SHV-011",
    sourceName: "Hojai District Administration & Assam Tourism",
    sourceUrl: "https://hojai.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Mayong Narasimha and Tantric Shrines Morigaon",
    nameLocal: "মায়ং নৰসিংহ মন্দিৰ মৰিগাঁও",
    stateCode: "AS",
    districtName: "Morigaon",
    localityName: "Mayong Heritage Village, Morigaon",
    latitude: 26.2411,
    longitude: 92.0511,
    mainDeity: "Lord Narasimha and Goddess Kamakhya",
    deities: ["Narasimha", "Shiva", "Kamakhya"],
    templeType: "Cradle of Indian Mysticism & Black Magic Heritage",
    tradition: ["Vaishnavism", "Tantric Shaktism"],
    architecture: "Ancient Hilltop Stone Shrines with Ancient Sanskrit Inscriptions",
    historicalPeriod: "Ancient Mahabharata Legend (Pragjyotisha King Ghatotkacha)",
    description: "Located in Mayong, universally known as India's capital of ancient mysticism and esoteric healing, preserving ancient copper plates and rock sculptures.",
    officialWebsite: "https://morigaon.assam.gov.in/tourist-place/mayong-heritage/",
    sourceRecordId: "AS-MOR-MYN-012",
    sourceName: "Morigaon District Administration & Assam Tourism",
    sourceUrl: "https://morigaon.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Billeswar Ancient Shiva Devalaya Nalbari",
    nameLocal: "বিল্লেশ্বৰ দেৱালয় বেলশৰ নলবাৰী",
    stateCode: "AS",
    districtName: "Nalbari",
    localityName: "Belsor, Nalbari",
    latitude: 26.3989,
    longitude: 91.3811,
    mainDeity: "Lord Shiva (Billeswar)",
    deities: ["Lord Shiva", "Parvati"],
    templeType: "500-Year-Old Ahom Consecrated Shivalinga",
    tradition: ["Shaivism"],
    architecture: "Ahom Spired Doul with Large Lotus Tank",
    historicalPeriod: "Ahom King Siva Singha (18th Century CE)",
    description: "Legend relates that a cow used to pour her milk over an underground stone, leading the local king to excavate this miraculous self-manifested lingam.",
    officialWebsite: "https://nalbari.assam.gov.in/tourist-place/billeswar-temple/",
    sourceRecordId: "AS-NLB-BLS-013",
    sourceName: "Nalbari District Administration & Assam Tourism",
    sourceUrl: "https://nalbari.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Bhairabkunda Temple Complex Udalguri",
    nameLocal: "ভৈৰৱকুণ্ড মন্দিৰ কমপ্লেক্স ওদালগুৰি",
    stateCode: "AS",
    districtName: "Udalguri",
    localityName: "Bhairabkunda, Bhutan-Arunachal Border, Udalguri",
    latitude: 26.8989,
    longitude: 92.1189,
    mainDeity: "Lord Shiva (Bhairava)",
    deities: ["Lord Shiva", "Dhansiri River"],
    templeType: "Tri-Junction Mountain River Confluence Peetha",
    tradition: ["Shaivism"],
    architecture: "Picturesque Spired Mandir on Mountain Gorge Riverbanks",
    historicalPeriod: "Ancient Sanctity / Consecrated by Regional Sadhus",
    description: "Located at the dramatic tri-junction of Assam, Arunachal Pradesh, and the kingdom of Bhutan where rivers Jampani and Bhairabi merge to form River Dhansiri.",
    officialWebsite: "https://udalguri.assam.gov.in/tourist-place/bhairabkunda/",
    sourceRecordId: "AS-UDL-BHR-014",
    sourceName: "Bodoland Territorial Council & Assam Tourism",
    sourceUrl: "https://udalguri.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Khatara Xatra Mangaldai Darrang",
    nameLocal: "খটৰা সত্ৰ মঙ্গলদৈ দৰং",
    stateCode: "AS",
    districtName: "Darrang",
    localityName: "Mangaldai, Darrang",
    latitude: 26.4389,
    longitude: 92.0389,
    mainDeity: "Lord Krishna (Govinda)",
    deities: ["Lord Krishna", "Sri Sri Madhavdeva"],
    templeType: "Historic 450-Year Vaishnava Monastic Center",
    tradition: ["Ekasarana Dharma"],
    architecture: "Traditional Assamese Xatra with Vast Prayer Hall",
    historicalPeriod: "Established by Sri Sri Ramchandra Ata (1568 CE)",
    description: "One of the most venerable Vaishnava institutions of Darrang district, preserving the sacred cultural lineage of Sattriya dance, music, and dramatic performances.",
    officialWebsite: "https://darrang.assam.gov.in/tourist-place/khatara-satra/",
    sourceRecordId: "AS-DRG-KHT-015",
    sourceName: "Darrang District Administration & Assam Tourism",
    sourceUrl: "https://darrang.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Bagheswari Temple Bongaigaon",
    nameLocal: "বাঘেশ্বৰী মন্দিৰ বঙাইগাঁও",
    stateCode: "AS",
    districtName: "Bongaigaon",
    localityName: "Bongaigaon Hilltop",
    latitude: 26.4789,
    longitude: 90.5589,
    mainDeity: "Maa Bagheswari (Durga)",
    deities: ["Maa Bagheswari", "Bhairava"],
    templeType: "One of the Oldest Shakti Shrines of Lower Assam",
    tradition: ["Shaktism"],
    architecture: "Hilltop Temple Complex Surrounded by Forested Greens",
    historicalPeriod: "Bijni Raj Family Consecration / 16th Century CE",
    description: "The supreme religious landmark of Bongaigaon, revered as the wish-fulfilling maternal protector of the historic Bijni royal territory.",
    officialWebsite: "https://bongaigaon.assam.gov.in/tourist-place/bagheswari-temple/",
    sourceRecordId: "AS-BNG-BGH-016",
    sourceName: "Bongaigaon District Administration & Assam Tourism",
    sourceUrl: "https://bongaigaon.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Tukreswari Temple Chirang Border",
    nameLocal: "টুক্ৰেশ্বৰী মন্দিৰ চিৰাং সীমান্ত",
    stateCode: "AS",
    districtName: "Chirang",
    localityName: "Tukreswari Hill, Bijni, Chirang",
    latitude: 26.4989,
    longitude: 90.7189,
    mainDeity: "Goddess Sati (Tukreswari)",
    deities: ["Maa Tukreswari", "Lord Shiva"],
    templeType: "Shakti Peetha (Where a Portion of Sati Fell)",
    tradition: ["Shaktism"],
    architecture: "Ancient Temple atop Isolated Granite Hill with Sacred Monkeys",
    historicalPeriod: "Bijni Royal Family / 17th Century CE",
    description: "Perched atop Tukreswari hill where according to local beliefs a sacred piece of Goddess Sati's body fell during Lord Shiva's cosmic Tandava dance.",
    officialWebsite: "https://chirang.assam.gov.in/culture-heritage/",
    sourceRecordId: "AS-CRG-TKR-017",
    sourceName: "Chirang District Administration & Assam Tourism",
    sourceUrl: "https://chirang.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Mahamaya Dham Bogribari Kokrajhar",
    nameLocal: "মহামায়া ধাম বগৰীবাৰী কোকৰাঝাৰ",
    stateCode: "AS",
    districtName: "Kokrajhar",
    localityName: "Bogribari, Kokrajhar",
    latitude: 26.2611,
    longitude: 90.1189,
    mainDeity: "Maa Mahamaya",
    deities: ["Maa Mahamaya", "Parvati"],
    templeType: "Koch-Rajbanshi Royal Shakti Peetha",
    tradition: ["Shaktism"],
    architecture: "Traditional Spired Assam Temple with Extensive Sacred Grounds",
    historicalPeriod: "Koch Dynasty (16th Century CE)",
    description: "One of the greatest pilgrimage destinations in Western Assam, revered across the Koch-Rajbanshi and Bodo communities as the universal mother.",
    officialWebsite: "https://kokrajhar.assam.gov.in/tourist-place/mahamaya-dham/",
    sourceRecordId: "AS-KKR-MHM-018",
    sourceName: "Bodoland Territorial Council & Assam Tourism",
    sourceUrl: "https://kokrajhar.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Siddheshwar Temple Badarpurghat Karimganj",
    nameLocal: "সিদ্ধেশ্বৰ মন্দিৰ বদৰপুৰঘাট কৰিমগঞ্জ",
    stateCode: "AS",
    districtName: "Karimganj",
    localityName: "Badarpurghat, Barak River, Karimganj",
    latitude: 24.8989,
    longitude: 92.5611,
    mainDeity: "Lord Shiva (Siddheshwar)",
    deities: ["Lord Shiva", "Sage Kapila"],
    templeType: "Barak Valley Prime Shiva Teertha on River Barak",
    tradition: ["Shaivism"],
    architecture: "Medieval Spired Temple overlooking the Expansive Barak River",
    historicalPeriod: "Sage Kapila Tapobhumi / Medieval Rebuilding",
    description: "The foremost Shiva temple of the Barak Valley, situated at the holy bend of the Barak river, celebrated for its annual Varuni snana fair.",
    officialWebsite: "https://karimganj.assam.gov.in/tourist-place/siddheswar-temple/",
    sourceRecordId: "AS-KRM-SDH-019",
    sourceName: "Karimganj District Administration & Assam Tourism",
    sourceUrl: "https://karimganj.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Siddheshwari Kali Temple Hailakandi",
    nameLocal: "সিদ্ধেশ্বৰী কালী মন্দিৰ হাইলাকান্দি",
    stateCode: "AS",
    districtName: "Hailakandi",
    localityName: "Badarpur Road, Hailakandi Town",
    latitude: 24.6811,
    longitude: 92.5689,
    mainDeity: "Maa Siddheshwari Kali",
    deities: ["Maa Kali", "Lord Shiva"],
    templeType: "Barak Valley Historic Shakti Sanctuary",
    tradition: ["Shaktism"],
    architecture: "Spired Bengali and Assamese Style Temple",
    historicalPeriod: "18th Century CE",
    description: "The primary devotional center of Hailakandi district, celebrated for its grand celebrations during Shyama Puja and Navratri.",
    officialWebsite: "https://hailakandi.assam.gov.in/culture-heritage/",
    sourceRecordId: "AS-HLK-SDK-020",
    sourceName: "Hailakandi District Administration & Assam Tourism",
    sourceUrl: "https://hailakandi.assam.gov.in",
    sourceType: "government",
  },
  {
    name: "Bogamati Picnic and Buddha-Shiva Stupa Baksa",
    nameLocal: "বগামাটি দেৱালয় বাক্সা",
    stateCode: "AS",
    districtName: "Baksa",
    localityName: "Bogamati, Bornadi River, Indo-Bhutan Border, Baksa",
    latitude: 26.7989,
    longitude: 91.5611,
    mainDeity: "Lord Shiva and Buddha",
    deities: ["Lord Shiva", "Buddha"],
    templeType: "Himalayan Foothill Syncretic Shrine",
    tradition: ["Shaivism", "Himalayan Buddhist Harmony"],
    architecture: "Golden Spired Stupa and Shrine Overlooking the Bornadi River Gorge",
    historicalPeriod: "20th Century Sanctuary",
    description: "Nestled in the lush Himalayan foothills on the pristine Bornadi river at the Bhutan border, celebrating peace and interfaith spiritual harmony.",
    officialWebsite: "https://baksa.assam.gov.in/tourist-place/bogamati/",
    sourceRecordId: "AS-BKS-BGM-021",
    sourceName: "Bodoland Territorial Council & Assam Tourism",
    sourceUrl: "https://baksa.assam.gov.in",
    sourceType: "government",
  },
];

export async function importBiharAssamPhase14(dryRun: boolean = false) {
  return processStateBatch(
    "Bihar Tourism & Assam Tourism Boards",
    "https://tourism.bihar.gov.in",
    PHASE14_BIHAR_ASSAM_AUTHORITATIVE_TEMPLES,
    { dryRun }
  );
}
