/**
 * Punjab & Haryana Official Ingestion Importer
 * Authoritative Sources:
 * - Kurukshetra Development Board (https://kurukshetra.gov.in)
 * - Shri Mata Mansa Devi Shrine Board Panchkula (https://mansadevi.org.in)
 * - Haryana Tourism Corporation (https://haryanatourism.gov.in)
 * - Punjab Heritage and Tourism Promotion Board (https://punjabtourism.punjab.gov.in)
 * - District Administrations across Punjab and Haryana
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const PUNJAB_HARYANA_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  // PUNJAB
  {
    name: "Devi Talab Mandir Jalandhar",
    nameLocal: "ਦੇਵੀ ਤਲਾਬ ਮੰਦਰ ਜਲੰਧਰ",
    stateCode: "PB",
    districtName: "Jalandhar",
    localityName: "Old Doaba Chowk, Jalandhar",
    latitude: 31.3361,
    longitude: 75.5806,
    mainDeity: "Maa Tripuramalini (Goddess Durga)",
    deities: ["Maa Tripuramalini", "Lord Shiva (Bhishan Bhairava)"],
    templeType: "51 Maha Shakti Peethas (Left Breast / Stana Peetha)",
    tradition: ["Shaktism", "Classical Hindustani Harivallabh Sangeet"],
    architecture: "Golden Spired Temple Centered in 200-Year-Old Sacred Water Tank",
    historicalPeriod: "Ancient Antiquity / Renowned Harivallabh Sangeet Sammelan (1875 CE)",
    description: "One of the 51 sacred Shakti Peethas where Goddess Sati's left breast fell. Famous worldwide for hosting the annual Harivallabh Sangeet Sammelan, India's oldest festival of classical Hindustani music.",
    officialWebsite: "https://jalandhar.nic.in/tourist-place/devi-talab-mandir/",
    sourceRecordId: "PB-TOUR-JAL-001",
    sourceName: "Devi Talab Mandir Prabandhak Committee & Jalandhar Admin",
    sourceUrl: "https://jalandhar.nic.in/tourist-place/devi-talab-mandir/",
    sourceType: "government",
  },
  {
    name: "Panch Mandir Kapurthala",
    nameLocal: "ਪੰਚ ਮੰਦਰ ਕਪੂਰਥਲਾ",
    stateCode: "PB",
    districtName: "Kapurthala",
    localityName: "City Centre, Kapurthala",
    latitude: 31.3800,
    longitude: 75.3800,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Surya", "Ganesha", "Durga", "Hanuman"],
    templeType: "Historic 1798 CE Five-Spired Royal Shikhara Complex",
    tradition: ["Shaivism", "Smarta Tradition"],
    architecture: "Central Giant Shikhara Surrounded by Four Symmetrical Corner Temples",
    historicalPeriod: "Sardar Fateh Singh Ahluwalia of Kapurthala State (1798 CE)",
    description: "A monumental heritage structure built during the reign of Sardar Fateh Singh Ahluwalia. Built in red sandstone and white plaster, all five spires are visible simultaneously from any approach angle.",
    officialWebsite: "https://kapurthala.nic.in/tourist-place/panch-mandir/",
    sourceRecordId: "PB-TOUR-KAP-002",
    sourceName: "Kapurthala District Administration & Punjab Tourism",
    sourceUrl: "https://kapurthala.nic.in/tourist-place/panch-mandir/",
    sourceType: "government",
  },
  {
    name: "Mata Kamahi Devi Temple Hoshiarpur",
    nameLocal: "ਮਾਤਾ ਕਮਾਹੀ ਦੇਵੀ ਮੰਦਰ ਹੁਸ਼ਿਆਰਪੁਰ",
    stateCode: "PB",
    districtName: "Hoshiarpur",
    localityName: "Kamahi Devi, Dasuya, Hoshiarpur",
    latitude: 31.8167,
    longitude: 75.9000,
    mainDeity: "Maa Kamakshi / Kamahi Devi",
    deities: ["Maa Durga / Kamakshi"],
    templeType: "Ancient Pandava Cave Hill Shrine of Shivalik Hills",
    tradition: ["Shaktism", "Mahabharata Tradition"],
    architecture: "Indigenous Shivalik Hill Temple Housing Ancient Rock Idol",
    historicalPeriod: "Pandava Exile Antiquity / Rebuilt by Raja Sansar Chand",
    description: "Nestled in the Shivalik foothills near Dasuya (ancient Matsya kingdom of the Mahabharata). Believed to have been founded by the Pandavas during their agyatvas (exile in disguise).",
    officialWebsite: "https://hoshiarpur.nic.in/tourist-place/kamahi-devi-temple/",
    sourceRecordId: "PB-TOUR-HOS-003",
    sourceName: "Hoshiarpur District Administration & Punjab Tourism",
    sourceUrl: "https://hoshiarpur.nic.in/tourist-place/kamahi-devi-temple/",
    sourceType: "government",
  },
  {
    name: "Mayser Khana Mandir Bathinda",
    nameLocal: "ਮਾਈਸਰ ਖਾਨਾ ਮੰਦਰ ਬਠਿੰਡਾ",
    stateCode: "PB",
    districtName: "Bathinda",
    localityName: "Maiser Khana, Maur, Bathinda",
    latitude: 30.1333,
    longitude: 75.1167,
    mainDeity: "Maa Jwala Ji (Goddess Durga)",
    deities: ["Maa Jwala Ji"],
    templeType: "Celebrated Malwa Jwala Ji Pilgrimage Shrine",
    tradition: ["Shaktism"],
    architecture: "Traditional Malwa Punjab Temple Complex with Sacred Sarovar",
    historicalPeriod: "1951 CE Reconstruction / Ancient Folk Devotion of Maiser",
    description: "Dedicated to Goddess Jwala Ji, built to honor the legend of a poor devotee named Maiser who was unable to travel to Kangra's Jawalamukhi, whereupon the Mother manifested here for him.",
    officialWebsite: "https://bathinda.nic.in/tourist-place/maiser-khana-temple/",
    sourceRecordId: "PB-TOUR-BAT-004",
    sourceName: "Bathinda District Administration & Maiser Khana Trust",
    sourceUrl: "https://bathinda.nic.in/tourist-place/maiser-khana-temple/",
    sourceType: "government",
  },
  {
    name: "Shri Durgiana Temple Amritsar",
    nameLocal: "ਸ਼੍ਰੀ ਦੁਰਗਿਆਨਾ ਮੰਦਰ ਅੰਮ੍ਰਿਤਸਰ",
    stateCode: "PB",
    districtName: "Amritsar",
    localityName: "Near Hathi Gate, Amritsar",
    latitude: 31.6319,
    longitude: 74.8694,
    mainDeity: "Goddess Durga & Lakshmi Narayana",
    deities: ["Maa Durga", "Lord Lakshmi Narayana", "Bara Hanuman", "Radha Krishna"],
    templeType: "Celebrated Silver Temple of North India",
    tradition: ["Vaishnavism", "Shaktism"],
    architecture: "Majestic Gilded Marble Temple Rising in Center of Sacred Sarovar",
    historicalPeriod: "Guru Shai Mal Kapoor & Pandit Madan Mohan Malaviya (1921 CE)",
    description: "Often called the Silver Temple for its exquisite embossed silver doors, this magnificent shrine rises from the waters of a sacred lake in the holy city of Amritsar. Consecrated by Pandit Madan Mohan Malaviya.",
    officialWebsite: "https://durgianatemple.com",
    sourceRecordId: "PB-DURG-AMR-005",
    sourceName: "Durgiana Temple Management Committee & Amritsar Admin",
    sourceUrl: "https://durgianatemple.com",
    sourceType: "official",
  },
  {
    name: "Bhagwan Valmiki Tirath Sthal Amritsar",
    nameLocal: "ਭਗਵਾਨ ਵਾਲਮੀਕਿ ਤੀਰਥ ਸਥਲ",
    stateCode: "PB",
    districtName: "Amritsar",
    localityName: "Chogawan Road, Amritsar",
    latitude: 31.6789,
    longitude: 74.7433,
    mainDeity: "Maharshi Valmiki",
    deities: ["Maharshi Valmiki", "Maa Sita", "Luv and Kush"],
    templeType: "Ramayana Holy Hermitage & Luv-Kush Birthplace Pilgrimage",
    tradition: ["Ramayana Tradition"],
    architecture: "Grand Gilded Dome Monument Housing 8-Foot Gilded Maharshi Valmiki Statue",
    historicalPeriod: "Treta Yuga Ramayana Era / Monumental Complex Consecrated 2016 CE",
    description: "The revered site of sage Valmiki's ashram where Goddess Sita took shelter after leaving Ayodhya and where twin princes Luv and Kush were born and taught the Ramayana.",
    officialWebsite: "https://amritsar.nic.in/tourist-place/ram-tirth-temple/",
    sourceRecordId: "PB-TOUR-AMR-006",
    sourceName: "Amritsar District Administration & Punjab Heritage Board",
    sourceUrl: "https://amritsar.nic.in/tourist-place/ram-tirth-temple/",
    sourceType: "government",
  },
  {
    name: "Shri Kali Devi Mandir Patiala",
    nameLocal: "ਸ਼੍ਰੀ ਕਾਲੀ ਦੇਵੀ ਮੰਦਰ ਪਟਿਆਲਾ",
    stateCode: "PB",
    districtName: "Patiala",
    localityName: "The Mall Road, Patiala",
    latitude: 30.3347,
    longitude: 76.3986,
    mainDeity: "Maa Mahakali",
    deities: ["Maa Kali (Six-Foot Consecrated Idol)"],
    templeType: "Royal Shakta Pilgrimage of Malwa (National Heritage Monument)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Royal Sikh and Rajput Fusion Temple with Intricate Frescoes and Gold Work",
    historicalPeriod: "Maharaja Bhupinder Singh of Patiala (1936 CE)",
    description: "Built by Maharaja Bhupinder Singh who brought the six-foot black marble idol from Bengal. Devotees visit during Navratri for relief from distress, celebrated for its golden Kalash.",
    officialWebsite: "https://patiala.nic.in/tourist-place/shri-kali-devi-temple/",
    sourceRecordId: "PB-TOUR-PAT-007",
    sourceName: "Patiala District Administration & Punjab Tourism",
    sourceUrl: "https://patiala.nic.in/tourist-place/shri-kali-devi-temple/",
    sourceType: "government",
  },

  // HARYANA
  {
    name: "Agroha Dham Mandir Hisar",
    nameLocal: "अग्रोहा धाम मंदिर हिसार",
    stateCode: "HR",
    districtName: "Hisar",
    localityName: "Agroha, Hisar",
    latitude: 29.3314,
    longitude: 75.6186,
    mainDeity: "Maharaja Agrasen & Goddess Mahalakshmi",
    deities: ["Maharaja Agrasen", "Maa Mahalakshmi", "Maa Saraswati", "Lord Shiva"],
    templeType: "National Cultural & Spiritual Capital of the Agrawal Community",
    tradition: ["Vaishnavism", "Vedic Heritage"],
    architecture: "Grand Three-Tiered Modern Complex with Shakti Sarovar and Ancient Archaeological Mound",
    historicalPeriod: "Founded 1976 CE (Tilakraj Agarwal) / Ancient Capital of Agroha (ASI Mound)",
    description: "The spiritual and cultural headquarters of the worldwide Agrawal community. Divided into three grand sections dedicated to Goddess Mahalakshmi, Maharaja Agrasen, and Goddess Saraswati.",
    officialWebsite: "https://agrohadham.org",
    sourceRecordId: "HR-AGRO-HIS-008",
    sourceName: "Agroha Vikas Trust & Hisar Administration",
    sourceUrl: "https://agrohadham.org",
    sourceType: "official",
  },
  {
    name: "Surajkund Sun Temple Complex Faridabad",
    nameLocal: "सूरजकुंड सूर्य मंदिर फरीदाबाद",
    stateCode: "HR",
    districtName: "Faridabad",
    localityName: "Surajkund, Faridabad",
    latitude: 28.4867,
    longitude: 77.2831,
    mainDeity: "Lord Surya Narayana",
    deities: ["Lord Surya"],
    templeType: "10th-Century Stepped Amphitheater Sun Reservoir (ASI Monument)",
    tradition: ["Saura Tradition", "Vedic Sun Worship"],
    architecture: "Semicircular Stepped Stone Amphitheater Shaped Like the Rising Sun",
    historicalPeriod: "Tomara King Suraj Pal (10th Century CE) / ASI National Monument",
    description: "Built by Tomara dynasty king Suraj Pal in the 10th century. Features an ancient stone stepped reservoir shaped like a rising sun (Suraj Kund) with ruins of a Sun temple.",
    officialWebsite: "https://faridabad.nic.in/tourist-place/surajkund/",
    sourceRecordId: "HR-ASI-FAR-009",
    sourceName: "Archaeological Survey of India & Haryana Tourism",
    sourceUrl: "https://faridabad.nic.in/tourist-place/surajkund/",
    sourceType: "asi",
  },
  {
    name: "Bhimashwari Devi Temple Beri",
    nameLocal: "भीमेश्वरी देवी मंदिर बेरी झज्जर",
    stateCode: "HR",
    districtName: "Jhajjar",
    localityName: "Beri Town, Jhajjar",
    latitude: 28.7019,
    longitude: 76.5814,
    mainDeity: "Maa Bhimashwari (Goddess Durga)",
    deities: ["Maa Durga (Baharli & Andarli Mata)"],
    templeType: "Mahabharata Bhima Consecration Twin Shakta Temple",
    tradition: ["Shaktism", "Mahabharata Tradition"],
    architecture: "Twin Temple Complex (Baharli and Andarli) in Historical Beri",
    historicalPeriod: "Mahabharata Antiquity / Consecrated by Pandava Bhima",
    description: "Legend holds that Pandava prince Bhima brought Goddess Hinglaj to bless the battlefield of Kurukshetra; when he put the idol down at Beri, it became permanently established here. Hosts immense Chaitra and Ashwin melas.",
    officialWebsite: "https://jhajjar.nic.in/tourist-place/bhimashwari-devi-temple-beri/",
    sourceRecordId: "HR-TOUR-JHJ-010",
    sourceName: "Jhajjar District Administration & Bhimashwari Trust",
    sourceUrl: "https://jhajjar.nic.in/tourist-place/bhimashwari-devi-temple-beri/",
    sourceType: "government",
  },
  {
    name: "Kapal Mochan Teerth Bilaspur",
    nameLocal: "कपाल मोचन तीर्थ यमुनानगर",
    stateCode: "HR",
    districtName: "Yamunanagar",
    localityName: "Bilaspur, Yamunanagar",
    latitude: 30.3167,
    longitude: 77.3167,
    mainDeity: "Lord Shiva & Rin Mochan Sarovar",
    deities: ["Lord Shiva", "Lord Brahma", "Guru Gobind Singh"],
    templeType: "Ancient Puranic Sin-Cleansing Sarovar Pilgrimage",
    tradition: ["Shaivism", "Puranic Tradition", "Sikh Heritage"],
    architecture: "Sacred Tri-Sarovar Complex (Kapal Mochan, Rin Mochan, Suraj Kund)",
    historicalPeriod: "Skanda Purana Antiquity / Guru Gobind Singh 1687 CE Visit",
    description: "Revered in the Mahabharata and Skanda Purana where Lord Shiva washed away the sin of severing Brahma's fifth head. Site of a massive Kartik Purnima pilgrimage bath.",
    officialWebsite: "https://yamunanagar.nic.in/tourist-place/kapal-mochan/",
    sourceRecordId: "HR-TOUR-YAM-011",
    sourceName: "Shri Kapal Mochan Shrine Board & Yamunanagar Admin",
    sourceUrl: "https://yamunanagar.nic.in/tourist-place/kapal-mochan/",
    sourceType: "government",
  },
  {
    name: "Baba Ladana Dham / Kapisthala Kaithal",
    nameLocal: "बाबा लदाना धाम / कपिस्थल कैथल",
    stateCode: "HR",
    districtName: "Kaithal",
    localityName: "Baba Ladana, Kaithal",
    latitude: 29.8000,
    longitude: 76.4000,
    mainDeity: "Lord Hanuman (Kapisthala)",
    deities: ["Lord Hanuman", "Baba Rajpuri"],
    templeType: "Ancient Kapisthala Birthplace Shrine of Lord Hanuman",
    tradition: ["Vaishnavism"],
    architecture: "Historic Math & Sarovar Complex in Ancient Kapisthala",
    historicalPeriod: "Treta Yuga Puranic Antiquity / Baba Rajpuri Tapobhumi",
    description: "Kaithal is revered in Hindu tradition as Kapisthala (abode of monkeys), the birthplace of Lord Hanuman. Baba Ladana is a celebrated centuries-old spiritual center and dera of Baba Rajpuri.",
    officialWebsite: "https://kaithal.gov.in/tourist-places/",
    sourceRecordId: "HR-TOUR-KAI-012",
    sourceName: "Kaithal District Administration & Haryana Tourism",
    sourceUrl: "https://kaithal.gov.in/tourist-places/",
    sourceType: "government",
  },
  {
    name: "Karna Tal & Sita Mai Temple Karnal",
    nameLocal: "कर्ण ताल एवं सीता माई मंदिर करनाल",
    stateCode: "HR",
    districtName: "Karnal",
    localityName: "Karnal City & Sitamai Village",
    latitude: 29.6858,
    longitude: 76.9897,
    mainDeity: "Raja Karna / Maa Sita",
    deities: ["Sita Devi", "Raja Karna (Dana-Veer)"],
    templeType: "Ancient Sita Dharti-Samaee Brick Shrine (ASI Protected)",
    tradition: ["Ramayana Tradition", "Mahabharata Heritage"],
    architecture: "Ancient Deeply Carved Terracotta Brick Shikhara / Sacred Tank",
    historicalPeriod: "Ancient Ramayana Era / Gupta Brickwork (ASI Monument)",
    description: "Karnal takes its name from Dana-Veer Karna of the Mahabharata. In Sitamai village nearby stands India's only ancient brick temple marking the spot where Goddess Sita entered Mother Earth.",
    officialWebsite: "https://karnal.gov.in/tourist-place/karna-lake/",
    sourceRecordId: "HR-ASI-KAR-013",
    sourceName: "Archaeological Survey of India & Karnal Administration",
    sourceUrl: "https://karnal.gov.in/tourist-place/karna-lake/",
    sourceType: "asi",
  },
  {
    name: "Bhuteshwar Temple Rani Talab Jind",
    nameLocal: "भूतेश्वर मंदिर रानी तालाब जींद",
    stateCode: "HR",
    districtName: "Jind",
    localityName: "Rani Talab, Jind City",
    latitude: 29.3139,
    longitude: 76.3150,
    mainDeity: "Bhuteshwar Mahadev (Lord Shiva)",
    deities: ["Lord Shiva", "Nandi"],
    templeType: "Golden Temple Architecture Styled Water-Surrounded Shiva Shrine",
    tradition: ["Shaivism"],
    architecture: "Island Shikhara Architecture Situated in Center of Large Circular Tank",
    historicalPeriod: "Raja Raghbir Singh of Jind State (1887 CE)",
    description: "Modeled after the architectural layout of the Golden Temple in Amritsar, Bhuteshwar Temple sits peacefully in the center of the large historical water body Rani Talab in Jind.",
    officialWebsite: "https://jind.gov.in/tourist-place/bhuteshwar-temple/",
    sourceRecordId: "HR-TOUR-JIN-014",
    sourceName: "Jind District Administration & Haryana Tourism",
    sourceUrl: "https://jind.gov.in/tourist-place/bhuteshwar-temple/",
    sourceType: "government",
  },
  {
    name: "Devsar Dham Durga Mandir Bhiwani",
    nameLocal: "देवसर धाम दुर्गा मंदिर भिवानी",
    stateCode: "HR",
    districtName: "Bhiwani",
    localityName: "Devsar, Bhiwani",
    latitude: 28.7500,
    longitude: 76.0833,
    mainDeity: "Maa Durga (Rani Sati / Devsar Vali Mata)",
    deities: ["Maa Durga"],
    templeType: "Prominent Hillock Shakta Shrine of Southern Haryana",
    tradition: ["Shaktism"],
    architecture: "Hillock Temple Complex in Sand Dunes with Marble Shikhara",
    historicalPeriod: "Ancient Local Shakta Heritage (Hundreds of Years Old)",
    description: "Located on a small hillock in Devsar near Bhiwani. Thousands of devotees climb the hill during the bi-annual Chaitra and Ashwin Navratras to offer prayers to Maa Durga.",
    officialWebsite: "https://bhiwani.nic.in/tourist-place/devsar-dham/",
    sourceRecordId: "HR-TOUR-BHI-015",
    sourceName: "Bhiwani District Administration & Devsar Dham Trust",
    sourceUrl: "https://bhiwani.nic.in/tourist-place/devsar-dham/",
    sourceType: "government",
  },
  {
    name: "Shri Mata Mansa Devi Panchkula",
    nameLocal: "श्री माता मनसा देवी पंचकूला",
    stateCode: "HR",
    districtName: "Panchkula",
    localityName: "Bilaspur, Mani Majra Foothills, Panchkula",
    latitude: 30.7183,
    longitude: 76.8497,
    mainDeity: "Maa Mansa Devi (Wish-Fulfilling Goddess)",
    deities: ["Maa Mansa Devi", "Maa Saraswati", "Maa Lakshmi"],
    templeType: "51 Maha Shakti Peethas & Premier Shrine Board of North India",
    tradition: ["Shaktism"],
    architecture: "Panchayati Shikhara Architecture with 38 Exquisite Mughal-Rajput Wall Frescoes",
    historicalPeriod: "Maharaja Gopal Singh of Manimajra (1815 CE)",
    description: "One of the most visited Shakta shrines in Northern India, nestled in the Shivalik foothills of Panchkula. Famed for its wish-fulfilling deity and historic 19th-century wall frescoes.",
    officialWebsite: "https://mansadevi.org.in",
    sourceRecordId: "HR-MANSA-PAN-016",
    sourceName: "Shri Mata Mansa Devi Shrine Board Panchkula",
    sourceUrl: "https://mansadevi.org.in",
    sourceType: "official",
  },
  {
    name: "Brahma Sarovar & Jyotisar Kurukshetra",
    nameLocal: "ब्रह्म सरोवर एवं ज्योतिसर कुरुक्षेत्र",
    stateCode: "HR",
    districtName: "Kurukshetra",
    localityName: "Thanesar, Kurukshetra",
    latitude: 29.9625,
    longitude: 76.8375,
    mainDeity: "Lord Krishna & Brahma",
    deities: ["Lord Krishna (Geetopadesh)", "Lord Brahma", "Sthaneshwar Mahadev"],
    templeType: "Supreme Holy Epic Battlefield & Birthplace of the Bhagavad Gita",
    tradition: ["Vaishnavism", "Mahabharata Heritage", "Vedic Heritage"],
    architecture: "Massive 1.8km x 837m Sacred Tank with Islands, Shrines, and Immortal Banyan Tree",
    historicalPeriod: "Mahabharata Antiquity / Kurukshetra Development Board",
    description: "The hallowed epicenter of the Mahabharata where Lord Krishna delivered the timeless message of the Bhagavad Gita to Arjuna under the Akshay Vat tree at Jyotisar. Brahma Sarovar hosts the grand Solar Eclipse bath.",
    officialWebsite: "https://kurukshetra.gov.in/tourist-place/brahma-sarovar/",
    sourceRecordId: "HR-KDB-KUR-017",
    sourceName: "Kurukshetra Development Board & Haryana Tourism",
    sourceUrl: "https://kurukshetra.gov.in/tourist-place/brahma-sarovar/",
    sourceType: "government",
  },
  {
    name: "Sheetla Mata Mandir Gurugram",
    nameLocal: "शीतला माता मंदिर गुरुग्राम",
    stateCode: "HR",
    districtName: "Gurugram",
    localityName: "Sheetla Mata Road, Gurugram",
    latitude: 28.4736,
    longitude: 77.0267,
    mainDeity: "Maa Sheetla (Kripi, Wife of Guru Dronacharya)",
    deities: ["Maa Sheetla", "Guru Dronacharya"],
    templeType: "Ancient Dronacharya Mahabharata Shrine Board",
    tradition: ["Shaktism", "Mahabharata Tradition"],
    architecture: "Sprawling Modern Shrine Board Complex with Sacred Healing Ponds",
    historicalPeriod: "Mahabharata Antiquity / Jawahar Singh of Bharatpur (18th Century)",
    description: "Dedicated to Mata Sheetla (Kripi), wife of royal preceptor Guru Dronacharya who gave Gurugram (Guru-Grama) its name. Millions visit during Chaitra month seeking protection and blessings for children.",
    officialWebsite: "https://sheetlamatagurugram.org",
    sourceRecordId: "HR-SHEET-GUR-018",
    sourceName: "Shri Mata Sheetla Devi Shrine Board Gurugram",
    sourceUrl: "https://sheetlamatagurugram.org",
    sourceType: "official",
  },
];

export async function importPunjabHaryanaTemples(options = {}) {
  return processStateBatch(
    "Punjab & Haryana Shrine Boards, ASI & Tourism",
    "https://haryanatourism.gov.in",
    PUNJAB_HARYANA_AUTHORITATIVE_TEMPLES,
    options
  );
}

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ PUNJAB & HARYANA TEMPLE INGESTION ENGINE");
  console.log("Source: Punjab & Haryana Shrine Boards, ASI & Tourism");
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await importPunjabHaryanaTemples({
    dryRun: isDryRun,
    parserVersion: "v1.0.0",
  });

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);

