/**
 * Rajasthan Official State Ingestion Importer
 * Authoritative Source: Devasthan Department Government of Rajasthan & Rajasthan Tourism
 * Portal: https://devasthan.rajasthan.gov.in / https://tourism.rajasthan.gov.in
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const RAJASTHAN_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Shrinathji Temple Nathdwara",
    nameLocal: "श्रीनाथजी मंदिर नाथद्वारा",
    stateCode: "RJ",
    districtName: "Rajsamand",
    localityName: "Nathdwara",
    latitude: 24.9333,
    longitude: 73.8167,
    mainDeity: "Shrinathji (Seven-year-old Krishna lifting Govardhan)",
    deities: ["Shrinathji"],
    templeType: "Pushtimarg Haveli & Principal Seat of Vallabhacharya Tradition",
    tradition: ["Vaishnavism", "Pushtimarg"],
    architecture: "Rajasthani Haveli Architecture",
    historicalPeriod: "Mewar Royalty / Maharana Raj Singh (1672 CE)",
    description: "The primary shrine of the Pushtimarg sect, manifesting Krishna lifting Mount Govardhan. The deity was brought from Govardhan to Rajasthan during the reign of Aurangzeb.",
    officialWebsite: "https://nathdwaratemple.org",
    sourceRecordId: "RJ-DEV-RAJ-001",
    sourceName: "Nathdwara Temple Board & Rajasthan Devasthan",
    sourceUrl: "https://nathdwaratemple.org",
    sourceType: "government",
  },
  {
    name: "Jagatpita Brahma Mandir Pushkar",
    nameLocal: "जगतपिता ब्रह्मा मंदिर पुष्कर",
    stateCode: "RJ",
    districtName: "Ajmer",
    localityName: "Pushkar",
    latitude: 26.4883,
    longitude: 74.5558,
    mainDeity: "Lord Brahma (Creator)",
    deities: ["Brahma", "Gayatri"],
    templeType: "Principal Brahma Kshetram",
    tradition: ["Smartha", "Puranic"],
    architecture: "Rajasthani Stone and Marble Shikhara Architecture",
    historicalPeriod: "14th Century CE (Current Structure)",
    description: "One of very few existing temples in the world dedicated to Lord Brahma, situated near sacred Pushkar Lake where Brahma performed yajna.",
    officialWebsite: "https://ajmer.rajasthan.gov.in/pages/tourist-places/pushkar-lake-and-temples",
    sourceRecordId: "RJ-DEV-AJM-002",
    sourceName: "Rajasthan Tourism & Ajmer District Administration",
    sourceUrl: "https://ajmer.rajasthan.gov.in/pages/tourist-places/pushkar-lake-and-temples",
    sourceType: "government",
  },
  {
    name: "Karni Mata Temple Deshnoke",
    nameLocal: "करणी माता मंदिर देशनोक",
    stateCode: "RJ",
    districtName: "Bikaner",
    localityName: "Deshnoke",
    latitude: 27.7914,
    longitude: 73.3411,
    mainDeity: "Karni Mata (Incarnation of Hinglaj / Durga)",
    deities: ["Karni Mata"],
    templeType: "World-Renowned Heritage Shrine (Temple of Rats)",
    tradition: ["Shaktism", "Charan Tradition"],
    architecture: "Mughal & Rajput Marble Architecture with Silver Doors",
    historicalPeriod: "Maharaja Ganga Singh of Bikaner (Early 20th Century)",
    description: "Famous worldwide for approximately 25,000 revered black rats (Kabbas) living within the marble temple precincts. Spotting a white rat is considered extraordinarily auspicious.",
    officialWebsite: "https://bikaner.rajasthan.gov.in/pages/tourist-places/karni-mata-temple",
    sourceRecordId: "RJ-DEV-BIK-003",
    sourceName: "Rajasthan Tourism & Devasthan Department",
    sourceUrl: "https://bikaner.rajasthan.gov.in/pages/tourist-places/karni-mata-temple",
    sourceType: "government",
  },
  {
    name: "Dilwara Jain Temples Mount Abu",
    nameLocal: "दिलवाड़ा जैन मंदिर माउंट आबू",
    stateCode: "RJ",
    districtName: "Sirohi",
    localityName: "Mount Abu",
    latitude: 24.6019,
    longitude: 72.7225,
    mainDeity: "Rishabhanatha & Neminatha (Tirthankaras)",
    deities: ["Adinatha", "Neminatha", "Parshvanatha", "Mahavira"],
    templeType: "World Heritage Marble Sculptural Wonder",
    tradition: ["Jainism", "Svetambara"],
    architecture: "Exquisite Maru-Gurjara White Marble Architecture",
    historicalPeriod: "Chalukya Dynasty (11th-13th Century CE)",
    description: "Located on Rajasthan's only hill station, globally renowned for mind-bogglingly intricate, paper-thin marble filigree ceilings and pillar carvings.",
    officialWebsite: "https://sirohi.rajasthan.gov.in/pages/tourist-places/dilwara-temple",
    sourceRecordId: "RJ-DEV-SIR-004",
    sourceName: "Rajasthan Tourism & Archaeological Registry",
    sourceUrl: "https://sirohi.rajasthan.gov.in/pages/tourist-places/dilwara-temple",
    sourceType: "government",
  },
  {
    name: "Shri Eklingji Temple Kailashpuri",
    nameLocal: "श्री एकलिंग जी मंदिर कैलाशपुरी",
    stateCode: "RJ",
    districtName: "Udaipur",
    localityName: "Kailashpuri",
    latitude: 24.7478,
    longitude: 73.7222,
    mainDeity: "Eklingji (Four-Faced Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Ruling Deity of Mewar Kingdom",
    tradition: ["Shaivism", "Pashupata"],
    architecture: "Double-Storeyed Pillared Mandapa Architecture",
    historicalPeriod: "Bappa Rawal (734 CE)",
    description: "The supreme patron deity of Mewar; the Maharanas of Udaipur ruled not as kings but as the Diwans (prime ministers) on behalf of Eklingji.",
    officialWebsite: "https://udaipur.rajasthan.gov.in/pages/tourist-places/eklingji-temple",
    sourceRecordId: "RJ-DEV-UDA-005",
    sourceName: "Devasthan Department Rajasthan",
    sourceUrl: "https://udaipur.rajasthan.gov.in/pages/tourist-places/eklingji-temple",
    sourceType: "government",
  },
  {
    name: "Khatu Shyam Ji Temple",
    nameLocal: "खाटू श्याम जी मंदिर",
    stateCode: "RJ",
    districtName: "Sikar",
    localityName: "Khatu",
    latitude: 27.3597,
    longitude: 75.3056,
    mainDeity: "Barbareek (Khatu Shyam / Krishna manifestation)",
    deities: ["Shyam Baba"],
    templeType: "Prominent North Indian Pilgrimage Center (Hare Ka Sahara)",
    tradition: ["Vaishnavism"],
    architecture: "Pure White Makrana Marble Architecture with Golden Shikhara",
    historicalPeriod: "Roop Singh Chauhan (1720 CE)",
    description: "One of the most visited pilgrimage destinations in Northern India, dedicated to Barbareek who sacrificed his head before the Kurukshetra War at Krishna's request.",
    officialWebsite: "https://shrishyammandir.com",
    sourceRecordId: "RJ-DEV-SIK-006",
    sourceName: "Shree Shyam Mandir Committee & Rajasthan Devasthan",
    sourceUrl: "https://shrishyammandir.com",
    sourceType: "government",
  },
  {
    name: "Salasar Balaji Mandir",
    nameLocal: "सालासर बालाजी मंदिर",
    stateCode: "RJ",
    districtName: "Churu",
    localityName: "Salasar",
    latitude: 27.7125,
    longitude: 74.8219,
    mainDeity: "Lord Hanuman (Balaji with Beard and Moustache)",
    deities: ["Hanuman"],
    templeType: "Swayambhu Hanuman Kshetra",
    tradition: ["Vaishnavism"],
    architecture: "Rajasthani Stone & Silver Work Architecture",
    historicalPeriod: "Mohan Das Ji Maharaj (1754 CE)",
    description: "A famous pilgrimage center in the Shekhawati region enshrining a swayambhu idol of Lord Hanuman unique for depicting him with a beard and moustache.",
    officialWebsite: "https://salasarbalaji.com",
    sourceRecordId: "RJ-DEV-CHU-007",
    sourceName: "Shree Hanuman Seva Samiti Salasar & Devasthan",
    sourceUrl: "https://salasarbalaji.com",
    sourceType: "government",
  },
  {
    name: "Govind Dev Ji Temple Jaipur",
    nameLocal: "गोविंद देव जी मंदिर जयपुर",
    stateCode: "RJ",
    districtName: "Jaipur",
    localityName: "City Palace Complex, Jaipur",
    latitude: 26.9264,
    longitude: 75.8247,
    mainDeity: "Govind Dev Ji (Lord Krishna)",
    deities: ["Govind Dev Ji", "Radha Rani"],
    templeType: "City Palace Presiding Shrine & Guinness Record Flat Roof",
    tradition: ["Vaishnavism", "Gaudiya Vaishnavism"],
    architecture: "Pillared Satsang Mandap with 119-Foot Single-Span Beam",
    historicalPeriod: "Maharaja Sawai Jai Singh II (1735 CE)",
    description: "Located within the City Palace complex in Jaipur, consecrated by Maharaja Sawai Jai Singh II who brought the original Vrindavan deity to his new capital.",
    officialWebsite: "https://govinddevji.net",
    sourceRecordId: "RJ-DEV-JAI-008",
    sourceName: "Govind Dev Ji Temple Trust & Rajasthan Devasthan",
    sourceUrl: "https://govinddevji.net",
    sourceType: "government",
  },
  {
    name: "Mehandipur Balaji Temple",
    nameLocal: "मेहंदीपुर बालाजी मंदिर",
    stateCode: "RJ",
    districtName: "Dausa",
    localityName: "Mehandipur",
    latitude: 26.9928,
    longitude: 76.7644,
    mainDeity: "Balaji (Lord Hanuman)",
    deities: ["Hanuman", "Pret Raj Sarkar", "Bhairav Ji"],
    templeType: "Spiritual Healing and Exorcism Pilgrimage Shrine",
    tradition: ["Vaishnavism", "Tantric-Vedic Confluence"],
    architecture: "Traditional Rajasthani Temple Structure",
    historicalPeriod: "Circa 1,000 Years Old Tradition",
    description: "Situated in the Aravali hills across Dausa/Karauli border, nationally noted for spiritual healing from afflictions and intense daily aarti rituals.",
    officialWebsite: "https://dausa.rajasthan.gov.in/pages/tourist-places/mehandipur-balaji",
    sourceRecordId: "RJ-DEV-DAU-010",
    sourceName: "Rajasthan Tourism & Devasthan Department",
    sourceUrl: "https://dausa.rajasthan.gov.in/pages/tourist-places/mehandipur-balaji",
    sourceType: "government",
  },
  {
    name: "Rani Sati Dadi Mandir Jhunjhunu",
    nameLocal: "राणी सती दादी मंदिर झुंझुनू",
    stateCode: "RJ",
    districtName: "Jhunjhunu",
    localityName: "Jhunjhunu",
    latitude: 28.1367,
    longitude: 75.4056,
    mainDeity: "Narayani Bai (Rani Sati)",
    deities: ["Rani Sati"],
    templeType: "Prominent Shekhawati Memorial Shrine",
    tradition: ["Folk Kuladevi Tradition", "Smartha"],
    architecture: "Sprawling White Makrana Marble Complex with Frescoes",
    historicalPeriod: "13th Century Historical Origin",
    description: "A colossal white marble temple complex adorned with wall paintings and frescoes, venerated as the principal shrine for devotees of the Marwari diaspora.",
    officialWebsite: "https://jhunjhunu.rajasthan.gov.in/pages/tourist-places/rani-sati-temple",
    sourceRecordId: "RJ-DEV-JHU-011",
    sourceName: "Jhunjhunu District Administration & Devasthan",
    sourceUrl: "https://jhunjhunu.rajasthan.gov.in/pages/tourist-places/rani-sati-temple",
    sourceType: "government",
  },
  {
    name: "Ranakpur Jain Temple",
    nameLocal: "रणकपुर जैन मंदिर",
    stateCode: "RJ",
    districtName: "Pali",
    localityName: "Ranakpur, Desuri",
    latitude: 25.1167,
    longitude: 73.4667,
    mainDeity: "Adinatha (First Jain Tirthankara)",
    deities: ["Adinatha", "Parshvanatha"],
    templeType: "Architectural Wonder of India (Chaumukha Mandir)",
    tradition: ["Jainism", "Svetambara"],
    architecture: "Maru-Gurjara Architecture with 1,444 Distinctly Carved Pillars",
    historicalPeriod: "Dharna Shah & Rana Kumbha (1437 CE)",
    description: "Nestled in a secluded valley of the Aravalli range in Pali district, famed worldwide for 1,444 intricately sculpted marble pillars, no two of which are identical.",
    officialWebsite: "https://pali.rajasthan.gov.in/pages/tourist-places/ranakpur-temple",
    sourceRecordId: "RJ-DEV-PAL-012",
    sourceName: "Rajasthan Tourism & Anandji Kalyanji Pedhi",
    sourceUrl: "https://pali.rajasthan.gov.in/pages/tourist-places/ranakpur-temple",
    sourceType: "government",
  },
  {
    name: "Tripura Sundari Temple",
    nameLocal: "त्रिपुरा सुंदरी मंदिर बांसवाड़ा",
    stateCode: "RJ",
    districtName: "Banswara",
    localityName: "Umrai (Talwara)",
    latitude: 23.5358,
    longitude: 74.3167,
    mainDeity: "Tripura Sundari (Turtai Mata)",
    deities: ["Tripura Sundari"],
    templeType: "Ancient Shakta Peetha of Southern Rajasthan (Vagad)",
    tradition: ["Shaktism", "Sri Vidya"],
    architecture: "Nagara Style Stone Sanctum with Black Stone Deity",
    historicalPeriod: "Kanishka / Kushan Era Inscription (Ancient)",
    description: "Located near Banswara, enshrining an 18-armed black stone idol of Goddess Tripura Sundari seated on a Sri Chakra, revered by kings and pilgrims across Gujarat and Rajasthan.",
    officialWebsite: "https://banswara.rajasthan.gov.in/pages/tourist-places/tripura-sundari-temple",
    sourceRecordId: "RJ-DEV-BAN-014",
    sourceName: "Rajasthan Devasthan Department",
    sourceUrl: "https://banswara.rajasthan.gov.in/pages/tourist-places/tripura-sundari-temple",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ RAJASTHAN TEMPLE INGESTION ENGINE");
  console.log(`Source: Devasthan Department Rajasthan & Tourism`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Devasthan Department Rajasthan & Rajasthan Tourism",
    "https://devasthan.rajasthan.gov.in",
    RAJASTHAN_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
