/**
 * Tamil Nadu Official State Ingestion Importer
 * Authoritative Source: Tamil Nadu Hindu Religious & Charitable Endowments (HR&CE) & TN Tourism
 * Portal: https://hrce.tn.gov.in / https://www.tamilnadutourism.tn.gov.in
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const TN_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Sri Ranganathaswamy Temple",
    nameLocal: "ஸ்ரீ ரங்கநாதசுவாமி திருக்கோயில்",
    stateCode: "TN",
    districtName: "Tiruchirappalli",
    localityName: "Srirangam",
    latitude: 10.8624,
    longitude: 78.6901,
    mainDeity: "Lord Ranganatha (Maha Vishnu)",
    deities: ["Lord Ranganatha", "Goddess Ranganayaki"],
    templeType: "Divya Desam",
    tradition: ["Vaishnavism", "Thenkalai"],
    architecture: "Dravidian Architecture",
    historicalPeriod: "Chola & Vijayanagara Era",
    description: "The premier of the 108 Divya Desams, Srirangam is one of the largest functioning religious complexes in the world, enclosed by seven concentric prakaras with 21 grand gopurams.",
    officialWebsite: "https://srirangam.org",
    sourceRecordId: "TN-HRCE-SRI-001",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://hrce.tn.gov.in/hrcehome/temple_det.php?temple_id=14138",
    sourceType: "government",
  },
  {
    name: "Brihadisvara Temple",
    nameLocal: "தஞ்சைப் பெருவுடையார் கோயில்",
    stateCode: "TN",
    districtName: "Thanjavur",
    localityName: "Thanjavur",
    latitude: 10.7828,
    longitude: 79.1318,
    mainDeity: "Peruvudaiyar (Lord Shiva)",
    deities: ["Peruvudaiyar", "Periyanayaki"],
    templeType: "UNESCO World Heritage Site",
    tradition: ["Shaivism"],
    architecture: "Chola Dravidian Architecture",
    historicalPeriod: "Chola Empire (1010 CE)",
    description: "Built by Emperor Raja Raja Chola I in 1010 CE, the Big Temple of Thanjavur is a masterpiece of Dravidian architecture featuring a 66-meter high vimana carved from monolithic granite.",
    officialWebsite: "https://thanjavur.nic.in/tourist-place/brihadeeswarar-temple/",
    sourceRecordId: "ASI-TN-N-TN-C1",
    sourceName: "Archaeological Survey of India & TN Tourism",
    sourceUrl: "https://asi.nic.in/world-heritage-sites-great-living-chola-temples/",
    sourceType: "government",
  },
  {
    name: "Ramanathaswamy Temple",
    nameLocal: "இராமேஸ்வரம் இராமநாதசுவாமி கோயில்",
    stateCode: "TN",
    districtName: "Ramanathapuram",
    localityName: "Rameswaram",
    latitude: 9.2881,
    longitude: 79.3174,
    mainDeity: "Ramanathaswamy (Lord Shiva)",
    deities: ["Ramanathaswamy", "Parvathavardhini"],
    templeType: "Jyotirlinga & Char Dham",
    tradition: ["Shaivism", "Smartha"],
    architecture: "Dravidian Architecture",
    historicalPeriod: "Pandya & Jaffna Kings",
    description: "One of the twelve sacred Jyotirlinga shrines and the southern point of the Char Dham pilgrimage. Renowned for having the longest temple corridor in the world with over 1,200 carved pillars.",
    officialWebsite: "https://rameswaramtemple.tnhrce.in",
    sourceRecordId: "TN-HRCE-RAM-002",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://rameswaramtemple.tnhrce.in",
    sourceType: "government",
  },
  {
    name: "Ekambareswarar Temple",
    nameLocal: "ஏகாம்பரேஸ்வரர் கோயில்",
    stateCode: "TN",
    districtName: "Kanchipuram",
    localityName: "Kanchipuram",
    latitude: 12.8475,
    longitude: 79.6997,
    mainDeity: "Ekambareswarar (Earth Lingam)",
    deities: ["Lord Shiva", "Goddess Kamakshi"],
    templeType: "Pancha Bhoota Stalam (Earth)",
    tradition: ["Shaivism"],
    architecture: "Dravidian Architecture",
    historicalPeriod: "Pallava & Vijayanagara Era",
    description: "Represents the element Earth (Prithvi) among the five Pancha Bhoota Stalam shrines. Its 59-meter southern gopuram was erected by Vijayanagara Emperor Krishnadevaraya.",
    officialWebsite: "https://kancheepuram.nic.in/tourism/ekambaranathar-temple/",
    sourceRecordId: "TN-HRCE-KAN-003",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://kancheepuram.nic.in/tourism/ekambaranathar-temple/",
    sourceType: "government",
  },
  {
    name: "Thillai Nataraja Temple",
    nameLocal: "சிதம்பரம் தில்லை நடராஜர் கோயில்",
    stateCode: "TN",
    districtName: "Cuddalore",
    localityName: "Chidambaram",
    latitude: 11.3992,
    longitude: 79.6934,
    mainDeity: "Lord Nataraja (Cosmic Dancer)",
    deities: ["Nataraja", "Sivakami Amman", "Govindaraja Perumal"],
    templeType: "Pancha Bhoota Stalam (Akasha)",
    tradition: ["Shaivism"],
    architecture: "Dravidian Architecture",
    historicalPeriod: "Chola & Pandya Era",
    description: "Represents the element Sky / Space (Akasha) in the Pancha Bhoota circuit, famous for the Chidambara Rahasya and its gold-plated hall where Shiva performs the Anandatandava.",
    officialWebsite: "https://cuddalore.nic.in/tourist-place/chidambaram-natarajar-temple/",
    sourceRecordId: "TN-HRCE-CUD-004",
    sourceName: "Tamil Nadu Tourism & District Administration",
    sourceUrl: "https://cuddalore.nic.in/tourist-place/chidambaram-natarajar-temple/",
    sourceType: "government",
  },
  {
    name: "Arunachaleswarar Temple",
    nameLocal: "திருவண்ணாமலை அருணாசலேஸ்வரர் கோயில்",
    stateCode: "TN",
    districtName: "Tiruvannamalai",
    localityName: "Tiruvannamalai",
    latitude: 12.2307,
    longitude: 79.0677,
    mainDeity: "Arunachaleswarar (Fire Lingam)",
    deities: ["Arunachaleswarar", "Unnamalai Amman"],
    templeType: "Pancha Bhoota Stalam (Fire)",
    tradition: ["Shaivism"],
    architecture: "Dravidian Architecture",
    historicalPeriod: "Chola, Hoysala & Vijayanagara Era",
    description: "Situated at the base of the sacred Arunachala hill representing the element Fire (Agni). Famous for the annual Karthigai Deepam festival where a beacon is lit atop the mountain.",
    officialWebsite: "https://tiruvannamalai.nic.in/tourist-place/arunachaleswarar-temple/",
    sourceRecordId: "TN-HRCE-TVM-005",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://tiruvannamalai.nic.in/tourist-place/arunachaleswarar-temple/",
    sourceType: "government",
  },
  {
    name: "Meenakshi Sundareswarar Temple",
    nameLocal: "மீனாட்சி சுந்தரேஸ்வரர் திருக்கோயில்",
    stateCode: "TN",
    districtName: "Madurai",
    localityName: "Madurai",
    latitude: 9.9195,
    longitude: 78.1193,
    mainDeity: "Goddess Meenakshi & Sundareswarar",
    deities: ["Meenakshi Amman", "Sundareswarar (Shiva)"],
    templeType: "Maha Shakti Peetha & Historic Shrine",
    tradition: ["Shaivism", "Shaktism"],
    architecture: "Dravidian Architecture with 14 Towering Gopurams",
    historicalPeriod: "Pandya Dynasty (Rebuilt 16th-17th Century Nayakas)",
    description: "Revered historic temple dedicated to Goddess Meenakshi and Lord Sundareswarar at the heart of Madurai. Renowned for its Hall of Thousand Pillars and celestial wedding festival (Chithirai Thiruvizha).",
    officialWebsite: "https://maduraimeenakshi.hrce.tn.gov.in",
    sourceRecordId: "TN-HRCE-MAD-006",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://maduraimeenakshi.hrce.tn.gov.in",
    sourceType: "government",
  },
  {
    name: "Shore Temple Mamallapuram",
    nameLocal: "மாமல்லபுரம் கடற்கரைக் கோயில்",
    stateCode: "TN",
    districtName: "Chengalpattu",
    localityName: "Mamallapuram",
    latitude: 12.6169,
    longitude: 80.1983,
    mainDeity: "Lord Shiva & Seshasayi Vishnu",
    deities: ["Shiva", "Vishnu"],
    templeType: "UNESCO World Heritage Site",
    tradition: ["Shaivism", "Vaishnavism"],
    architecture: "Pallava Structural Stone Architecture",
    historicalPeriod: "Narasimhavarman II / Rajasimha (700–728 CE)",
    description: "One of the earliest structural stone temples of Southern India, overlooking the Bay of Bengal at Mahabalipuram, built during the Pallava dynasty.",
    officialWebsite: "https://chengalpattu.nic.in/tourist-place/shore-temple/",
    sourceRecordId: "ASI-TN-N-TN-C2",
    sourceName: "Archaeological Survey of India & TN Tourism",
    sourceUrl: "https://asi.nic.in/monuments-mamallapuram/",
    sourceType: "government",
  },
  {
    name: "Dhandayuthapani Swamy Temple Palani",
    nameLocal: "பழனி தண்டாயுதபாணி சுவாமி திருக்கோயில்",
    stateCode: "TN",
    districtName: "Dindigul",
    localityName: "Palani",
    latitude: 10.4439,
    longitude: 77.5208,
    mainDeity: "Lord Murugan (Dhandayuthapani)",
    deities: ["Murugan"],
    templeType: "Arupadai Veedu (Third Abode)",
    tradition: ["Kaumaram", "Shaivism"],
    architecture: "Dravidian Hill Temple Architecture",
    historicalPeriod: "Chera Dynasty & Sage Bogar",
    description: "Perched atop Sivagiri hill in Palani, consecrated with an idol crafted by Siddha Bogar from Navapashanam (nine medicinal poisons). One of the most visited pilgrimage sites in South India.",
    officialWebsite: "https://palanimurugan.hrce.tn.gov.in",
    sourceRecordId: "TN-HRCE-DIN-007",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://palanimurugan.hrce.tn.gov.in",
    sourceType: "government",
  },
  {
    name: "Subramaniya Swamy Temple Tiruchendur",
    nameLocal: "திருச்செந்தூர் சுப்பிரமணிய சுவாமி திருக்கோயில்",
    stateCode: "TN",
    districtName: "Thoothukudi",
    localityName: "Tiruchendur",
    latitude: 8.4965,
    longitude: 78.1287,
    mainDeity: "Subramaniya Swamy (Murugan)",
    deities: ["Lord Murugan", "Valli", "Deivayanai"],
    templeType: "Arupadai Veedu (Second Abode)",
    tradition: ["Kaumaram"],
    architecture: "Dravidian Coastal Architecture with 137ft Raja Gopuram",
    historicalPeriod: "Pandya Dynasty & 17th Century Additions",
    description: "The only seashore abode among Murugan's six sacred encampments (Arupadai Veedu), celebrating the divine vanquishing of demon Surapadman during Soorasamharam.",
    officialWebsite: "https://tiruchendurmurugan.hrce.tn.gov.in",
    sourceRecordId: "TN-HRCE-THO-008",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://tiruchendurmurugan.hrce.tn.gov.in",
    sourceType: "government",
  },
  {
    name: "Srivilliputhur Andal Temple",
    nameLocal: "ஸ்ரீவில்லிபுத்தூர் ஆண்டாள் திருக்கோயில்",
    stateCode: "TN",
    districtName: "Virudhunagar",
    localityName: "Srivilliputhur",
    latitude: 9.5103,
    longitude: 77.6322,
    mainDeity: "Goddess Andal & Rangamannar",
    deities: ["Andal", "Rangamannar", "Vatapatrasayee"],
    templeType: "Divya Desam & State Emblem Temple",
    tradition: ["Vaishnavism", "Sri Vaishnava"],
    architecture: "Dravidian Architecture with 11-Tiered Gopuram",
    historicalPeriod: "Pandya & Nayaka Dynasties",
    description: "The birthplace of the sacred Vaishnavite poet-saint Andal and her foster father Periyalwar. Its towering 59-meter Rajagopuram is the official emblem of the Government of Tamil Nadu.",
    officialWebsite: "https://srivilliputhurandal.hrce.tn.gov.in",
    sourceRecordId: "TN-HRCE-VIR-009",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://srivilliputhurandal.hrce.tn.gov.in",
    sourceType: "government",
  },
  {
    name: "Kanchi Kamakshi Amman Temple",
    nameLocal: "காஞ்சி காமாட்சி அம்மன் கோயில்",
    stateCode: "TN",
    districtName: "Kanchipuram",
    localityName: "Kanchipuram",
    latitude: 12.8407,
    longitude: 79.7032,
    mainDeity: "Goddess Kamakshi (Tripura Sundari)",
    deities: ["Kamakshi Amman"],
    templeType: "Maha Shakti Peetha (Nabhi Kshetra)",
    tradition: ["Shaktism", "Smartha"],
    architecture: "Dravidian Architecture with Golden Vimana",
    historicalPeriod: "Pallava & Chola Period (Sri Chakra consecrated by Adi Shankara)",
    description: "One of the preeminent Shakti shrines in India where Adi Shankara established the Sri Chakra. The presiding deity sits in the Padmasana posture radiating transcendent compassion.",
    officialWebsite: "https://kanchikamakshi.com",
    sourceRecordId: "TN-HRCE-KAN-010",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://kanchikamakshi.com",
    sourceType: "government",
  },
  {
    name: "Jambukeswarar Temple Thiruvanaikaval",
    nameLocal: "திருவானைக்காவல் ஜம்புகேஸ்வரர் திருக்கோயில்",
    stateCode: "TN",
    districtName: "Tiruchirappalli",
    localityName: "Thiruvanaikaval",
    latitude: 10.8533,
    longitude: 78.7056,
    mainDeity: "Jambukeswarar (Water Lingam)",
    deities: ["Jambukeswarar", "Akilandeswari"],
    templeType: "Pancha Bhoota Stalam (Water)",
    tradition: ["Shaivism"],
    architecture: "Chola Dravidian Architecture",
    historicalPeriod: "Early Chola King Kocengannan (1800 Years Old)",
    description: "Represents the element Water (Appu) among the Pancha Bhoota Stalams. An underground water spring continuously submerges the sanctum sanctorum lingam.",
    officialWebsite: "https://thiruvanaikavaljambukeswarar.hrce.tn.gov.in",
    sourceRecordId: "TN-HRCE-TIR-011",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://thiruvanaikavaljambukeswarar.hrce.tn.gov.in",
    sourceType: "government",
  },
  {
    name: "Swami Nellaiappar Temple",
    nameLocal: "திருநெல்வேலி நெல்லையப்பர் திருக்கோயில்",
    stateCode: "TN",
    districtName: "Tirunelveli",
    localityName: "Tirunelveli",
    latitude: 8.7289,
    longitude: 77.6886,
    mainDeity: "Nellaiappar (Lord Shiva)",
    deities: ["Nellaiappar", "Kanthimathi Amman"],
    templeType: "Pancha Sabhai (Thamira Sabhai / Copper Hall)",
    tradition: ["Shaivism"],
    architecture: "Dravidian Architecture with Musical Pillars",
    historicalPeriod: "Pandya Dynasty (7th Century CE)",
    description: "Spread over 14.5 acres, famous for the Thamira Sabhai (Copper Hall of Dance) and wondrous musical pillars that produce musical notes when struck.",
    officialWebsite: "https://tirunelvelinellaiappar.hrce.tn.gov.in",
    sourceRecordId: "TN-HRCE-TIN-012",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://tirunelvelinellaiappar.hrce.tn.gov.in",
    sourceType: "government",
  },
  {
    name: "Karpaka Vinayakar Temple Pillayarpatti",
    nameLocal: "பிள்ளையார்பட்டி கற்பக விநாயகர் கோயில்",
    stateCode: "TN",
    districtName: "Sivaganga",
    localityName: "Pillayarpatti",
    latitude: 10.1206,
    longitude: 78.6756,
    mainDeity: "Karpaka Vinayakar",
    deities: ["Lord Ganesha"],
    templeType: "Rock-Cut Cave Temple",
    tradition: ["Ganapatya", "Shaivism"],
    architecture: "Early Pandya Rock-Cut Cave Architecture",
    historicalPeriod: "Early Pandya Dynasty (4th Century CE)",
    description: "Ancient rock-cut temple dedicated to Lord Ganesha carved into a hillock, featuring a 6-foot monolithic deity with trunk turned towards the right (Valampuri).",
    officialWebsite: "https://pillayarpattikarpagavinayagar.org",
    sourceRecordId: "TN-HRCE-SIV-013",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://pillayarpattikarpagavinayagar.org",
    sourceType: "government",
  },
  {
    name: "Namakkal Anjaneyar Temple",
    nameLocal: "நாமக்கல் ஆஞ்சநேயர் கோயில்",
    stateCode: "TN",
    districtName: "Namakkal",
    localityName: "Namakkal",
    latitude: 11.2215,
    longitude: 78.1648,
    mainDeity: "Sri Anjaneyar (Lord Hanuman)",
    deities: ["Anjaneyar"],
    templeType: "Rock-Fort Monolith Shrine",
    tradition: ["Vaishnavism"],
    architecture: "Open-Sky Dravidian Monolithic Style",
    historicalPeriod: "Adiyaman / Pallava Dynasty (8th Century CE)",
    description: "Enshrines a magnificent 18-foot monolithic statue of Lord Hanuman standing under open sky facing Lord Narasimha carved in the adjacent rock-cut hill cave.",
    officialWebsite: "https://namakkalanjaneyar.hrce.tn.gov.in",
    sourceRecordId: "TN-HRCE-NAM-014",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://namakkalanjaneyar.hrce.tn.gov.in",
    sourceType: "government",
  },
  {
    name: "Bhagavathy Amman Temple Kanyakumari",
    nameLocal: "கன்னியாகுமரி பகவதி அம்மன் கோயில்",
    stateCode: "TN",
    districtName: "Kanniyakumari",
    localityName: "Kanyakumari",
    latitude: 8.0780,
    longitude: 77.5550,
    mainDeity: "Goddess Kanya Kumari",
    deities: ["Kanya Kumari Amman"],
    templeType: "Shakti Peetha (Southern Confluence Shrine)",
    tradition: ["Shaktism"],
    architecture: "Kerala & Dravidian Confluence Architecture",
    historicalPeriod: "Pre-Sangam Era (Over 3,000 Years Old)",
    description: "Situated at the southernmost tip of mainland India where the Arabian Sea, Indian Ocean, and Bay of Bengal converge. Famous for the goddess's diamond nose ring shining out to sea.",
    officialWebsite: "https://kanyakumaribhagavathy.hrce.tn.gov.in",
    sourceRecordId: "TN-HRCE-KAN-015",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://kanyakumaribhagavathy.hrce.tn.gov.in",
    sourceType: "government",
  },
  {
    name: "Bannari Amman Temple",
    nameLocal: "பண்ணாரி அம்மன் திருக்கோயில்",
    stateCode: "TN",
    districtName: "Erode",
    localityName: "Bannari",
    latitude: 11.5542,
    longitude: 77.1278,
    mainDeity: "Goddess Bannari Amman (Mariamman)",
    deities: ["Bannari Amman"],
    templeType: "Prominent Forest Shrine",
    tradition: ["Shaktism", "Village Traditions"],
    architecture: "Dravidian Temple Architecture",
    historicalPeriod: "Circa 300 Years Old",
    description: "Located near the Sathyamangalam Tiger Reserve in the Western Ghats, renowned for the massive annual Kundam fire-walking festival where lakhs of pilgrims walk on embers.",
    officialWebsite: "https://bannariammantemple.org",
    sourceRecordId: "TN-HRCE-ERO-016",
    sourceName: "Tamil Nadu HR&CE Department",
    sourceUrl: "https://bannariammantemple.org",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ TAMIL NADU TEMPLE INGESTION ENGINE");
  console.log(`Source: TN HR&CE Department & Tourism`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Tamil Nadu HR&CE Department",
    "https://hrce.tn.gov.in",
    TN_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
