/**
 * Telangana Official State Ingestion Importer
 * Authoritative Sources:
 * - Telangana Endowments Department (https://tggovendowments.gov.in)
 * - Yadagirigutta Temple Development Authority (https://yadadritemple.telangana.gov.in)
 * - Telangana State Tourism Development Corporation (https://tourism.telangana.gov.in)
 * - Archaeological Survey of India (Hyderabad Circle) (https://asihyd.encircle.in)
 * - District Administrations of Telangana
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const TELANGANA_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Yadadri Sri Lakshmi Narasimha Swamy Temple",
    nameLocal: "యాదాద్రి శ్రీ లక్ష్మీ నరసింహ స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Yadadri Bhuvanagiri",
    localityName: "Yadagirigutta Hill",
    latitude: 17.5886,
    longitude: 78.9392,
    mainDeity: "Lord Narasimha Swamy (Pancha Narasimha Kshetram)",
    deities: ["Jwala Narasimha", "Yogananda Narasimha", "Gandabherunda Narasimha", "Lakshmi Devi"],
    templeType: "Supreme Monolithic Krishna Shila Temple of Telangana",
    tradition: ["Vaishnavism", "Sri Vaishnava Pancharatra Agama"],
    architecture: "Spectacular All-Black-Granite (Krishna Shila) Dravidian-Kakatiya Architectural Marvel",
    historicalPeriod: "Ancient Sage Yadarishi Legend / Monumental Reconstruction 2022 CE",
    description: "The spiritual heart of Telangana, situated atop Yadagirigutta hill. Completely reconstructed using 250,000 tonnes of sculpted black granite without cement, standing as a modern architectural wonder.",
    officialWebsite: "https://yadadritemple.telangana.gov.in",
    sourceRecordId: "TS-YTDA-YAD-001",
    sourceName: "Yadagirigutta Temple Development Authority & Telangana Endowments",
    sourceUrl: "https://yadadritemple.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Ramappa Temple Rudreshwara",
    nameLocal: "రామప్ప దేవాలయం (రుద్రేశ్వర స్వామి)",
    stateCode: "TS",
    districtName: "Mulugu",
    localityName: "Palampet Village, Mulugu",
    latitude: 18.2611,
    longitude: 79.9431,
    mainDeity: "Ramalingeswara (Lord Shiva)",
    deities: ["Lord Shiva", "Nandi", "Madanikas"],
    templeType: "UNESCO World Heritage Site & Kakatiya Floating Brick Masterpiece",
    tradition: ["Shaivism"],
    architecture: "Kakatiya Vesara Architecture with Floating Bricks and Sandbox Foundation",
    historicalPeriod: "General Recharla Rudra / Kakatiya King Ganapati Deva / 1213 CE",
    description: "Inscribed as a UNESCO World Heritage site, named after its master sculptor Ramappa. Built with lightweight floating bricks, sandbox anti-seismic foundation, and exquisitely polished black basalt dancers.",
    officialWebsite: "https://mulugu.telangana.gov.in/tourist-place/ramappa-temple/",
    sourceRecordId: "TS-UNESCO-MUL-002",
    sourceName: "Archaeological Survey of India & UNESCO World Heritage",
    sourceUrl: "https://tourism.telangana.gov.in",
    sourceType: "asi",
  },
  {
    name: "Thousand Pillar Temple Hanamkonda",
    nameLocal: "వేయి స్తంభాల గుడి హనుమకొండ",
    stateCode: "TS",
    districtName: "Hanumakonda",
    localityName: "Hanamkonda, Warangal Urban",
    latitude: 18.0061,
    longitude: 79.5750,
    mainDeity: "Trikuta Temple (Shiva, Vishnu, Surya)",
    deities: ["Rudreshwara (Shiva)", "Vasudeva (Vishnu)", "Surya", "Monolithic Black Nandi"],
    templeType: "12th-Century Kakatiya Trikutalaya (ASI Monument)",
    tradition: ["Shaivism", "Smartha Trikuta"],
    architecture: "Kakatiya Star-Shaped Triple Sanctum with 1000 Interlocking Pillars",
    historicalPeriod: "Kakatiya King Rudra Deva / 1163 CE",
    description: "One of the crowning glories of Kakatiya architecture protected by ASI, built in star-shaped trikuta layout with a magnificent monolithic black basalt Nandi bull.",
    officialWebsite: "https://hanumakonda.telangana.gov.in/tourist-place/thousand-pillar-temple/",
    sourceRecordId: "TS-ASI-HAN-003",
    sourceName: "Archaeological Survey of India Hyderabad Circle",
    sourceUrl: "https://hanumakonda.telangana.gov.in",
    sourceType: "asi",
  },
  {
    name: "Bhadrachalam Sri Sita Ramachandra Swamy Temple",
    nameLocal: "భద్రాచలం శ్రీ సీతా రామచంద్రస్వామి వారి దేవస్థానం",
    stateCode: "TS",
    districtName: "Bhadradri Kothagudem",
    localityName: "Bhadrachalam, Godavari River Bank",
    latitude: 17.6689,
    longitude: 80.8936,
    mainDeity: "Lord Rama (Vaikuntha Rama with Shankha & Chakra)",
    deities: ["Sri Rama", "Mata Sita", "Lakshmana", "Bhakta Ramadasu Sthal"],
    templeType: "Supreme Holy Abode of Sri Rama on Godavari",
    tradition: ["Vaishnavism", "Sri Vaishnava Agama"],
    architecture: "Dravidian Temple Complex with Historic Gold Ornaments",
    historicalPeriod: "Kancherla Gopanna (Bhakta Ramadasu) / 17th Century CE",
    description: "The holiest Sri Rama pilgrimage on the banks of Godavari, where Sri Rama appeared to sage Bhadra. Built by Bhakta Ramadasu, celebrated worldwide for Sri Rama Navami Kalyanam.",
    officialWebsite: "https://bhadrachalam.org",
    sourceRecordId: "TS-TOUR-BHA-004",
    sourceName: "Bhadrachalam Devasthanam & Telangana Endowments",
    sourceUrl: "https://bhadrachalam.org",
    sourceType: "official",
  },
  {
    name: "Sri Raja Rajeshwara Swamy Temple Vemulawada",
    nameLocal: "శ్రీ రాజరాజేశ్వర స్వామి దేవస్థానం వేములవాడ",
    stateCode: "TS",
    districtName: "Rajanna Sircilla",
    localityName: "Vemulawada Town",
    latitude: 18.4689,
    longitude: 78.8683,
    mainDeity: "Sri Raja Rajeshwara Swamy (Rajanna / Lord Shiva)",
    deities: ["Lord Shiva (Rajanna)", "Sri Raja Rajeshwari Devi", "Lord Ganesha"],
    templeType: "Dakshina Kasi of the Deccan (Kode Mokku Tradition)",
    tradition: ["Shaivism"],
    architecture: "Chalukya-Kakatiya Fusion Architecture with Dharmagundam Holy Tank",
    historicalPeriod: "Vemulawada Chalukyas / 750-973 CE",
    description: "Renowned as 'Dakshina Kasi', famous for the unique 'Kode Mokku' ritual where devotees tie a sacred bull calf around the sanctum for fulfillment of vows.",
    officialWebsite: "https://vemulawadatemple.telangana.gov.in",
    sourceRecordId: "TS-ENDOW-RAJ-005",
    sourceName: "Sri Raja Rajeshwara Devasthanam & Telangana Endowments",
    sourceUrl: "https://tggovendowments.gov.in",
    sourceType: "official",
  },
  {
    name: "Gnana Saraswati Temple Basar",
    nameLocal: "జ్ఞాన సరస్వతి దేవాలయం బాసర",
    stateCode: "TS",
    districtName: "Nirmal",
    localityName: "Basar, Godavari River Bank",
    latitude: 18.8778,
    longitude: 77.9542,
    mainDeity: "Goddess Saraswati",
    deities: ["Gnana Saraswati", "Maha Lakshmi", "Maha Kali (Trishakti)"],
    templeType: "Pan-India Supreme Seat of Learning (Aksharabhyasam Kshetra)",
    tradition: ["Shaktism", "Vedic Sage Vyasa Tradition"],
    architecture: "Ancient Dravidian Temple on Godavari River Bank",
    historicalPeriod: "Maharshi Veda Vyasa Ashram Tradition",
    description: "One of only two prominent temples dedicated to Goddess Saraswati in India, established by Sage Veda Vyasa on the banks of Godavari, where lakhs of children perform their Aksharabhyasam.",
    officialWebsite: "https://basaratemple.org",
    sourceRecordId: "TS-TOUR-NIR-006",
    sourceName: "Sri Gnana Saraswati Devasthanam & Telangana Endowments",
    sourceUrl: "https://basaratemple.org",
    sourceType: "official",
  },
  {
    name: "Alampur Jogulamba & Navabrahma Temples",
    nameLocal: "అలంపూర్ జోగులాంబ నవబ్రహ్మ దేవాలయాలు",
    stateCode: "TS",
    districtName: "Gadwal Jogulamba",
    localityName: "Alampur, Tungabhadra-Krishna Sangam",
    latitude: 15.8828,
    longitude: 78.1328,
    mainDeity: "Goddess Jogulamba & Bala Brahmeswara Swamy",
    deities: ["Maa Jogulamba (5th Shakti Peetha)", "9 Brahma Temples (Navabrahma)"],
    templeType: "5th Maha Shakti Peetha (Upper Teeth Peetha) & Western Chalukya Group",
    tradition: ["Shaktism", "Shaivism", "Western Chalukyan"],
    architecture: "7th-Century Badami Chalukyan Sandstone Nagara Architecture (ASI Monument)",
    historicalPeriod: "Badami Chalukya Kings / 7th Century CE",
    description: "The 5th Maha Shakti Peetha where Sati's upper teeth fell, complemented by the remarkable cluster of nine early Chalukyan Navabrahma temples protected by the ASI.",
    officialWebsite: "https://jogulambatemple.telangana.gov.in",
    sourceRecordId: "TS-ASI-GAD-007",
    sourceName: "Archaeological Survey of India & Alampur Devasthanam",
    sourceUrl: "https://tggovendowments.gov.in",
    sourceType: "asi",
  },
  {
    name: "Sri Lakshmi Narasimha Swamy Temple Dharmapuri",
    nameLocal: "శ్రీ లక్ష్మీ నరసింహ స్వామి దేవాలయం ధర్మపురి",
    stateCode: "TS",
    districtName: "Jagtial",
    localityName: "Dharmapuri, Godavari River Bank",
    latitude: 18.9500,
    longitude: 79.0917,
    mainDeity: "Lord Narasimha Swamy (Yoga Narasimha)",
    deities: ["Yoga Narasimha", "Ugra Narasimha", "Brahma Temple", "Yama Temple"],
    templeType: "Teertharaja on Holy Godavari River",
    tradition: ["Vaishnavism"],
    architecture: "Medieval Dravidian Temple on Sacred Bathing Ghats",
    historicalPeriod: "Ancient Vedic Tradition / King Dharma Varma",
    description: "Sacred Teertha Kshetra on the holy Godavari River where unique shrines dedicated to Lord Brahma and Lord Yama exist alongside Lord Narasimha.",
    officialWebsite: "https://jagtial.telangana.gov.in/tourist-place/dharmapuri-temple/",
    sourceRecordId: "TS-TOUR-JAG-008",
    sourceName: "Dharmapuri Devasthanam & Jagtial District Administration",
    sourceUrl: "https://jagtial.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Kaleshwaram Mukteshwara Swamy Temple",
    nameLocal: "కాళేశ్వరం ముక్తేశ్వర స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Jayashankar Bhupalpally",
    localityName: "Kaleshwaram, Godavari-Pranahita-Saraswati Sangam",
    latitude: 18.8167,
    longitude: 79.9083,
    mainDeity: "Twin Shiva Lingams (Lord Shiva & Lord Yama)",
    deities: ["Kaleshwara (Lord Yama)", "Mukteshwara (Lord Shiva)"],
    templeType: "Unique Twin-Lingam on Single Panavattam & Triveni Sangam",
    tradition: ["Shaivism"],
    architecture: "Historic Kakatiya Stone Temple at Sacred Triple Confluence",
    historicalPeriod: "Ancient Puranic / Kakatiya Patronage",
    description: "World-renowned holy pilgrimage where two Shiva Lingams exist on a single pedestal, representing Lord Shiva and Lord Yama at the Triveni Sangam of Godavari, Pranahita, and underground Saraswati.",
    officialWebsite: "https://jayashankar.telangana.gov.in/tourist-place/kaleshwaram-temple/",
    sourceRecordId: "TS-TOUR-JAY-009",
    sourceName: "Kaleshwaram Devasthanam & Telangana Endowments",
    sourceUrl: "https://jayashankar.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Kondagattu Sri Anjaneya Swamy Temple",
    nameLocal: "కొండగట్టు శ్రీ ఆంజనేయ స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Karimnagar",
    localityName: "Muthyampet Hills, Kondagattu",
    latitude: 18.7333,
    longitude: 78.9333,
    mainDeity: "Lord Hanuman (Swayambhu Anjaneya Swamy)",
    deities: ["Sri Anjaneya Swamy (with Narasimha & Garuda Mukhas)"],
    templeType: "Hilltop Miraculous Hanuman Healing Sanctuary",
    tradition: ["Vaishnavism"],
    architecture: "Scenic Hilltop Dravidian Temple Complex",
    historicalPeriod: "Cowherd Krishna Rao Tradition / 18th Century CE",
    description: "Famed Hanuman pilgrimage hillock where the self-manifested deity possesses two faces: Lord Narasimha and Lord Garuda, sought by millions for spiritual healing and blessings.",
    officialWebsite: "https://karimnagar.telangana.gov.in/tourist-place/kondagattu-temple/",
    sourceRecordId: "TS-TOUR-KAR-010",
    sourceName: "Kondagattu Devasthanam & Karimnagar Administration",
    sourceUrl: "https://karimnagar.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Edupayala Vana Durga Bhavani Temple",
    nameLocal: "ఏడుపాయల వనదుర్గా భవాని గుడి",
    stateCode: "TS",
    districtName: "Medak",
    localityName: "Nagasanpalli, Manjeera River",
    latitude: 17.9167,
    longitude: 78.1667,
    mainDeity: "Goddess Vana Durga Bhavani",
    deities: ["Vana Durga", "7 Manjeera River Streams"],
    templeType: "Seven-Stream River Island Shakti Sanctuary",
    tradition: ["Shaktism"],
    architecture: "Natural River Rock Island Shrine on Manjeera",
    historicalPeriod: "Mahabharata King Janamejaya Sarpa Yajna Legend",
    description: "Located where the sacred Manjeera River splits into seven distinct streams (Edupayalu) around a natural rocky sanctum, celebrated for its massive Maha Shivaratri Jatara.",
    officialWebsite: "https://medak.telangana.gov.in/tourist-place/edupayala-vana-durga-bhavani-temple/",
    sourceRecordId: "TS-TOUR-MED-011",
    sourceName: "Edupayala Devasthanam & Medak Administration",
    sourceUrl: "https://medak.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Manyamkonda Sri Venkateswara Swamy Temple",
    nameLocal: "మన్యంకొండ శ్రీ వేంకటేశ్వర స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Mahabubnagar",
    localityName: "Manyamkonda Hill, Mahabubnagar",
    latitude: 16.6333,
    longitude: 77.9167,
    mainDeity: "Lord Venkateswara (Harihara Kshetra)",
    deities: ["Lord Venkateswara", "Alivelu Manga", "Garudazhwar"],
    templeType: "Palamuru Tirupati (Hilltop Cave Sanctum)",
    tradition: ["Vaishnavism"],
    architecture: "Natural Cave Temple atop 1,000-ft Hill",
    historicalPeriod: "Sage Alahari Rama Sharma Penance Legend / 14th Century CE",
    description: "Affectionately called 'Palamuru Tirupati', where Lord Venkateswara is enshrined inside a natural rock cavern atop Manyamkonda hill.",
    officialWebsite: "https://mahabubnagar.telangana.gov.in/tourist-place/manyamkonda-temple/",
    sourceRecordId: "TS-TOUR-MBN-012",
    sourceName: "Manyamkonda Devasthanam & Telangana Endowments",
    sourceUrl: "https://mahabubnagar.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Dichpally Ramalayam Temple Complex",
    nameLocal: "డిచ్‌పల్లి రామాలయం",
    stateCode: "TS",
    districtName: "Nizamabad",
    localityName: "Dichpally, Nizamabad",
    latitude: 18.5833,
    longitude: 78.2167,
    mainDeity: "Lord Rama, Sita & Lakshmana",
    deities: ["Lord Rama", "Mata Sita", "Lakshmana", "Lord Ganesha"],
    templeType: "Khajuraho of Telangana (Kakatiya White Stone Marvel)",
    tradition: ["Vaishnavism"],
    architecture: "Kakatiya White and Black Basalt Stone Nagara-Vesara Style",
    historicalPeriod: "Kakatiya Dynasty / 14th Century CE",
    description: "Celebrated as the 'Khajuraho of Telangana', built by the Kakatiya rulers on a stone hillock with 105 ornate steps and breathtaking erotic and divine sculptures.",
    officialWebsite: "https://nizamabad.telangana.gov.in/tourist-place/dichpally-ramalayam/",
    sourceRecordId: "TS-TOUR-NIZ-013",
    sourceName: "Nizamabad District Administration & Telangana Tourism",
    sourceUrl: "https://nizamabad.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Chaya Someswara Swamy Temple Panagal",
    nameLocal: "ఛాయా సోమేశ్వర స్వామి దేవాలయం పానగల్లు",
    stateCode: "TS",
    districtName: "Nalgonda",
    localityName: "Panagal, Nalgonda Town",
    latitude: 17.0667,
    longitude: 79.2833,
    mainDeity: "Lord Shiva (Chaya Someswara)",
    deities: ["Lord Shiva Lingam", "Mystic Perennial Pillar Shadow"],
    templeType: "Architectural Physics Marvel (Permanent Stationary Shadow)",
    tradition: ["Shaivism"],
    architecture: "Kundu Chola / Kakatiya Trikutalaya Stone Architecture",
    historicalPeriod: "Kundu Chola Rulers / 11th-12th Century CE",
    description: "World-famous architectural wonder where an inexplicable stationary single-pillar shadow falls perpetually on the Shiva Lingam from dawn to dusk, despite sunlight angle shifts.",
    officialWebsite: "https://nalgonda.telangana.gov.in/tourist-place/chaya-someswara-temple/",
    sourceRecordId: "TS-TOUR-NAL-014",
    sourceName: "Nalgonda District Administration & Telangana Tourism",
    sourceUrl: "https://nalgonda.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Kambhammettu Narasimha Swamy Temple",
    nameLocal: "ఖమ్మం ఖిల్లా నరసింహ స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Khammam",
    localityName: "Khammam Fort Hill, Stambhadri",
    latitude: 17.2500,
    longitude: 80.1500,
    mainDeity: "Lord Narasimha Swamy (Stambhadri)",
    deities: ["Lord Narasimha", "Lakshmi Devi"],
    templeType: "Ancient Pillar Origin Fort Sanctum",
    tradition: ["Vaishnavism"],
    architecture: "Kakatiya Rock-Cut Hilltop Temple with Fort Walls",
    historicalPeriod: "Kakatiya King Prataparudra / 950 CE",
    description: "The historical foundation temple of Khammam, originally known as Stambhadri (pillar of Lord Narasimha), situated atop the monolithic granite fort hill.",
    officialWebsite: "https://khammam.telangana.gov.in/tourist-place/khammam-fort/",
    sourceRecordId: "TS-TOUR-KHA-015",
    sourceName: "Khammam District Administration & Telangana Endowments",
    sourceUrl: "https://khammam.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Chilkur Balaji Temple Osman Sagar",
    nameLocal: "చిలుకూరు బాలాజీ దేవాలయం (వీసా బాలాజీ)",
    stateCode: "TS",
    districtName: "Rangareddy",
    localityName: "Chilkur Village, Gandipet",
    latitude: 17.3600,
    longitude: 78.3000,
    mainDeity: "Lord Venkateswara (Chilkur Balaji)",
    deities: ["Lord Venkateswara", "Sridevi", "Bhudevi"],
    templeType: "Visa Balaji (Hundi-Free, Equalitarian Sanatana Temple)",
    tradition: ["Vaishnavism"],
    architecture: "Ancient Dravidian Temple with 108 Pradakshina Pathway",
    historicalPeriod: "Akkanna & Madanna Era / 14th Century CE",
    description: "One of the most extraordinary temples in India: accepts no monetary offerings (zero hundi, no VIP darshan), famous for the 108 circumambulation (pradakshina) fulfillment vow.",
    officialWebsite: "https://rangareddy.telangana.gov.in/tourist-place/chilkoor-balaji-temple/",
    sourceRecordId: "TS-TOUR-RAN-016",
    sourceName: "Chilkur Balaji Devasthanam & Rangareddy Administration",
    sourceUrl: "https://rangareddy.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Kethaki Sangameshwara Swamy Temple Jharasangam",
    nameLocal: "కేతకీ సంగమేశ్వర స్వామి దేవాలయం ఝరాసంగం",
    stateCode: "TS",
    districtName: "Sangareddy",
    localityName: "Jharasangam, Zaheerabad",
    latitude: 17.7500,
    longitude: 77.6667,
    mainDeity: "Lord Shiva (Sangameshwara)",
    deities: ["Lord Shiva Lingam", "Amrutha Gundam Holy Pushkarini"],
    templeType: "Historic Kethaki Flower Shiva Worship Temple",
    tradition: ["Shaivism"],
    architecture: "Ancient Chalukya-Kakatiya Stone Temple and Sacred Gundam",
    historicalPeriod: "King Kupendra Tradition / Chalukya Dynasty",
    description: "One of the very rare temples in India where Lord Shiva is worshipped with the sacred Ketaki flower, featuring the divine spring-fed Amrutha Gundam tank.",
    officialWebsite: "https://sangareddy.telangana.gov.in/tourist-place/jharasangam/",
    sourceRecordId: "TS-TOUR-SAN-017",
    sourceName: "Jharasangam Devasthanam & Sangareddy Administration",
    sourceUrl: "https://sangareddy.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Komuravelli Mallanna Swamy Temple",
    nameLocal: "కొమురవెల్లి మల్లన్న స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Siddipet",
    localityName: "Komuravelli, Siddipet",
    latitude: 17.9333,
    longitude: 78.9167,
    mainDeity: "Mallikarjuna Swamy (Mallanna / Khandoba)",
    deities: ["Sri Mallanna Swamy", "Goddess Medalamma", "Goddess Ketamma"],
    templeType: "Supreme Deccan Pastoral Shaiva Deity Shrine",
    tradition: ["Shaivism", "Deccan Folk Tradition"],
    architecture: "Natural Cave Sanctum in Indra Keeladri Hill",
    historicalPeriod: "Ancient Deccan Folk Legend / 600-year Temple Complex",
    description: "Major pilgrimage destination in northern Telangana enshrining Lord Shiva in the vibrant warrior-pastoral form of Mallanna, celebrated for the giant Oggu Katha folk performances.",
    officialWebsite: "https://siddipet.telangana.gov.in/tourist-place/komuravelli-mallanna-temple/",
    sourceRecordId: "TS-TOUR-SID-018",
    sourceName: "Komuravelli Devasthanam & Telangana Endowments",
    sourceUrl: "https://siddipet.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Phanigiri Sacred Buddhist & Shiva Sthal",
    nameLocal: "ఫణిగిరి బౌద్ధ మరియు శైవ క్షేత్రం",
    stateCode: "TS",
    districtName: "Suryapet",
    localityName: "Phanigiri Hill, Alair River, Suryapet",
    latitude: 17.3167,
    longitude: 79.4833,
    mainDeity: "Ancient Buddhist Stupa & Shiva Lingam",
    deities: ["Lord Buddha", "Lord Shiva"],
    templeType: "1st-3rd Century CE Ancient Hilltop Heritage Complex",
    tradition: ["Buddhism", "Early Shaivism"],
    architecture: "Hilltop Toranas, Monolithic Stupas and Rock Sanctuaries",
    historicalPeriod: "Ikshvaku & Satavahana Dynasties / 1st Century BCE - 3rd Century CE",
    description: "Spectacular hilltop archaeological and pilgrimage site in Suryapet district with ancient Buddhist monastery complexes and early Shaivite rock monuments.",
    officialWebsite: "https://suryapet.telangana.gov.in/tourist-place/phanigiri-buddhist-site/",
    sourceRecordId: "TS-TOUR-SUR-019",
    sourceName: "Telangana Heritage & Suryapet District Administration",
    sourceUrl: "https://tourism.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Sri Anantha Padmanabha Swamy Temple Ananthagiri",
    nameLocal: "శ్రీ అనంత పద్మనాభ స్వామి దేవాలయం అనంతగిరి",
    stateCode: "TS",
    districtName: "Vikarabad",
    localityName: "Ananthagiri Hills, Musi River Source",
    latitude: 17.3167,
    longitude: 77.8667,
    mainDeity: "Lord Anantha Padmanabha Swamy",
    deities: ["Lord Vishnu on Shesha Naga", "Shiva Lingam in Cave"],
    templeType: "Musi River Origin Hilltop Vaishnavite Kshetra",
    tradition: ["Vaishnavism"],
    architecture: "Ancient Dravidian Temple Complex in Dense Forest Hill",
    historicalPeriod: "Rishi Markandeya Penance Tradition / Nizam Endowments",
    description: "Ancient temple situated in the dense Ananthagiri forest hills, source of the sacred River Musi, where Sage Markandeya received divine darshan of Lord Vishnu.",
    officialWebsite: "https://vikarabad.telangana.gov.in/tourist-place/ananthagiri-hills/",
    sourceRecordId: "TS-TOUR-VIK-020",
    sourceName: "Vikarabad District Administration & Telangana Tourism",
    sourceUrl: "https://vikarabad.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Sri Ranganayaka Swamy Temple Srirangapur",
    nameLocal: "శ్రీ రంగనాయక స్వామి దేవాలయం శ్రీరంగాపూర్",
    stateCode: "TS",
    districtName: "Wanaparthy",
    localityName: "Srirangapur, Rangasamudram Lake",
    latitude: 16.2167,
    longitude: 77.9833,
    mainDeity: "Lord Sri Ranganatha Swamy (Reclining Vishnu)",
    deities: ["Sri Ranganatha Swamy", "Ranganayaki Ammavaru"],
    templeType: "18th-Century Vijayanagara Royal Lake Temple",
    tradition: ["Vaishnavism", "Sri Vaishnava"],
    architecture: "Vijayanagara Style Grand Gopuram and Water Enclosure",
    historicalPeriod: "Wanaparthy Samsthanam King Gopal Rao / 18th Century CE",
    description: "Magnificent temple built by the Wanaparthy rulers on the banks of Rangasamudram lake, constructed as a replica of Srirangam in Tamil Nadu.",
    officialWebsite: "https://wanaparthy.telangana.gov.in/tourist-place/sri-ranganayaka-swamy-temple/",
    sourceRecordId: "TS-TOUR-WAN-021",
    sourceName: "Wanaparthy District Administration & Telangana Endowments",
    sourceUrl: "https://wanaparthy.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Warangal Fort Swayambhu Shiva & Keerti Toranas",
    nameLocal: "ఓరుగల్లు కోట స్వయంభూ శివాలయం & కీర్తి తోరణాలు",
    stateCode: "TS",
    districtName: "Warangal",
    localityName: "Warangal Fort Complex",
    latitude: 17.9583,
    longitude: 79.6167,
    mainDeity: "Swayambhu Sambhulingeshwara (Lord Shiva)",
    deities: ["Lord Shiva", "Kakatiya Keerti Toranas (Emblem of Telangana)"],
    templeType: "12th-Century Royal Capital Fortress Temple (ASI Monument)",
    tradition: ["Shaivism"],
    architecture: "Kakatiya Granitic Gateway Toranas and Monolithic Columns",
    historicalPeriod: "Kakatiya Kings Ganapati Deva & Rudrama Devi / 12th-13th Century CE",
    description: "The historic religious epicenter of the Kakatiya Empire protected by ASI. The grand four Keerti Torana gateways form the official state symbol of Telangana.",
    officialWebsite: "https://warangal.telangana.gov.in/tourist-place/warangal-fort/",
    sourceRecordId: "TS-ASI-WAR-022",
    sourceName: "Archaeological Survey of India Hyderabad Circle",
    sourceUrl: "https://warangal.telangana.gov.in",
    sourceType: "asi",
  },
  {
    name: "Jainath Sri Lakshmi Narayana Swamy Temple",
    nameLocal: "జైనాథ్ శ్రీ లక్ష్మీ నారాయణ స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Adilabad",
    localityName: "Jainath Village, Adilabad",
    latitude: 19.7333,
    longitude: 78.6500,
    mainDeity: "Lord Surya Narayana (Sun God / Vishnu)",
    deities: ["Sri Lakshmi Narayana", "Surya Rays on Sanctum"],
    templeType: "Jain-Hindu Heritage Solar Temple",
    tradition: ["Vaishnavism", "Solar Tradition"],
    architecture: "Ancient Chalukya-Rashtrakuta Stone Architecture",
    historicalPeriod: "Pallava-Chalukya Influence / 4th-9th Century CE Inscriptions",
    description: "Ancient stone temple in northernmost Telangana built on a high platform, where morning sun rays directly illuminate the lotus feet of the deity on specific equinox days.",
    officialWebsite: "https://adilabad.telangana.gov.in/tourist-place/jainath-temple/",
    sourceRecordId: "TS-TOUR-ADI-023",
    sourceName: "Adilabad District Administration & Telangana Tourism",
    sourceUrl: "https://adilabad.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Kolanupaka Someswara Swamy & Jain Mandir",
    nameLocal: "కొలనుపాక సోమేశ్వర స్వామి మరియు జైన మందిరం",
    stateCode: "TS",
    districtName: "Jangaon",
    localityName: "Kolanupaka, Alair Mandal",
    latitude: 17.7250,
    longitude: 79.0417,
    mainDeity: "Lord Shiva (Kollipaka Someswara) & Lord Rishabhanatha",
    deities: ["Lord Shiva", "Lord Rishabhanatha", "Mahavira (Jade Idol)"],
    templeType: "2,000-Year Historical Shaivite & Jain Pilgrimage Capital",
    tradition: ["Shaivism", "Jainism"],
    architecture: "Western Chalukyan Pillar Shrines and Marble Jain Temple",
    historicalPeriod: "Western Chalukya Capital (Kollipaka) / 11th Century CE",
    description: "The celebrated 11th-century capital of Western Chalukyas, housing both the historic Someswara temple and the famous 2,000-year-old Jain temple with a five-foot emerald/jade Mahavira.",
    officialWebsite: "https://jangaon.telangana.gov.in/tourist-place/kolanupaka-temple/",
    sourceRecordId: "TS-TOUR-JAN-024",
    sourceName: "Jangaon District Administration & Telangana Tourism",
    sourceUrl: "https://jangaon.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Biknoor Siddha Rameshwara Swamy Temple",
    nameLocal: "భిక్కనూరు సిద్ధ రామేశ్వర స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Kamareddy",
    localityName: "Biknoor, Kamareddy",
    latitude: 18.2500,
    longitude: 78.4167,
    mainDeity: "Lord Shiva (Siddha Rameshwara)",
    deities: ["Lord Shiva", "Parvati", "Sacred Pushkarini"],
    templeType: "Historical Kakatiya Shaiva Pilgrimage",
    tradition: ["Shaivism"],
    architecture: "Stone Pillar Temple with Massive Entrance Gopuram",
    historicalPeriod: "Kakatiya Dynasty Footprint",
    description: "Centuries-old pilgrimage center in Kamareddy district renowned for its architectural entrance and vibrant annual Maha Shivaratri Bramhotsavams.",
    officialWebsite: "https://kamareddy.telangana.gov.in/tourist-place/bikknoor-temple/",
    sourceRecordId: "TS-TOUR-KAM-025",
    sourceName: "Kamareddy District Administration & Telangana Endowments",
    sourceUrl: "https://kamareddy.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Gangapur Sri Shiva Temple Asifabad",
    nameLocal: "గంగాపూర్ శ్రీ శివాలయం ఆసిఫాబాద్",
    stateCode: "TS",
    districtName: "Kumuram Bheem Asifabad",
    localityName: "Gangapur, Rebbena Mandal",
    latitude: 19.3667,
    longitude: 79.2833,
    mainDeity: "Lord Shiva",
    deities: ["Lord Shiva", "Tribal Ancestral Sthals"],
    templeType: "Forest Frontier Ancient Shaiva Shrine",
    tradition: ["Shaivism", "Gond Tribal Heritage"],
    architecture: "Ancient Stone Temple in Tribal Forest Belt",
    historicalPeriod: "Medieval Gond Kings & Kakatiya Heritage",
    description: "Revered historical temple standing in the tribal homeland of Kumuram Bheem in northern Telangana, where Gond and Telugu pilgrims unite during festivals.",
    officialWebsite: "https://asifabad.telangana.gov.in/",
    sourceRecordId: "TS-TOUR-KBA-026",
    sourceName: "Kumuram Bheem Asifabad Administration & CG Tourism",
    sourceUrl: "https://asifabad.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Kuravi Sri Veerabhadra Swamy Temple",
    nameLocal: "కురవి శ్రీ వీరభద్ర స్వామి దేవస్థానం",
    stateCode: "TS",
    districtName: "Mahaboobabad",
    localityName: "Kuravi, Mahabubabad",
    latitude: 17.5167,
    longitude: 80.0000,
    mainDeity: "Lord Veerabhadra Swamy (Fierce Avatar of Shiva)",
    deities: ["Lord Veerabhadra Swamy", "Bhadrakali Ammavaru"],
    templeType: "Historic 9th-Century Vengipuram Warrior Shaiva Shrine",
    tradition: ["Shaivism"],
    architecture: "Ancient Chalukya-Kakatiya Stone Temple Complex",
    historicalPeriod: "Vengipuram Kings / Bheemaraju / 900 CE",
    description: "Ancient and powerful Shaivite temple built by Vengipuram rulers in the 9th century, famous for its intense spiritual vibrations and grand Maha Shivaratri Jatara.",
    officialWebsite: "https://mahabubabad.telangana.gov.in/tourist-place/kuravi-veerabhadra-swamy-temple/",
    sourceRecordId: "TS-TOUR-MAH-027",
    sourceName: "Kuravi Devasthanam & Mahabubabad Administration",
    sourceUrl: "https://mahabubabad.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Gudem Gutta Sri Satyanarayana Swamy Temple",
    nameLocal: "గూడెం గుట్ట శ్రీ సత్యనారాయణ స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Mancherial",
    localityName: "Gudem Hillock, Dandepalli, Godavari Bank",
    latitude: 18.9167,
    longitude: 79.4500,
    mainDeity: "Sri Satyanarayana Swamy",
    deities: ["Lord Satyanarayana Swamy", "Anantha Lakshmi Devi"],
    templeType: "Annavaram of Telangana (Godavari River Hilltop)",
    tradition: ["Vaishnavism"],
    architecture: "Hillside White Dravidian Shikhara Temple",
    historicalPeriod: "Consecrated 1964 CE on Godavari River Hillock",
    description: "Revered as the 'Annavaram of Telangana', situated on a peaceful hillock beside the holy Godavari River where thousands perform Sri Satyanarayana Vratams daily.",
    officialWebsite: "https://mancherial.telangana.gov.in/tourist-place/gudem-gutta-temple/",
    sourceRecordId: "TS-TOUR-MAN-028",
    sourceName: "Gudem Devasthanam & Mancherial District Administration",
    sourceUrl: "https://mancherial.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Keesaragutta Sri Ramalingeswara Swamy Temple",
    nameLocal: "కీసరగుట్ట శ్రీ రామలింగేశ్వర స్వామి దేవస్థానం",
    stateCode: "TS",
    districtName: "Medchal-Malkajgiri",
    localityName: "Keesara Hillock, Outer Hyderabad",
    latitude: 17.5167,
    longitude: 78.6833,
    mainDeity: "Lord Shiva (Ramalingeswara Swamy)",
    deities: ["Lord Shiva", "Bhavani Mata", "Siva Durga", "Hundreds of Shivalingams"],
    templeType: "Historic 5th-Century Vishnukundina Dynasty Hill Capital (ASI Monument)",
    tradition: ["Shaivism"],
    architecture: "Ancient Vishnukundina Stone Shrines across Hillock",
    historicalPeriod: "Vishnukundina Dynasty / 5th Century CE",
    description: "Famous hill shrine where Lord Rama consecrated thousands of Shiva Lingams to atone for killing Ravana, serving as the royal capital of the 5th-century Vishnukundina dynasty. Protected by ASI.",
    officialWebsite: "https://medchal-malkajgiri.telangana.gov.in/tourist-place/keesaragutta-temple/",
    sourceRecordId: "TS-TOUR-MED-029",
    sourceName: "Keesaragutta Devasthanam & Telangana Endowments",
    sourceUrl: "https://medchal-malkajgiri.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Uma Maheshwaram Temple Srisailam North Gateway",
    nameLocal: "ఉమా మహేశ్వరం దేవాలయం (శ్రీశైలం ఉత్తర ద్వారం)",
    stateCode: "TS",
    districtName: "Nagarkurnool",
    localityName: "Nallamala Hills, Achampet",
    latitude: 16.3667,
    longitude: 78.7333,
    mainDeity: "Lord Shiva (Uma Maheshwara)",
    deities: ["Lord Shiva", "Uma Devi", "Natural Perennial Spring Papanashini"],
    templeType: "Historic Northern Gateway to Srisailam Jyotirlinga",
    tradition: ["Shaivism"],
    architecture: "Nallamala Mountain Cliff Temple and Sacred Springs",
    historicalPeriod: "Mauryan Era / Kakatiya King Prataparudra / 2nd Century BCE",
    description: "Revered as the sacred Northern Gateway (Uttara Dwaram) of Srisailam Jyotirlinga, perched on a dramatic 1,500-foot cliff inside the Nallamala tiger forest.",
    officialWebsite: "https://nagarkurnool.telangana.gov.in/tourist-place/uma-maheswaram/",
    sourceRecordId: "TS-TOUR-NAG-030",
    sourceName: "Uma Maheshwaram Devasthanam & Nagarkurnool Administration",
    sourceUrl: "https://nagarkurnool.telangana.gov.in",
    sourceType: "official",
  },
  {
    name: "Ghanpur Sri Venkateswara Swamy Temple",
    nameLocal: "ఘనపూర్ శ్రీ వేంకటేశ్వర స్వామి దేవాలయం",
    stateCode: "TS",
    districtName: "Narayanpet",
    localityName: "Ghanpur, Narayanpet Border",
    latitude: 16.6833,
    longitude: 77.5000,
    mainDeity: "Lord Venkateswara Swamy",
    deities: ["Lord Venkateswara", "Padmavathi Ammavaru"],
    templeType: "Historic Border Samsthanam Temple",
    tradition: ["Vaishnavism"],
    architecture: "Dravidian Shikhara Temple Complex",
    historicalPeriod: "Ghanpur Samsthanam / 17th Century CE",
    description: "Historic temple situated in Narayanpet near the Karnataka border, established under the patronage of the Ghanpur Samsthanam rajas.",
    officialWebsite: "https://narayanpet.telangana.gov.in/",
    sourceRecordId: "TS-TOUR-NAR-031",
    sourceName: "Narayanpet District Administration & Telangana Tourism",
    sourceUrl: "https://narayanpet.telangana.gov.in",
    sourceType: "government",
  },
  {
    name: "Dhulikatta Stupa & Ramagundam Shiva Shrines",
    nameLocal: "ధూళికట్ట బౌద్ధ స్తూపం & రామగుండం శివాలయాలు",
    stateCode: "TS",
    districtName: "Peddapalli",
    localityName: "Dhulikatta, Peddapalli",
    latitude: 18.7000,
    longitude: 79.3167,
    mainDeity: "Lord Shiva & Ancient Dhulikatta Mahastupa",
    deities: ["Lord Shiva", "Dhulikatta Mahastupa"],
    templeType: "Satavahana 2nd-Century BCE Sacred Heritage Complex",
    tradition: ["Buddhism", "Shaivism"],
    architecture: "Ancient Satavahana Brick Stupa & Medieval Shiva Shrines",
    historicalPeriod: "Satavahana Dynasty / 2nd Century BCE",
    description: "One of the most remarkable archaeological and sacred sites in the Godavari basin, featuring a 2,200-year-old Buddhist Mahastupa alongside ancient Shaivite shrines in Peddapalli.",
    officialWebsite: "https://peddapalli.telangana.gov.in/tourist-place/dhulikatta-buddhist-stupa/",
    sourceRecordId: "TS-TOUR-PED-032",
    sourceName: "Archaeological Survey of India & Peddapalli Administration",
    sourceUrl: "https://peddapalli.telangana.gov.in",
    sourceType: "government",
  },
];

export async function importTelanganaTemples(options: { dryRun?: boolean; parserVersion?: string } = {}) {
  console.log("==================================================");
  console.log("🏛️ TELANGANA TEMPLE INGESTION ENGINE");
  console.log("Source: Telangana Endowments, YTDA, TSTDC & ASI");
  console.log(`Mode: ${options.dryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  return processStateBatch(
    "Telangana Endowments, YTDA, TSTDC & ASI",
    "https://tggovendowments.gov.in",
    TELANGANA_AUTHORITATIVE_TEMPLES,
    options
  );
}

// CLI runner
if (process.argv[1]?.endsWith("telangana.ts")) {
  const isDryRun = process.argv.includes("--dry-run");
  importTelanganaTemples({ dryRun: isDryRun })
    .then((report) => {
      console.log("\nTelemetry Report:");
      console.log(JSON.stringify(report, null, 2));
      process.exit(0);
    })
    .catch((err) => {
      console.error("\n❌ Importer crashed:", err);
      process.exit(1);
    });
}
