/**
 * Uttarakhand Official State Ingestion Importer
 * Authoritative Source: Shri Badrinath - Shri Kedarnath Temple Committee (BKTC), Uttarakhand Tourism Development Board, ASI
 * Portal: https://badrinath-kedarnath.gov.in / https://uttarakhandtourism.gov.in
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const UTTARAKHAND_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Kedarnath Jyotirlinga Temple",
    nameLocal: "केदारनाथ ज्योतिर्लिंग मंदिर",
    stateCode: "UK",
    districtName: "Rudraprayag",
    localityName: "Kedarnath, Mandakini Valley",
    latitude: 30.7352,
    longitude: 79.0669,
    mainDeity: "Kedarnath (Hump of Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Highest Jyotirlinga & Chota Char Dham & Panch Kedar",
    tradition: ["Shaivism"],
    architecture: "Massive Grey Granite Cut-Stone Slabs amidst Himalayan Glaciers",
    historicalPeriod: "Adi Shankaracharya Restored (8th Century CE)",
    description: "Perched at 3,583 meters against the snow-clad Kedarnath peak in the Garhwal Himalayas. The northernmost of the 12 Jyotirlingas and the supreme shrine among the five Panch Kedar pilgrimage temples.",
    officialWebsite: "https://badrinath-kedarnath.gov.in",
    sourceRecordId: "UK-BKTC-RUD-001",
    sourceName: "Shri Badrinath - Shri Kedarnath Temple Committee (BKTC)",
    sourceUrl: "https://badrinath-kedarnath.gov.in",
    sourceType: "government",
  },
  {
    name: "Badrinath Temple",
    nameLocal: "बद्रीनाथ मंदिर",
    stateCode: "UK",
    districtName: "Chamoli",
    localityName: "Badrinath, Alaknanda Valley",
    latitude: 30.7447,
    longitude: 79.4911,
    mainDeity: "Badri Vishal (Self-Manifested Shaligram Vishnu)",
    deities: ["Lord Vishnu", "Garuda", "Kubera", "Narada", "Nara-Narayana"],
    templeType: "Maha Char Dham & Chota Char Dham & Divya Desam",
    tradition: ["Vaishnavism", "Smartha"],
    architecture: "Traditional Himalayan Wood & Stone Architecture with Brightly Painted Facade",
    historicalPeriod: "Consecrated by Adi Shankara (8th Century CE)",
    description: "Nestled between the Nar and Narayana mountain ranges beside River Alaknanda at 3,133 meters altitude. The only shrine that belongs to both the All-India Maha Char Dham and Himalayan Chota Char Dham circuits.",
    officialWebsite: "https://badrinath-kedarnath.gov.in",
    sourceRecordId: "UK-BKTC-CHA-002",
    sourceName: "Shri Badrinath - Shri Kedarnath Temple Committee (BKTC)",
    sourceUrl: "https://badrinath-kedarnath.gov.in",
    sourceType: "government",
  },
  {
    name: "Gangotri Temple",
    nameLocal: "गंगोत्री मंदिर",
    stateCode: "UK",
    districtName: "Uttarkashi",
    localityName: "Gangotri, Bhagirathi Valley",
    latitude: 30.9947,
    longitude: 78.9397,
    mainDeity: "Goddess Ganga",
    deities: ["Goddess Ganga", "Bhagiratha", "Shiva"],
    templeType: "Chota Char Dham Pilgrimage Shrine",
    tradition: ["Smartha", "Shaktism"],
    architecture: "White Granite Himalayan Sanctum overlooking Bhagirathi River",
    historicalPeriod: "Gorkha General Amar Singh Thapa (Early 18th Century CE)",
    description: "Situated at 3,100 meters on the banks of River Bhagirathi, commemorating the descent of the celestial River Ganga to Earth through King Bhagiratha's severe penance.",
    officialWebsite: "https://uttarkashi.nic.in/tourist-place/gangotri/",
    sourceRecordId: "UK-BKTC-UTT-003",
    sourceName: "Gangotri Temple Committee & Uttarkashi Administration",
    sourceUrl: "https://uttarkashi.nic.in/tourist-place/gangotri/",
    sourceType: "government",
  },
  {
    name: "Yamunotri Temple",
    nameLocal: "यमुनोत्री मंदिर",
    stateCode: "UK",
    districtName: "Uttarkashi",
    localityName: "Yamunotri",
    latitude: 31.0139,
    longitude: 78.4600,
    mainDeity: "Goddess Yamuna",
    deities: ["Goddess Yamuna"],
    templeType: "Chota Char Dham Pilgrimage Shrine",
    tradition: ["Smartha"],
    architecture: "Himalayan Granite Stone Shrine beside Surya Kund Thermal Springs",
    historicalPeriod: "Maharani Guleria of Jaipur (Reconstructed 19th Century)",
    description: "Perched at 3,293 meters in the Western Garhwal Himalayas near the origin of River Yamuna. Devotees cook rice and potatoes wrapped in muslin cloth in the boiling hot springs of Surya Kund as prasad.",
    officialWebsite: "https://uttarkashi.nic.in/tourist-place/yamunotri/",
    sourceRecordId: "UK-BKTC-UTT-004",
    sourceName: "Yamunotri Temple Committee & Uttarkashi Administration",
    sourceUrl: "https://uttarkashi.nic.in/tourist-place/yamunotri/",
    sourceType: "government",
  },
  {
    name: "Tungnath Mahadev Temple",
    nameLocal: "तुंगनाथ महादेव मंदिर",
    stateCode: "UK",
    districtName: "Rudraprayag",
    localityName: "Chandrashila Base, Chopta",
    latitude: 30.4883,
    longitude: 79.2169,
    mainDeity: "Tungnath (Arms of Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Panch Kedar (Highest Shiva Temple in the World)",
    tradition: ["Shaivism"],
    architecture: "Ancient Heavy Granite Slabs at 3,680 Meters Altitude",
    historicalPeriod: "Pandava Tradition / Adi Shankara Consecration",
    description: "Standing at an astounding 3,680 meters (12,073 feet) above sea level, Tungnath is the highest Shiva temple on planet Earth. Reached via a scenic rhododendron trek from Chopta.",
    officialWebsite: "https://rudraprayag.nic.in/tourist-place/tungnath-temple/",
    sourceRecordId: "UK-BKTC-RUD-005",
    sourceName: "Shri Badrinath - Shri Kedarnath Temple Committee (BKTC)",
    sourceUrl: "https://badrinath-kedarnath.gov.in",
    sourceType: "government",
  },
  {
    name: "Jageshwar Mahadev Temple Complex",
    nameLocal: "जाగेश्वर धाम मंदिर समूह अल्मोड़ा",
    stateCode: "UK",
    districtName: "Almora",
    localityName: "Jageshwar Dham",
    latitude: 29.6389,
    longitude: 79.8536,
    mainDeity: "Maha Mrityunjaya & Jageshwar Shiva",
    deities: ["Lord Shiva", "Maha Mrityunjaya", "Pushti Devi"],
    templeType: "ASI Monument of National Importance (124 Temple Cluster)",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Clustered Stone Temples surrounded by Tall Deodar Trees",
    historicalPeriod: "Katyuri Dynasty (7th to 12th Century CE)",
    description: "A serene complex of 124 stone temples tucked in a narrow Himalayan deodar valley near Almora, venerated as the place where the Linga worship tradition was revealed according to regional Shiva Purana tradition.",
    officialWebsite: "https://asi.nic.in/monuments-jageshwar/",
    sourceRecordId: "ASI-UK-N-UK-C1",
    sourceName: "Archaeological Survey of India & Almora Administration",
    sourceUrl: "https://asi.nic.in/monuments-jageshwar/",
    sourceType: "government",
  },
  {
    name: "Baijnath Temple Complex Katyuri",
    nameLocal: "बैजनाथ मंदिर समूह बागेश्वर",
    stateCode: "UK",
    districtName: "Bageshwar",
    localityName: "Baijnath, Garur Valley",
    latitude: 29.9078,
    longitude: 79.6194,
    mainDeity: "Vaidyanatha (Healing Lord Shiva)",
    deities: ["Lord Shiva", "Goddess Parvati", "Ganesha"],
    templeType: "ASI Monument of National Importance",
    tradition: ["Shaivism"],
    architecture: "12th-Century Katyuri Stone Temples on River Gomati",
    historicalPeriod: "Katyuri Kings of Kumaon (1150 CE)",
    description: "Situated on the banks of River Gomati in Bageshwar district, celebrated for its 26 preserved stone shrines and an exquisite, dark stone idol of Goddess Parvati depicted performing penance.",
    officialWebsite: "https://bageshwar.nic.in/tourist-place/baijnath-temple/",
    sourceRecordId: "ASI-UK-N-UK-C2",
    sourceName: "Archaeological Survey of India & Bageshwar Administration",
    sourceUrl: "https://bageshwar.nic.in/tourist-place/baijnath-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Dhari Devi Temple Kalyasaur",
    nameLocal: "माँ धारी देवी मंदिर कल्यासौड़",
    stateCode: "UK",
    districtName: "Pauri Garhwal",
    localityName: "Kalyasaur, Srinagar",
    latitude: 30.2458,
    longitude: 78.8258,
    mainDeity: "Maa Dhari Devi (Guardian Goddess of Uttarakhand)",
    deities: ["Kali / Durga"],
    templeType: "Guardian Mother Goddess of the Himalayas",
    tradition: ["Shaktism"],
    architecture: "Elevated Concrete and Stone Sanctuary perched directly above River Alaknanda",
    historicalPeriod: "Ancient Garhwal Tradition",
    description: "Situated in the middle of the roaring Alaknanda River between Srinagar and Rudraprayag. Revered as the supreme guardian deity (Rakshak Devi) of the Char Dham pilgrimage.",
    officialWebsite: "https://pauri.nic.in/tourist-place/dhari-devi-temple/",
    sourceRecordId: "UK-TOUR-PAU-006",
    sourceName: "Maa Dhari Devi Temple Trust & Pauri Garhwal Administration",
    sourceUrl: "https://pauri.nic.in/tourist-place/dhari-devi-temple/",
    sourceType: "government",
  },
  {
    name: "Surkanda Devi Temple Dhanaulti",
    nameLocal: "सुरकंडा देवी मंदिर धनोल्टी",
    stateCode: "UK",
    districtName: "Tehri Garhwal",
    localityName: "Kaddukhal, Dhanaulti",
    latitude: 30.4139,
    longitude: 78.2861,
    mainDeity: "Goddess Surkanda (Head/Sirsha Peetha)",
    deities: ["Surkanda Devi"],
    templeType: "Maha Shakti Peetha at 2,756m Elevation",
    tradition: ["Shaktism"],
    architecture: "Mountain Peak Temple with 360-Degree Panoramic Himalayan Views",
    historicalPeriod: "Epic Puranic Tradition",
    description: "Perched atop a 2,756-meter mountain ridge in Tehri Garhwal district, where the head (Sirsha) of Goddess Sati is believed to have fallen. Reached by a scenic ridge trek or ropeway.",
    officialWebsite: "https://tehri.nic.in/tourist-place/surkanda-devi-temple/",
    sourceRecordId: "UK-TOUR-TEH-007",
    sourceName: "Surkanda Devi Temple Trust & Tehri Garhwal Administration",
    sourceUrl: "https://tehri.nic.in/tourist-place/surkanda-devi-temple/",
    sourceType: "government",
  },
  {
    name: "Baleshwar Temple Complex Champawat",
    nameLocal: "बालेश्वर मंदिर चम्पावत",
    stateCode: "UK",
    districtName: "Champawat",
    localityName: "Champawat",
    latitude: 29.3361,
    longitude: 80.0889,
    mainDeity: "Baleshwar (Lord Shiva)",
    deities: ["Lord Shiva", "Ratneshwar", "Champawati"],
    templeType: "ASI Monument of National Importance",
    tradition: ["Shaivism"],
    architecture: "13th-Century South Indian & Nagara Confluence Stone Filigree Carvings",
    historicalPeriod: "Chand Dynasty Kings of Kumaon (1272 CE)",
    description: "One of the most artistic and historically significant stone temple complexes in Kumaon, renowned for its extraordinarily detailed stone ceiling carvings and filigree mandapas.",
    officialWebsite: "https://asi.nic.in/monuments-champawat/",
    sourceRecordId: "ASI-UK-N-UK-C3",
    sourceName: "Archaeological Survey of India & Champawat Administration",
    sourceUrl: "https://asi.nic.in/monuments-champawat/",
    sourceType: "government",
  },
  {
    name: "Maa Chaiti Devi Temple Kashipur",
    nameLocal: "माँ चैती देवी मंदिर काशीपुर",
    stateCode: "UK",
    districtName: "Udham Singh Nagar",
    localityName: "Kashipur",
    latitude: 29.2108,
    longitude: 78.9619,
    mainDeity: "Maa Balasundari (Chaiti Devi)",
    deities: ["Balasundari"],
    templeType: "Prominent Terai Shakta Pilgrimage",
    tradition: ["Shaktism"],
    architecture: "Traditional North Indian White Shikhara Temple Complex",
    historicalPeriod: "King of Kashipur Royal Patronage (18th Century)",
    description: "Also known as Maa Balasundari Mandir, situated in Kashipur in Udham Singh Nagar district. Draws over a million pilgrims during the famous Chaiti Mela held during Chaitra Navratri.",
    officialWebsite: "https://usnagar.nic.in/tourist-place/chaiti-temple/",
    sourceRecordId: "UK-TOUR-UDH-008",
    sourceName: "Udham Singh Nagar District Administration & Temple Trust",
    sourceUrl: "https://usnagar.nic.in/tourist-place/chaiti-temple/",
    sourceType: "government",
  },
  {
    name: "Neelkanth Mahadev Temple Rishikesh",
    nameLocal: "नीलकंठ महादेव मंदिर ऋषिकेश",
    stateCode: "UK",
    districtName: "Pauri Garhwal",
    localityName: "Manikoot Parvat, Rishikesh",
    latitude: 30.0833,
    longitude: 78.3361,
    mainDeity: "Neelkanth (Blue-Throated Lord Shiva)",
    deities: ["Lord Shiva"],
    templeType: "Sacred Samudra Manthan Poison Consumption Shrine",
    tradition: ["Shaivism"],
    architecture: "Vibrant Multicoloured Sculpted Tower surrounded by Three Mountain Peaks",
    historicalPeriod: "Ancient Puranic Samudra Manthan Era",
    description: "Nestled at 1,330 meters surrounded by dense valley forests of Brahmakoot, Manikoot, and Vishnukoot mountains, where Lord Shiva consumed the Halahala poison churned from the cosmic ocean.",
    officialWebsite: "https://pauri.nic.in/tourist-place/neelkanth-mahadev/",
    sourceRecordId: "UK-TOUR-PAU-009",
    sourceName: "Neelkanth Mahadev Mandir Samiti & Pauri Administration",
    sourceUrl: "https://pauri.nic.in/tourist-place/neelkanth-mahadev/",
    sourceType: "government",
  },
  {
    name: "Raghunath Temple Devprayag",
    nameLocal: "रघुनाथ मंदिर देवप्रयाग",
    stateCode: "UK",
    districtName: "Tehri Garhwal",
    localityName: "Devprayag Confluence",
    latitude: 30.1458,
    longitude: 78.5989,
    mainDeity: "Lord Raghunath (Rama)",
    deities: ["Rama", "Sita", "Lakshmana"],
    templeType: "108 Divya Desams (Thirukkandiyur / Devaprayagai)",
    tradition: ["Vaishnavism"],
    architecture: "Ancient Himalayan Granitic Shikhara above Sacred River Confluence",
    historicalPeriod: "Consecrated by Adi Shankara / Alvar Praise",
    description: "Perched dramatically above the holy confluence of the Alaknanda and Bhagirathi rivers where River Ganga officially begins. Celebrated as the northernmost Divya Desam in India praised by the Alvars.",
    officialWebsite: "https://tehri.nic.in/tourist-place/raghunath-temple/",
    sourceRecordId: "UK-TOUR-TEH-010",
    sourceName: "Badrinath-Kedarnath Temple Committee & Tehri Administration",
    sourceUrl: "https://tehri.nic.in/tourist-place/raghunath-temple/",
    sourceType: "government",
  },
  {
    name: "Mansa Devi Temple Haridwar",
    nameLocal: "मनसा देवी मंदिर हरिद्वार",
    stateCode: "UK",
    districtName: "Haridwar",
    localityName: "Bilwa Parvat, Haridwar",
    latitude: 29.9575,
    longitude: 78.1633,
    mainDeity: "Goddess Mansa Devi (Wish-Fulfilling Serpent Deity)",
    deities: ["Mansa Devi"],
    templeType: "Siddhapeetha of the Shivalik Foothills",
    tradition: ["Shaktism"],
    architecture: "Hilltop Temple Complex reached by Ropeway overlooking River Ganga",
    historicalPeriod: "Centuries-Old Shivalik Tradition",
    description: "Perched atop the Bilwa Parvat in the Shivalik foothills of the Himalayas, venerated as the wish-fulfilling sister of Nagaraja Vasuki. Part of the sacred Siddhapeetha triangle of Haridwar.",
    officialWebsite: "https://haridwar.nic.in/tourist-place/mansa-devi-temple/",
    sourceRecordId: "UK-TOUR-HAR-011",
    sourceName: "Haridwar District Administration & Uttarakhand Tourism",
    sourceUrl: "https://haridwar.nic.in/tourist-place/mansa-devi-temple/",
    sourceType: "government",
  },
  {
    name: "Kasar Devi Temple Almora",
    nameLocal: "कसार देवी मंदिर अल्मोड़ा",
    stateCode: "UK",
    districtName: "Almora",
    localityName: "Kasar Devi Ridge, Almora",
    latitude: 29.6333,
    longitude: 79.6667,
    mainDeity: "Kasar Devi (Durga)",
    deities: ["Durga"],
    templeType: "Ancient Cave Shrine & Geomagnetic Energy Center",
    tradition: ["Shaktism"],
    architecture: "Rock-Cut Hilltop Cave Sanctum with Panoramic Himalayan Peaks",
    historicalPeriod: "2nd Century CE Inscription Era",
    description: "Situated on a high ridge near Almora with panoramic views of Nanda Devi and Trishul peaks. Noted by NASA for its unique geomagnetic radiation belt (Van Allen belt), where Swami Vivekananda meditated in 1890.",
    officialWebsite: "https://almora.nic.in/tourist-place/kasar-devi-temple/",
    sourceRecordId: "UK-TOUR-ALM-012",
    sourceName: "Almora District Administration & Uttarakhand Tourism",
    sourceUrl: "https://almora.nic.in/tourist-place/kasar-devi-temple/",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ UTTARAKHAND TEMPLE INGESTION ENGINE");
  console.log(`Source: Shri Badrinath-Kedarnath Temple Committee & UTDB`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "Shri Badrinath-Kedarnath Committee & Uttarakhand Tourism",
    "https://badrinath-kedarnath.gov.in",
    UTTARAKHAND_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
