/**
 * Uttar Pradesh Official State Ingestion Importer
 * Authoritative Source: Shri Kashi Vishwanath Board, Shri Ram Janmabhoomi Teerth Kshetra, UP Braj Teerth Vikas Parishad, UP Tourism, ASI
 * Portal: https://shrikashivishwanath.org / https://srjbtkshetra.org / https://uptourism.gov.in
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const UTTAR_PRADESH_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Kashi Vishwanath Jyotirlinga Temple",
    nameLocal: "काशी विश्वनाथ ज्योतिर्लिंग मंदिर",
    stateCode: "UP",
    districtName: "Varanasi",
    localityName: "Lahori Tola, Varanasi",
    latitude: 25.3108,
    longitude: 83.0108,
    mainDeity: "Vishveshwara / Vishwanath (Lord of the Universe)",
    deities: ["Lord Shiva", "Maa Annapurna", "Kaal Bhairav"],
    templeType: "Supreme Jyotirlinga & Mokshapuri",
    tradition: ["Shaivism"],
    architecture: "Nagara Style Gold-Plated Shikhara with Kashi Vishwanath Corridor",
    historicalPeriod: "Ahilyabai Holkar of Indore (1780 CE) / Corridor (2021 CE)",
    description: "One of the most sacred pilgrimage shrines in Hinduism, located on the western bank of holy River Ganga. Its gold-plated spire was donated by Maharaja Ranjit Singh, seamlessly connected to the river ghats by the grand corridor.",
    officialWebsite: "https://shrikashivishwanath.org",
    sourceRecordId: "UP-VISH-VAR-001",
    sourceName: "Shri Kashi Vishwanath Special Area Development Board",
    sourceUrl: "https://shrikashivishwanath.org",
    sourceType: "government",
  },
  {
    name: "Sankat Mochan Hanuman Temple",
    nameLocal: "संकट मोचन हनुमान मंदिर वाराणसी",
    stateCode: "UP",
    districtName: "Varanasi",
    localityName: "Saket Nagar, Varanasi",
    latitude: 25.2819,
    longitude: 82.9989,
    mainDeity: "Sankat Mochan Hanuman",
    deities: ["Hanuman", "Rama", "Sita"],
    templeType: "Historic Goswami Tulsidas Consecration Shrine",
    tradition: ["Vaishnavism"],
    architecture: "Traditional North Indian Courtyard Architecture on River Asi",
    historicalPeriod: "Goswami Tulsidas (Early 16th Century CE)",
    description: "Founded by saint-poet Goswami Tulsidas where he had a divine vision of Lord Hanuman. Pilgrims from across the world chant the Hanuman Chalisa here for relief from astrologic and personal difficulties.",
    officialWebsite: "https://varanasi.nic.in/tourist-place/sankat-mochan-temple/",
    sourceRecordId: "UP-TOUR-VAR-002",
    sourceName: "Sankat Mochan Foundation & Varanasi Administration",
    sourceUrl: "https://varanasi.nic.in/tourist-place/sankat-mochan-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Annapurna Mandir Varanasi",
    nameLocal: "माँ अन्नपूर्णा मंदिर वाराणसी",
    stateCode: "UP",
    districtName: "Varanasi",
    localityName: "Visheshwarganj, Varanasi",
    latitude: 25.3114,
    longitude: 83.0103,
    mainDeity: "Maa Annapurna (Goddess of Food and Nourishment)",
    deities: ["Maa Annapurna"],
    templeType: "Supreme Nourishment Shakta Shrine of Kashi",
    tradition: ["Shaktism"],
    architecture: "Nagara Style Temple adjacent to Kashi Vishwanath",
    historicalPeriod: "Peshwa Baji Rao I (1729 CE)",
    description: "Situated adjacent to Kashi Vishwanath, dedicated to Goddess Annapurna who feeds the city of Kashi and even fed Lord Shiva when He was a mendicant. Famous for its golden idol shown once a year on Annakut.",
    officialWebsite: "https://varanasi.nic.in/tourist-place/annapurna-temple/",
    sourceRecordId: "UP-TOUR-VAR-003",
    sourceName: "Annapurna Temple Trust & Varanasi Administration",
    sourceUrl: "https://varanasi.nic.in/tourist-place/annapurna-temple/",
    sourceType: "government",
  },
  {
    name: "Shri Ram Janmabhoomi Temple Ayodhya",
    nameLocal: "श्री राम जन्मभूमि मंदिर अयोध्या",
    stateCode: "UP",
    districtName: "Ayodhya",
    localityName: "Ramkot, Ayodhya",
    latitude: 26.7956,
    longitude: 82.1942,
    mainDeity: "Bhagwan Shri Ram Lalla Virajman (Child Rama)",
    deities: ["Ram Lalla", "Lakshmana", "Bharata", "Shatrughna", "Hanuman"],
    templeType: "Supreme Vaishnavite Birthplace Pilgrimage & Mokshapuri",
    tradition: ["Vaishnavism", "Ramanandi Sampradaya"],
    architecture: "Monumental Gurjara-Chalukya Nagara Architecture in Bansi Paharpur Pink Sandstone",
    historicalPeriod: "Consecrated by Prana Pratishtha (January 2024 CE)",
    description: "The grand three-storeyed temple built on the sacred birthplace of Lord Rama in Ayodhya. Constructed entirely with pink sandstone without using iron or steel, supported by 392 intricately carved pillars and 44 teakwood doors.",
    officialWebsite: "https://srjbtkshetra.org",
    sourceRecordId: "UP-RJBT-AYO-004",
    sourceName: "Shri Ram Janmbhoomi Teerth Kshetra Trust",
    sourceUrl: "https://srjbtkshetra.org",
    sourceType: "government",
  },
  {
    name: "Hanuman Garhi Temple Ayodhya",
    nameLocal: "हनुमान गढ़ी मंदिर अयोध्या",
    stateCode: "UP",
    districtName: "Ayodhya",
    localityName: "Ayodhya",
    latitude: 26.7975,
    longitude: 82.2033,
    mainDeity: "Lord Hanuman (Seated in Lap of Mother Anjani)",
    deities: ["Hanuman", "Maa Anjani"],
    templeType: "Fortress Temple of Ayodhya's Protector",
    tradition: ["Vaishnavism", "Ramanandi Nirmohi Akhada"],
    architecture: "10th-Century Hilltop Fortified Bastion reached by 76 Wide Stone Steps",
    historicalPeriod: "Nawab Shuja-ud-Daula / Ancient Royal Fortification",
    description: "A monumental 10th-century four-sided fort complex with circular bastions in the center of Ayodhya. Custom mandates that pilgrims must first take the blessings of Lord Hanuman here before visiting Ram Janmabhoomi.",
    officialWebsite: "https://ayodhya.nic.in/tourist-place/hanuman-garhi/",
    sourceRecordId: "UP-TOUR-AYO-005",
    sourceName: "Hanuman Garhi Trust & Ayodhya District Administration",
    sourceUrl: "https://ayodhya.nic.in/tourist-place/hanuman-garhi/",
    sourceType: "government",
  },
  {
    name: "Shri Krishna Janmasthan Temple Complex",
    nameLocal: "श्री कृष्ण जन्मस्थान मंदिर मथुरा",
    stateCode: "UP",
    districtName: "Mathura",
    localityName: "Deeg Gate, Mathura",
    latitude: 27.5053,
    longitude: 77.6697,
    mainDeity: "Lord Krishna (Garbha Griha Birthplace)",
    deities: ["Lord Krishna", "Radha Rani", "Keshavdeva"],
    templeType: "Supreme Vaishnavite Birthplace Shrine & Mokshapuri",
    tradition: ["Vaishnavism", "Gaudiya", "Pushtimarg"],
    architecture: "Sandstone Nagara Temple Complex enclosing Ancient Prison Cell (Garbha Griha)",
    historicalPeriod: "Vajranabha (Grandson of Krishna) / Consecrated 1965",
    description: "The revered birthplace of Lord Krishna in the holy city of Mathura. The complex encloses the subterranean stone prison cell (Garbha Griha) where Krishna was born to Devaki and Vasudeva.",
    officialWebsite: "https://mathura.nic.in/tourist-place/sri-krishna-janmasthan/",
    sourceRecordId: "UP-BRAJ-MAT-006",
    sourceName: "Shri Krishna Janmasthan Seva Sansthan & UP Braj Teerth Vikas",
    sourceUrl: "https://mathura.nic.in/tourist-place/sri-krishna-janmasthan/",
    sourceType: "government",
  },
  {
    name: "Banke Bihari Temple Vrindavan",
    nameLocal: "बांके बिहारी मंदिर वृन्दावन",
    stateCode: "UP",
    districtName: "Mathura",
    localityName: "Vrindavan",
    latitude: 27.5811,
    longitude: 77.7011,
    mainDeity: "Banke Bihari (Lord Krishna in Tribhanga Stance)",
    deities: ["Banke Bihari"],
    templeType: "Heart of Braj Vaishnavite Pilgrimage",
    tradition: ["Vaishnavism", "Haridasi Sampradaya"],
    architecture: "Rajasthani Stone Architecture with Purdah Darshan Rhythm",
    historicalPeriod: "Swami Haridas (Established 1864 CE Current Structure)",
    description: "One of the most revered temples of Lord Krishna in Vrindavan. The curtain (purdah) before the deity is periodically drawn back and closed every few minutes, preventing devotees from fainting from Krishna's divine charm.",
    officialWebsite: "https://mathura.nic.in/tourist-place/bankey-bihari-temple/",
    sourceRecordId: "UP-BRAJ-MAT-007",
    sourceName: "Shree Bankey Bihari Mandir Trust & Mathura Administration",
    sourceUrl: "https://mathura.nic.in/tourist-place/bankey-bihari-temple/",
    sourceType: "government",
  },
  {
    name: "Maa Vindhyavasini Temple Vindhyachal",
    nameLocal: "माँ विंध्यवासिनी मंदिर विंध्याचल",
    stateCode: "UP",
    districtName: "Mirzapur",
    localityName: "Vindhyachal, Mirzapur",
    latitude: 25.1611,
    longitude: 82.5028,
    mainDeity: "Maa Vindhyavasini (Mahishasuramardini)",
    deities: ["Vindhyavasini", "Maha Kali (Kalikhoh)", "Maha Saraswati (Ashtabhuja)"],
    templeType: "Maha Shakti Peetha on River Ganga (Trikona Yatra)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Nagara Style Stone Sanctum with Newly Restored Vindhya Corridor",
    historicalPeriod: "Ancient Puranic Era (Mahabharata Invocations)",
    description: "Located on the banks of River Ganga in Mirzapur, revered as the permanent abode of Goddess Durga who incarnated as the daughter of Yashoda. Pilgrims complete the sacred triangular pilgrimage (Trikona Yatra).",
    officialWebsite: "https://mirzapur.nic.in/tourist-place/vindhyavasini-temple/",
    sourceRecordId: "UP-VIND-MIR-008",
    sourceName: "Shri Vindhya Panda Samaj & Mirzapur District Administration",
    sourceUrl: "https://mirzapur.nic.in/tourist-place/vindhyavasini-temple/",
    sourceType: "government",
  },
  {
    name: "Gorakhnath Temple Gorakhpur",
    nameLocal: "गोरखनाथ मंदिर गोरखपुर",
    stateCode: "UP",
    districtName: "Gorakhpur",
    localityName: "Gorakhnath Road, Gorakhpur",
    latitude: 26.7783,
    longitude: 83.3556,
    mainDeity: "Guru Gorakhnath & Shiva",
    deities: ["Guru Gorakhnath", "Matsyendranath", "Lord Shiva"],
    templeType: "Supreme Seat & Math of Nath Sampradaya",
    tradition: ["Nath Sampradaya", "Shaivism"],
    architecture: "Grand White Marble Complex with Mansarovar Lake",
    historicalPeriod: "Ancient Nath Tradition / Consecrated Modern Sanctum",
    description: "The international headquarters of the Nath monastic order, named after medieval yogi Guru Gorakhnath. World-famous for the month-long Khichdi Mela celebrated during Makar Sankranti with millions of pilgrims.",
    officialWebsite: "https://gorakhpur.nic.in/tourist-place/gorakhnath-temple/",
    sourceRecordId: "UP-GORK-GOR-009",
    sourceName: "Gorakhnath Temple Trust & Gorakhpur Administration",
    sourceUrl: "https://gorakhpur.nic.in/tourist-place/gorakhnath-temple/",
    sourceType: "government",
  },
  {
    name: "Kamadgiri Temple Chitrakoot",
    nameLocal: "कामदगिरि मंदिर चित्रकूट",
    stateCode: "UP",
    districtName: "Chitrakoot",
    localityName: "Kamadgiri Parikrama, Chitrakoot",
    latitude: 25.1783,
    longitude: 80.8667,
    mainDeity: "Kamadgiri (Lord Rama manifest as Holy Mountain)",
    deities: ["Lord Rama", "Sita", "Lakshmana", "Kamtanath"],
    templeType: "Sacred Forest Exile Pilgrimage (Ramayana Kshetra)",
    tradition: ["Vaishnavism"],
    architecture: "Circular 5-Kilometer Stone Parikrama Path lined with Ancient Shrines",
    historicalPeriod: "Epic Treta Yuga Ramayana Era",
    description: "The sacred hill of Kamtanath in Chitrakoot where Lord Rama, Goddess Sita, and Lakshmana spent eleven and a half years of their fourteen-year forest exile, surrounded by lush flora and sacred river Mandakini.",
    officialWebsite: "https://chitrakoot.nic.in/tourist-place/kamadgiri/",
    sourceRecordId: "UP-TOUR-CHI-010",
    sourceName: "Kamadgiri Mandir Trust & Chitrakoot District Administration",
    sourceUrl: "https://chitrakoot.nic.in/tourist-place/kamadgiri/",
    sourceType: "government",
  },
  {
    name: "Naimisharanya Lalita Devi & Chakra Tirtha",
    nameLocal: "नैमिषारण्य ललिता देवी व चक्र तीर्थ सीतापुर",
    stateCode: "UP",
    districtName: "Sitapur",
    localityName: "Naimisharanya, Misrikh",
    latitude: 27.3486,
    longitude: 80.4858,
    mainDeity: "Goddess Lalita Devi & Lord Vishnu",
    deities: ["Lalita Devi", "Vishnu", "Vyasa"],
    templeType: "Puranic Forest of 88,000 Sages & Maha Shakti Peetha (Heart/Hridaya)",
    tradition: ["Smartha", "Shaktism", "Vaishnavism"],
    architecture: "Circular Spring Reservoir (Chakra Kund) and Nagara Stone Temples",
    historicalPeriod: "Vedic & Puranic Era (Mahabharata Recitation)",
    description: "Situated on the banks of River Gomti in Sitapur district, where Brahma's mind-wheel (Manomaya Chakra) fell. The sacred forest where 88,000 rishis under Sage Shaunaka listened to the 18 Mahapuranas.",
    officialWebsite: "https://sitapur.nic.in/tourist-place/naimisharanya/",
    sourceRecordId: "UP-TOUR-SIT-011",
    sourceName: "Naimisharanya Teerth Vikas Parishad & Sitapur Administration",
    sourceUrl: "https://sitapur.nic.in/tourist-place/naimisharanya/",
    sourceType: "government",
  },
  {
    name: "Maa Shakumbhari Devi Temple",
    nameLocal: "माँ शाकम्भरी देवी मंदिर सहारनपुर",
    stateCode: "UP",
    districtName: "Saharanpur",
    localityName: "Jasmour, Behat",
    latitude: 30.2522,
    longitude: 77.6833,
    mainDeity: "Maa Shakumbhari (Goddess of Vegetation)",
    deities: ["Shakumbhari Devi", "Bhura Dev (Bhairav)"],
    templeType: "Ancient Shakta Peetha of the Shivalik Mountains",
    tradition: ["Shaktism"],
    architecture: "Mountain Ravine Marble and Stone Sanctuary",
    historicalPeriod: "Ancient Puranic Tradition",
    description: "Located in a serene riverbed ravine surrounded by the Shivalik mountain ranges in Saharanpur district. Goddess Durga manifested here as Shakumbhari to nourish living beings during a hundred-year drought.",
    officialWebsite: "https://saharanpur.nic.in/tourist-place/shakumbari-devi-temple/",
    sourceRecordId: "UP-TOUR-SAH-012",
    sourceName: "Shri Shakumbhari Devi Mandir Trust & Saharanpur Administration",
    sourceUrl: "https://saharanpur.nic.in/tourist-place/shakumbari-devi-temple/",
    sourceType: "government",
  },
  {
    name: "Alopi Devi Temple Prayagraj",
    nameLocal: "अलोपी देवी मंदिर प्रयागराज",
    stateCode: "UP",
    districtName: "Prayagraj",
    localityName: "Alopibagh, Prayagraj",
    latitude: 25.4339,
    longitude: 81.8725,
    mainDeity: "Alopi Mata (The Disappeared Goddess)",
    deities: ["Alopi Devi"],
    templeType: "Unique Shakti Peetha of the Triveni Sangam",
    tradition: ["Shaktism"],
    architecture: "Courtyard Temple featuring Sacred Doli (Palanquin) without Idol",
    historicalPeriod: "Ancient Prayag Teertha Tradition",
    description: "Situated near the sacred Triveni Sangam in Prayagraj. Unique among Shakti Peethas because it contains no stone idol; devotees worship a sanctified wooden palanquin (Doli) where Sati's final remains disappeared (Alop).",
    officialWebsite: "https://prayagraj.nic.in/tourist-place/alopi-devi-mandir/",
    sourceRecordId: "UP-TOUR-PRA-013",
    sourceName: "Alopi Devi Mandir Trust & Prayagraj Administration",
    sourceUrl: "https://prayagraj.nic.in/tourist-place/alopi-devi-mandir/",
    sourceType: "government",
  },
  {
    name: "Maa Pateshwari Devi Temple Devipatan",
    nameLocal: "माँ पाटेश्वरी देवी मंदिर देवीपाटन",
    stateCode: "UP",
    districtName: "Balrampur",
    localityName: "Tulsipur, Balrampur",
    latitude: 27.5333,
    longitude: 82.4167,
    mainDeity: "Maa Pateshwari",
    deities: ["Pateshwari Devi", "Karna"],
    templeType: "51 Shakti Peethas (Right Shoulder / Patam) & Nath Peetha",
    tradition: ["Shaktism", "Nath Sampradaya"],
    architecture: "Nagara Style Temple Complex with Ancient Surya Kund",
    historicalPeriod: "Consecrated by Guru Gorakhnath & King Vikramaditya",
    description: "Located near the Indo-Nepal border in Balrampur district, venerated as the spot where the right shoulder (Patam) of Sati fell. Features an ancient Surya Kund built by warrior Karna of the Mahabharata.",
    officialWebsite: "https://balrampur.nic.in/tourist-place/devipatan-temple/",
    sourceRecordId: "UP-TOUR-BAL-014",
    sourceName: "Devipatan Temple Trust & Balrampur District Administration",
    sourceUrl: "https://balrampur.nic.in/tourist-place/devipatan-temple/",
    sourceType: "government",
  },
  {
    name: "Sheetla Mata Mandir Kara Dham",
    nameLocal: "शीतला माता मंदिर कड़ा धाम कौशाम्बी",
    stateCode: "UP",
    districtName: "Kaushambi",
    localityName: "Kara, Sirathu",
    latitude: 25.6983,
    longitude: 81.3683,
    mainDeity: "Maa Sheetla (Goddess of Healing)",
    deities: ["Sheetla Devi"],
    templeType: "51 Shakti Peethas (Hands / Kara) on River Ganga",
    tradition: ["Shaktism"],
    architecture: "Ganga Riverside Fortified Stone Temple Complex",
    historicalPeriod: "1000 CE (Chandela & Gahadavala Eras)",
    description: "Perched along the high banks of holy River Ganga in Kaushambi district, where the hand (Kara) of Goddess Sati fell. Highly revered across northern India for curing heat ailments and infectious sickness.",
    officialWebsite: "https://kaushambi.nic.in/tourist-place/kara-dham/",
    sourceRecordId: "UP-TOUR-KAU-015",
    sourceName: "Kara Dham Trust & Kaushambi District Administration",
    sourceUrl: "https://kaushambi.nic.in/tourist-place/kara-dham/",
    sourceType: "government",
  },
  {
    name: "Nilkanth Mahadev Temple Kalinjar",
    nameLocal: "नीलकंठ महादेव मंदिर कालिंजर दुर्ग",
    stateCode: "UP",
    districtName: "Banda",
    localityName: "Kalinjar Fort, Banda",
    latitude: 25.0153,
    longitude: 80.4858,
    mainDeity: "Neelkanth (Eighteen-Armed Bhairava Shiva)",
    deities: ["Lord Shiva", "Kaal Bhairav"],
    templeType: "ASI Monument of National Importance inside Kalinjar Fort",
    tradition: ["Shaivism"],
    architecture: "Monumental Rock-Cut Cave Temple with Multi-Armed Giant Bas-Reliefs",
    historicalPeriod: "Chandela Dynasty / King Paramardi Deva (12th Century CE)",
    description: "Carved into the living cliff-side inside the historic impregnable Kalinjar fortress in Banda district, where Lord Shiva rested after drinking the cosmic poison. Features a monumental 24-foot rock-cut dancing Shiva.",
    officialWebsite: "https://asi.nic.in/monuments-kalinjar/",
    sourceRecordId: "ASI-UP-N-UP-C1",
    sourceName: "Archaeological Survey of India & Banda District Administration",
    sourceUrl: "https://asi.nic.in/monuments-kalinjar/",
    sourceType: "government",
  },
];

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ UTTAR PRADESH TEMPLE INGESTION ENGINE");
  console.log(`Source: Kashi Vishwanath Board, Ram Janmabhoomi, Braj Parishad & UP Tourism`);
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await processStateBatch(
    "UP Tourism, Kashi Vishwanath Board & Ram Janmabhoomi Trust",
    "https://uptourism.gov.in",
    UTTAR_PRADESH_AUTHORITATIVE_TEMPLES,
    { dryRun: isDryRun, parserVersion: "v1.0.0" }
  );

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);
