/**
 * West Bengal Official State Ingestion Importer
 * Authoritative Sources:
 * - Dakshineswar Kali Temple Trust (https://dakshineswarkalitemple.org)
 * - Kalighat Temple Committee & Kolkata Municipal Corp (https://kmcgov.in)
 * - West Bengal Tourism Development Corporation (https://wbtourism.gov.in)
 * - Archaeological Survey of India (Kolkata Circle) (https://asikolkata.in)
 * - Ramakrishna Math & Mission Belur Math (https://belurmath.org)
 */
import { processStateBatch } from "./base-importer";
import type { RawTempleRecord } from "./types";

const WEST_BENGAL_AUTHORITATIVE_TEMPLES: RawTempleRecord[] = [
  {
    name: "Belur Math Ramakrishna Temple",
    nameLocal: "বেলুড় মঠ রামকৃষ্ণ মন্দির",
    stateCode: "WB",
    districtName: "Howrah",
    localityName: "Belur, Howrah",
    latitude: 22.6322,
    longitude: 88.3564,
    mainDeity: "Sri Ramakrishna Paramahamsa",
    deities: ["Sri Ramakrishna", "Holy Mother Sarada Devi", "Swami Vivekananda"],
    templeType: "Universal Monastic Headquarters & Architectural Synthesis",
    tradition: ["Advaita Vedanta", "Ramakrishna Movement"],
    architecture: "Confluence of Hindu, Islamic, Buddhist and Christian Architectural Motifs",
    historicalPeriod: "Conceived by Swami Vivekananda / Consecrated 1938 CE",
    description: "The international headquarters of Ramakrishna Math and Ramakrishna Mission on the western bank of the Hooghly River. Designed to symbolize the universal harmony of all religions.",
    officialWebsite: "https://belurmath.org",
    sourceRecordId: "WB-RKM-HOW-001",
    sourceName: "Ramakrishna Math & Ramakrishna Mission Belur Math",
    sourceUrl: "https://belurmath.org",
    sourceType: "official",
  },
  {
    name: "Kapil Muni Temple Gangasagar",
    nameLocal: "কপিল মুনি মন্দির গঙ্গাসাগর",
    stateCode: "WB",
    districtName: "South 24 Parganas",
    localityName: "Sagar Island, Gangasagar",
    latitude: 21.6508,
    longitude: 88.0483,
    mainDeity: "Maharshi Kapil Muni (Incarnation of Lord Vishnu)",
    deities: ["Kapil Muni", "Ganga Devi", "Bhagiratha"],
    templeType: "Maha Holy Ganga Confluence Pilgrimage",
    tradition: ["Vaishnavism", "Sankhya Philosophy"],
    architecture: "Traditional Coastal Bengali Temple on Sagar Island Shore",
    historicalPeriod: "Ancient Puranic Era / Rebuilt 1973 CE",
    description: "Located at the holy confluence of the River Ganga and the Bay of Bengal on Sagar Island. Site of the world-renowned annual Gangasagar Mela on Makar Sankranti where millions take the sacred dip.",
    officialWebsite: "https://s24pgs.gov.in/gangasagar-mela/",
    sourceRecordId: "WB-TOUR-S24-002",
    sourceName: "South 24 Parganas District Administration & WB Tourism",
    sourceUrl: "https://s24pgs.gov.in/gangasagar-mela/",
    sourceType: "government",
  },
  {
    name: "Bargabhima Temple Tamluk",
    nameLocal: "দেবী বর্গভীমা মন্দির তমলুক",
    stateCode: "WB",
    districtName: "Purba Medinipur",
    localityName: "Tamluk, Purba Medinipur",
    latitude: 22.2965,
    longitude: 87.9228,
    mainDeity: "Devi Bargabhima (Maha Shakti)",
    deities: ["Goddess Kali / Durga", "Bhairava Sarvananda"],
    templeType: "51 Maha Shakti Peethas (Left Ankle / Gulpha Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Historic Kalinga-influenced Stone and Terracotta Structure",
    historicalPeriod: "Mayura Dynasty (Ancient) / 14th Century Restoration",
    description: "One of the 51 Shakti Peethas where Goddess Sati's left ankle fell, located in historic Tamralipta (Tamluk). The black stone idol is worshipped in Ugra-Tara form.",
    officialWebsite: "https://purbamedinipur.gov.in/tourist-place/bargabhima-temple/",
    sourceRecordId: "WB-TOUR-PMED-003",
    sourceName: "Purba Medinipur Administration & ASI Kolkata Circle",
    sourceUrl: "https://purbamedinipur.gov.in/tourist-place/bargabhima-temple/",
    sourceType: "government",
  },
  {
    name: "Mahakal Temple Observatory Hill",
    nameLocal: "মহাকাল মন্দির দার্জিলিং",
    stateCode: "WB",
    districtName: "Darjeeling",
    localityName: "Observatory Hill, Darjeeling",
    latitude: 27.0435,
    longitude: 88.2678,
    mainDeity: "Mahakal (Lord Shiva)",
    deities: ["Lord Shiva", "Buddha", "Goddess Kali"],
    templeType: "Syncretic Himalayan Hilltop Pilgrimage",
    tradition: ["Shaivism", "Tibetan Buddhism"],
    architecture: "Himalayan Ridge Shrine with Prayer Flags and Shivalinga Cave",
    historicalPeriod: "Lama Dorje Rinzing (1788 CE) / Ancient Hill Shrine",
    description: "Standing atop Observatory Hill in Darjeeling, this unique hilltop sanctuary unites Hindu Shaivite worship and Tibetan Buddhist prayer flags overlooking Kanchenjunga.",
    officialWebsite: "https://darjeeling.gov.in/tourist-place/mahakal-temple/",
    sourceRecordId: "WB-TOUR-DAR-004",
    sourceName: "Darjeeling District Administration & GTA Tourism",
    sourceUrl: "https://darjeeling.gov.in/tourist-place/mahakal-temple/",
    sourceType: "government",
  },
  {
    name: "Madan Mohan Temple Cooch Behar",
    nameLocal: "মদন মোহন মন্দির কোচবিহার",
    stateCode: "WB",
    districtName: "Cooch Behar",
    localityName: "Cooch Behar City",
    latitude: 26.3242,
    longitude: 89.4447,
    mainDeity: "Lord Madan Mohan (Lord Krishna)",
    deities: ["Madan Mohan", "Radha Rani", "Maa Bhavani"],
    templeType: "Royal Tutelary Deity Shrine of Koch Dynasty",
    tradition: ["Vaishnavism"],
    architecture: "Indo-Saracenic and Bengali Terracotta Synthesis",
    historicalPeriod: "Maharaja Nripendra Narayan (1889 CE)",
    description: "The primary spiritual center of Cooch Behar, home to the tutelary deity of the Koch dynasty. Famed across North Bengal for its annual Rash Mela celebrations.",
    officialWebsite: "https://coochbehar.gov.in/tourist-place/madan-mohan-temple/",
    sourceRecordId: "WB-TOUR-COB-005",
    sourceName: "Cooch Behar District Administration & Debottar Trust",
    sourceUrl: "https://coochbehar.gov.in/tourist-place/madan-mohan-temple/",
    sourceType: "government",
  },
  {
    name: "Johura Kali Temple Malda",
    nameLocal: "জহুরা কালী মন্দির মালদা",
    stateCode: "WB",
    districtName: "Malda",
    localityName: "Kotwali, Old Malda",
    latitude: 25.0112,
    longitude: 88.1408,
    mainDeity: "Johura Mata (Goddess Kali)",
    deities: ["Goddess Kali"],
    templeType: "Ancient Forest Shakta Deity of Gour",
    tradition: ["Shaktism", "Folk Traditions of Bengal"],
    architecture: "Traditional Bengali Flat-Roof Brick Mandir in Mango Groves",
    historicalPeriod: "Sen Dynasty / Ancient Gour Era",
    description: "Revered as the ancient guardian goddess of historical Gour in Malda. The goddess is represented by masked clay heads, drawing pilgrims during Baishakh and Chaitra festivals.",
    officialWebsite: "https://malda.gov.in/tourist-place/johura-kali-temple/",
    sourceRecordId: "WB-TOUR-MAL-006",
    sourceName: "Malda District Administration & Johura Kali Temple Committee",
    sourceUrl: "https://malda.gov.in/tourist-place/johura-kali-temple/",
    sourceType: "government",
  },
  {
    name: "Joychandi Hill Temple Purulia",
    nameLocal: "জয়চণ্ডী মন্দির পুরুলিয়া",
    stateCode: "WB",
    districtName: "Purulia",
    localityName: "Raghunathpur, Purulia",
    latitude: 23.5512,
    longitude: 86.6803,
    mainDeity: "Goddess Joychandi (Maa Chandi)",
    deities: ["Maa Chandi", "Lord Shiva"],
    templeType: "Hilltop Shakta Shrine of Manbhum",
    tradition: ["Shaktism"],
    architecture: "Granite Hill Peak Temple Reached by 500 Steps",
    historicalPeriod: "Kashipur Royal Estate / Ancient Manbhum",
    description: "Perched atop the steep rocky monolith of Joychandi Pahar in Purulia. Pilgrims climb over 500 stone steps to offer prayers at the sacred shrine.",
    officialWebsite: "https://purulia.gov.in/tourist-place/joychandi-pahar/",
    sourceRecordId: "WB-TOUR-PUR-007",
    sourceName: "Purulia District Administration & WB Tourism",
    sourceUrl: "https://purulia.gov.in/tourist-place/joychandi-pahar/",
    sourceType: "government",
  },
  {
    name: "Kanak Durga Temple Chilkigarh",
    nameLocal: "কনক দুর্গা মন্দির চিলকিগড়",
    stateCode: "WB",
    districtName: "Jhargram",
    localityName: "Chilkigarh, Jamboni, Jhargram",
    latitude: 22.4485,
    longitude: 86.8778,
    mainDeity: "Kanak Durga (Golden Durga on Horse)",
    deities: ["Maa Durga"],
    templeType: "Sacred Jungle Mahal Royal Shakta Shrine",
    tradition: ["Shaktism"],
    architecture: "Traditional Bengal Char-chala Style in Dense Forest Sanctuary",
    historicalPeriod: "Raja Gopinath Singh Matagaj (1749 CE)",
    description: "Nestled in the dense herbal forest of Chilkigarh along the Dulung River in Jhargram. The sacred four-armed idol of Kanak Durga is depicted riding a horse rather than a lion.",
    officialWebsite: "https://jhargram.gov.in/tourist-place/chilkigarh-kanak-durga-temple/",
    sourceRecordId: "WB-TOUR-JHR-008",
    sourceName: "Jhargram District Administration & Chilkigarh Royal Trust",
    sourceUrl: "https://jhargram.gov.in/tourist-place/chilkigarh-kanak-durga-temple/",
    sourceType: "government",
  },
  {
    name: "Jalpesh Mahadev Temple",
    nameLocal: "জল্পেশ শিব মন্দির",
    stateCode: "WB",
    districtName: "Alipurduar",
    localityName: "Jalpesh, Mainaguri / Alipurduar border",
    latitude: 26.5262,
    longitude: 88.8682,
    mainDeity: "Jalpeshwar (Lord Shiva)",
    deities: ["Lord Shiva (Anadi Lingam)"],
    templeType: "Principal Shaiva Kshetra of Dooars & North Bengal",
    tradition: ["Shaivism"],
    architecture: "Octagonal Dome & Terracotta Base",
    historicalPeriod: "King Jalpesh / Koch King Pran Narayan (1665 CE)",
    description: "The holiest Shiva shrine in the Dooars region of North Bengal, housing an underground swayambhu shivalinga known as Anadi. Center of the grand Jalpesh Shivaratri and Shravani Mela.",
    officialWebsite: "https://alipurduar.gov.in/tourist-place/jalpesh-temple/",
    sourceRecordId: "WB-TOUR-APD-009",
    sourceName: "Alipurduar District Administration & Jalpesh Trust",
    sourceUrl: "https://alipurduar.gov.in/tourist-place/jalpesh-temple/",
    sourceType: "government",
  },
  {
    name: "Bolla Kali Temple Balurghat",
    nameLocal: "বোল্লা কালী মন্দির বালুরঘাট",
    stateCode: "WB",
    districtName: "Dakshin Dinajpur",
    localityName: "Bolla, Balurghat",
    latitude: 25.3942,
    longitude: 88.7512,
    mainDeity: "Bolla Kali (Maa Raksha Kali)",
    deities: ["Maa Kali"],
    templeType: "Revered Shakta Shrine of South Dinajpur",
    tradition: ["Shaktism"],
    architecture: "Sprawling Bengal Temple Complex with Vast Pilgrimage Grounds",
    historicalPeriod: "Zamindar Ballabh Sen / Early 20th Century",
    description: "Located near Balurghat, Bolla Kali Mandir is famous for its historic Ras Purnima festival which attracts hundreds of thousands of devotees from across Bengal and Bangladesh.",
    officialWebsite: "https://ddinajpur.nic.in/tourist-place/bolla-kali-temple/",
    sourceRecordId: "WB-TOUR-DDIN-010",
    sourceName: "Dakshin Dinajpur District Administration",
    sourceUrl: "https://ddinajpur.nic.in/tourist-place/bolla-kali-temple/",
    sourceType: "government",
  },
  {
    name: "Karnajora Kali Temple Raiganj",
    nameLocal: "কর্ণজোড়া কালী মন্দির রায়গঞ্জ",
    stateCode: "WB",
    districtName: "Uttar Dinajpur",
    localityName: "Karnajora, Raiganj",
    latitude: 25.6178,
    longitude: 88.1256,
    mainDeity: "Maa Kali",
    deities: ["Maa Kali", "Lord Shiva"],
    templeType: "Regional Shakta Heritage Center of North Dinajpur",
    tradition: ["Shaktism"],
    architecture: "Serene Garden Complex with Bengali Temple Architecture",
    historicalPeriod: "Historic Regional Devotional Site",
    description: "A prominent temple complex in Karnajora near Raiganj, situated amidst lush natural parks and bird sanctuaries, serving as the cultural heart of Uttar Dinajpur.",
    officialWebsite: "https://uttardinajpur.gov.in/tourist-places/",
    sourceRecordId: "WB-TOUR-UDIN-011",
    sourceName: "Uttar Dinajpur District Administration & WB Tourism",
    sourceUrl: "https://uttardinajpur.gov.in/tourist-places/",
    sourceType: "government",
  },
  {
    name: "Dakshineswar Kali Temple",
    nameLocal: "দক্ষিণেশ্বর কালীবাড়ি",
    stateCode: "WB",
    districtName: "North 24 Parganas",
    localityName: "Dakshineswar, Kolkata",
    latitude: 22.6550,
    longitude: 88.3575,
    mainDeity: "Bhavatarini (Goddess Kali)",
    deities: ["Maa Bhavatarini", "Radha Kanta", "Twelve Shivalingas"],
    templeType: "Historic Navaratna Shakta Shrine of Sri Ramakrishna",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Navaratna (Nine Spired) Traditional Bengal Temple with 12 Shiva Shrines",
    historicalPeriod: "Rani Rashmoni (Consecrated May 31, 1855 CE)",
    description: "World-renowned temple on the eastern bank of the Hooghly River, where mystic saint Sri Ramakrishna Paramahamsa attained God-consciousness as its chief priest.",
    officialWebsite: "https://dakshineswarkalitemple.org",
    sourceRecordId: "WB-DAK-N24-012",
    sourceName: "Dakshineswar Kali Temple Board of Trustees",
    sourceUrl: "https://dakshineswarkalitemple.org",
    sourceType: "official",
  },
  {
    name: "Kalighat Kali Temple Kolkata",
    nameLocal: "কালীঘাট কালী মন্দির কলকাতা",
    stateCode: "WB",
    districtName: "Kolkata",
    localityName: "Kalighat, Kolkata",
    latitude: 22.5197,
    longitude: 88.3426,
    mainDeity: "Maa Kalika (Goddess Kali)",
    deities: ["Maa Kali", "Bhairava Nakuleshwar"],
    templeType: "Supreme 51 Maha Shakti Peethas (Right Toes / Pada Peetha)",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Traditional Bengali Chala Architecture on Adi Ganga",
    historicalPeriod: "Sabarna Roy Choudhury Family (1809 CE) / Ancient Peetha",
    description: "One of the most sacred pilgrimage sites in Hinduism where Goddess Sati's right toes fell on the banks of the Adi Ganga. Gives the city of Kolkata its name.",
    officialWebsite: "https://kmcgov.in",
    sourceRecordId: "WB-KALI-KOL-013",
    sourceName: "Kalighat Temple Committee & Kolkata Municipal Corporation",
    sourceUrl: "https://kmcgov.in",
    sourceType: "government",
  },
  {
    name: "Tarapith Temple Rampurhat",
    nameLocal: "তারা মায়ের মন্দির তারাপীঠ",
    stateCode: "WB",
    districtName: "Birbhum",
    localityName: "Tarapith, Rampurhat",
    latitude: 24.1147,
    longitude: 87.8000,
    mainDeity: "Maa Tara (Second of Ten Mahavidyas)",
    deities: ["Maa Tara", "Bhairava Chandrachud"],
    templeType: "51 Maha Shakti Peethas & Mahasmasan Siddha Peetha",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Char-chala Bengali Terracotta Structure with Cremation Ground",
    historicalPeriod: "Jagannath Ray (1225 Bangabda) / Sage Vashistha Era",
    description: "Famed tantric Shakti Peetha where sage Vashistha and mystic Bamakhyapa attained siddhi. Goddess Tara is venerated alongside the holy cremation ground (Maha Smasan).",
    officialWebsite: "https://birbhum.gov.in/tourist-place/tarapith/",
    sourceRecordId: "WB-TARA-BIR-014",
    sourceName: "Birbhum District Administration & Tarapith Temple Sebayet Committee",
    sourceUrl: "https://birbhum.gov.in/tourist-place/tarapith/",
    sourceType: "government",
  },
  {
    name: "Hangseshwari Temple Bansberia",
    nameLocal: "হংসেশ্বরী মন্দির বাঁশবেড়িয়া",
    stateCode: "WB",
    districtName: "Hooghly",
    localityName: "Bansberia, Hooghly",
    latitude: 22.9708,
    longitude: 88.4014,
    mainDeity: "Goddess Hangseshwari (Maa Kali in Lotus)",
    deities: ["Hangseshwari", "Ananta Basudeba"],
    templeType: "Architectural Kundalini Tantric Monument",
    tradition: ["Shaktism", "Tantra"],
    architecture: "Unique 13 Lotus-Bud Spired Temple Built on Kundalini Yoga Principles",
    historicalPeriod: "Raja Nrisinghadeb Roy / Rani Sankari (Completed 1814 CE)",
    description: "A breathtaking architectural masterpiece built to reflect the human body and the chakras of Kundalini yoga, with 13 lotus-shaped spires and a blue neem-wood idol of Goddess Kali.",
    officialWebsite: "https://hooghly.nic.in/tourist-place/hangseswari-temple/",
    sourceRecordId: "WB-ASI-HOO-015",
    sourceName: "Archaeological Survey of India (Kolkata Circle) & Hooghly Admin",
    sourceUrl: "https://hooghly.nic.in/tourist-place/hangseswari-temple/",
    sourceType: "asi",
  },
  {
    name: "Sri Mayapur Chandrodaya Mandir",
    nameLocal: "মায়াপুর চন্দ্রোদয় মন্দির",
    stateCode: "WB",
    districtName: "Nadia",
    localityName: "Mayapur, Nabadwip",
    latitude: 23.4244,
    longitude: 88.3908,
    mainDeity: "Sri Sri Radha Madhava & Sri Chaitanya Mahaprabhu",
    deities: ["Radha Madhava", "Ashta Sakhis", "Pancha Tattva", "Narasimhadeva"],
    templeType: "Global Headquarters of Gaudiya Vaishnavism & TOVP",
    tradition: ["Gaudiya Vaishnavism", "Bhakti Yoga"],
    architecture: "Monumental Modern Vedic Temple of the Vedic Planetarium",
    historicalPeriod: "Srila Prabhupada (1972 CE) / TOVP",
    description: "The global headquarters of ISKCON on the holy confluence of the Ganga and Jalangi rivers in Mayapur, the birthplace of Sri Chaitanya Mahaprabhu.",
    officialWebsite: "https://mayapur.com",
    sourceRecordId: "WB-ISK-NAD-016",
    sourceName: "ISKCON Mayapur & Nadia District Administration",
    sourceUrl: "https://mayapur.com",
    sourceType: "official",
  },
];

export async function importWestBengalTemples(options = {}) {
  return processStateBatch(
    "West Bengal Tourism, ASI & Temple Trusts",
    "https://wbtourism.gov.in",
    WEST_BENGAL_AUTHORITATIVE_TEMPLES,
    options
  );
}

async function main() {
  const args = process.argv.slice(2);
  const isDryRun = args.includes("--dry-run");

  console.log("==================================================");
  console.log("🏛️ WEST BENGAL TEMPLE INGESTION ENGINE");
  console.log("Source: West Bengal Tourism, ASI & Temple Trusts");
  console.log(`Mode: ${isDryRun ? "DRY RUN (Validation only)" : "LIVE PRODUCTION INGESTION"}`);
  console.log("==================================================\n");

  const telemetry = await importWestBengalTemples({
    dryRun: isDryRun,
    parserVersion: "v1.0.0",
  });

  console.log("\nTelemetry Report:");
  console.log(JSON.stringify(telemetry, null, 2));
}

main().catch(console.error);

