import { existsSync, writeFileSync } from "node:fs";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../src/generated/prisma/client";
import { ALL_INDIA_DESTINATIONS } from "../../src/lib/destinations/all-india-data";

if (existsSync(".env.local")) process.loadEnvFile(".env.local");
if (existsSync(".env")) process.loadEnvFile(".env");

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

export interface CanonicalBenchmarkSpec {
  id: string;
  benchmarkName: string;
  canonicalName: string;
  expectedState: string;
  expectedStateCode: string;
  expectedDistrict: string;
  expectedLocality: string;
  latitude: number;
  longitude: number;
  deity: string;
  circuit?: string;
  primaryKeywords: string[];
  secondaryKeywords?: string[];
  negativeKeywords: string[];
  officialSource: string;
  officialSourceUrl: string;
}

export const CANONICAL_BENCHMARK_SPECS: CanonicalBenchmarkSpec[] = [
  // --- ANDHRA PRADESH ---
  {
    id: "bm-ap-tirumala-venkateswara",
    benchmarkName: "Tirumala Venkateswara",
    canonicalName: "Sri Venkateswara Swamy Vaari Temple",
    expectedState: "Andhra Pradesh",
    expectedStateCode: "AP",
    expectedDistrict: "Tirupati",
    expectedLocality: "Tirumala",
    latitude: 13.6833,
    longitude: 79.3472,
    deity: "Lord Venkateswara / Srinivasa / Balaji",
    circuit: "Char Dham / Divya Desam",
    primaryKeywords: ["sri venkateswara", "venkateswara swamy", "tirumala temple", "tirupati balaji"],
    negativeKeywords: ["varaha", "bedi anjaneya", "govindaraja", "kodandarama", "dwaraka tirumala", "padmavathi"],
    officialSource: "Tirumala Tirupati Devasthanams (TTD)",
    officialSourceUrl: "https://www.tirumala.org/"
  },
  {
    id: "bm-ap-srisailam-mallikarjuna",
    benchmarkName: "Srisailam Mallikarjuna",
    canonicalName: "Sri Bhramaramba Mallikarjuna Swamy Temple",
    expectedState: "Andhra Pradesh",
    expectedStateCode: "AP",
    expectedDistrict: "Nandyal",
    expectedLocality: "Srisailam",
    latitude: 16.0739,
    longitude: 78.8683,
    deity: "Lord Shiva (Mallikarjuna) & Goddess Bhramaramba",
    circuit: "12 Jyotirlingas / 51 Shakti Peethas",
    primaryKeywords: ["bhramaramba mallikarjuna", "mallikarjuna swamy temple, srisailam", "srisailam temple"],
    negativeKeywords: ["araku", "basaralu", "nadkalsi"],
    officialSource: "Sri Srisaila Devasthanam",
    officialSourceUrl: "https://www.srisailadevasthanam.org/"
  },
  {
    id: "bm-ap-srikalahasti",
    benchmarkName: "Srikalahasteeswara",
    canonicalName: "Sri Kalahasteeswara Temple",
    expectedState: "Andhra Pradesh",
    expectedStateCode: "AP",
    expectedDistrict: "Tirupati",
    expectedLocality: "Srikalahasti",
    latitude: 13.7498,
    longitude: 79.6984,
    deity: "Lord Shiva (Vayu Linga) & Goddess Gnanaprasunambika",
    circuit: "Pancha Bhoota Sthalam (Air/Vayu)",
    primaryKeywords: ["kalahasteeswara", "srikalahasti temple"],
    negativeKeywords: ["madurai"],
    officialSource: "Sri Kalahasteeswara Swamy Devasthanam",
    officialSourceUrl: "https://srikalahasthitemple.com/"
  },
  {
    id: "bm-ap-simhachalam",
    benchmarkName: "Simhachalam",
    canonicalName: "Varaha Lakshmi Narasimha Temple, Simhachalam",
    expectedState: "Andhra Pradesh",
    expectedStateCode: "AP",
    expectedDistrict: "Visakhapatnam",
    expectedLocality: "Simhachalam",
    latitude: 17.7667,
    longitude: 83.2500,
    deity: "Lord Varaha Lakshmi Narasimha",
    circuit: "Nava Narasimha Kshetra",
    primaryKeywords: ["simhachalam", "varaha lakshmi narasimha"],
    negativeKeywords: ["ahobilam"],
    officialSource: "Simhachalam Devasthanam",
    officialSourceUrl: "https://simhachalamdevasthanam.net/"
  },
  {
    id: "bm-ap-kanaka-durga",
    benchmarkName: "Kanaka Durga",
    canonicalName: "Sri Durga Malleswara Swamy Varla Devasthanam (Kanaka Durga Temple)",
    expectedState: "Andhra Pradesh",
    expectedStateCode: "AP",
    expectedDistrict: "NTR",
    expectedLocality: "Vijayawada",
    latitude: 16.5150,
    longitude: 80.6050,
    deity: "Goddess Kanaka Durga",
    circuit: "Major Devi Kshetra",
    primaryKeywords: ["kanaka durga", "indrakeeladri", "durga malleswara"],
    negativeKeywords: [],
    officialSource: "Sri Durga Malleswara Swamy Varla Devasthanam",
    officialSourceUrl: "https://kanakadurgamma.org/"
  },
  {
    id: "bm-ap-ahobilam",
    benchmarkName: "Ahobilam",
    canonicalName: "Ahobilam Nava Narasimha Swamy Temple Complex",
    expectedState: "Andhra Pradesh",
    expectedStateCode: "AP",
    expectedDistrict: "Nandyal",
    expectedLocality: "Ahobilam",
    latitude: 15.1340,
    longitude: 78.7290,
    deity: "Nava Narasimha (Nine Forms of Lord Narasimha)",
    circuit: "108 Divya Desams / Nava Narasimha",
    primaryKeywords: ["ahobilam", "nava narasimha"],
    negativeKeywords: [],
    officialSource: "Sri Ahobila Mutt",
    officialSourceUrl: "https://ahobilamutt.org/"
  },

  // --- ASSAM ---
  {
    id: "bm-as-kamakhya",
    benchmarkName: "Kamakhya",
    canonicalName: "Maa Kamakhya Devalaya",
    expectedState: "Assam",
    expectedStateCode: "AS",
    expectedDistrict: "Kamrup Metropolitan",
    expectedLocality: "Guwahati",
    latitude: 26.1664,
    longitude: 91.7056,
    deity: "Goddess Kamakhya",
    circuit: "51 Shakti Peethas (Yoni Peetha)",
    primaryKeywords: ["kamakhya", "nilachal hill"],
    negativeKeywords: [],
    officialSource: "Maa Kamakhya Devalaya Management Board",
    officialSourceUrl: "https://www.maakamakhya.org/"
  },
  {
    id: "bm-as-umananda",
    benchmarkName: "Umananda",
    canonicalName: "Umananda Devalaya, Peacock Island",
    expectedState: "Assam",
    expectedStateCode: "AS",
    expectedDistrict: "Kamrup Metropolitan",
    expectedLocality: "Guwahati",
    latitude: 26.1925,
    longitude: 91.7456,
    deity: "Lord Shiva (Umananda)",
    circuit: "Brahmaputra Sacred Geography",
    primaryKeywords: ["umananda", "peacock island"],
    negativeKeywords: [],
    officialSource: "Assam Tourism Development Corporation",
    officialSourceUrl: "https://tourism.assam.gov.in/"
  },
  {
    id: "bm-as-navagraha",
    benchmarkName: "Navagraha Temple",
    canonicalName: "Navagraha Temple, Chitrasal Hill",
    expectedState: "Assam",
    expectedStateCode: "AS",
    expectedDistrict: "Kamrup Metropolitan",
    expectedLocality: "Guwahati",
    latitude: 26.1722,
    longitude: 91.7458,
    deity: "Nine Planetary Deities (Navagrahas)",
    circuit: "Ancient Astronomical Shrines",
    primaryKeywords: ["navagraha temple", "chitrasal hill"],
    negativeKeywords: [],
    officialSource: "Assam Tourism",
    officialSourceUrl: "https://tourism.assam.gov.in/"
  },
  {
    id: "bm-as-batadrava",
    benchmarkName: "Batadrava Than",
    canonicalName: "Batadrava Than (Sri Sri Batadrava Than, Bordowa)",
    expectedState: "Assam",
    expectedStateCode: "AS",
    expectedDistrict: "Nagaon",
    expectedLocality: "Bordowa",
    latitude: 26.3740,
    longitude: 92.5950,
    deity: "Mahapurush Srimanta Sankardeva Vaishnava Center",
    circuit: "Neo-Vaishnavite Satras of Assam",
    primaryKeywords: ["batadrava than", "bordowa than"],
    negativeKeywords: [],
    officialSource: "Sri Sri Batadrava Than Management Committee",
    officialSourceUrl: "https://nagaon.gov.in/"
  },

  // --- BIHAR ---
  {
    id: "bm-br-mahabodhi",
    benchmarkName: "Mahabodhi",
    canonicalName: "Mahabodhi Temple Complex (UNESCO World Heritage)",
    expectedState: "Bihar",
    expectedStateCode: "BR",
    expectedDistrict: "Gaya",
    expectedLocality: "Bodh Gaya",
    latitude: 24.6959,
    longitude: 84.9914,
    deity: "Gautama Buddha / Sacred Bodhi Tree",
    circuit: "UNESCO World Heritage / Buddhist Circuit",
    primaryKeywords: ["mahabodhi", "bodh gaya temple"],
    negativeKeywords: [],
    officialSource: "Bodhgaya Temple Management Committee (BTMC) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/1056/"
  },
  {
    id: "bm-br-vishnupad",
    benchmarkName: "Vishnupad",
    canonicalName: "Vishnupad Temple, Gaya",
    expectedState: "Bihar",
    expectedStateCode: "BR",
    expectedDistrict: "Gaya",
    expectedLocality: "Gaya",
    latitude: 24.7770,
    longitude: 85.0064,
    deity: "Lord Vishnu (Dharmasila Footprint)",
    circuit: "Pinda Daan Pilgrimage Circuit",
    primaryKeywords: ["vishnupad", "falgu river temple"],
    negativeKeywords: [],
    officialSource: "Gaya District Administration / Bihar Tourism",
    officialSourceUrl: "https://tourism.bihar.gov.in/"
  },
  {
    id: "bm-br-mundeshwari",
    benchmarkName: "Mundeshwari",
    canonicalName: "Mundeshwari Devi Temple",
    expectedState: "Bihar",
    expectedStateCode: "BR",
    expectedDistrict: "Kaimur",
    expectedLocality: "Ramgarh",
    latitude: 25.0347,
    longitude: 83.5683,
    deity: "Goddess Mundeshwari & Lord Shiva",
    circuit: "Oldest Functioning Hindu Temple (108 CE)",
    primaryKeywords: ["mundeshwari"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI) / Bihar Tourism",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-br-deo-sun",
    benchmarkName: "Deo Sun Temple",
    canonicalName: "Deo Sun Temple (Deo Surya Mandir)",
    expectedState: "Bihar",
    expectedStateCode: "BR",
    expectedDistrict: "Aurangabad",
    expectedLocality: "Deo",
    latitude: 24.6588,
    longitude: 84.4370,
    deity: "Surya Bhagwan (Sun God)",
    circuit: "Chhath Mahaparva Epicenter",
    primaryKeywords: ["deo sun temple", "deo surya mandir"],
    negativeKeywords: ["konark", "modhera"],
    officialSource: "Bihar State Tourism Development Corporation",
    officialSourceUrl: "https://tourism.bihar.gov.in/"
  },

  // --- CHHATTISGARH ---
  {
    id: "bm-cg-danteshwari",
    benchmarkName: "Danteshwari",
    canonicalName: "Maa Danteshwari Temple, Dantewada",
    expectedState: "Chhattisgarh",
    expectedStateCode: "CG",
    expectedDistrict: "Dantewada",
    expectedLocality: "Dantewada",
    latitude: 18.8942,
    longitude: 81.3528,
    deity: "Goddess Danteshwari",
    circuit: "51 Shakti Peethas (Kuldevi of Bastar)",
    primaryKeywords: ["danteshwari"],
    negativeKeywords: [],
    officialSource: "Dantewada District Administration / Chhattisgarh Tourism",
    officialSourceUrl: "https://dantewada.nic.in/"
  },
  {
    id: "bm-cg-bhoramdeo",
    benchmarkName: "Bhoramdeo",
    canonicalName: "Bhoramdeo Temple Complex (Khajuraho of Chhattisgarh)",
    expectedState: "Chhattisgarh",
    expectedStateCode: "CG",
    expectedDistrict: "Kabirdham",
    expectedLocality: "Chhapri / Kawardha",
    latitude: 22.1228,
    longitude: 81.1472,
    deity: "Lord Shiva (Bhoramdeo)",
    circuit: "Nagara Architecture Heritage Circuit",
    primaryKeywords: ["bhoramdeo"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI) / CG Tourism",
    officialSourceUrl: "https://chhattisgarhtourism.cg.gov.in/"
  },

  // --- GOA ---
  {
    id: "bm-ga-mangueshi",
    benchmarkName: "Mangueshi",
    canonicalName: "Shri Manguesh Temple, Priol",
    expectedState: "Goa",
    expectedStateCode: "GA",
    expectedDistrict: "North Goa",
    expectedLocality: "Priol",
    latitude: 15.3969,
    longitude: 73.9689,
    deity: "Lord Shiva (Manguesh)",
    circuit: "Goan Saraswat Heritage Shrines",
    primaryKeywords: ["manguesh", "mangeshi"],
    negativeKeywords: [],
    officialSource: "Shri Manguesh Saunsthan",
    officialSourceUrl: "https://www.goatourism.gov.in/"
  },
  {
    id: "bm-ga-shantadurga",
    benchmarkName: "Shantadurga",
    canonicalName: "Shri Shantadurga Temple, Kavlem",
    expectedState: "Goa",
    expectedStateCode: "GA",
    expectedDistrict: "South Goa",
    expectedLocality: "Kavlem",
    latitude: 15.3622,
    longitude: 73.9856,
    deity: "Goddess Shantadurga",
    circuit: "Goan Temple Architecture",
    primaryKeywords: ["shantadurga temple, kavlem", "shri shantadurga"],
    negativeKeywords: [],
    officialSource: "Shri Shantadurga Saunsthan",
    officialSourceUrl: "https://shrishantadurga.com/"
  },
  {
    id: "bm-ga-mahalasa",
    benchmarkName: "Mahalasa",
    canonicalName: "Shri Mahalasa Narayani Temple, Mardol",
    expectedState: "Goa",
    expectedStateCode: "GA",
    expectedDistrict: "North Goa",
    expectedLocality: "Mardol",
    latitude: 15.3931,
    longitude: 73.9786,
    deity: "Goddess Mahalasa Narayani (Mohini Avatar)",
    circuit: "Deepastambha Architectural Circuit",
    primaryKeywords: ["mahalasa narayani", "mahalasa temple"],
    negativeKeywords: [],
    officialSource: "Shri Mahalasa Saunsthan",
    officialSourceUrl: "https://www.goatourism.gov.in/"
  },

  // --- GUJARAT ---
  {
    id: "bm-gj-somnath",
    benchmarkName: "Somnath",
    canonicalName: "Shree Somnath Jyotirlinga Temple",
    expectedState: "Gujarat",
    expectedStateCode: "GJ",
    expectedDistrict: "Gir Somnath",
    expectedLocality: "Prabhas Patan",
    latitude: 20.8880,
    longitude: 70.4012,
    deity: "Lord Shiva (First of the 12 Jyotirlingas)",
    circuit: "12 Jyotirlingas / Triveni Sangam",
    primaryKeywords: ["somnath temple", "shree somnath", "prabhas patan"],
    negativeKeywords: ["dungarpur", "deo somnath"],
    officialSource: "Shree Somnath Trust",
    officialSourceUrl: "https://somnath.org/"
  },
  {
    id: "bm-gj-dwarkadhish",
    benchmarkName: "Dwarkadhish",
    canonicalName: "Dwarkadhish Temple (Jagat Mandir), Dwarka",
    expectedState: "Gujarat",
    expectedStateCode: "GJ",
    expectedDistrict: "Devbhumi Dwarka",
    expectedLocality: "Dwarka",
    latitude: 22.2376,
    longitude: 68.9678,
    deity: "Lord Krishna (Dwarkadhish / King of Dwarka)",
    circuit: "Char Dham / Sapta Puri / 108 Divya Desams",
    primaryKeywords: ["dwarkadhish temple", "jagat mandir", "dwarka temple"],
    negativeKeywords: [],
    officialSource: "Shree Dwarkadhish Mandir Devasthan Samiti",
    officialSourceUrl: "https://dwarkadhish.org/"
  },
  {
    id: "bm-gj-nageshwar",
    benchmarkName: "Nageshwar",
    canonicalName: "Shree Nageshwar Jyotirlinga Temple, Darukavana",
    expectedState: "Gujarat",
    expectedStateCode: "GJ",
    expectedDistrict: "Devbhumi Dwarka",
    expectedLocality: "Daarukavanam / Dwarka",
    latitude: 22.3353,
    longitude: 69.0531,
    deity: "Lord Shiva (Nageshwar Jyotirlinga)",
    circuit: "12 Jyotirlingas",
    primaryKeywords: ["nageshwar jyotirlinga", "nageshwar temple"],
    negativeKeywords: ["aundha nagnath"],
    officialSource: "Gujarat Tourism / Devasthan Trust",
    officialSourceUrl: "https://www.gujarattourism.com/"
  },
  {
    id: "bm-gj-ambaji",
    benchmarkName: "Ambaji",
    canonicalName: "Shri Arasuri Ambaji Mata Temple",
    expectedState: "Gujarat",
    expectedStateCode: "GJ",
    expectedDistrict: "Banaskantha",
    expectedLocality: "Ambaji",
    latitude: 24.3314,
    longitude: 72.8533,
    deity: "Goddess Amba (Viso Yantra)",
    circuit: "51 Shakti Peethas (Heart of Sati)",
    primaryKeywords: ["ambaji mata", "arasuri ambaji", "gabbar hill"],
    negativeKeywords: [],
    officialSource: "Shree Arasuri Ambaji Mata Devasthan Trust",
    officialSourceUrl: "https://www.ambajitemple.in/"
  },
  {
    id: "bm-gj-modhera",
    benchmarkName: "Modhera",
    canonicalName: "Sun Temple, Modhera (ASI Protected Monument)",
    expectedState: "Gujarat",
    expectedStateCode: "GJ",
    expectedDistrict: "Mehsana",
    expectedLocality: "Modhera",
    latitude: 23.5835,
    longitude: 72.1331,
    deity: "Surya Bhagwan (Sun God) / Solanki Architecture",
    circuit: "Ancient Sun Temples / Maru-Gurjara Architecture",
    primaryKeywords: ["sun temple, modhera", "modhera sun temple"],
    negativeKeywords: ["konark", "deo sun"],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-gj-akshardham",
    benchmarkName: "Akshardham",
    canonicalName: "Swaminarayan Akshardham, Gandhinagar",
    expectedState: "Gujarat",
    expectedStateCode: "GJ",
    expectedDistrict: "Gandhinagar",
    expectedLocality: "Gandhinagar",
    latitude: 23.2294,
    longitude: 72.6744,
    deity: "Bhagwan Swaminarayan",
    circuit: "Modern Monumental Architecture",
    primaryKeywords: ["akshardham, gandhinagar", "swaminarayan akshardham"],
    negativeKeywords: [],
    officialSource: "BAPS Swaminarayan Sanstha",
    officialSourceUrl: "https://akshardham.com/gujarat/"
  },

  // --- HARYANA ---
  {
    id: "bm-hr-mansa-devi",
    benchmarkName: "Mansa Devi",
    canonicalName: "Mata Mansa Devi Temple, Panchkula",
    expectedState: "Haryana",
    expectedStateCode: "HR",
    expectedDistrict: "Panchkula",
    expectedLocality: "Panchkula / Bilaspur",
    latitude: 30.7083,
    longitude: 76.8778,
    deity: "Mata Mansa Devi",
    circuit: "Shivalik Devi Pilgrimage",
    primaryKeywords: ["mata mansa devi temple, panchkula", "mansa devi panchkula"],
    negativeKeywords: ["haridwar"],
    officialSource: "Mata Mansa Devi Shrine Board",
    officialSourceUrl: "https://mansadevi.org.in/"
  },
  {
    id: "bm-hr-sheetla-mata",
    benchmarkName: "Sheetla Mata",
    canonicalName: "Sheetla Mata Temple, Gurugram",
    expectedState: "Haryana",
    expectedStateCode: "HR",
    expectedDistrict: "Gurugram",
    expectedLocality: "Gurugram",
    latitude: 28.4722,
    longitude: 77.0264,
    deity: "Mata Sheetla (Kripa / Kripi Devi)",
    circuit: "Historic Haryana Devi Shrines",
    primaryKeywords: ["sheetla mata temple", "sheetla mata mandir", "sheetla mata", "sheetla mata gurugram"],
    negativeKeywords: [],
    officialSource: "Shri Mata Sheetla Devi Shrine Board",
    officialSourceUrl: "https://gurgaon.gov.in/"
  },

  // --- HIMACHAL PRADESH ---
  {
    id: "bm-hp-jwala-ji",
    benchmarkName: "Jwala Ji",
    canonicalName: "Maa Jwala Ji Temple, Jwalamukhi",
    expectedState: "Himachal Pradesh",
    expectedStateCode: "HP",
    expectedDistrict: "Kangra",
    expectedLocality: "Jwalamukhi",
    latitude: 31.8767,
    longitude: 76.3236,
    deity: "Goddess Jwalamukhi (Eternal Natural Blue Flame)",
    circuit: "51 Shakti Peethas (Tongue of Sati)",
    primaryKeywords: ["jwala ji", "jwalamukhi temple"],
    negativeKeywords: [],
    officialSource: "Temple Trust Jwalamukhi / HP Tourism",
    officialSourceUrl: "https://himachaltourism.gov.in/"
  },
  {
    id: "bm-hp-naina-devi",
    benchmarkName: "Naina Devi",
    canonicalName: "Maa Naina Devi Temple, Bilaspur",
    expectedState: "Himachal Pradesh",
    expectedStateCode: "HP",
    expectedDistrict: "Bilaspur",
    expectedLocality: "Naina Devi",
    latitude: 31.3061,
    longitude: 76.5369,
    deity: "Maa Naina Devi (Eyes of Sati)",
    circuit: "51 Shakti Peethas",
    primaryKeywords: ["naina devi temple, bilaspur", "shri naina devi"],
    negativeKeywords: ["nainital"],
    officialSource: "Shri Naina Devi Shrine Board",
    officialSourceUrl: "https://bilaspur.hp.gov.in/"
  },
  {
    id: "bm-hp-chintpurni",
    benchmarkName: "Chintpurni",
    canonicalName: "Mata Chintpurni Devi Temple (Chhinnamastika Dham)",
    expectedState: "Himachal Pradesh",
    expectedStateCode: "HP",
    expectedDistrict: "Una",
    expectedLocality: "Chintpurni",
    latitude: 31.8083,
    longitude: 76.1264,
    deity: "Goddess Chinnamastika / Chintpurni",
    circuit: "51 Shakti Peethas (Feet of Sati)",
    primaryKeywords: ["chintpurni", "chhinnamastika dham"],
    negativeKeywords: [],
    officialSource: "Mata Chintpurni Shrine Board",
    officialSourceUrl: "https://matachintpurni.com/"
  },
  {
    id: "bm-hp-chamunda-devi",
    benchmarkName: "Chamunda Devi",
    canonicalName: "Chamunda Nandikeshwar Dham, Kangra",
    expectedState: "Himachal Pradesh",
    expectedStateCode: "HP",
    expectedDistrict: "Kangra",
    expectedLocality: "Dharamsala / Padar",
    latitude: 32.1481,
    longitude: 76.4172,
    deity: "Maa Chamunda Devi & Lord Nandikeshwar",
    circuit: "Kangra Valley Devi Shrines",
    primaryKeywords: ["chamunda devi", "chamunda nandikeshwar"],
    negativeKeywords: [],
    officialSource: "HP Tourism / Kangra District Administration",
    officialSourceUrl: "https://himachaltourism.gov.in/"
  },
  {
    id: "bm-hp-baijnath",
    benchmarkName: "Baijnath",
    canonicalName: "Baijnath Temple (Vaidyanath Shiva Temple), Kangra",
    expectedState: "Himachal Pradesh",
    expectedStateCode: "HP",
    expectedDistrict: "Kangra",
    expectedLocality: "Baijnath",
    latitude: 32.0522,
    longitude: 76.6492,
    deity: "Lord Shiva (Vaidyanath)",
    circuit: "Nagara Architecture / Himalayan Shrines",
    primaryKeywords: ["baijnath temple, kangra", "baijnath shiva temple"],
    negativeKeywords: ["deoghar", "baidyanath dham", "almora"],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-hp-hidimba-devi",
    benchmarkName: "Hidimba Devi",
    canonicalName: "Hidimba Devi Temple (Dhungari Temple), Manali",
    expectedState: "Himachal Pradesh",
    expectedStateCode: "HP",
    expectedDistrict: "Kullu",
    expectedLocality: "Manali",
    latitude: 32.2483,
    longitude: 77.1814,
    deity: "Hidimba Devi (Wife of Bhima)",
    circuit: "Pagoda Wooden Temple Architecture",
    primaryKeywords: ["hidimba devi", "dhungari temple", "hadimba temple"],
    negativeKeywords: [],
    officialSource: "HP Tourism Development Corporation",
    officialSourceUrl: "https://himachaltourism.gov.in/"
  },

  // --- JAMMU & KASHMIR ---
  {
    id: "bm-jk-vaishno-devi",
    benchmarkName: "Vaishno Devi",
    canonicalName: "Shri Mata Vaishno Devi Shrine, Katra",
    expectedState: "Jammu and Kashmir",
    expectedStateCode: "JK",
    expectedDistrict: "Reasi",
    expectedLocality: "Katra / Trikuta Hills",
    latitude: 33.0308,
    longitude: 74.9490,
    deity: "Mata Vaishno Devi (Maha Kali, Maha Lakshmi, Maha Saraswati Pindis)",
    circuit: "National Trikuta Holy Cave Pilgrimage",
    primaryKeywords: ["mata vaishno devi", "vaishno devi shrine", "bhawan katra"],
    negativeKeywords: [],
    officialSource: "Shri Mata Vaishno Devi Shrine Board (SMVDSB)",
    officialSourceUrl: "https://www.maavaishnodevi.org/"
  },
  {
    id: "bm-jk-amarnath",
    benchmarkName: "Amarnath",
    canonicalName: "Shri Amarnath Cave Shrine",
    expectedState: "Jammu and Kashmir",
    expectedStateCode: "JK",
    expectedDistrict: "Anantnag",
    expectedLocality: "Pahalgam / Baltal",
    latitude: 34.2156,
    longitude: 75.5039,
    deity: "Lord Shiva (Natural Ice Lingam)",
    circuit: "51 Shakti Peethas / Holy Cave Yatra",
    primaryKeywords: ["amarnath cave", "shri amarnathji", "amarnath temple", "holy cave shrine of shri amarnathji", "amarnathji"],
    negativeKeywords: [],
    officialSource: "Shri Amarnathji Shrine Board (SASB)",
    officialSourceUrl: "https://jksasb.nic.in/"
  },
  {
    id: "bm-jk-shankaracharya",
    benchmarkName: "Shankaracharya",
    canonicalName: "Shankaracharya Temple (Jyeshteshwara Temple), Srinagar",
    expectedState: "Jammu and Kashmir",
    expectedStateCode: "JK",
    expectedDistrict: "Srinagar",
    expectedLocality: "Gopadari Hill / Srinagar",
    latitude: 34.0722,
    longitude: 74.8467,
    deity: "Lord Shiva (Jyeshteshwara)",
    circuit: "Adi Shankara Circuit",
    primaryKeywords: ["shankaracharya temple", "jyeshteshwara"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI) / J&K Tourism",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-jk-martand",
    benchmarkName: "Martand",
    canonicalName: "Martand Sun Temple Ruins (ASI Monument of National Importance)",
    expectedState: "Jammu and Kashmir",
    expectedStateCode: "JK",
    expectedDistrict: "Anantnag",
    expectedLocality: "Mattan / Anantnag",
    latitude: 33.7464,
    longitude: 75.2208,
    deity: "Surya Bhagwan (Sun God) / Karkota Dynasty",
    circuit: "Ancient Kashmiri Stone Temple Architecture",
    primaryKeywords: ["martand sun temple", "martand ruins"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-jk-kheer-bhawani",
    benchmarkName: "Kheer Bhawani",
    canonicalName: "Kheer Bhawani Temple (Ragnya Devi Mandir), Tulmulla",
    expectedState: "Jammu and Kashmir",
    expectedStateCode: "JK",
    expectedDistrict: "Ganderbal",
    expectedLocality: "Tulmulla",
    latitude: 34.2239,
    longitude: 74.7431,
    deity: "Goddess Ragnya Devi (Spring of Miracles)",
    circuit: "Kashmiri Pandit Sacred Shrines",
    primaryKeywords: ["kheer bhawani", "ragnya devi temple", "tulmulla"],
    negativeKeywords: [],
    officialSource: "J&K Dharmarth Trust / J&K Tourism",
    officialSourceUrl: "https://jktourism.jk.gov.in/"
  },

  // --- KARNATAKA ---
  {
    id: "bm-ka-udupi-krishna",
    benchmarkName: "Udupi Krishna",
    canonicalName: "Udupi Sri Krishna Matha",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Udupi",
    expectedLocality: "Udupi",
    latitude: 13.3409,
    longitude: 74.7525,
    deity: "Lord Krishna (Kanakana Kindi)",
    circuit: "Ashta Mathas of Udupi / Dvaita Vedanta",
    primaryKeywords: ["udupi sri krishna", "udupi krishna matha"],
    negativeKeywords: [],
    officialSource: "Sri Krishna Matha Udupi",
    officialSourceUrl: "https://srikrishnamatha.org/"
  },
  {
    id: "bm-ka-murudeshwar",
    benchmarkName: "Murudeshwar",
    canonicalName: "Murudeshwar Temple & Raja Gopuram",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Uttara Kannada",
    expectedLocality: "Murudeshwar",
    latitude: 14.0944,
    longitude: 74.4847,
    deity: "Lord Shiva (Atmalinga Piece / Giant 123ft Statue)",
    circuit: "Coastal Karnataka Sacred Circuit",
    primaryKeywords: ["murudeshwar temple"],
    negativeKeywords: [],
    officialSource: "Karnataka State Tourism Development Corporation",
    officialSourceUrl: "https://karnatakatourism.org/"
  },
  {
    id: "bm-ka-gokarna-mahabaleshwar",
    benchmarkName: "Gokarna Mahabaleshwar",
    canonicalName: "Mahabaleshwar Temple, Gokarna",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Uttara Kannada",
    expectedLocality: "Gokarna",
    latitude: 14.5422,
    longitude: 74.3167,
    deity: "Lord Shiva (Atmalinga of Ravana)",
    circuit: "Mukti Sthetra / Dakshina Kashi",
    primaryKeywords: ["mahabaleshwar temple, gokarna", "mahabaleshwar temple", "gokarna temple"],
    negativeKeywords: ["mahabaleshwar hill station maharashtra"],
    officialSource: "Shree Mahabaleshwar Temple Trust",
    officialSourceUrl: "https://gokarnamahit.org/"
  },
  {
    id: "bm-ka-kukke-subramanya",
    benchmarkName: "Kukke Subramanya",
    canonicalName: "Kukke Sri Subramanya Temple",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Dakshina Kannada",
    expectedLocality: "Subramanya",
    latitude: 12.6644,
    longitude: 75.6158,
    deity: "Lord Subramanya & Vasuki (King of Serpents)",
    circuit: "Sarpa Dosha Nivarana Kshetra",
    primaryKeywords: ["kukke subramanya", "kukke sri subrahmanya"],
    negativeKeywords: [],
    officialSource: "Kukke Sri Subrahmanya Temple Administration",
    officialSourceUrl: "https://kukke.org/"
  },
  {
    id: "bm-ka-dharmasthala",
    benchmarkName: "Dharmasthala",
    canonicalName: "Sri Kshetra Dharmasthala Manjunatha Swamy Temple",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Dakshina Kannada",
    expectedLocality: "Dharmasthala",
    latitude: 12.9558,
    longitude: 75.3789,
    deity: "Lord Manjunatha (Shiva) & Goddess Annapoorna",
    circuit: "Unique Heggade / Jain Trustee Hindu Worship",
    primaryKeywords: ["dharmasthala", "manjunatha swamy temple"],
    negativeKeywords: [],
    officialSource: "Sri Kshetra Dharmasthala",
    officialSourceUrl: "https://shridharmasthala.org/"
  },
  {
    id: "bm-ka-kollur-mookambika",
    benchmarkName: "Kollur Mookambika",
    canonicalName: "Kollur Sri Mookambika Temple",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Udupi",
    expectedLocality: "Kollur / Kodachadri Foothills",
    latitude: 13.8653,
    longitude: 74.8142,
    deity: "Goddess Mookambika (Jyotirlinga & Mahalakshmi)",
    circuit: "Adi Shankara Consecrated Devi Shrines",
    primaryKeywords: ["kollur mookambika", "sri mookambika temple"],
    negativeKeywords: [],
    officialSource: "Kollur Sri Mookambika Temple Trust",
    officialSourceUrl: "https://kollurmookambika.org/"
  },
  {
    id: "bm-ka-sringeri",
    benchmarkName: "Sringeri",
    canonicalName: "Sringeri Sharada Peetham & Vidyashankara Temple",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Chikkamagaluru",
    expectedLocality: "Sringeri",
    latitude: 13.4183,
    longitude: 75.2536,
    deity: "Goddess Sharadamba (Saraswati) & Vidyashankara",
    circuit: "First of the Four Amnaya Peethas of Adi Shankara",
    primaryKeywords: ["sringeri", "sharadamba", "vidyashankara"],
    negativeKeywords: [],
    officialSource: "Dakshinamnaya Sri Sharada Peetham, Sringeri",
    officialSourceUrl: "https://sringeri.net/"
  },
  {
    id: "bm-ka-belur",
    benchmarkName: "Belur",
    canonicalName: "Chennakeshava Temple, Belur (UNESCO World Heritage)",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Hassan",
    expectedLocality: "Belur",
    latitude: 13.1628,
    longitude: 75.8600,
    deity: "Lord Chennakeshava (Vishnu) / Hoysala Architecture",
    circuit: "UNESCO World Heritage: Sacred Ensembles of the Hoysalas",
    primaryKeywords: ["chennakeshava temple, belur", "chennakeshava temple", "belur temple", "sacred ensembles of the hoysalas"],
    negativeKeywords: ["somnathpura", "halebidu"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/1670/"
  },
  {
    id: "bm-ka-halebidu",
    benchmarkName: "Halebidu",
    canonicalName: "Hoysaleswara Temple, Halebidu (UNESCO World Heritage)",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Hassan",
    expectedLocality: "Halebidu",
    latitude: 13.2131,
    longitude: 75.9944,
    deity: "Lord Hoysaleswara and Santaleswara (Twin Shiva Lingams)",
    circuit: "UNESCO World Heritage: Sacred Ensembles of the Hoysalas",
    primaryKeywords: ["hoysaleswara temple", "halebidu temple"],
    negativeKeywords: ["belur"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/1670/"
  },
  {
    id: "bm-ka-somanathapura",
    benchmarkName: "Somanathapura",
    canonicalName: "Keshava Temple, Somanathapura (UNESCO World Heritage)",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Mysuru",
    expectedLocality: "Somanathapura",
    latitude: 12.2761,
    longitude: 76.9042,
    deity: "Lord Keshava (Trikuta Hoysala Sanctuary)",
    circuit: "UNESCO World Heritage: Sacred Ensembles of the Hoysalas",
    primaryKeywords: ["somanathapura", "keshava temple, somanathapura", "chennakeshava temple"],
    negativeKeywords: ["somnath gujarat"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/1670/"
  },
  {
    id: "bm-ka-hampi",
    benchmarkName: "Hampi",
    canonicalName: "Virupaksha Temple, Hampi (UNESCO World Heritage)",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Vijayanagara",
    expectedLocality: "Hampi",
    latitude: 15.3353,
    longitude: 76.4600,
    deity: "Lord Virupaksha (Shiva) & Goddess Pampa",
    circuit: "UNESCO World Heritage: Group of Monuments at Hampi",
    primaryKeywords: ["virupaksha temple", "virupaksha temple, hampi", "group of monuments at hampi", "hampi virupaksha"],
    negativeKeywords: ["pattadakal"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/241/"
  },
  {
    id: "bm-ka-pattadakal",
    benchmarkName: "Pattadakal",
    canonicalName: "Group of Monuments at Pattadakal (UNESCO World Heritage)",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Bagalkote",
    expectedLocality: "Pattadakal",
    latitude: 15.9492,
    longitude: 75.8164,
    deity: "Virupaksha, Mallikarjuna & Sangameshwara Temples",
    circuit: "UNESCO World Heritage / Badami Chalukya Capital",
    primaryKeywords: ["pattadakal temple", "monuments at pattadakal", "pattadakal badami chalukya sanctuary", "group of monuments at pattadakal"],
    negativeKeywords: ["aihole"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/239/"
  },
  {
    id: "bm-ka-aihole",
    benchmarkName: "Aihole",
    canonicalName: "Durga Temple & Lad Khan Temple Complex, Aihole",
    expectedState: "Karnataka",
    expectedStateCode: "KA",
    expectedDistrict: "Bagalkote",
    expectedLocality: "Aihole",
    latitude: 16.0194,
    longitude: 75.8822,
    deity: "Durga Temple (Apsidal Sanctum) / Cradle of Temple Architecture",
    circuit: "Chalukya Rock-Cut & Structural Temples",
    primaryKeywords: ["durga temple", "durga temple, aihole", "aihole temple complex", "cradle of indian temple architecture", "aihole"],
    negativeKeywords: ["pattadakal"],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },

  // --- KERALA ---
  {
    id: "bm-kl-padmanabhaswamy",
    benchmarkName: "Padmanabhaswamy",
    canonicalName: "Sree Padmanabhaswamy Temple",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Thiruvananthapuram",
    expectedLocality: "East Fort, Thiruvananthapuram",
    latitude: 8.4828,
    longitude: 76.9436,
    deity: "Lord Padmanabha (Anantha Sayana posture)",
    circuit: "108 Divya Desams / Royal Travancore Shrine",
    primaryKeywords: ["padmanabhaswamy temple", "sree padmanabhaswamy"],
    negativeKeywords: ["attukal"],
    officialSource: "Sree Padmanabhaswamy Temple Trust",
    officialSourceUrl: "https://spst.org/"
  },
  {
    id: "bm-kl-sabarimala",
    benchmarkName: "Sabarimala",
    canonicalName: "Sabarimala Sree Dharma Sastha Temple",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Pathanamthitta",
    expectedLocality: "Sabarimala / Periyar Tiger Reserve",
    latitude: 9.4408,
    longitude: 77.0819,
    deity: "Lord Ayyappa (Dharma Sastha)",
    circuit: "Mandala-Makaravilakku Pilgrimage",
    primaryKeywords: ["sabarimala", "dharma sastha temple"],
    negativeKeywords: [],
    officialSource: "Travancore Devaswom Board (TDB)",
    officialSourceUrl: "https://sabarimala.kerala.gov.in/"
  },
  {
    id: "bm-kl-guruvayur",
    benchmarkName: "Guruvayur",
    canonicalName: "Guruvayur Sree Krishna Swamy Temple (Bhuloka Vaikuntha)",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Thrissur",
    expectedLocality: "Guruvayur",
    latitude: 10.5947,
    longitude: 76.0389,
    deity: "Lord Krishna (Guruvayurappan / Unnikrishnan)",
    circuit: "Bhuloka Vaikuntham",
    primaryKeywords: ["guruvayur", "guruvayurappan"],
    negativeKeywords: [],
    officialSource: "Guruvayur Devaswom",
    officialSourceUrl: "https://guruvayurdevaswom.nic.in/"
  },
  {
    id: "bm-kl-chottanikkara",
    benchmarkName: "Chottanikkara",
    canonicalName: "Chottanikkara Bhagavathy Temple",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Ernakulam",
    expectedLocality: "Chottanikkara / Kochi",
    latitude: 9.9328,
    longitude: 76.3917,
    deity: "Goddess Rajarajeshwari (Saraswati, Lakshmi, Durga) & Bhadrakali (Keezhkavu)",
    circuit: "Guruthi Pooja / Devi Kshetra",
    primaryKeywords: ["chottanikkara bhagavathy", "chottanikkara temple"],
    negativeKeywords: [],
    officialSource: "Cochin Devaswom Board",
    officialSourceUrl: "https://chottanikkarabhagavathy.org/"
  },
  {
    id: "bm-kl-attukal",
    benchmarkName: "Attukal",
    canonicalName: "Attukal Bhagavathy Temple (Women's Sabarimala)",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Thiruvananthapuram",
    expectedLocality: "Attukal",
    latitude: 8.4719,
    longitude: 76.9536,
    deity: "Goddess Kannaki / Attukalamma",
    circuit: "Attukal Pongala Guinness Record Gathering",
    primaryKeywords: ["attukal", "attukal bhagavathy"],
    negativeKeywords: ["padmanabhaswamy"],
    officialSource: "Attukal Bhagavathy Temple Trust",
    officialSourceUrl: "https://attukal.org/"
  },
  {
    id: "bm-kl-vadakkunnathan",
    benchmarkName: "Vadakkunnathan",
    canonicalName: "Sree Vadakkunnathan Temple, Thrissur",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Thrissur",
    expectedLocality: "Thekkinkadu Maidan, Thrissur",
    latitude: 10.5244,
    longitude: 76.2144,
    deity: "Lord Shiva (Vadakkunnathan - Ghee Covered Lingam)",
    circuit: "UNESCO Asia-Pacific Heritage Award / Thrissur Pooram",
    primaryKeywords: ["vadakkunnathan temple"],
    negativeKeywords: [],
    officialSource: "Cochin Devaswom Board",
    officialSourceUrl: "https://cochindevaswomboard.org/"
  },
  {
    id: "bm-kl-ettumanoor",
    benchmarkName: "Ettumanoor",
    canonicalName: "Ettumanoor Mahadeva Temple",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Kottayam",
    expectedLocality: "Ettumanoor",
    latitude: 9.6706,
    longitude: 76.5628,
    deity: "Lord Shiva (Aghora Murthy)",
    circuit: "Ezharaponnana (Seven-and-a-half Golden Elephants) Shrine",
    primaryKeywords: ["ettumanoor mahadeva", "ettumanoor temple"],
    negativeKeywords: [],
    officialSource: "Travancore Devaswom Board (TDB)",
    officialSourceUrl: "https://travancoredevaswomboard.org/"
  },
  {
    id: "bm-kl-mannarasala",
    benchmarkName: "Mannarasala",
    canonicalName: "Mannarasala Sree Nagaraja Temple",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Alappuzha",
    expectedLocality: "Haripad",
    latitude: 9.2783,
    longitude: 76.4719,
    deity: "Serpent Gods (Nagaraja & Sarpayakshi)",
    circuit: "Largest Serpent Shrine in Kerala / Priestess Valia Amma",
    primaryKeywords: ["mannarasala", "nagaraja temple"],
    negativeKeywords: [],
    officialSource: "Mannarasala Temple Trust",
    officialSourceUrl: "https://mannarasala.org/"
  },
  {
    id: "bm-kl-ambalappuzha",
    benchmarkName: "Ambalappuzha",
    canonicalName: "Ambalappuzha Sri Krishna Temple",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Alappuzha",
    expectedLocality: "Ambalappuzha",
    latitude: 9.3833,
    longitude: 76.3556,
    deity: "Lord Krishna (Parthasarathi / Palpayasam)",
    circuit: "Guruvayur Idol Safe Haven during Tipu Invasion",
    primaryKeywords: ["ambalappuzha sri krishna", "ambalapuzha temple"],
    negativeKeywords: [],
    officialSource: "Travancore Devaswom Board (TDB)",
    officialSourceUrl: "https://travancoredevaswomboard.org/"
  },
  {
    id: "bm-kl-vaikom",
    benchmarkName: "Vaikom",
    canonicalName: "Vaikom Mahadeva Temple (Dakshina Kashi)",
    expectedState: "Kerala",
    expectedStateCode: "KL",
    expectedDistrict: "Kottayam",
    expectedLocality: "Vaikom",
    latitude: 9.7508,
    longitude: 76.3958,
    deity: "Lord Shiva (Annadana Prabhu)",
    circuit: "Vaikom Ashtami / Historic Vaikom Satyagraha Site",
    primaryKeywords: ["vaikom sree mahadeva temple", "vaikom mahadeva", "vaikom temple"],
    negativeKeywords: [],
    officialSource: "Travancore Devaswom Board (TDB)",
    officialSourceUrl: "https://travancoredevaswomboard.org/"
  },

  // --- MADHYA PRADESH ---
  {
    id: "bm-mp-mahakaleshwar",
    benchmarkName: "Mahakaleshwar",
    canonicalName: "Shree Mahakaleshwar Jyotirlinga Temple Ujjain",
    expectedState: "Madhya Pradesh",
    expectedStateCode: "MP",
    expectedDistrict: "Ujjain",
    expectedLocality: "Ujjain",
    latitude: 23.1828,
    longitude: 75.7681,
    deity: "Lord Shiva (Dakshinamurti Jyotirlinga / Bhasma Aarti)",
    circuit: "12 Jyotirlingas / Kumbh Mela Simhastha",
    primaryKeywords: ["mahakaleshwar", "shree mahakaleshwar jyotirlinga"],
    negativeKeywords: ["harsiddhi", "udaipur"],
    officialSource: "Shri Mahakaleshwar Temple Management Committee",
    officialSourceUrl: "https://shrimahakaleshwar.com/"
  },
  {
    id: "bm-mp-omkareshwar",
    benchmarkName: "Omkareshwar",
    canonicalName: "Shri Omkareshwar Jyotirlinga Temple (Mandhata Island)",
    expectedState: "Madhya Pradesh",
    expectedStateCode: "MP",
    expectedDistrict: "Khandwa",
    expectedLocality: "Mandhata / Omkareshwar",
    latitude: 22.2464,
    longitude: 76.1506,
    deity: "Lord Shiva (Omkareshwar & Mamleshwar)",
    circuit: "12 Jyotirlingas / Narmada Parikrama",
    primaryKeywords: ["omkareshwar", "omkareshwar jyotirlinga"],
    negativeKeywords: [],
    officialSource: "Shri Omkareshwar Temple Trust / MP Tourism",
    officialSourceUrl: "https://shriomkareshwar.org/"
  },
  {
    id: "bm-mp-maihar",
    benchmarkName: "Maihar",
    canonicalName: "Maa Sharda Devi Temple (Maihar Devi), Trikuta Hill",
    expectedState: "Madhya Pradesh",
    expectedStateCode: "MP",
    expectedDistrict: "Maihar",
    expectedLocality: "Maihar",
    latitude: 24.2694,
    longitude: 80.7583,
    deity: "Goddess Sharda (Saraswati) & Alha-Udal Legacy",
    circuit: "51 Shakti Peethas (Necklace of Sati)",
    primaryKeywords: ["maihar", "sharda devi temple, maihar"],
    negativeKeywords: [],
    officialSource: "Maa Sharda Devi Mandir Samiti",
    officialSourceUrl: "https://mahashardadevi.org/"
  },
  {
    id: "bm-mp-khajuraho",
    benchmarkName: "Khajuraho",
    canonicalName: "Kandariya Mahadeva Temple, Khajuraho (UNESCO World Heritage)",
    expectedState: "Madhya Pradesh",
    expectedStateCode: "MP",
    expectedDistrict: "Chhatarpur",
    expectedLocality: "Khajuraho",
    latitude: 24.8536,
    longitude: 79.9197,
    deity: "Lord Shiva (Kandariya Mahadeva) / Chandela Architecture",
    circuit: "UNESCO World Heritage: Khajuraho Group of Monuments",
    primaryKeywords: ["kandariya mahadeva", "khajuraho temple"],
    negativeKeywords: ["duladeo"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/240/"
  },
  {
    id: "bm-mp-bhojeshwar",
    benchmarkName: "Bhojeshwar",
    canonicalName: "Bhojeshwar Temple (Bhojpur Shiva Temple)",
    expectedState: "Madhya Pradesh",
    expectedStateCode: "MP",
    expectedDistrict: "Raisen",
    expectedLocality: "Bhojpur",
    latitude: 23.1008,
    longitude: 77.5867,
    deity: "Lord Shiva (Largest Monolithic 18ft Lingam of King Bhoja)",
    circuit: "Paramara Royal Heritage Shrines",
    primaryKeywords: ["bhojeshwar", "bhojpur temple"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },

  // --- MAHARASHTRA ---
  {
    id: "bm-mh-trimbakeshwar",
    benchmarkName: "Trimbakeshwar",
    canonicalName: "Shree Trimbakeshwar Jyotirlinga Temple, Nashik",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Nashik",
    expectedLocality: "Trimbak",
    latitude: 19.9322,
    longitude: 73.5306,
    deity: "Lord Shiva (Three-Faced Lingam: Brahma, Vishnu, Rudra)",
    circuit: "12 Jyotirlingas / Godavari River Origin",
    primaryKeywords: ["trimbakeshwar", "tryambakeshwar"],
    negativeKeywords: [],
    officialSource: "Shri Trimbakeshwar Devasthan Trust",
    officialSourceUrl: "https://trimbakeshwartrust.org/"
  },
  {
    id: "bm-mh-bhimashankar",
    benchmarkName: "Bhimashankar",
    canonicalName: "Bhimashankar Jyotirlinga Temple, Pune",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Pune",
    expectedLocality: "Bhavagiri / Khed",
    latitude: 19.0722,
    longitude: 73.5358,
    deity: "Lord Shiva (Bhimashankar Jyotirlinga)",
    circuit: "12 Jyotirlingas / Bhima River Origin / Wildlife Sanctuary",
    primaryKeywords: ["bhimashankar", "bhimashankar jyotirlinga"],
    negativeKeywords: [],
    officialSource: "Shree Bhimashankar Sansthan Trust",
    officialSourceUrl: "https://bhimashankar.in/"
  },
  {
    id: "bm-mh-grishneshwar",
    benchmarkName: "Grishneshwar",
    canonicalName: "Grishneshwar Jyotirlinga Temple, Verul",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Chhatrapati Sambhajinagar",
    expectedLocality: "Verul / Ellora",
    latitude: 20.0242,
    longitude: 75.1706,
    deity: "Lord Shiva (12th and Final Jyotirlinga)",
    circuit: "12 Jyotirlingas / Ellora Caves Precinct",
    primaryKeywords: ["grishneshwar", "ghrushneshwar"],
    negativeKeywords: [],
    officialSource: "Shri Grishneshwar Devasthan Trust",
    officialSourceUrl: "https://grishneshwar.org/"
  },
  {
    id: "bm-mh-shirdi",
    benchmarkName: "Shirdi",
    canonicalName: "Shri Saibaba Sansthan Temple, Shirdi",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Ahmednagar",
    expectedLocality: "Shirdi",
    latitude: 19.7667,
    longitude: 74.4764,
    deity: "Shri Sai Baba of Shirdi (Samadhi Mandir)",
    circuit: "National Composite Inter-Faith Pilgrimage",
    primaryKeywords: ["shirdi sai baba", "saibaba sansthan"],
    negativeKeywords: [],
    officialSource: "Shri Saibaba Sansthan Trust, Shirdi",
    officialSourceUrl: "https://sai.org.in/"
  },
  {
    id: "bm-mh-siddhivinayak",
    benchmarkName: "Siddhivinayak",
    canonicalName: "Shree Siddhivinayak Ganapati Temple, Prabhadevi",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Mumbai City",
    expectedLocality: "Prabhadevi, Mumbai",
    latitude: 19.0169,
    longitude: 72.8303,
    deity: "Lord Ganesha (Right-sided trunk Navasacha Ganpati)",
    circuit: "Premier Ganesha Shrines",
    primaryKeywords: ["siddhivinayak temple", "prabhadevi ganpati"],
    negativeKeywords: [],
    officialSource: "Shree Siddhivinayak Ganapati Temple Trust",
    officialSourceUrl: "https://siddhivinayak.org/"
  },
  {
    id: "bm-mh-tulja-bhavani",
    benchmarkName: "Tulja Bhavani",
    canonicalName: "Shree Tulja Bhavani Temple, Tuljapur",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Dharashiv",
    expectedLocality: "Tuljapur",
    latitude: 18.0108,
    longitude: 76.0719,
    deity: "Goddess Tulja Bhavani (Kuldevi of Chhatrapati Shivaji Maharaj)",
    circuit: "3.5 Shakti Peethas of Maharashtra",
    primaryKeywords: ["tulja bhavani", "tuljapur temple"],
    negativeKeywords: [],
    officialSource: "Shree Tulja Bhavani Temple Trust",
    officialSourceUrl: "https://tuljabhavani.in/"
  },
  {
    id: "bm-mh-mahalakshmi-kolhapur",
    benchmarkName: "Mahalakshmi Kolhapur",
    canonicalName: "Shri Ambabai Mahalakshmi Temple, Kolhapur",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Kolhapur",
    expectedLocality: "Kolhapur",
    latitude: 16.6947,
    longitude: 74.2239,
    deity: "Goddess Mahalakshmi (Ambabai) - Kirnotsav Solar Phenomenon",
    circuit: "3.5 Shakti Peethas of Maharashtra / 108 Shakti Peethas",
    primaryKeywords: ["mahalakshmi", "ambabai", "kolhapur"],
    negativeKeywords: ["kanaka mahalakshmi", "visakhapatnam"],
    officialSource: "West Maharashtra Devasthan Management Committee",
    officialSourceUrl: "https://mahalaxmikolhapur.com/"
  },
  {
    id: "bm-mh-dagdusheth",
    benchmarkName: "Dagdusheth",
    canonicalName: "Shreemant Dagdusheth Halwai Ganpati Temple, Pune",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Pune",
    expectedLocality: "Budhwar Peth, Pune",
    latitude: 18.5165,
    longitude: 73.8561,
    deity: "Lord Ganesha (Gold-adorned Ganpati)",
    circuit: "Ganeshotsav Movement Epicenter",
    primaryKeywords: ["dagdusheth halwai ganpati", "dagdusheth temple"],
    negativeKeywords: [],
    officialSource: "Shreemant Dagdusheth Halwai Public Ganpati Trust",
    officialSourceUrl: "https://www.dagdushethganpati.com/"
  },
  {
    id: "bm-mh-ganpatipule",
    benchmarkName: "Ganpatipule",
    canonicalName: "Swayambhu Ganpati Temple, Ganpatipule",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Ratnagiri",
    expectedLocality: "Ganpatipule Beach",
    latitude: 17.1458,
    longitude: 73.2667,
    deity: "Lord Ganesha (Self-manifested Paschim Dwardevata)",
    circuit: "Ashta Ganpati of Konkan Coast",
    primaryKeywords: ["ganpatipule", "swayambhu ganpati", "ganpatipule ganesh"],
    negativeKeywords: ["tamil nadu"],
    officialSource: "Ganpatipule Temple Trust / MTDC",
    officialSourceUrl: "https://www.maharashtratourism.gov.in/"
  },
  {
    id: "bm-mh-aundha-nagnath",
    benchmarkName: "Aundha Nagnath",
    canonicalName: "Aundha Nagnath Jyotirlinga Temple",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Hingoli",
    expectedLocality: "Aundha Nagnath",
    latitude: 19.5447,
    longitude: 77.0417,
    deity: "Lord Shiva (8th Jyotirlinga / Hemadpanthi Architecture)",
    circuit: "12 Jyotirlingas",
    primaryKeywords: ["aundha nagnath"],
    negativeKeywords: ["dwarka nageshwar"],
    officialSource: "Shree Aundha Nagnath Sansthan Trust",
    officialSourceUrl: "https://hingoli.gov.in/"
  },
  {
    id: "bm-mh-parli-vaijnath",
    benchmarkName: "Parli Vaijnath",
    canonicalName: "Shree Parli Vaijnath Jyotirlinga Temple",
    expectedState: "Maharashtra",
    expectedStateCode: "MH",
    expectedDistrict: "Beed",
    expectedLocality: "Parli",
    latitude: 18.8492,
    longitude: 76.5350,
    deity: "Lord Shiva (Dhanwantari / Vaidyanath)",
    circuit: "12 Jyotirlingas",
    primaryKeywords: ["parli vaijnath", "parli temple"],
    negativeKeywords: ["deoghar", "kangra baijnath"],
    officialSource: "Shri Parli Vaijnath Devasthan Trust",
    officialSourceUrl: "https://beed.gov.in/"
  },

  // --- ODISHA ---
  {
    id: "bm-od-jagannath",
    benchmarkName: "Jagannath",
    canonicalName: "Shree Jagannatha Temple, Puri",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Puri",
    expectedLocality: "Puri",
    latitude: 19.8049,
    longitude: 85.8179,
    deity: "Lord Jagannatha, Balabhadra, Subhadra, Sudarshana",
    circuit: "Original Char Dham / Rath Yatra",
    primaryKeywords: ["shree jagannatha temple puri", "jagannath temple puri"],
    negativeKeywords: ["assam", "chhattisgarh", "ahmedabad", "ranchi"],
    officialSource: "Shree Jagannatha Temple Administration (SJTA)",
    officialSourceUrl: "https://www.shreejagannatha.in/"
  },
  {
    id: "bm-od-konark",
    benchmarkName: "Konark",
    canonicalName: "Konark Sun Temple (Surya Deula - UNESCO World Heritage)",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Puri",
    expectedLocality: "Konark",
    latitude: 19.8876,
    longitude: 86.0945,
    deity: "Surya Bhagwan (Colossal Stone Chariot with 24 Wheels)",
    circuit: "UNESCO World Heritage / Golden Triangle of Odisha",
    primaryKeywords: ["konark sun temple", "surya deula", "black pagoda"],
    negativeKeywords: ["deo sun", "modhera"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/246/"
  },
  {
    id: "bm-od-lingaraj",
    benchmarkName: "Lingaraj",
    canonicalName: "Lingaraj Temple, Bhubaneswar",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Khordha",
    expectedLocality: "Bhubaneswar",
    latitude: 20.2381,
    longitude: 85.8336,
    deity: "Lord Shiva & Lord Vishnu (Harihara)",
    circuit: "Ekamra Kshetra / Kalinga Architecture (Deula)",
    primaryKeywords: ["lingaraj temple", "lingaraj temple bhubaneswar"],
    negativeKeywords: ["mukteshwar", "rajarani"],
    officialSource: "Archaeological Survey of India (ASI) / Odisha Tourism",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-od-mukteshwar",
    benchmarkName: "Mukteshwar",
    canonicalName: "Mukteshvara Temple Complex, Bhubaneswar",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Khordha",
    expectedLocality: "Bhubaneswar",
    latitude: 20.2431,
    longitude: 85.8350,
    deity: "Lord Shiva (Gem of Odishan Temple Architecture / Torana Arch)",
    circuit: "Ekamra Kshetra / Kalinga Classical Evolution",
    primaryKeywords: ["mukteshvara temple", "mukteshwar temple", "mukteshwar temple, bhubaneswar"],
    negativeKeywords: ["uttarakhand mukteshwar", "lingaraj"],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-od-rajarani",
    benchmarkName: "Rajarani",
    canonicalName: "Rajarani Temple, Bhubaneswar",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Khordha",
    expectedLocality: "Bhubaneswar",
    latitude: 20.2522,
    longitude: 85.8458,
    deity: "Love Temple / Indradyumna Kshetra (Yellow Rajaraniya Sandstone)",
    circuit: "ASI Protected Monuments of Ekamra Kshetra",
    primaryKeywords: ["rajarani temple"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-od-taratarini",
    benchmarkName: "Taratarini",
    canonicalName: "Maa Tara Tarini Temple, Rushikulya River",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Ganjam",
    expectedLocality: "Purushottampur / Purnagiri Hill",
    latitude: 19.4939,
    longitude: 84.9011,
    deity: "Twin Goddesses Tara and Tarini (Breast Peetha)",
    circuit: "4 Adi Shakti Peethas of Ancient Texts",
    primaryKeywords: ["tara tarini", "taratarini temple"],
    negativeKeywords: [],
    officialSource: "Maa Tara Tarini Temple Trust",
    officialSourceUrl: "https://taratarini.nic.in/"
  },
  {
    id: "bm-od-biraja",
    benchmarkName: "Biraja",
    canonicalName: "Maa Biraja Temple (Gadakshetra), Jajpur",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Jajpur",
    expectedLocality: "Jajpur",
    latitude: 20.8528,
    longitude: 86.3400,
    deity: "Goddess Biraja (Dvibhuji Durga trampling Mahishasura)",
    circuit: "51 Shakti Peethas (Navi Gaya / Nabhi Peetha)",
    primaryKeywords: ["biraja temple", "maa biraja"],
    negativeKeywords: [],
    officialSource: "Jajpur District Administration / Odisha Tourism",
    officialSourceUrl: "https://jajpur.nic.in/"
  },
  {
    id: "bm-od-sakshigopal",
    benchmarkName: "Sakshigopal",
    canonicalName: "Sakshigopal Temple (Satyabadi Gopinatha Temple)",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Puri",
    expectedLocality: "Satyabadi",
    latitude: 19.9536,
    longitude: 85.8239,
    deity: "Lord Krishna (Sakshi Gopal / Witness Gopal)",
    circuit: "Essential Part of Jagannath Puri Pilgrimage",
    primaryKeywords: ["sakshigopal", "sakshi gopal"],
    negativeKeywords: [],
    officialSource: "Odisha Tourism / SJTA",
    officialSourceUrl: "https://puri.nic.in/"
  },
  {
    id: "bm-od-samaleswari",
    benchmarkName: "Samaleswari",
    canonicalName: "Maa Samaleswari Temple, Sambalpur",
    expectedState: "Odisha",
    expectedStateCode: "OD",
    expectedDistrict: "Sambalpur",
    expectedLocality: "Sambalpur",
    latitude: 21.4644,
    longitude: 83.9686,
    deity: "Maa Samaleswari (Presiding Deity of Western Odisha)",
    circuit: "Mahanadi Sacred River Shrines",
    primaryKeywords: ["samaleswari", "maa samaleswari"],
    negativeKeywords: [],
    officialSource: "Maa Samaleswari Trust Board / SAMALEI Project",
    officialSourceUrl: "https://sambalpur.nic.in/"
  },

  // --- RAJASTHAN ---
  {
    id: "bm-rj-brahma-pushkar",
    benchmarkName: "Brahma Pushkar",
    canonicalName: "Jagatpita Brahma Mandir, Pushkar",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Ajmer",
    expectedLocality: "Pushkar",
    latitude: 26.4889,
    longitude: 74.5511,
    deity: "Lord Brahma (Creator of the Universe)",
    circuit: "King of Pilgrimages (Teerth Raj Pushkar)",
    primaryKeywords: ["brahma temple, pushkar", "jagatpita brahma mandir"],
    negativeKeywords: [],
    officialSource: "Pushkar Devasthan / Rajasthan Tourism",
    officialSourceUrl: "https://tourism.rajasthan.gov.in/"
  },
  {
    id: "bm-rj-shrinathji",
    benchmarkName: "Shrinathji",
    canonicalName: "Shrinathji Temple, Nathdwara",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Rajsamand",
    expectedLocality: "Nathdwara",
    latitude: 24.9317,
    longitude: 73.8200,
    deity: "Lord Krishna (Shrinathji 7-Year-Old Govardhan Form)",
    circuit: "Pushtimarg / Vallabhacharya Sampradaya",
    primaryKeywords: ["shrinathji temple", "nathdwara"],
    negativeKeywords: [],
    officialSource: "Nathdwara Temple Board",
    officialSourceUrl: "https://nathdwaratemple.org/"
  },
  {
    id: "bm-rj-eklingji",
    benchmarkName: "Eklingji",
    canonicalName: "Shree Eklingnath Ji Temple, Kailashpuri",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Udaipur",
    expectedLocality: "Kailashpuri",
    latitude: 24.7478,
    longitude: 73.7228,
    deity: "Lord Shiva (Eklingji - Supreme Ruler of Mewar)",
    circuit: "Mewar Royal Heritage Shrines",
    primaryKeywords: ["eklingji", "eklingnath ji"],
    negativeKeywords: [],
    officialSource: "Maharana of Mewar Charitable Foundation",
    officialSourceUrl: "https://www.eternalmewar.in/"
  },
  {
    id: "bm-rj-karni-mata",
    benchmarkName: "Karni Mata",
    canonicalName: "Karni Mata Temple (Temple of Rats), Deshnoke",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Bikaner",
    expectedLocality: "Deshnoke",
    latitude: 27.7911,
    longitude: 73.3411,
    deity: "Goddess Karni Mata (25,000 Sacred White & Black Rats / Kabas)",
    circuit: "Charan / Rajput Sacred Sanctuaries",
    primaryKeywords: ["karni mata", "deshnoke"],
    negativeKeywords: [],
    officialSource: "Shri Karni Mandir Trust",
    officialSourceUrl: "https://bikaner.rajasthan.gov.in/"
  },
  {
    id: "bm-rj-ranakpur",
    benchmarkName: "Ranakpur",
    canonicalName: "Ranakpur Jain Temple (Chaturmukha Dharana Vihara)",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Pali",
    expectedLocality: "Ranakpur / Sadri",
    latitude: 25.1158,
    longitude: 73.4728,
    deity: "Bhagwan Rishabhdev (Adinatha) - 1,444 Carved Pillars",
    circuit: "Premier Jain Pilgrimage Circuit (Tirthas)",
    primaryKeywords: ["ranakpur jain", "ranakpur temple"],
    negativeKeywords: [],
    officialSource: "Sheth Anandji Kalyanji Pedhi",
    officialSourceUrl: "https://ranakpurjaintemple.com/"
  },
  {
    id: "bm-rj-dilwara",
    benchmarkName: "Dilwara",
    canonicalName: "Dilwara Jain Temples, Mount Abu",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Sirohi",
    expectedLocality: "Mount Abu",
    latitude: 24.6033,
    longitude: 72.7231,
    deity: "Vimal Vasahi & Luna Vasahi (Pure White Marble Wonder)",
    circuit: "Maru-Gurjara Jain Heritage Architecture",
    primaryKeywords: ["dilwara", "dilwara jain temples"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI) / Jain Trust",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-rj-salasar",
    benchmarkName: "Salasar",
    canonicalName: "Salasar Balaji Mandir",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Churu",
    expectedLocality: "Salasar",
    latitude: 27.7214,
    longitude: 74.7208,
    deity: "Lord Hanuman (Moustache & Beard Idol / Chamatkari Balaji)",
    circuit: "Shekhawati Sacred Circuit",
    primaryKeywords: ["salasar balaji", "salasar mandir"],
    negativeKeywords: ["mehandipur"],
    officialSource: "Hanuman Seva Samiti Salasar",
    officialSourceUrl: "https://shreesalasarbalaji.net/"
  },
  {
    id: "bm-rj-mehandipur",
    benchmarkName: "Mehandipur",
    canonicalName: "Mehandipur Balaji Mandir",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Dausa",
    expectedLocality: "Mehandipur",
    latitude: 26.9942,
    longitude: 76.7642,
    deity: "Lord Hanuman (Pret Raj Sarkar & Bhairav Baba)",
    circuit: "Sankat Mochan Divine Healing Shrines",
    primaryKeywords: ["mehandipur balaji"],
    negativeKeywords: ["salasar"],
    officialSource: "Mehandipur Balaji Trust",
    officialSourceUrl: "https://dausa.rajasthan.gov.in/"
  },
  {
    id: "bm-rj-khatu-shyam",
    benchmarkName: "Khatu Shyam",
    canonicalName: "Khatu Shyam Ji Mandir (Barbarika Dham)",
    expectedState: "Rajasthan",
    expectedStateCode: "RJ",
    expectedDistrict: "Sikar",
    expectedLocality: "Khatu",
    latitude: 27.3589,
    longitude: 75.3056,
    deity: "Barbarika / Shyam Baba (Head of Barbarika given to Krishna)",
    circuit: "Haare Ka Sahara / Shekhawati Pilgrimage",
    primaryKeywords: ["khatu shyam", "khatu shyam ji"],
    negativeKeywords: [],
    officialSource: "Shri Shyam Mandir Committee Khatu",
    officialSourceUrl: "https://khatushyam.in/"
  },

  // --- TAMIL NADU ---
  {
    id: "bm-tn-brihadisvara-thanjavur",
    benchmarkName: "Brihadisvara Thanjavur",
    canonicalName: "Brihadisvara Temple (Peruvudaiyar Kovil), Thanjavur",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Thanjavur",
    expectedLocality: "Thanjavur",
    latitude: 10.7828,
    longitude: 79.1319,
    deity: "Lord Shiva (Peruvudaiyar / Rajarajeswaram)",
    circuit: "UNESCO World Heritage: Great Living Chola Temples",
    primaryKeywords: ["brihadisvara temple, thanjavur", "brihadisvara temple", "arulmigu brihadisvara", "peruvudaiyar kovil", "thanjavur big temple"],
    negativeKeywords: ["gangaikonda cholapuram"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/250/"
  },
  {
    id: "bm-tn-brihadisvara-gangaikonda",
    benchmarkName: "Brihadisvara Gangaikondacholapuram",
    canonicalName: "Brihadisvara Temple, Gangaikonda Cholapuram",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Ariyalur",
    expectedLocality: "Gangaikonda Cholapuram",
    latitude: 11.2061,
    longitude: 79.4542,
    deity: "Lord Shiva (Built by Rajendra Chola I)",
    circuit: "UNESCO World Heritage: Great Living Chola Temples",
    primaryKeywords: ["gangaikonda cholapuram", "brihadisvara temple, gangaikonda"],
    negativeKeywords: ["thanjavur"],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/250/"
  },
  {
    id: "bm-tn-airavatesvara",
    benchmarkName: "Airavatesvara",
    canonicalName: "Airavatesvara Temple, Darasuram",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Thanjavur",
    expectedLocality: "Darasuram / Kumbakonam",
    latitude: 10.9189,
    longitude: 79.3562,
    deity: "Lord Shiva (Airavatesvara / White Elephant of Indra)",
    circuit: "UNESCO World Heritage: Great Living Chola Temples",
    primaryKeywords: ["airavatesvara", "darasuram"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/250/"
  },
  {
    id: "bm-tn-meenakshi",
    benchmarkName: "Meenakshi",
    canonicalName: "Arulmigu Meenakshi Sundareswarar Temple, Madurai",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Madurai",
    expectedLocality: "Madurai",
    latitude: 9.9197,
    longitude: 78.1194,
    deity: "Goddess Meenakshi & Lord Sundareswarar",
    circuit: "Pancha Sabha (Velli Ambalam / Silver Hall)",
    primaryKeywords: ["meenakshi amman", "meenakshi sundareswarar", "meenakshi sundareshwarar", "meenakshi temple", "madurai meenakshi"],
    negativeKeywords: [],
    officialSource: "Arulmigu Meenakshi Sundareswarar Thirukoil / HR&CE",
    officialSourceUrl: "https://maduraimeenakshi.hrce.tn.gov.in/"
  },
  {
    id: "bm-tn-ranganathaswamy",
    benchmarkName: "Ranganathaswamy",
    canonicalName: "Sri Ranganathaswamy Temple, Srirangam",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Tiruchirappalli",
    expectedLocality: "Srirangam",
    latitude: 10.8625,
    longitude: 78.6900,
    deity: "Lord Ranganatha (First and Foremost of the 108 Divya Desams)",
    circuit: "108 Divya Desams / UNESCO Asia-Pacific Award",
    primaryKeywords: ["sri ranganathaswamy temple", "ranganathaswamy temple, srirangam", "srirangam temple"],
    negativeKeywords: ["srirangapatna", "shivanasamudra"],
    officialSource: "Arulmigu Ranganathaswamy Temple / HR&CE",
    officialSourceUrl: "https://srirangam.org/"
  },
  {
    id: "bm-tn-chidambaram",
    benchmarkName: "Chidambaram",
    canonicalName: "Thillai Nataraja Temple, Chidambaram",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Cuddalore",
    expectedLocality: "Chidambaram",
    latitude: 11.3992,
    longitude: 79.6934,
    deity: "Lord Shiva (Nataraja - Cosmic Dance of Bliss) & Chidambara Rahasya",
    circuit: "Pancha Bhoota Sthalam (Akasha / Space / Sky)",
    primaryKeywords: ["thillai nataraja", "chidambaram nataraja"],
    negativeKeywords: ["chowara"],
    officialSource: "Pothu Deekshithars / HR&CE TN",
    officialSourceUrl: "https://hrce.tn.gov.in/"
  },
  {
    id: "bm-tn-ramanathaswamy",
    benchmarkName: "Ramanathaswamy",
    canonicalName: "Arulmigu Ramanathaswamy Temple, Rameswaram",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Ramanathapuram",
    expectedLocality: "Rameswaram",
    latitude: 9.2881,
    longitude: 79.3175,
    deity: "Lord Shiva (Consecrated by Lord Rama) & 22 Sacred Teerthams",
    circuit: "Char Dham / 12 Jyotirlingas",
    primaryKeywords: ["ramanathaswamy temple", "rameswaram temple"],
    negativeKeywords: [],
    officialSource: "Arulmigu Ramanathaswamy Thirukoil / HR&CE",
    officialSourceUrl: "https://rameswaramtemple.tnhrce.in/"
  },
  {
    id: "bm-tn-arunachaleswarar",
    benchmarkName: "Arunachaleswarar",
    canonicalName: "Arulmigu Arunachaleswarar Temple, Tiruvannamalai",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Tiruvannamalai",
    expectedLocality: "Tiruvannamalai",
    latitude: 12.2300,
    longitude: 79.0678,
    deity: "Lord Shiva (Agni Lingam / Pillar of Fire)",
    circuit: "Pancha Bhoota Sthalam (Fire / Agni) / Girivalam",
    primaryKeywords: ["arunachaleswarar", "tiruvannamalai temple", "annamaliar temple"],
    negativeKeywords: [],
    officialSource: "Arulmigu Arunachaleswarar Thirukoil / HR&CE",
    officialSourceUrl: "https://tiruvannamalai.nic.in/"
  },
  {
    id: "bm-tn-kamakshi-amman",
    benchmarkName: "Kamakshi",
    canonicalName: "Arulmigu Kamakshi Amman Temple, Kanchipuram",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Kanchipuram",
    expectedLocality: "Kanchipuram",
    latitude: 12.8412,
    longitude: 79.7032,
    deity: "Goddess Kamakshi (Padmasana Form / Sri Chakra Yantra)",
    circuit: "51 Shakti Peethas (Nabhi Peetha) / Kanchi Mokshapuri",
    primaryKeywords: ["kamakshi amman", "kamakshi amman temple", "kanchipuram kamakshi", "arulmigu kamakshi"],
    negativeKeywords: ["shiroda", "goa", "ekambareswarar"],
    officialSource: "Arulmigu Kamakshi Amman Devasthanam",
    officialSourceUrl: "https://kanchikamakshi.com/"
  },
  {
    id: "bm-tn-ekambareswarar",
    benchmarkName: "Ekambareswarar",
    canonicalName: "Ekambareswarar Temple, Kanchipuram",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Kanchipuram",
    expectedLocality: "Kanchipuram",
    latitude: 12.8475,
    longitude: 79.6997,
    deity: "Lord Shiva (Prithvi Lingam / Earth Element)",
    circuit: "Pancha Bhoota Sthalam (Earth / Prithvi)",
    primaryKeywords: ["ekambareswarar temple", "kanchipuram ekambareswarar"],
    negativeKeywords: ["kamakshi", "varadaraja", "chennai"],
    officialSource: "HR&CE Department, Government of Tamil Nadu",
    officialSourceUrl: "https://hrce.tn.gov.in/"
  },
  {
    id: "bm-tn-varadaraja-perumal",
    benchmarkName: "Varadaraja Perumal",
    canonicalName: "Arulmigu Varadaraja Perumal Temple, Kanchipuram",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Kanchipuram",
    expectedLocality: "Vishnu Kanchi, Kanchipuram",
    latitude: 12.8193,
    longitude: 79.7246,
    deity: "Lord Varadaraja Perumal (Atti Varadar 40-Year Festival)",
    circuit: "108 Divya Desams / Hastagiri",
    primaryKeywords: ["varadaraja perumal", "varadaraja perumal temple", "kanchipuram varadaraja", "arulmigu varadaraja", "athi varadar", "atti varadar"],
    negativeKeywords: ["puducherry", "dharmapuri", "ekambareswarar"],
    officialSource: "HR&CE Department, Government of Tamil Nadu",
    officialSourceUrl: "https://hrce.tn.gov.in/"
  },
  {
    id: "bm-tn-kapaleeshwarar",
    benchmarkName: "Kapaleeshwarar",
    canonicalName: "Arulmigu Kapaleeshwarar Temple, Mylapore",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Chennai",
    expectedLocality: "Mylapore, Chennai",
    latitude: 13.0336,
    longitude: 80.2694,
    deity: "Lord Shiva (Kapaleeshwarar) & Goddess Karpagambal",
    circuit: "Paadal Petra Sthalam / Pallava-Chola Heritage",
    primaryKeywords: ["kapaleeshwarar temple", "mylapore kapaleeshwarar"],
    negativeKeywords: [],
    officialSource: "Arulmigu Kapaleeshwarar Thirukoil / HR&CE",
    officialSourceUrl: "https://mylapoorekapaleeswarar.hrce.tn.gov.in/"
  },
  {
    id: "bm-tn-palani",
    benchmarkName: "Palani",
    canonicalName: "Arulmigu Dhandayuthapani Swamy Temple, Palani",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Dindigul",
    expectedLocality: "Palani",
    latitude: 10.4497,
    longitude: 77.5186,
    deity: "Lord Murugan (Dhandayuthapani - Navapashanam Idol by Bhogar)",
    circuit: "Murugan Arupadai Veedu (3rd Abode)",
    primaryKeywords: ["dhandayuthapani swamy", "palani murugan", "palani temple"],
    negativeKeywords: [],
    officialSource: "Arulmigu Dhandayuthapani Swamy Thirukoil / HR&CE",
    officialSourceUrl: "https://palanimurugan.hrce.tn.gov.in/"
  },
  {
    id: "bm-tn-tiruchendur",
    benchmarkName: "Tiruchendur",
    canonicalName: "Arulmigu Subramanya Swamy Temple, Tiruchendur",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Thoothukudi",
    expectedLocality: "Tiruchendur Sea Shore",
    latitude: 8.4965,
    longitude: 78.1288,
    deity: "Lord Murugan (Jayanthinathar - Victory over Soorapadman)",
    circuit: "Murugan Arupadai Veedu (2nd Abode / Seashore)",
    primaryKeywords: ["subramaniya swamy temple", "tiruchendur murugan", "tiruchendur subramanya", "thiruchendur temple"],
    negativeKeywords: ["andaman", "coimbatore", "kollam"],
    officialSource: "Arulmigu Subramanya Swamy Thirukoil / HR&CE",
    officialSourceUrl: "https://tiruchendurmurugan.hrce.tn.gov.in/"
  },
  {
    id: "bm-tn-thiruttani",
    benchmarkName: "Thiruttani",
    canonicalName: "Arulmigu Subramanya Swamy Temple, Thiruttani",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Tiruvallur",
    expectedLocality: "Thiruttani Hill",
    latitude: 13.1783,
    longitude: 79.6053,
    deity: "Lord Murugan (Tanikesan - Shanti / Peaceful Abode)",
    circuit: "Murugan Arupadai Veedu (5th Abode - 365 Hill Steps)",
    primaryKeywords: ["subramaniya swamy temple, tiruttani", "thiruttani murugan", "thiruttani subramanya"],
    negativeKeywords: [],
    officialSource: "Arulmigu Subramanya Swamy Thirukoil / HR&CE",
    officialSourceUrl: "https://thiruttanimurugan.hrce.tn.gov.in/"
  },
  {
    id: "bm-tn-swamimalai",
    benchmarkName: "Swamimalai",
    canonicalName: "Arulmigu Swaminatha Swamy Temple, Swamimalai",
    expectedState: "Tamil Nadu",
    expectedStateCode: "TN",
    expectedDistrict: "Thanjavur",
    expectedLocality: "Swamimalai / Kumbakonam",
    latitude: 10.9575,
    longitude: 79.3283,
    deity: "Lord Murugan (Swaminatha - Guru to Father Lord Shiva)",
    circuit: "Murugan Arupadai Veedu (4th Abode - 60 Tamil Year Steps)",
    primaryKeywords: ["swaminatha swamy temple", "swamimalai swaminatha", "swamimalai murugan"],
    negativeKeywords: [],
    officialSource: "Arulmigu Swaminatha Swamy Thirukoil / HR&CE",
    officialSourceUrl: "https://swamimalaimurugan.hrce.tn.gov.in/"
  },

  // --- TELANGANA ---
  {
    id: "bm-tg-ramappa",
    benchmarkName: "Ramappa",
    canonicalName: "Ramappa Temple (Kakatiya Rudreshwara - UNESCO World Heritage)",
    expectedState: "Telangana",
    expectedStateCode: "TG",
    expectedDistrict: "Mulugu",
    expectedLocality: "Palampet",
    latitude: 18.2592,
    longitude: 79.9431,
    deity: "Lord Ramalingeswara / Floating Bricks Kakatiya Masterwork",
    circuit: "UNESCO World Heritage / Kakatiya Heritage Circuit",
    primaryKeywords: ["ramappa temple", "rudreshwara"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI) / UNESCO",
    officialSourceUrl: "https://whc.unesco.org/en/list/1570/"
  },
  {
    id: "bm-tg-yadadri",
    benchmarkName: "Yadadri",
    canonicalName: "Sri Lakshmi Narasimha Swamy Temple, Yadagirigutta (Yadadri)",
    expectedState: "Telangana",
    expectedStateCode: "TG",
    expectedDistrict: "Yadadri Bhuvanagiri",
    expectedLocality: "Yadagirigutta",
    latitude: 17.5892,
    longitude: 78.9392,
    deity: "Lord Lakshmi Narasimha (Pancha Narasimha Kshetra)",
    circuit: "Monumental Black Krishna Stone Shrine",
    primaryKeywords: ["yadadri", "yadagirigutta"],
    negativeKeywords: [],
    officialSource: "Yadagirigutta Temple Development Authority (YTDA)",
    officialSourceUrl: "https://yadadritemple.telangana.gov.in/"
  },
  {
    id: "bm-tg-bhadrachalam",
    benchmarkName: "Bhadrachalam",
    canonicalName: "Sri Sita Ramachandra Swamy Temple, Bhadrachalam",
    expectedState: "Telangana",
    expectedStateCode: "TG",
    expectedDistrict: "Bhadradri Kothagudem",
    expectedLocality: "Bhadrachalam",
    latitude: 17.6689,
    longitude: 80.8847,
    deity: "Lord Rama (Vaikuntha Rama) & Goddess Sita on Godavari River",
    circuit: "Bhadrachalam Ramadasu Pilgrimage / Godavari Pushkaralu",
    primaryKeywords: ["bhadrachalam", "sita ramachandra swamy"],
    negativeKeywords: [],
    officialSource: "Sri Sita Ramachandra Swamy Devasthanam",
    officialSourceUrl: "https://bhadrachalam.org/"
  },
  {
    id: "bm-tg-thousand-pillar",
    benchmarkName: "Thousand Pillar",
    canonicalName: "Thousand Pillar Temple (Rudreswara Swamy Temple), Hanamkonda",
    expectedState: "Telangana",
    expectedStateCode: "TG",
    expectedDistrict: "Hanamkonda",
    expectedLocality: "Hanamkonda / Warangal",
    latitude: 18.0044,
    longitude: 79.5742,
    deity: "Trikuta Temple: Shiva, Vishnu, Surya (Kakatiya Monolithic Nandi)",
    circuit: "Kakatiya Dynasty Heritage Architecture",
    primaryKeywords: ["thousand pillar temple", "rudreswara swamy hanamkonda"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-tg-bhadrakali",
    benchmarkName: "Bhadrakali",
    canonicalName: "Bhadrakali Temple, Warangal",
    expectedState: "Telangana",
    expectedStateCode: "TS",
    expectedDistrict: "Warangal",
    expectedLocality: "Warangal",
    latitude: 17.9944,
    longitude: 79.5858,
    deity: "Goddess Bhadrakali (Koh-i-Noor diamond eye legacy)",
    circuit: "Chalukya-Kakatiya Sacred Shrines",
    primaryKeywords: ["bhadrakali temple, warangal", "bhadrakali temple", "warangal bhadrakali"],
    negativeKeywords: [],
    officialSource: "Telangana Endowments Department",
    officialSourceUrl: "https://warangal.telangana.gov.in/"
  },
  {
    id: "bm-tg-jogulamba",
    benchmarkName: "Jogulamba",
    canonicalName: "Jogulamba Temple, Alampur (Brahmeswara Temple Complex)",
    expectedState: "Telangana",
    expectedStateCode: "TG",
    expectedDistrict: "Jogulamba Gadwal",
    expectedLocality: "Alampur",
    latitude: 15.8778,
    longitude: 78.1325,
    deity: "Goddess Jogulamba (5th Shakti Peetha) & Navabrahma Temples",
    circuit: "51 Shakti Peethas (Upper Teeth) / Western Chalukya",
    primaryKeywords: ["jogulamba temple", "alampur jogulamba"],
    negativeKeywords: [],
    officialSource: "Jogulamba Temple Devasthanam / Telangana Endowments",
    officialSourceUrl: "https://jogulamba.org/"
  },
  {
    id: "bm-tg-chilkur",
    benchmarkName: "Chilkur",
    canonicalName: "Chilkur Balaji Temple (Visa Balaji), Osman Sagar",
    expectedState: "Telangana",
    expectedStateCode: "TS",
    expectedDistrict: "Rangareddy",
    expectedLocality: "Chilkur / Hyderabad",
    latitude: 17.3592,
    longitude: 78.2989,
    deity: "Lord Balaji (108 Pradakshinas / No Hundi Temple)",
    circuit: "Telangana Heritage Shrines",
    primaryKeywords: ["chilkur balaji", "chilkoor balaji", "chilkoor", "visa balaji"],
    negativeKeywords: [],
    officialSource: "Chilkur Balaji Devasthanam",
    officialSourceUrl: "https://chilkurbalaji.com/"
  },

  // --- TRIPURA ---
  {
    id: "bm-tr-tripura-sundari",
    benchmarkName: "Tripura Sundari",
    canonicalName: "Maa Tripura Sundari Temple (Matabari), Udaipur",
    expectedState: "Tripura",
    expectedStateCode: "TR",
    expectedDistrict: "Gomati",
    expectedLocality: "Udaipur / Matabari",
    latitude: 23.5186,
    longitude: 91.4939,
    deity: "Maa Kali / Tripura Sundari (Kurma Peetha Tortoise Shape)",
    circuit: "51 Shakti Peethas (Right Foot of Sati)",
    primaryKeywords: ["tripura sundari temple", "matabari"],
    negativeKeywords: ["banswara", "rajasthan"],
    officialSource: "Matabari Temple Trust / Tripura Tourism",
    officialSourceUrl: "https://gomati.nic.in/"
  },

  // --- UTTAR PRADESH ---
  {
    id: "bm-up-kashi-vishwanath",
    benchmarkName: "Kashi Vishwanath",
    canonicalName: "Shri Kashi Vishwanath Temple, Varanasi",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Varanasi",
    expectedLocality: "Kashi Vishwanath Corridor, Varanasi",
    latitude: 25.3109,
    longitude: 83.0107,
    deity: "Lord Shiva (Golden Spire Jyotirlinga / King of Kashi)",
    circuit: "12 Jyotirlingas / Sapta Puri / Sacred Ganga",
    primaryKeywords: ["kashi vishwanath temple", "shri kashi vishwanath"],
    negativeKeywords: ["annapurna", "kaal bhairav", "sankat mochan"],
    officialSource: "Shri Kashi Vishwanath Temple Trust",
    officialSourceUrl: "https://shrikashivishwanath.org/"
  },
  {
    id: "bm-up-ram-mandir",
    benchmarkName: "Ram Mandir",
    canonicalName: "Shri Ram Janmbhoomi Mandir, Ayodhya",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Ayodhya",
    expectedLocality: "Ramkot, Ayodhya",
    latitude: 26.7956,
    longitude: 82.1944,
    deity: "Bhagwan Shri Ram Lalla Virajman",
    circuit: "Sapta Puri / Ram Janmabhoomi",
    primaryKeywords: ["ram mandir", "ram janmabhoomi", "shri ram janmbhoomi mandir"],
    negativeKeywords: ["hanuman garhi", "kanak bhawan"],
    officialSource: "Shri Ram Janmbhoomi Teerth Kshetra",
    officialSourceUrl: "https://srjbtkshetra.org/"
  },
  {
    id: "bm-up-krishna-janmabhoomi",
    benchmarkName: "Krishna Janmabhoomi",
    canonicalName: "Shri Krishna Janmasthan Temple Complex, Mathura",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Mathura",
    expectedLocality: "Mathura",
    latitude: 27.5053,
    longitude: 77.6694,
    deity: "Lord Krishna (Garbha Griha Birthplace / Keshavdev)",
    circuit: "Sapta Puri / Braj Bhoomi 84 Kosi Yatra",
    primaryKeywords: ["krishna janmasthan", "krishna janmabhoomi", "keshav dev temple"],
    negativeKeywords: ["banke bihari", "prem mandir"],
    officialSource: "Shri Krishna Janmasthan Seva Sansthan",
    officialSourceUrl: "https://mathura.nic.in/"
  },
  {
    id: "bm-up-banke-bihari",
    benchmarkName: "Banke Bihari",
    canonicalName: "Shri Banke Bihari Mandir, Vrindavan",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Mathura",
    expectedLocality: "Vrindavan",
    latitude: 27.5817,
    longitude: 77.7006,
    deity: "Lord Krishna (Banke Bihari - Swami Haridas Manifestation)",
    circuit: "Braj Bhoomi / Nidhivan Connection",
    primaryKeywords: ["banke bihari mandir", "banke bihari temple", "banke bihari", "shri banke bihari"],
    negativeKeywords: ["prem mandir", "iskcon vrindavan"],
    officialSource: "Shri Bankey Bihari Ji Mandir Trust",
    officialSourceUrl: "https://www.bihariji.org/"
  },
  {
    id: "bm-up-prem-mandir",
    benchmarkName: "Prem Mandir",
    canonicalName: "Prem Mandir (Temple of Divine Love), Vrindavan",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Mathura",
    expectedLocality: "Vrindavan",
    latitude: 27.5722,
    longitude: 77.6744,
    deity: "Radha Krishna & Sita Rama (Italian White Carrara Marble)",
    circuit: "Jagadguru Kripalu Parishat Shrines",
    primaryKeywords: ["prem mandir"],
    negativeKeywords: ["banke bihari"],
    officialSource: "Jagadguru Kripalu Parishat",
    officialSourceUrl: "https://jkp.org.in/"
  },
  {
    id: "bm-up-vindhyavasini",
    benchmarkName: "Vindhyavasini",
    canonicalName: "Maa Vindhyavasini Temple, Vindhyachal",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Mirzapur",
    expectedLocality: "Vindhyachal",
    latitude: 25.1639,
    longitude: 82.5056,
    deity: "Goddess Vindhyavasini (Mahishasuramardini Kajali)",
    circuit: "51 Shakti Peethas / Trikona Parikrama",
    primaryKeywords: ["vindhyavasini", "vindhyachal temple"],
    negativeKeywords: [],
    officialSource: "Shri Vindhyavasini Mandir Parishad / UP Tourism",
    officialSourceUrl: "https://mirzapur.nic.in/"
  },
  {
    id: "bm-up-hanuman-garhi",
    benchmarkName: "Hanuman Garhi",
    canonicalName: "Shri Hanuman Garhi Mandir, Ayodhya",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Ayodhya",
    expectedLocality: "Ayodhya",
    latitude: 26.7972,
    longitude: 82.2014,
    deity: "Lord Hanuman (Guardian of Ayodhya - 76 Steps Fort)",
    circuit: "Essential Prelim to Ram Janmabhoomi Darshan",
    primaryKeywords: ["hanuman garhi", "hanumangarhi ayodhya"],
    negativeKeywords: ["ram mandir"],
    officialSource: "Ayodhya District Administration",
    officialSourceUrl: "https://ayodhya.nic.in/"
  },
  {
    id: "bm-up-sankat-mochan",
    benchmarkName: "Sankat Mochan",
    canonicalName: "Sankat Mochan Hanuman Temple, Varanasi",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Varanasi",
    expectedLocality: "Saket Nagar, Varanasi",
    latitude: 25.2819,
    longitude: 82.9983,
    deity: "Lord Hanuman (Established by Goswami Tulsidas)",
    circuit: "Sankat Mochan Sangeet Samaroh",
    primaryKeywords: ["sankat mochan", "sankat mochan hanuman temple"],
    negativeKeywords: ["kashi vishwanath"],
    officialSource: "Sankat Mochan Mandir Trust",
    officialSourceUrl: "https://varanasi.nic.in/"
  },
  {
    id: "bm-up-gorakhnath",
    benchmarkName: "Gorakhnath",
    canonicalName: "Gorakhnath Temple (Gorakhnath Math), Gorakhpur",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Gorakhpur",
    expectedLocality: "Gorakhpur",
    latitude: 26.7708,
    longitude: 83.3547,
    deity: "Guru Gorakhnath (Nath Sampradaya World Headquarters)",
    circuit: "Nath Sampradaya & Makar Sankranti Khichdi Fair",
    primaryKeywords: ["gorakhnath temple", "gorakhnath math"],
    negativeKeywords: [],
    officialSource: "Gorakhnath Temple Trust",
    officialSourceUrl: "https://gorakhnathmandir.in/"
  },
  {
    id: "bm-up-kaal-bhairav",
    benchmarkName: "Kal Bhairav",
    canonicalName: "Kaal Bhairav Temple (Kotwal of Varanasi)",
    expectedState: "Uttar Pradesh",
    expectedStateCode: "UP",
    expectedDistrict: "Varanasi",
    expectedLocality: "Visheshwarganj, Varanasi",
    latitude: 25.3183,
    longitude: 83.0142,
    deity: "Lord Kaal Bhairav (Divine Magistrate / Kotwal of Kashi)",
    circuit: "Ashtabhairava of Varanasi",
    primaryKeywords: ["kaal bhairav temple", "kaal bhairav", "kal bhairav varanasi", "kal bhairav"],
    negativeKeywords: ["ujjain kal bhairav", "kashi vishwanath"],
    officialSource: "Varanasi District Administration",
    officialSourceUrl: "https://varanasi.nic.in/"
  },

  // --- UTTARAKHAND ---
  {
    id: "bm-uk-kedarnath",
    benchmarkName: "Kedarnath",
    canonicalName: "Kedarnath Temple (Himalayan Jyotirlinga)",
    expectedState: "Uttarakhand",
    expectedStateCode: "UK",
    expectedDistrict: "Rudraprayag",
    expectedLocality: "Kedarnath / Mandakini Valley",
    latitude: 30.7352,
    longitude: 79.0669,
    deity: "Lord Shiva (Sadashiva Triangular Hump - Highest Jyotirlinga)",
    circuit: "Char Dham / Chota Char Dham / 12 Jyotirlingas / Panch Kedar",
    primaryKeywords: ["kedarnath temple", "shri kedarnath"],
    negativeKeywords: [],
    officialSource: "Shri Badrinath-Kedarnath Temple Committee (BKTC)",
    officialSourceUrl: "https://badrinath-kedarnath.gov.in/"
  },
  {
    id: "bm-uk-badrinath",
    benchmarkName: "Badrinath",
    canonicalName: "Badrinath Temple (Badri Vishal)",
    expectedState: "Uttarakhand",
    expectedStateCode: "UK",
    expectedDistrict: "Chamoli",
    expectedLocality: "Badrinath / Alaknanda Valley",
    latitude: 30.7447,
    longitude: 79.4911,
    deity: "Lord Badrinarayan (Black Saligram Shila of Lord Vishnu)",
    circuit: "Char Dham / Chota Char Dham / 108 Divya Desams",
    primaryKeywords: ["badrinath temple", "badri vishal"],
    negativeKeywords: [],
    officialSource: "Shri Badrinath-Kedarnath Temple Committee (BKTC)",
    officialSourceUrl: "https://badrinath-kedarnath.gov.in/"
  },
  {
    id: "bm-uk-gangotri",
    benchmarkName: "Gangotri",
    canonicalName: "Gangotri Temple (Origin of Bhagirathi)",
    expectedState: "Uttarakhand",
    expectedStateCode: "UK",
    expectedDistrict: "Uttarkashi",
    expectedLocality: "Gangotri",
    latitude: 30.9947,
    longitude: 78.9397,
    deity: "Goddess Ganga (Bhagirath Shila)",
    circuit: "Chota Char Dham / Sacred Ganga Origin",
    primaryKeywords: ["gangotri temple", "gangotri"],
    negativeKeywords: [],
    officialSource: "Gangotri Temple Committee",
    officialSourceUrl: "https://uttarkashi.nic.in/"
  },
  {
    id: "bm-uk-yamunotri",
    benchmarkName: "Yamunotri",
    canonicalName: "Yamunotri Temple (Origin of Yamuna)",
    expectedState: "Uttarakhand",
    expectedStateCode: "UK",
    expectedDistrict: "Uttarkashi",
    expectedLocality: "Yamunotri",
    latitude: 31.0142,
    longitude: 78.4600,
    deity: "Goddess Yamuna (Surya Kund & Divya Shila)",
    circuit: "Chota Char Dham / Sacred Yamuna Origin",
    primaryKeywords: ["yamunotri temple", "yamunotri"],
    negativeKeywords: [],
    officialSource: "Yamunotri Temple Committee",
    officialSourceUrl: "https://uttarkashi.nic.in/"
  },
  {
    id: "bm-uk-tungnath",
    benchmarkName: "Tungnath",
    canonicalName: "Tungnath Temple (Highest Shiva Temple in the World)",
    expectedState: "Uttarakhand",
    expectedStateCode: "UK",
    expectedDistrict: "Rudraprayag",
    expectedLocality: "Chandrashila / Chopta",
    latitude: 30.4886,
    longitude: 79.2169,
    deity: "Lord Shiva (Arms of Shiva / 3,680m Elevation)",
    circuit: "Panch Kedar (Highest of the Five)",
    primaryKeywords: ["tungnath temple", "tungnath", "highest shiva temple"],
    negativeKeywords: [],
    officialSource: "BKTC / Uttarakhand Tourism",
    officialSourceUrl: "https://badrinath-kedarnath.gov.in/"
  },
  {
    id: "bm-uk-jageshwar",
    benchmarkName: "Jageshwar",
    canonicalName: "Jageshwar Dham Temple Complex (ASI Monument)",
    expectedState: "Uttarakhand",
    expectedStateCode: "UK",
    expectedDistrict: "Almora",
    expectedLocality: "Jageshwar",
    latitude: 29.6386,
    longitude: 79.8544,
    deity: "Lord Shiva (Tarun Jageshwar & Maha Mritunjaya)",
    circuit: "Cluster of 124 Nagara Stone Temples / Deodar Forest",
    primaryKeywords: ["jageshwar dham", "jageshwar temple", "jageshwar"],
    negativeKeywords: [],
    officialSource: "Archaeological Survey of India (ASI)",
    officialSourceUrl: "https://asi.nic.in/"
  },
  {
    id: "bm-uk-mansa-devi-haridwar",
    benchmarkName: "Mansa Devi Haridwar",
    canonicalName: "Maa Mansa Devi Temple, Bilwa Parvat, Haridwar",
    expectedState: "Uttarakhand",
    expectedStateCode: "UK",
    expectedDistrict: "Haridwar",
    expectedLocality: "Bilwa Parvat, Haridwar",
    latitude: 29.9575,
    longitude: 78.1633,
    deity: "Goddess Mansa (Wish-Fulfilling Serpent Daughter of Shiva)",
    circuit: "Siddhapeeth Triangle of Haridwar (with Chandi Devi & Maya Devi)",
    primaryKeywords: ["mansa devi temple, haridwar", "mansa devi temple", "mansa devi haridwar"],
    negativeKeywords: ["panchkula"],
    officialSource: "Haridwar District Administration / UP & UK Tourism",
    officialSourceUrl: "https://haridwar.nic.in/"
  },
  {
    id: "bm-uk-hemkund-sahib",
    benchmarkName: "Hemkund Sahib",
    canonicalName: "Gurudwara Shri Hemkund Sahib Ji",
    expectedState: "Uttarakhand",
    expectedStateCode: "UK",
    expectedDistrict: "Chamoli",
    expectedLocality: "Hemkund Lake / Ghangaria",
    latitude: 30.7289,
    longitude: 79.5797,
    deity: "Guru Gobind Singh Ji Meditation Sanctuary (4,632m)",
    circuit: "Highest Altitude Gurudwara in the World",
    primaryKeywords: ["hemkund sahib", "gurudwara shri hemkund"],
    negativeKeywords: [],
    officialSource: "Gurudwara Sri Hemkund Sahib Management Trust",
    officialSourceUrl: "https://chamoli.nic.in/"
  },

  // --- WEST BENGAL ---
  {
    id: "bm-wb-dakshineswar",
    benchmarkName: "Dakshineswar",
    canonicalName: "Dakshineswar Kali Temple (Bhavatarini)",
    expectedState: "West Bengal",
    expectedStateCode: "WB",
    expectedDistrict: "North 24 Parganas",
    expectedLocality: "Dakshineswar, Kolkata",
    latitude: 22.6553,
    longitude: 88.3575,
    deity: "Maa Bhavatarini (Kali) & Sri Ramakrishna Paramahamsa Legacy",
    circuit: "Navaratna Architectural Masterpiece on the Hooghly",
    primaryKeywords: ["dakshineswar kali temple", "dakshineswar"],
    negativeKeywords: ["thillai kali", "tamil nadu"],
    officialSource: "Dakshineswar Kali Temple Board of Trustees",
    officialSourceUrl: "https://dakshineswarkalitemple.org/"
  },
  {
    id: "bm-wb-kalighat",
    benchmarkName: "Kalighat",
    canonicalName: "Kalighat Kali Temple, Kolkata",
    expectedState: "West Bengal",
    expectedStateCode: "WB",
    expectedDistrict: "Kolkata",
    expectedLocality: "Kalighat, Kolkata",
    latitude: 22.5208,
    longitude: 88.3425,
    deity: "Maa Kalika (Four-Armed Gold Tongue Kali)",
    circuit: "51 Shakti Peethas (Right Toes of Sati)",
    primaryKeywords: ["kalighat kali temple", "kalighat"],
    negativeKeywords: [],
    officialSource: "Kalighat Temple Committee",
    officialSourceUrl: "https://kolkata.gov.in/"
  },
  {
    id: "bm-wb-tarapith",
    benchmarkName: "Tarapith",
    canonicalName: "Tarapith Temple (Maa Tara Dham), Birbhum",
    expectedState: "West Bengal",
    expectedStateCode: "WB",
    expectedDistrict: "Birbhum",
    expectedLocality: "Tarapith / Rampurhat",
    latitude: 24.1147,
    longitude: 87.7981,
    deity: "Maa Tara (Tantric Mahavidya) & Sadhak Bamakhyapa",
    circuit: "51 Shakti Peethas (Eyeball / Third Eye of Sati)",
    primaryKeywords: ["tarapith temple", "maa tara dham"],
    negativeKeywords: [],
    officialSource: "Tarapith Temple Management Committee",
    officialSourceUrl: "https://birbhum.gov.in/"
  },
  {
    id: "bm-wb-belur-math",
    benchmarkName: "Belur Math",
    canonicalName: "Belur Math (Ramakrishna Math and Ramakrishna Mission Headquarters)",
    expectedState: "West Bengal",
    expectedStateCode: "WB",
    expectedDistrict: "Howrah",
    expectedLocality: "Belur, Howrah",
    latitude: 22.6322,
    longitude: 88.3564,
    deity: "Sri Ramakrishna, Holy Mother Sri Sarada Devi & Swami Vivekananda",
    circuit: "Universal Inter-Faith Architectural Confluence",
    primaryKeywords: ["belur math", "ramakrishna math belur"],
    negativeKeywords: [],
    officialSource: "Ramakrishna Math and Ramakrishna Mission",
    officialSourceUrl: "https://belurmath.org/"
  },
  {
    id: "bm-wb-mayapur",
    benchmarkName: "Mayapur",
    canonicalName: "ISKCON Mayapur (Temple of the Vedic Planetarium - TOVP)",
    expectedState: "West Bengal",
    expectedStateCode: "WB",
    expectedDistrict: "Nadia",
    expectedLocality: "Mayapur",
    latitude: 23.4244,
    longitude: 88.3892,
    deity: "Sri Sri Radha Madhava & Chaitanya Mahaprabhu",
    circuit: "World Headquarters of ISKCON / Gaudiya Vaishnavism",
    primaryKeywords: ["mayapur", "chandrodaya", "vedic planetarium"],
    negativeKeywords: ["samayapuram"],
    officialSource: "International Society for Krishna Consciousness (ISKCON)",
    officialSourceUrl: "https://www.mayapur.com/"
  },
  {
    id: "bm-wb-tarakeswar",
    benchmarkName: "Tarakeswar",
    canonicalName: "Tarakeswar Temple (Taraknath Mandir), Hooghly",
    expectedState: "West Bengal",
    expectedStateCode: "WB",
    expectedDistrict: "Hooghly",
    expectedLocality: "Tarakeswar",
    latitude: 22.8889,
    longitude: 88.0208,
    deity: "Lord Shiva (Baba Taraknath)",
    circuit: "Atchala Bengal Temple Architecture / Shravan Shibbari Yatra",
    primaryKeywords: ["tarakeswar temple", "taraknath temple", "taraknath mandir"],
    negativeKeywords: ["hangseshwari"],
    officialSource: "Tarakeswar Estate Board / Hooghly District Administration",
    officialSourceUrl: "https://hooghly.nic.in/"
  }
];

// Helper to calculate Haversine distance in km
export function haversineDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Earth radius in km
  const dLat = (lat2 - lat1) * (Math.PI / 180);
  const dLon = (lon2 - lon1) * (Math.PI / 180);
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * (Math.PI / 180)) * Math.cos(lat2 * (Math.PI / 180)) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

export type BenchmarkMatchStatus =
  | "PRESENT_VERIFIED"
  | "PRESENT_NEEDS_REPAIR"
  | "WRONG_CANONICAL_MATCH"
  | "WRONG_LOCATION"
  | "DUPLICATE"
  | "MISSING"
  | "NEEDS_REVIEW";

export interface ReconciliationResult {
  benchmarkId: string;
  benchmarkName: string;
  expectedState: string;
  expectedDistrict: string;
  expectedLocality: string;
  status: BenchmarkMatchStatus;
  canonicalId?: string;
  canonicalName?: string;
  slug?: string;
  matchedState?: string;
  matchedDistrict?: string;
  latitude?: number;
  longitude?: number;
  distanceKm?: number;
  source?: string;
  sourceUrl?: string;
  verificationStatus?: string;
  issueDescription?: string;
  previousFalsePositiveMapping?: string;
}
